### DISCUSSION TITLE
Is there a reason to keep AbstractResourceType autowired false ?

### DISCUSSION THREAD

**Discussion by maximehuran** [Sylius/Sylius#17638] [Q&A]
A Sylius project comes from this configuration : 

```yaml
    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false
```

When I declare a new Sylius resource form, I can autowire it like this : 

```php

    public function __construct(
        #[Autowire('%app.model.my_resource.class%')]
        string $dataClass,
        #[Autowire(['app'])]
        array $validationGroups = []
    ) {
        parent::__construct($dataClass, $validationGroups);
    }
```

This avoids the YAML declaration part when autowire is enabled on AbstractResourceType.

Do you think we can remove these 2 lines without impact in Sylius existing resources form types ? 

```
        Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType:
            autowire: false
```
