### ISSUE TITLE
Customizing Controllers is not working with autowire and autoconfigure

### ISSUE THREAD

**Issue by Prometee** [Sylius/Sylius#10003]
**Sylius docs version**: 1.3 / latest

**Description**
Customizing Controllers do not indicate that the Controller service should not be define automatically.
I help a Sylius dev and we found that we have to exclude this newly created Controller from the service autoconfiguration adding : 
```
# config/services.yaml

# line 21 to 23 replaced by (to avoid creation of a service)
App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php,Controller/ProductController.php}'

# line 27 to 29 replaced by (to avoid auto tagging and creation)
App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        exclude: '../src/Controller/{ProductController.php}'
```

Maybe there is a better way to indicate this fact ?
Perhaps a new folder `src/Controller/Sylius/` witch can be excluded instead of only excluding a file, in that case we have to made some little changes to `Sylius/Sylius-standard` repository to fix this use case.

I personally disable all autowiring and autoconfigure because I want to decide by my own what my services are actually doing, but for other devs maybe they want it to be active to speed up there developments.

**Comment by Roshyo** [comment]
Hi,

You can easily do it yourself with this config 👍 
```yaml
App\Controller\:
        resource: '../src/Controller/*'
        exclude: '../src/Controller/Resources'
        tags: ['controller.service_arguments']
```
