### ISSUE TITLE
Missing parts on translation

### ISSUE THREAD

**Issue by jcgdjob** [Sylius/Sylius#10007]
**Sylius docs version**: 1.2.9

**Description**
1) On form validation:
https://docs.sylius.com/en/1.2/customization/validation.html
Should include:
```
Sylius\Component\Product\Model\Product:
    properties:
        translations:
            - Valid: ~
```
(p.s. I would like to suggest adding few lines about how to add the validation_groups to the form as not everyone has knowledge on it)

2) On custom translatable model:
https://docs.sylius.com/en/1.2/cookbook/entities/custom-translatable-model.html
Grid sorting and filtering on translatable field is not working.
I solved it by creating a new repository with:
`            ->addSelect('translation')
`
