### ISSUE TITLE
Sylius 1.3 customizing model extend BaseCountry dose not working

### ISSUE THREAD

**Issue by zhasan0** [Sylius/Sylius#10005]
**Sylius docs version**: 1.3 / latest

**It's my class file Country.php**

```php
<?php
namespace App\Entity;
use Sylius\Component\Addressing\Model\Country as BaseCountry;

class Country extends BaseCountry {

/**
 * @var bool
 */
private $flag;

/**
 * @return bool|null
 */
public function getFlag(): ?bool {
    return $this->flag;
}

/**
 * @param bool $flag
 */
public function setFlag(bool $flag): void {
    $this->flag = $flag;
   }

}
```

 **It's my orm file. AppBundle/Resources/config/doctrine/Country.orm.yml**

```
App\Entity\Country:
      type:entity
      table: sylius_country
             fields:
                    flag:
                         type: boolean
                         nullable: true
```

**It's my config file. config/_sylius.yml**

```
sylius_addressing:
resources:
country:
classes:
model: App\Entity\Country
```
