### ISSUE TITLE
Argument 3 passed to Sonata\Twig\Extension\TemplateExtension::__construct() must be an instance of Sonata\CoreBundle\Model\Adapter\AdapterInterface, instance of Sonata\Doctrine\Adapter\AdapterChain given

### ISSUE THREAD

**Issue by solutionDrive-Alt** [Sylius/Sylius#10035]
**Sylius version affected**: 1.0, 1.1, 1.2

**Description**  
This error is thrown when calling `bin/console cache:warmup` in a fresh installation with  `composer create-project` 

**Steps to reproduce**  
run 
```bash
$ composer create-project sylius/sylius test
```
follow the install-instructions.

run
```bash
$ bin/console cache:warmup 
```
in the created project.

**Possible Solution**  
Quick fix could be to set a conflict in composer.json like:
```yaml
    "conflict": {
        "sonata-project/core-bundle": ">=3.12"
    },
```
