### ISSUE TITLE
Custom Resource class parameter is not set for Grid usage

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#10142]
**Sylius version affected**: 1.3.*

**Description**  
When new custom Resource is created via DI configuration of it's Bundle or Plugin, `%acme.model.feature.class%` parameter is set as expected and can be seen via `container:debug` command, but then this parameter can't be used with Grid component.

```
 You have requested a non-existent parameter "acme.model.feature.class". 
```

```
 sylius_grid:
     grids:
         acme_admin_feature:
             driver:
                 name: doctrine/orm
                 options:
                     #class: "%acme.model.feature.class%" ### DOESNT WORK
                     class: "Acme\\Bundle\\FeatureBundle\\Entity\\Feature" ### WORKS
```

Sometimes there is also issue with repository class, which isn't set to custom repository class.

So far I've debuged it into some Grid internals, where nor class, nor repository method were set, when they should have been.

I've this issue across three different projects, all of them are Sylius 1.3+.
