### ISSUE TITLE
[CoreBundle] oAuth user provider broken

### ISSUE THREAD

**Issue by kboduch** [Sylius/Sylius#10196]
**Sylius version affected**: 1.4

**Description**  
oAuth User Provider throws erros when executing [`$oauth = $this->oauthFactory->createNew();`](https://github.com/Sylius/Sylius/blob/1.4/src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php#L167).

Problem lies within oAuthFactory which is being decorated and replaced with [`Sylius\Bundle\UserBundle\Factory\UserWithEncoderFactory`](https://github.com/Sylius/Sylius/blob/1.4/src/Sylius/Bundle/UserBundle/Factory/UserWithEncoderFactory.php) in [`Sylius\Bundle\UserBundle\DependencyInjection\SyliusUserExtension`](https://github.com/Sylius/Sylius/blob/1.4/src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php#L248). 

The `UserWithEncoderFactory::createNew` must return `Sylius\Component\User\Model\UserInterface` but oAuthFactory returns `Sylius\Component\User\Model\UserOAuthInterface` and we get error. Before we get invalid return type error, we get not found method error first [`$user->setEncoderName($this->encoderName);`](https://github.com/Sylius/Sylius/blob/1.4/src/Sylius/Bundle/UserBundle/Factory/UserWithEncoderFactory.php#L38)

**Steps to reproduce**  
Follow https://docs.sylius.com/en/1.4/cookbook/shop/facebook-login.html and you will eventually get this error when trying to log in with social media.
or
take a look at this test https://github.com/Sylius/Sylius/pull/10197

**Possible Solution**  

1. Either replace Definition with ChildDefinition and [inject](https://github.com/Sylius/Sylius/blob/1.4/src/Sylius/Bundle/CoreBundle/Resources/config/services/integrations/hwi_oauth.xml#L23) parent definition (correct service) https://symfony.com/doc/current/service_container/service_decoration.html

2. Add the ability to omit overwriting resource factory from config
e.x.
``` 
       oauth:
            user:
                encoder: false
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
                    controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
```

and [adjust if statement](https://github.com/Sylius/Sylius/blob/1.4/src/Sylius/Bundle/UserBundle/DependencyInjection/SyliusUserExtension.php#L92) to respect false and continue (ommit)

```
if (null === $encoder) {
      continue;
}
```
