### ISSUE TITLE
Search by code coupon

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#10208]
**Feature find coupon by code**

A customer call you and say that a coupon doesnt work. 
The admin will go to admin and search in promotion section, coupon by code, and see the promotion where is the coupon.

Now you must navigate into all promotions to find the coupon

**Comment by gabiudrescu** [comment]
we solved this by adding a workaround:
 - allowed admin operators to search all orders with a certain coupon
 - in the admin order show screen, on orders with coupons, we put a link to the promotion and coupon show page. 

the right way to do this is, imho, customize the promotions grid.

**Comment by Chrysweel** [comment]
Thanks for to reply @gabiudrescu but I think that the solution should be in Sylius by default. So this will be available to everyone.

**Comment by alexrowesoap** [comment]
Hey. We actually implemented this. Give me a min to dig out the code and I'll make a PR

**Comment by Chrysweel** [comment]
Hello @alexrowesoap you will can to do the PR?

**Comment by alexrowesoap** [comment]
Crumbs! Sorry, completely forgot. I'm fully allocated today, but I'll make a note to do it on Friday :)

**Comment by Chrysweel** [comment]
Hello @CoderMaggie this feature is out of Sylius`s Roadmap ?

**Comment by Chrysweel** [comment]
ping @alexrowesoap

**Comment by alexrowesoap** [comment]
Wow, Friday really got away from me! :joy: 
I'm just catching up after the Christmas break but I'll do my best to update here in the near future

**Comment by Chrysweel** [comment]
:(

**Comment by lchrusciel** [comment]
I can reopen this issue, however, I cannot guarantee that someone will find time to implement this feature. However, it should be pretty straightforward, from the implementation side. We just need one scenario for that and search box ;)

**Comment by vvasiloi** [comment]
I could think of 2 solutions, but I'm not very fond of both.
1. The straightforward one, which @lchrusciel suggested, which turns in a BC Break, because it requires to make a join with promotion's coupons and therefore a new repository class/interface method to do so.
2. The creative one, which requires a modification of the Grid Bundle's Doctrine ORM Expression Builder, that will do the join automatically if the specified filter field has an non-existent alias, but and association with same name exists.
In this case, with the following grid configuration:
```
sylius_grid:
    grids:
        sylius_admin_promotion:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.promotion.class%"
            filters:
                coupon_code:
                    type: string
                    label: sylius.ui.coupon
                    options:
                        fields: [coupons.code]
```
the Expression Builder will do:
```
$this->queryBuilder->leftJoin('o.coupons', 'coupons');
```
I implemented and tested both, including the scenario, but didn't write the spec for the second solution.
WDYT?
