### ISSUE TITLE
Can't redirect with setResponse() in index and show event in ResourceController

### ISSUE THREAD

**Issue by aakashtushar** [Sylius/Sylius#10286]
**Sylius version affected**: 1.2.16

**Description**  
When trying to set `RedirectResponse` in `setResponse()`, the `ResourceController` does not handle the event in `indexAction()` and `showAction()`.

**Steps to reproduce**  
> Listener
```php
class SomeIndexListener {
    public function indexListenerMethod(ResourceControllerEvent $event) {
        ... 
        $event->setResponse(new RedirectResponse($url));
    }
}
```
> event_listener_service.yml
```yaml
app.listener.product.index:
    class: AppBundle\EventListener\SomeIndexListener
    tags:
      - { name: kernel.event_listener, event: sylius.product.index, method: indexListenerMethod }
```

**Possible Solution**  
> ResourceController
```php
public function indexAction(Request $request) {
    ...
    $event = $this->eventDispatcher->dispatchMultiple(ResourceActions::INDEX, $configuration, $resources);
    if($event->hasResponse()) {
        return $event->getResponse();
    }
    ...
}
```
