### ISSUE TITLE
REST API unable to make requests with slash (/) in variant code

### ISSUE THREAD

**Issue by podgaard** [Sylius/Sylius#10293]
**Sylius version affected**: 1.x.y

**Description**  
Inside the REST API, it is impossible to patch a variant that has code containing a forward slash.
Example: Patch /api/v2/products/122013424253/variants/36/34

**Steps to reproduce**  
Make product and a variant code with a forward slash

**Possible Solution**  
It seems that Magento had this issue once, but it was fixed. it appears there were some work-arounds.
https://github.com/magento/magento2/issues/8615

**Comment by mamazu** [comment]
In the route definition we are missing the requirement for the code.
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/product_variant.yml#L59

```yml
sylius_admin_api_product_variant_show:
    path: /variants/{code}
    methods: [GET]
    requirements:
        code: .+
    defaults:
        _controller: sylius.controller.product_variant:showAction
        _sylius:
            serialization_version: $version
            section: admin_api
            serialization_groups: [Default, Detailed]
            repository:
                method: findOneByCodeAndProductCode
                arguments: [$code, $productCode]
```
