### ISSUE TITLE
Fixtures: Avoid using `$baseLocale` at `LocaleFixture`

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10307]
**Sylius version affected**: any

**Description**  
`LocaleFixture` adding `$baseFixture` to list of fixtures to load.
This not allow us to load `locale:` fixtures second time:

```bash
An exception occurred while executing 'INSERT INTO sylius_locale (code, created_at, updated_at) VALUES (?, ?, ?)' with params ["en_US", "2019-04-12 18:10:00", "2019-04-12 18:10:00"]:  
                                                                                                                                                                                          
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en_US' for key 'UNIQ_7BA1286477153098'         
```

**Steps to reproduce**  
- Load default fixtures suite
- Load another suite with `orm_purger: false` and `locale:` fixture

**Possible Solution**  
- Avoid using `$baseLocale`. 
- Specify basic locale right at `fixtures.yml`:

```yaml
sylius_fixtures:
    suites:
        default:
            listeners:
                orm_purger: ~
                logger: ~
            fixtures:
                locale:
                    options:
                        locales:
                            - "%locale%"
```

I will make PR if you guys OK with this.
Let me know please if I can do this on `1.4` or even `1.3` rather than `master` - I'm not sure how strict BC compatibility should be...

**Comment by vvasiloi** [comment]
Would be great to add it only if it wasn't already added in the fixture configuration.
I had to do this to avoid the issue and also providing some information about it:
```
sylius_fixtures:
    suites:
        default:
            fixtures:
                locale:
                    options:
                        locales:
#                            - 'en' # will be added as default locale ('locale' container parameter)
                            - 'nl'
                            - 'fr'
                            - 'de'
```
