### ISSUE TITLE
Product pagination bug (again)

### ISSUE THREAD

**Issue by vvasiloi** [Sylius/Sylius#10343]
**Sylius version affected**: 1.4.1 and up (didn't test lower versions)
**Description**  
The same bug described here: https://github.com/Sylius/Sylius/issues/9699
Opened this issue to keep record.

**Steps to reproduce**  
It's not persistent across all categories.
Here is one where the bug occurs: https://demo.sylius.com/en_US/taxons/t-shirts?limit=9

**Possible Solution**  
https://github.com/Sylius/Sylius/issues/9699#issuecomment-487631905

**Comment by mmenozzi** [comment]
Another quick solution to this problem is to change the file `config/packages/_sylius.yaml` from:
```yaml
sylius_shop:
    product_grid:
        include_all_descendants: true
```
to:
```yaml
sylius_shop:
    product_grid:
        include_all_descendants: false
```
Of course this will stop to include all descendants product but if you have this bug probably is because products are associated to both a parent and a child category. Indeed on the Sylius demo, T-Shirts are associated both to the `T-Shirt` and `T-Shirt/Geneder` categories.

So I don't know if this is really a bug in such situations.
