### ISSUE TITLE
Argon2i algorithm is not supported. Install the libsodium extension or use BCrypt instead

### ISSUE THREAD

**Issue by axzx** [Sylius/Sylius#10403]
**Sylius version affected**: 1.5.0

**Description**  

I have an error:
```
In SecurityExtension.php line 569:
!!                                                                                 
!!    Argon2i algorithm is not supported. Install the libsodium extension or use   
!!    BCrypt instead.  
```

`config/packages/security.yaml`:
```
security:
    always_authenticate_before_granting: true
    providers:
        sylius_admin_user_provider:
            id: sylius.admin_user_provider.email_or_name_based
        sylius_shop_user_provider:
            id: sylius.shop_user_provider.email_or_name_based
    encoders:
        Sylius\Component\User\Model\UserInterface:
            algorithm: bcrypt
    firewalls:
```

What else do I have to do to change to bcrypt?

**Comment by lchrusciel** [comment]
Can you also specify the version of PHP?

**Comment by axzx** [comment]
php7.2 without libsodium, I don't why...

**Comment by patrickouc** [comment]
- Configuring sylius/theme-bundle (>=v1.4.6): From auto-generated recipe
  - Configuring sylius/mailer-bundle (>=v1.4.4): From auto-generated recipe
  - Configuring sylius/grid-bundle (>=v1.5.1): From auto-generated recipe
  - Configuring sylius/fixtures-bundle (>=v1.4.1): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In SecurityExtension.php line 578:
!!
!!    Argon2i algorithm is not supported. Install the libsodium extension or use
!!    "auto" instead.
!!
!!
!!
Script @auto-scripts was called via post-install-cmd

**Comment by avrahamm** [comment]
got same error, in symfony 4.3
$ php bin/console

In SecurityExtension.php line 610:

  Libsodium is not available. Install the sodium extension or use "auto" instead.

**Comment by avrahamm** [comment]
https://symfonycasts.com/screencast/symfony-security/user-password

There are at least two good algorithm options here: bcrypt and argon2i. The argon2i encoder is actually a bit more secure. But, it's only available on PHP 7.2 or by installing an extension called Sodium.

**Comment by unixslayer** [comment]
I have the same problem. PHP 7.2.11 and PHP 7.3.0, both with sodium enabled. 

Turns out that application registers two security encoders, both using `argon2i` algorithm. First one is defined in `config/packages/security.yaml` 

```yaml
security:
    ...
    encoders:
        Sylius\Component\User\Model\UserInterface: argon2i
```

and you can easily change it, e.g. to `bcrypt`.

Second one was a little harder to find. It is registered in [@SyliusUserBundle/Resources/config/app/config.yml](https://github.com/Sylius/SyliusUserBundle/blob/master/Resources/config/app/config.yml)

```yaml
security:
    encoders:
        argon2i: argon2i
```

@pamil I think that second one should be removed from configuration to make it more straightforward. As a user I want to be able to choose which encoder will be used for `sylius_user`. Right now application depends on extension that I may not be able nor want to install.

**Comment by unixslayer** [comment]
@imajim if you, for some reason cannot use `argon2i` algorithm, you can override Sylius hidden configuration by changing encoder in your `config/packages/security.yaml` file:

```yaml
security:
    ...
    encoders:
        Sylius\Component\User\Model\UserInterface: bcrypt
        argon2i: bcrypt
```
