### ISSUE TITLE
Cannot create locale

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#10424]
**Sylius version affected**: 1.5

**Description** 
When trying to create a new locale in the admin interface I get the following error: `Property "code" does not exist in class "Sylius\Component\Locale\Model\LocaleInterface"`

**Steps to reproduce**
1. Create a new plugin skeleton app
2. Go to `http://127.0.0.1:8000/admin/locales/new`
3. Try and create a new locale

**Comment by vvasiloi** [comment]
Known issue, poped up a lot in Slack recently: https://github.com/symfony/symfony/issues/31752
You can mitigate it by adding a conflict `"symfony/doctrine-bridge": "4.3.0"` to `composer.json`
Or by adding the following configuration:
```
framework:
    validation:
        auto_mapping:
            App\Entity\: []
```
