### ISSUE TITLE
Extend interface of entity of sylius (TAxonImage or ProductImage) not worked

### ISSUE THREAD

**Issue by chadyred** [Sylius/Sylius#10436]
**Sylius docs version**: 1.5.1 / latest
``
**Description**
<!-- Describe what is missing or where exactly is the bug/typo/issue located. Links highly appreciated. --!>

Hello,

So I want to add `alt` on each filed of form. 

I success to see my field but when I send the form it says : 

`Property "alt" does not exist in class Sylius\Component\Core\Model\ProductImageInterface`.

So I created an interface which extend the existent one for this two entity their interface:

```
<?php

namespace App\Entity\Taxonomy;

use Sylius\Component\Core\Model\TaxonImageInterface as BaseTaxonImageInterface;

interface TaxonImageInterface extends BaseTaxonImageInterface
{
    public function getAlt(): ?string;

    public function setAlt(?string $alt);
}
```

And I configured it properly:

```
sylius_core:
    resources:
        product_image:
            classes:
                model: App\Entity\Product\ProductImage
                interface: App\Entity\Product\ProductImageInterface
        taxon_image:
            classes:
                model: App\Entity\Taxonomy\TaxonImage
                interface: App\Entity\Taxonomy\TaxonImageInterface
```

So now I have the error (for taxonimage) : 

`Property "alt" does not exist in class "App\Entity\Taxonomy\TaxonImageInterface"`
