### ISSUE TITLE
Not same behavior at example factories configuration

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10474]
**Sylius version affected**: 1.5 (any actually)

**Description**  
`PromotionRuleExampleFactory` and `PromotionActionExampleFactory` converts `amount` from `configuration` to `* 100` at normalizer. But shipping method calculator configuration normalizer at `ShippingMethodExampleFactory` not doing such conversion.

**Steps to reproduce**  
```yaml
sylius_fixtures:
    suites:
        default:
            fixtures:
                shipping_method:
                    options:
                        custom:
                            delivery:
                                code: "delivery"
                                name: "Delivery"
                                enabled: true
                                calculator:
                                    type: "flat_rate"
                                    configuration: 
                                        US_WEB:
                                            amount: 20.00
```

Select that shipping method for any order and then get order's data any way you like:
```json
    "adjustments": [
        {
            "id": 2639,
            "type": "shipping",
            "label": "Delivery",
            "amount": 20 <-- Which means 0.20$, but should be 2000 which means 20.00$
        }
    ],
```

**Possible Solution**  
I believe we should add conversion to all similar places or remove from everywhere so behavior will be the same.
