### ISSUE TITLE
Add more promotions examples to default fixture suite

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10475]
**Describe the proposed solution**
Add more promotions examples to default fixture suite, so all actions, rules and their configuration examples will be present at default fixture suite. 

That way it will be easier to build own suites based on default.

I can perform PR.
Thanks

**Comment by Zales0123** [comment]
I'm definitely for extending the default fixtures with promotions, but I'm not sure should we include **all** of promotions rules and actions there. We have right now 8 default promotion rules, which would require to create 8 promotions and/or promotions with many rules inside which can make fixtures harder to read and maintain. Maybe we can start with adding some rule and action to the Christmas promotion (it has none 😱) and maybe a start and end date (Christmas 😄)? Regarding making it easier to build custom fixtures suites, I would go with a better fixtures documentation and/or some cookbook cc @pamil @CoderMaggie

**Comment by igormukhingmailcom** [comment]
I'll just leave some minimalistic examples that could save a lot of time by copy-pasting rather than digging:

```yaml
# config/packages/sylius_fixtures.yaml

sylius_fixtures:
    suites:
        default:
            fixtures:

                # @see vendor/sylius/sylius/docs/book/orders/promotions.rst
                # @see vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Tests/Fixture/PromotionFixtureTest.php
                
                # Make sure you provide per-channel amounts for *_fixed_discount/*_fixed_price
                # and percentage for *_percentage_discount
                
                # Existing promotion rules:
                # - customer_group
                # - cart_quantity
                # - nth_order
                # - shipping_country
                # - has_taxon
                # - total_of_items_from_taxon
                # - has_n_from_taxon (setono/sylius-promotion-extensions-plugin)
                # - contains_product
                # - item_total 
                # Promotion actions:
                # - order_fixed_discount
                # - unit_fixed_discount
                # - order_percentage_discount
                # - shipping_percentage_discount
                # - unit_fixed_price (setono/sylius-promotion-extensions-plugin)
                
                promotion:
                    options:
                        custom:

                            30_off_for_3_items_at_cart:
                                code: "30_off_for_3_items_at_cart"
                                name: "Put 3 items in your cart and get 30% off"
                                exclusive: false
                                rules:
                                    -
                                        type: "cart_quantity"
                                        configuration:
                                            count: 3
                                actions:
                                    -
                                        type: "order_percentage_discount"
                                        configuration:
                                            percentage: 30

                            free_shipping_for_wholesale_users:
                                code: "free_shipping_for_wholesale_users"
                                name: "Free shipping for wholesale users"
                                exclusive: false
                                rules:
                                    -
                                        type: "customer_group"
                                        configuration:
                                            group_code: "wholesale"
                                actions:
                                    -
                                        type: "shipping_percentage_discount"
                                        configuration:
                                            percentage: 100

                            10_off_for_3rd_order:
                                code: "10_off_for_3rd_order"
                                name: "10% off for 3rd order"
                                exclusive: false
                                rules:
                                    -
                                        type: "nth_order"
                                        configuration:
                                            nth: 3
                                actions:
                                    -
                                        type: "order_percentage_discount"
                                        configuration:
                                            percentage: 10

                            10_off_for_dk_shipping:
                                code: "10_off_for_dk_shipping"
                                name: "10% off for DK shipping"
                                exclusive: false
                                rules:
                                    -
                                        type: "shipping_country"
                                        configuration:
                                            country: "DK"
                                actions:
                                    -
                                        type: "shipping_percentage_discount"
                                        configuration:
                                            percentage: 10

                            buy_iphone_get_50_off_on_accessories:
                                code: "buy_iphone_get_50_off_on_accessories"
                                name: "7 days only: Buy iPhone - get 50% off on accessories"
                                exclusive: false
                                starts_at: "-1 day"
                                ends_at: "6 day"
                                rules:
                                    -
                                        type: "has_taxon"
                                        configuration:
                                            taxons:
                                                - "category_iphone"
                                actions:
                                    -
                                        type: "shipping_percentage_discount"
                                        configuration:
                                            percentage: 50
                                            filters:
                                                taxons_filter:
                                                    taxons:
                                                        - "category_iphone_accessories"
```
