### ISSUE TITLE
Specifying the search option for a string-filter in "sylius_grid.yaml" does not work

### ISSUE THREAD

**Issue by schollsebastian** [Sylius/Sylius#10556]
**Sylius version affected**: 1.5.2

**Description**  
I have set the filter option for my filter to `equal` but unless I don't specify the `type` in an URL-parameter, the filter option is `contains`.

**Steps to reproduce**  
`config/packages/sylius_grid.yaml`:

```yamlsylius_grid:
    grids:
        app_admin_api_customer:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.customer.class%"
            filters:
                phoneNumber:
                    type: string
                    form_options:
                        type: equal
```

**Comment by schollsebastian** [comment]
The solution was to replace `form_options` with `options`.

```yaml
sylius_grid:
    grids:
        app_admin_api_customer:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.customer.class%"
            filters:
                phoneNumber:
                    type: string
                    options:
                        type: equal
```
