### ISSUE TITLE
Custom fixture suite do not purge DB when loading

### ISSUE THREAD

**Issue by tom10271** [Sylius/Sylius#10569]
**Sylius version affected**: 1.5.2

**Description**  
<!-- A clear and concise description of the bug you are experiencing. -->
I was trying to create our own fixture suite.

**Steps to reproduce**  
`sylius_fixtures.yaml`

```yaml
sylius_fixtures:
    suites:
        wow:
            fixtures:
                locale:
                    options:
                        locales:
                            - 'JP'
                currency:
                    options:
                        currencies: ['JPY']
```

```bash
$ symfony console sy:fi:lo wow

Warning! Loading fixtures will purge your database for the dev environment.

Continue? (y/N) y

In AbstractMySQLDriver.php line 55:
                                                                                                                                                                                          
  An exception occurred while executing 'INSERT INTO sylius_locale (code, created_at, updated_at) VALUES (?, ?, ?)' with params ["en_US", "2019-08-02 00:34:57", "2019-08-02 00:34:57"]:  
                                                                                                                                                                                          
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en_US' for key 'UNIQ_7BA1286477153098'                                                                           
                                                                                                                                                                                          

In PDOStatement.php line 119:
                                                                                                                 
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en_US' for key 'UNIQ_7BA1286477153098'  
                                                                                                                 

In PDOStatement.php line 117:
                                                                                                                 
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en_US' for key 'UNIQ_7BA1286477153098'  
                                                                                                                 

sylius:fixtures:load [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<suite>]

exit status 1
```

**Possible Solution**  
<!--- Optional: if you have any suggestions on a fix/reason for the bug -->
Purge DB first

**Comment by tom10271** [comment]
Oh this part is missing actually

```yaml
            listeners:
                orm_purger: ~
                logger: ~
```
