### ISSUE TITLE
Private `sylius.repository.product`

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10663]
**Sylius version affected**: 1.5.2

**Description** 
Navigating to `/_partial/cart/add-item` (or to `/products/some-product` as it have sub-request to add-item at `_inventory.html.twig`) throw next exception:

```
The "sylius.repository.product" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
```

As I see route `sylius_shop_partial_cart_add_item` have options that refers to `sylius.repository.product` so it should be public:
```yaml
            factory:
                method: createForProduct
                arguments: [expr:notFoundOnNull(service('sylius.repository.product').find($productId))]
            form:
                type: Sylius\Bundle\CoreBundle\Form\Type\Order\AddToCartType
                options:
                    product: expr:notFoundOnNull(service('sylius.repository.product').find($productId))
```

but as I see - it actually not:

```bash
bin/console debug:container sylius.repository.product

Information for Service "sylius.repository.product"
===================================================

 ----------------- ------------------------------------- 
  Option            Value                                
 ----------------- ------------------------------------- 
  Service ID        sylius.repository.product            
  Class             App\Repository\ProductRepository     
  Tags              -                                    
  Calls             setRuleQueryBuilder                  
  Public            no                                   
  Synthetic         no                                   
  Lazy              no                                   
  Shared            yes                                  
  Abstract          no                                   
  Autowired         no                                   
  Autoconfigured    no                                   
  Factory Service   doctrine.orm.default_entity_manager  
  Factory Method    getRepository                        
 ----------------- ------------------------------------- 
```

**Steps to reproduce**  
- Navigate to any product show page
- See exception

**Possible Solution**  
Not yet found. Will be updated later.
