### ISSUE TITLE
[Bug] Infinite order fixture load when additional channel(-s) added

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10719]
**Sylius version affected**: 1.6

**Description**  
When you add additional channel to `default` suite in your app, `order` fixture could get one of that new channels randomly at `channel` option via option resolver. And as far as all `default` suite products have only `FASHION_WEB` channel assigned to them, next piece of code makes loop infinite:

```php
            if (!$product->hasChannel($order->getChannel())) {
                $i--;
                continue;
            }
```

**Steps to reproduce**  
- Just add one or more (to increase possibility of random "wrong" channel) channel fixture
- And optionally define another `order` fixture like this (to get 100% possibility of failing):

```yaml
sylius_fixtures:
    suites:
        default:
            fixtures:
                order:
                    options:
                        amount: 20
                        channel: YOUR_NEW_CHANNEL_CODE_YOU_HAVENT_PRODUCTS_AT
```

**Possible Solution**  
1. Use `$productRepository->findByChannel($order->getChannel())` rather than `->findAll()` 
2. AND Throw an exception if `$products` is empty (or just skip? or skip and warn there are no products in channel X?)
3. AND Explicitly define `channel` option for `order` fixture at `default` suite like this:

```yaml
# src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/custom_fixtures.yaml
sylius_fixtures:
    suites:
        default:
            fixtures:
                order:
                    options:
                        amount: 20
                        channel: FASHION_WEB
```

4. Also, to prevent future problems on setups that have too much products, please use some limiting when getting products (almost same issue like described at https://github.com/Sylius/Sylius/issues/10493)

I will provide PR if you guys ok with this changes.
