### ISSUE TITLE
Error: Nesting level too deep - recursive dependency For Taxon model

### ISSUE THREAD

**Issue by ostrolucky** [Sylius/Sylius#10797]
**Sylius version affected**: 1.6.1

**Description**  
We changed our taxon fixtures and now we are getting random `Error: Nesting level too deep - recursive dependency?" at /calida/shop/vendor/gedmo/doctrine-extensions/lib/Gedmo/Sortable/SortableListener.php line 471` errors. This happens when comparing two Taxon objects. 

**Steps to reproduce**  
This is the relevant fixture configuration we added
```yml
sylius_fixtures:
  suites:
    default:
      fixtures:
        taxon:
          options:
            custom:
              - name: root
                code: root
                translations:
                  en_US:
                    name: Root
                children:
                  - code: men
                    name: Men
                    slug: men
                    translations:
                      en_US:
                        name: Men
                    children:
                      - code: mens_jeans
                        name: Jeans
                        slug: men/jeans
                        translations:
                          en_us:
                            name: Jeans
                      - code: mens_tops
                        name: Tops
                        slug: men/tops
                        translations:
                          en_US:
                            name: Tops
                  - code: women
                    name: Women
                    slug: women
                    translations:
                      en_US:
                        name: Women
                    children:
                      - code: womens_jeans
                        name: Jeans
                        slug: women/jeans
                        translations:
                          en_US:
                            name: Jeans
                      - code: womens_tops
                        name: Tops
                        slug: women/tops
                        translations:
                          en_US:
                            name: Tops
                      - code: dresses
                        name: Dresses
                        slug: women/dresses
                        translations:
                          en_US:
                            name: Dresses
```

Obviously posting full reproducing example is hard, but this happens when hitting product edit endpoint and changing mainTaxon

**Possible Solution**  
Consider implementing `Doctrine\Common\Comparable` interface on your Taxon model to avoid weak comparison check.
