### ISSUE TITLE
Migrate SyliusProductBundle to another driver

### ISSUE THREAD

**Issue by aa-ahmed-aa** [Sylius/Sylius#10804]
I'm using sylius/product-bundle and I need to migrate sylius tables to different database driver I followed the Symfony docs here  https://symfony.com/doc/3.4/doctrine/multiple_entity_managers.html
my mappings array in the new driver was :-
```
sylius_db:
           connection: sylius_db
           mappings:
               SyliusAttributeBundle: ~
               SyliusProductBundle: ~
               SyliusLocaleBundle: ~
               SyliusResourceBundle: ~
```
when I migrate the database I get 
> No Metadata Classes to process.

I tried another solution by dir the directories of the migration paths so the new mappings array became :-
```
sylius_db:
           connection: sylius_db
           mappings:
               SyliusAttributeBundle:
                   type: xml
                   prefix: Sylius\Component\Attribute\Model
                   dir: '%kernel.root_dir%/../vendor/sylius/attribute-bundle/Resources/config/doctrine/model'
               SyliusProductBundle:
                   type: xml
                   prefix: Sylius\Component\Product\Model
                   dir: '%kernel.root_dir%/../vendor/sylius/product-bundle/Resources/config/doctrine/model'
               SyliusLocaleBundle:
                   type: xml
                   prefix: Sylius\Component\Locale\Model
                   dir: '%kernel.root_dir%/../vendor/sylius/locale-bundle/Resources/config/doctrine/model'
               SyliusResourceBundle:
                   type: xml
                   prefix: Sylius\Component\Resource\Model
                   dir: '%kernel.root_dir%/../vendor/sylius/resource-bundle/src/Bundle/Resources/config/doctrine/model'
```
when i migrate i get this error 
> There is no column with name 'locale' on table 'sylius_product_translation'. 

So, my current problem is I want to migrate sylius to another database driver
