### ISSUE TITLE
OrderController::saveAction doesn't call manager flush if request is not html

### ISSUE THREAD

**Issue by pfazzi** [Sylius/Sylius#10930]
**Sylius version affected**: 1.6.4

**Description**  
As you can see in the following snippet, if request is not HTML, ` $this->manager->flush();` is never called, so client receive a 204 HTTP status but entity is not actually updated.
https://github.com/Sylius/Sylius/blob/dcee256fbe487a7777607f22e9787f540d1ff9b5/src/Sylius/Bundle/OrderBundle/Controller/OrderController.php#L103-L115

**Steps to reproduce**  

1. Add a route with the following config:
```yaml
pp_ajax_shop_cart_save:
    path: /ajax/cart/
    methods: [PUT]
    defaults:
        _controller: sylius.controller.order:saveAction
        _format: json
        _sylius:
            form:
                type: App\Form\CheckoutFunnel\SummaryType
                options:
                    product: "expr:service('app.service.subscription_provider').getProduct()"
```

2. Create a form `App\Form\CheckoutFunnel\SummaryType` with some fields, like the following:
```php
final class SummaryType extends AbstractResourceType
{
    public function __construct(array $validationGroups = [])
    {
        parent::__construct(Order::class, $validationGroups);
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('subscriptionItem', PlanSelectionType::class, [
                'product' => $options['product'],
            ])
            ->add('promotionCoupon', PromotionCouponToCodeType::class, [
                'by_reference' => false,
                'label' => 'sylius.form.cart.coupon',
                'required' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        parent::configureOptions($resolver);

        $resolver->setRequired('product');
    }
}
```
3. Create an order as usual and then make an HTTP call passing a json body like the following:
```json
{
	"subscriptionItem": {
		"variant": 321
	},
	"promotionCoupon": "SERGIO19"
}
```
And with the following headers:
```
Content-Type:application/json
Accept:application/json
```
4. Verify that order has not been updated.

**Possible Solution**  
Simply move lines from 105 to 107 under the `$this->manager->flush()` call:
```php
$this->eventDispatcher->dispatchPostEvent(ResourceActions::UPDATE, $configuration, $resource);

$this->getEventDispatcher()->dispatch(SyliusCartEvents::CART_CHANGE, new GenericEvent($resource));
$this->manager->flush();

if (!$configuration->isHtmlRequest()) {
	return $this->viewHandler->handle($configuration, View::create(null, Response::HTTP_NO_CONTENT));
}

$this->flashHelper->addSuccessFlash($configuration, ResourceActions::UPDATE, $resource);

return $this->redirectHandler->redirectToResource($configuration, $resource);
```
