### ISSUE TITLE
Infinite redirect loop when trying to prevent transition from happening

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#10948]
**Sylius version affected**: 1.6

**Description**  
Have you tried using a Guard? The [docs say](https://github.com/winzou/state-machine/blob/master/examples/simple.php) one should return a `boolean false` to indicate the transition must not happen. Returning `boolean false` results in an infinite error loop though. 

**Steps to reproduce**  

```
winzou_state_machine:
  sylius_order_checkout:
    callbacks:
      guard:
        logistic_minimum:
          on: address
          do: ['@App\Order\EventListener\OrderMinimumQuantityGuardListener', check]
          args: [object]
```

The callback:
```

class OrderMinimumQuantityGuardListener
{
    public function check(OrderInterface $order): bool
    {
        return false;
    }
}

```

This also happens when trying to prevent the transition using an event listener:

```
class OrderMinimumQuantityGuardListener implements EventSubscriberInterface
{
    public function check(TransitionEvent $event): void
    {
        $event->setRejected();
    }

    public static function getSubscribedEvents()
    {
        return [SMEvents::TEST_TRANSITION => 'check'];
    }
}
```
