### ISSUE TITLE
Validation override is not working

### ISSUE THREAD

**Issue by tuala** [Sylius/Sylius#11045]
I'm trying to let 0€ be set in product's prices under 1.6 but the documentation is not working for me whatever I try.

```
parameters:
    sylius.form.type.channel_pricing.validation_groups: [app_product]
```

**/config/validator/validation.yaml**
```
Sylius\Component\Product\Model\ChannelPricing:
    properties:
        price:
            - Range:
                  message: sylius.channel_pricing.price.min
                  groups: [app_product]
                  min: 0
        originalPrice:
            - Range:
                  message: sylius.channel_pricing.original_price.min
                  groups: [app_product]
                  min: 0
```

According to the doc that should be it

> Done. Now in all forms where the Product name is being used, 

But it is not working at all.
