### ISSUE TITLE
Getting "Using $this when not in object context" in state machine callback

### ISSUE THREAD

**Issue by tuala** [Sylius/Sylius#11056]
Any workaround ? I do not understand how we are supposed to customize business logic via state machine if the callback method is called statically... What I am missing ?

**Comment by vvasiloi** [comment]
Is is called statically if you give a class instead of an object, or the method is static, see callback docs here https://www.php.net/manual/en/language.types.callable.php

**Comment by tuala** [comment]
Yeah that is what I figured, what I couldn't figure is why winzou was calling it that way when I followed the document. Seems toying around with the callback config did the trick. Dunno exactly what was the problem but her is what I got working now if other people get the same issue:

```
winzou_state_machine:
    sylius_payment:
        callbacks:
            after:
                sylius_completed_payment:
                    on: ["complete"]
                    do: ["@sylius_subscription.payment.confirmation", "create"]
                    args: ["object"]
```


  ```
  sylius_subscription.payment.confirmation:
        class: App\Payment\Listeners\ConfirmationPayment
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            -  "@sm.factory"
            - "@logger"
```

May be something missing from the doc ?

**Comment by vvasiloi** [comment]
@tuala you were missing the `@`, which is required to reference services, so it was interpreted as a FQCN, therefore it was called statically.
Here's how it should be:
```
winzou_state_machine:
    sylius_payment:
        callbacks:
            after:
                sylius_completed_payment:
                    on: ["complete"]
                    do: ['@App\Payment\Callback\ConfirmationPayment', "create"]
                    args: ["object"]
```
