### ISSUE TITLE
Unable to use geographical fixture twice

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#11216]
**Sylius version affected**: 1.7 / any

**Description**  
* When you want to use `geographical` fixture twice (example: https://github.com/Setono/SyliusCorePlugin/pull/3/commits/78bae0e9561202a48a19f95dff3c8d191fcdde32), you will get something like:

```
In GeographicalFixture.php line 189:
                                                                               
  An exception was thrown during loading zone "zone_tax_25" with code "zone_t  
  ax_25"!                                                                      
                                                                               

In GeographicalFixture.php line 256:
                                                    
  Could not find country "DK", defined ones are: !  
```

As fixture checks country exists at options array, but not at database.
* From other side, if you specify required country at countries option (example: https://github.com/Setono/SyliusCorePlugin/pull/3/commits/30ab8b616f6268d84afa1181340462c2c83c8f02) - fixture will try to create it again with duplication exception.

```
In AbstractMySQLDriver.php line 55:
                                                                               
  An exception occurred while executing 'INSERT INTO sylius_country (code, en  
  abled) VALUES (?, ?)' with params ["US", 1]:                                 
                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'US'   
  for key 'sylius_country.UNIQ_E74256BF77153098' 
```

**Steps to reproduce**  
See https://github.com/Setono/SyliusCorePlugin/pull/3

**Possible Solution**
* Use Country repository to check countries. Like done at https://github.com/Setono/SyliusCorePlugin/pull/3/commits/50edeae1777c549fbd7596646ea250d21316ecc6
* Use Country repository to check country exists before create. Like done at https://github.com/Setono/SyliusCorePlugin/pull/3/commits/c07043d5fe2afe215a2156a2f694440549cceb52

**Comment by lchrusciel** [comment]
Our fixtures usually cannot be run twice without purging the database. However, since FixtureBundle 1.5 you can specify the suite, that will be run before yours and append data later, will it work for you? Or perhaps we should fix GeographicalFixture in the core. Would you like to open a PR with the fix?

**Comment by igormukhingmailcom** [comment]
I'm talking about something else. You can't even define more than one `geographical` fixture in one suite like at example below because:
- From one side, you should have country listed at `countries`
- From another, if you pass same countries to different sets, you will get duplication issue

```
sylius_fixtures:
    suites:
        default:
            fixtures:

                countries:
                    name: geographical
                    options:
                        countries:
                            - 'US'
                            - 'DK'
                            - 'SE'

                tax_zones:
                    name: geographical
                    options:
                        countries: []
                        zones:
                            zone_tax_25:
                                name: "zone_tax_25"
                                scope: "tax"
                                countries:
                                    - "DK"
                                    - "SE"

                shipping_zones:
                    name: geographical
                    options:
                        countries: []
                        zones:
                            DK:
                                name: "Denmark"
                                scope: "shipping"
                                countries:
                                    - "DK"
                            SE:
                                name: "Sweden"
                                scope: "shipping"
                                countries:
                                    - "SE"
```
