### ISSUE TITLE
[ResourceBundle] problem when creating a resource via REST API

### ISSUE THREAD

**Issue by jjanvier** [Sylius/Sylius#1123]
Hi @Sylius,

Silly question (maybe not...). Does anyone succeeded in creating a resource via the REST API ?
Let's say I have a resource defined in `config.yml`:

```
sylius_resource:
    resources:
        my.resource:
            driver: doctrine/orm
            classes:
                model: blablabla\MyResource
```

Normally I could create it directly via the API if the routes are defined, right ?

With something like `curl -i -H "Content-Type: application/json"  -H "Accept: application/json" -X POST -d '{"my_attr":"my_value"}' 'http://blablabla/api/v1/resource/'`the resource is not created because the form is not correctly bound. Tthe method `createAction` of `ResourceController` is actually waiting for something like `{"resource_form":{"my_attr":"my_value"}}`.

I surely miss something... But what ? Or is it a bug ?
