### ISSUE TITLE
Document the preferred way to handle timezones

### ISSUE THREAD

**Issue by mvriel** [Sylius/Sylius#11516]
**Sylius docs version**: 1.x / latest

**Description**

For our project, we wanted the server configuration in UTC because imports and subprocesses depend on this (also: for server-side handling UTC is recommended as _the_ timezone to make handling more consistent and maintainable; it will prevent time-travelling issues due to summertime). However, the date was always displayed in UTC, even when the locale was set to nl_NL.

I found out, and couldn't find this in the documentation, that you can have proper timezone handling by using the twig format_date and format_datetime functions for formatting the dates, AND that you need to create a sonata_intl.yaml in config/packages with a mapping for the locales to timezones.

Example:

```
sonata_intl:
  timezone:
    default: Europe/Amsterdam
    locales:
      en_GB: Europe/London
      nl_NL: Europe/Amsterdam
```

I discovered this by following the source code of the twig filters, discovering the timezone detectors of Sonata and then reading the docs on Sonata Intl (https://sonata-project.org/bundles/intl/2-x/doc/reference/configuration.html).
