### ISSUE TITLE
Problem with custom product serialization including hatoas

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#11565]
**Sylius version affected**: 1.7

**Description**  
I am trying to minimize things to serialize in the product so we use serialization groups for jms serializer but then hatoas properties are not serialized.

For that we override the route of product index of admin by ajax

```

sylius_admin_ajax_product_index:
    path: /pagos/administration/ajax/products/
    defaults:
        _controller: sylius.controller.product:indexAction
        _format: json
        _sylius:
            permission: true
            grid: "sylius_admin_product"
            serialization_groups: ['Autocomplete', 'hatoas']
```

If no groups are set, all is being serialized.

**Steps to reproduce**  
In order to serialize the hateoas properties we have the following config

```
Hateoas\Representation\CollectionRepresentation:
    properties:
        resources: # here is the real problem we don't know how to tell to serialize embedded objects
            groups: [ "hatoas" ]
```

```
Hateoas\Representation\PaginatedRepresentation:
    properties:
        page:
            groups: [ "hatoas" ]
        pages:
            groups: [ "hatoas" ]
```

```
Hateoas\Representation\RouteAwareRepresentation:
    properties:
        inline:
            inline: true
            groups: [ "hatoas" ]
```

```
Hateoas\Representation\AbstractSegmentedRepresentation:
    properties:
        limit:
            groups: [ "hatoas" ]
        total:
            groups: [ "hatoas" ]
```

Our custom product serialization config is:

```
Opos\SyliusIntegrationBundle\Entity\Product:
    exclusion_policy: ALL
    xml_root_name: product
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, Autocomplete]
        code:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
        options:
            expose: true
            type: array
            groups: [Default, Detailed]
        attributes:
            expose: true
            type: array
            groups: [Detailed]
        associations:
            exlucde: true
        translations:
            expose: true
            type: array
            groups: [Detailed]
    virtual_properties:
        getName:
            serialized_name: name
            groups: [Default, Detailed, Autocomplete]
        getVariants:
            serialized_name: variants
        getImages:
            serialized_name: images
```

Any sugenstion is wellcome.

Thanks

**Comment by vvasiloi** [comment]
Try this
```
sylius_admin_ajax_product_index:
    path: /pagos/administration/ajax/products/
    defaults:
        _controller: sylius.controller.product:indexAction
        _format: json
        _sylius:
            permission: true
            grid: sylius_admin_product
            serialization_groups:  { 0: Default, items: [ Autocomplete ] }
```
Here's a working example I tested https://gist.github.com/vvasiloi/368b5c9474ca0bf3d5bbbb0c3eb301e0
