### ISSUE TITLE
Impossible to access an attribute ("avatar") on a null variable, When we create a new router

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/Sylius#11588]
Hi,

I'm trying to adda new route and a new view in admin. my router will looks like
```
admin_api_branch_index:
    path: /channel/show-branch
    methods: [GET]
    defaults:
        _controller: sylius.controller.channel:showBranchAction
```

I created a view in  **templates/bundles/SyliusAdminBundle/Channel/show_branch.html.twig**

I included layout file in view like this to get the template layouts to my new page
`{% extends '@SyliusAdmin/layout.html.twig' %}`

then I'm getting error like **Impossible to access an attribute ("avatar") on a null variable.**, I have already login the system also..

can you please guide me to fix this issue
