### ISSUE TITLE
Custom grid show action lack documentation

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#11594]
**Sylius docs version**: 1.x / latest

**Description**
Why the ["Your first grid"](https://sylius-older.readthedocs.io/en/latest/bundles/SyliusGridBundle/your_first_grid.html#generating-the-crud-routing) guide is missing the `show` action:

```
app_admin_supplier:
    resource: |
        alias: app.supplier
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']      <------------------------ HERE
```

If one follows this tutorial, but want to have the "show" action, we end up with 500 error:

```
Unable to find template "SyliusAdminBundle:Crud:show.html.twig" (looked into: /var/www/html/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /var/www/html/templates, /var/www/html/templates, /var/www/html/vendor/symfony/twig-bridge/Resources/views/Form).
```
