### ISSUE TITLE
Invalid JOINs when filtering over multiple fields using the string filter

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#11647]
**Sylius version affected**: every

**Description**  
Grid `string` filter doesn't work properly when filtering by multiple relations. The expression builder joins foreign relations using an `INNER JOIN` – if any relation is missing, nothing will be returned. The filter would work correctly if `LEFT JOIN` were used.

**Steps to reproduce**  
Filter by multiple fields, eg. in the `order` admin:

```
      filters:
        customer:
          type: string
          label: sylius.ui.customer
          options: {fields: [customer.user.email, customer.defaultAddress.company]}
```

Generated SQL query (pseudo code):

```
SELECT * FROM sylius_customer c
INNER JOIN sylius_shop_user u ON c.id = u.customer_id
INNER JOIN sylius_address a ON a.id = c.default_address_id
WHERE (u.email LIKE '%value%' OR a.company LIKE '%value%')
```

Above filter won't work at all if the customer:

1. has no default address, or
2. has no user

**Possible Solution**  
Use `LEFT JOIN`s, let `WHERE` statements do their job.
