### ISSUE TITLE
Avatar on null or login page with selenium driver

### ISSUE THREAD

**Issue by Kazadri** [Sylius/Sylius#11770]
**Sylius version affected**: 1.7.5

**Description**
When I launch a set of behat test with a selenium driver (1.3^), I got an error saying :
```
Impossible to access an attribute (“avatar”) on a null variable
```

The real issues is the error occurred randomly, I can launch the test several times and the error will occur on different scenarios or will not occur at all.

When I launch the test with the symfony driver, the error never shows up.

I suspect the session is lost somewhere and we are disconnected.

**Steps to reproduce**

behat.yml.dist :
```yaml
imports:
    - behat/Resources/config/suites.yml

default:
    formatters:
        progress: true

    extensions:
        Lakion\Behat\MinkDebugExtension:
            directory: build
            clean_start: true
            screenshot: true

        Behat\MinkExtension:
            files_path: "%paths.base%/behat/Resources/fixtures/"
            base_url: "http://rflyer-nginx/"
            default_session: symfony
            javascript_session: chrome
            show_auto: false
            sessions:
                symfony:
                    symfony: ~
                chrome:
                    selenium2:
                        browser: chrome
                        wd_host: "http://selenium:4444/wd/hub"
                        capabilities:
                            browserName: chrome
                            browser: chrome
                            version: ""
                            marionette: null
                            chrome:
                                switches:
                                    - "start-fullscreen"
                                    - "start-maximized"
                                    - "no-sandbox"
                            extra_capabilities:
                                unexpectedAlertBehaviour: accept

        FriendsOfBehat\SymfonyExtension: ~
        FriendsOfBehat\VariadicExtension: ~
        FriendsOfBehat\SuiteSettingsExtension:
            paths:
                - "features"

    gherkin:
        filters:
            tags: "~@todo && ~@cli"

```
