### ISSUE TITLE
Use expressionLanguage into ParametersParser

### ISSUE THREAD

**Issue by amenophis** [Sylius/Sylius#1179]
Hi @Sylius,
I see the ExpressionLanguage is injected into the ParametersParser but not used ...
It would be nice to it !! I can do this, but i'm not sure how to do this into the right way ;)

My principal use case, is I want to add a filter on the currently logged user. This is my routes:

```
my_event_index:
    pattern: /my-events
    methods: [GET]
    defaults:
        _controller: my.controller.event:indexAction
        _sylius:
            criteria:
                owner: app.user

my_event_show:
    pattern: /my-events/{id}
    methods: [GET]
    defaults:
        _controller: my.controller.event:showAction
        _sylius:
            criteria:
                owner: app.user
```

The idea is I want to show a different list for each user without use a route parameter. Or deny the access to the show route if the id item don't match with the currently logged user.
