### ISSUE TITLE
Cannot migrate from scratch

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#11841]
**Sylius version affected**: 1.8

**Description**  
I get this exception when trying to migrate from scratch:

![image](https://user-images.githubusercontent.com/2412177/93093661-3d7d2280-f6a1-11ea-8bcf-db9f00cf9717.png)

**Steps to reproduce**  
To test the migration in 1.8 I did the following:

1. `php bin/console doc:data:drop --force`
2. `php bin/console doc:data:create`
3. Removed all migrations in our app migrations dir: `rm -rf src/Migrations/*`
4. `php bin/console doc:mig:mig`

Here is the `doctrine_migrations.yaml` file:

```yaml
doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
```
