### ISSUE TITLE
Default value for fixture option not take effect

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#12040]
**Sylius version affected**: 1.7 / any I guess

**Description**

Lets say we have this definition (with`associated_products` option commented out):

```
# fixtures.yaml
...
sylius_fixtures:
    suites:
        default:
            fixtures:
                product_association:
                    options:
                        custom:
                            - type: related_products
                              owner: 'some_product_code'
                              # associated_products: ['some_other_product_code']
```

We expect that `associated_products` will be filled by random products due to resolver configuraion at `ProductAssociationExampleFactory`:

```
$resolver
    ...
    ->setDefault('associated_products', LazyOption::randomOnes($this->productRepository, 3))
```

But this never happens, as far as `associated_products` option always will be present as `[]` after processing by `TreeBuilder` at `ProductAssociationFixture`:

```
protected function configureResourceNode(ArrayNodeDefinition $resourceNode): void
{
    $resourceNode
        ...
            ->arrayNode('associated_products')->scalarPrototype()->end()->end()
```

From other side, if we remove that option from `configureResourceNode`, it will be filled with random products from `ProductAssociationExampleFactory` (as far as that option not defined).

But this also not a solution, as once we specify `associated_products: [...]` (uncomment last line of provided fixture example), we will get something like:

```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                                                              
  Unrecognized option "associated_products" under "product_association". Available options are ... 
```

So as I see, the only way defaults for arrays currently takes effect - is when we call `$exampleFactory->create([...])` programmatically without that option provided. And there is no way to have defaults via fixtures configuration (`sylius_fixtures: ...`).

That is the reason why we have 

```
channels:
    - 'FASHION_WEB'
```

in all places at fixtures, I guess.

**Possible Solution**  
I don't see solution, but hope someone have some thoughts about how to deal with this.

My thoughts (which I don't feel are good):
- Call `$optionsNode->ignoreExtraKeys(false);` globally at `AbstractFixture` to allow extra keys
- Remove array nodes like `channels`, `associated_products`, etc and only add some comments that such an option can be provided
- This way defaults will be applied if option not provided, but used as before if provided without exception about extra key
