### ISSUE TITLE
Add filters in product grid rise an error

### ISSUE THREAD

**Issue by SylvanoTombo** [Sylius/Sylius#12097]
Hi guys, is a bug or my misunderstanding..i override the product grid and add filters like below

filters:
    search:
        type: string
        label: sylius.ui.search
        options:
            fields: [code, translation.name, mainTaxon.translation.name]

But it gives me an error No mapping found for field 'translation' on class 'App\Entity\Taxonomy\Taxon' , can someone help me?

**Comment by morgan-blondellet** [comment]
@SylvanoTombo I found your issue while looking for the same error.

I managed to fix this by adding this to my grid config 

```
driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Cms\Page
                    repository:
                        method: createListQueryBuilder
                        arguments: ["expr:service('sylius.context.locale').getLocaleCode()", $taxonId]
```

The repository is the important part here.

Then you need to add this method in your repository class to join the translations with your entity.

```
public function createListQueryBuilder(string $locale): QueryBuilder
    {
        $queryBuilder = $this->createQueryBuilder('o')
            ->addSelect('translation')
            ->innerJoin('o.translations', 'translation', 'WITH', 'translation.locale = :locale')
            ->setParameter('locale', $locale)
        ;

        return $queryBuilder;
    }
```

I hope this can help someone !

**Comment by Wojdylak** [comment]
Hi @SylvanoTombo 

I don't think it is a bug on our side of the configuration.

You can handle this in two way:

1. Use `mainTaxon.translations.name` instead of `mainTaxon.translation.name`. However, this will search in all translations, so it is not efficient.
2. As @morgan-blondellet suggested, you can add the translation to the `QueryBuilder` and then you it in the configuration. In this case, it will be 
```php
$queryBuilder = $this->createQueryBuilder('o')
      ->addSelect('translation')
      ->addSelect('mainTaxon')
      ->addSelect('mainTaxonTranslation')
      ->innerJoin('o.mainTaxon', 'mainTaxon')
      ->leftJoin('o.translations', 'translation', 'WITH', 'translation.locale = :locale')
      ->leftJoin('mainTaxon.translations', 'mainTaxonTranslation', 'WITH', 'mainTaxonTranslation.locale = :locale')
      ->setParameter('locale', $locale)
  ;
```
and configuration:
```
search:
    type: string
    label: sylius.ui.search
    options:
        fields: [code, translation.name, mainTaxonTranslation.name]
```

I am closing this issue. If you have any other questions or issues, don't hesitate to create a new issue.
