### ISSUE TITLE
Redirect to Index with no parameters

### ISSUE THREAD

**Issue by pdias** [Sylius/Sylius#1214]
Hello,

I'm using SyliusResourceBundle. I have this routes:

```
catalogue_product_index:
    pattern: /admin/catalogue/products
    methods: [GET]
    defaults:
        _controller: catalogue.controller.product:indexAction
        _sylius:
            method: filterPaginator
            arguments: [$criteria, $sorting, $deleted]

catalogue_product_create:
    pattern: /admin/catalogue/products/new
    methods: [GET, POST]
    defaults:
        _controller: catalogue.controller.product:createAction
        _sylius:
            redirect: catalogue_product_índex
```

When a create a "product", with this path, it redirect to **"catalogue_product_index"** and in the **browser url** shows **"/admin/catalogue/products?id=32"**, where **"32"** is the new product **ID**.

It is possible redirect to índex and not show the **ID** in url?

Thanks.

Paulo Dias
