### ISSUE TITLE
Order recalculation issue 🧐

### ISSUE THREAD

**Issue by jelen07** [Sylius/Sylius#12437]
**Sylius version affected**: 1.8.9 (also in earlier versions)

**Description**  
When you're trying to manipulate with already placed order (applying changes from ERP like change shipment or payment, remove/add order item, change the quantity, etc.) there is unexpected behavior. An extra payment is added due `OrderPaymentProcessor`.

[As mentioned in docs](https://docs.sylius.com/en/latest/book/orders/orders.html#:~:text=sylius.order_processing.order_processor), I'm using `sylius.order_processing.order_processor` to have everything recalculated. But the given **OrderPaymentProcessor** is IMHO configured for checkout purposes.

**Steps to reproduce**  
1. Place order as usual.
2. Copy&Paste these lines to your controller:
```php
        $orderRepository = $this->container->get('sylius.repository.order');
        $orderManager = $this->container->get('sylius.manager.order');
        $orderProcessor = $this->container->get('sylius.order_processing.order_processor');

        /** @var OrderInterface $order */
        $order = $orderRepository->find(21); // <--- Enter your order id
        dump([
            'before',
            'total' => $order->getTotal(),
            'taxTotal' => $order->getTaxTotal(),
        ]);
        $orderProcessor->process($order);
        $orderManager->flush();
        dump([
            'after',
            'total' => $order->getTotal(),
            'taxTotal' => $order->getTaxTotal(),
        ]);
        dump($order->getPayments()); // See the collection
 ```

The new payment is added due to [this line](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php#L72). The previous block (in the link)
```php
$lastPayment = $order->getLastPayment($this->targetState);
```

doesn't return any payment, because [it's configured to `cart`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/services/order_processing.xml#L62).

Another issue is when you change the payment method after the order was placed, the recalculation process is not called. But it should be probably called because may have a payment fee and so on.

When using adjustments it's a little bit messy.

**Possible Solution**  
- Configure the `sylius.order_processing.order_payment_processor.checkout` service using multiple `$targetStates`?
- Use another approach to get consistent order before and after recalculations [while the whole order's lifecycle](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/OrderProcessing/OrderPaymentProcessor.php#L46).

**Related**
https://github.com/Sylius/Sylius/issues/11927

**Comment by jelen07** [comment]
The same problem occurs when you change the payment state (on fail or cancel) coz the `@sylius.order_processing.order_payment_processor.after_checkout` callback is registered and a new payment appears.

<img width="867" alt="Snímek obrazovky 2021-05-13 v 9 37 47" src="https://user-images.githubusercontent.com/2346295/118094333-e2860180-b3ce-11eb-86a2-c47351d24e1e.png">

<img width="563" alt="Snímek obrazovky 2021-05-13 v 9 42 55" src="https://user-images.githubusercontent.com/2346295/118094861-99827d00-b3cf-11eb-84f9-49e049f9ee19.png">

### Workaround
Remove those payments before persisting the order.

```php
<?php

declare(strict_types=1);

namespace App\Nextgen\Bundle\CoreBundle\OrderProcessing;

use App\Nextgen\Bundle\OrderBundle\Entity\OrderInterface;
use App\Nextgen\Bundle\PaymentBundle\Entity\PaymentInterface;
use Sylius\Component\Order\Model\OrderInterface as BaseOrderInterface;
use Sylius\Component\Order\Processor\OrderProcessorInterface;
use Webmozart\Assert\Assert;

final class RemoveDummyOrderPaymentProcessor implements OrderProcessorInterface
{
    /** @var OrderProcessorInterface */
    private $orderPaymentProcessor;

    /** @var array|string[] */
    private $allowedPaymentStates = [
        PaymentInterface::STATE_CART,
        PaymentInterface::STATE_NEW,
    ];

    public function __construct(OrderProcessorInterface $orderPaymentProcessor)
    {
        $this->orderPaymentProcessor = $orderPaymentProcessor;
    }

    public function process(BaseOrderInterface $order): void
    {
        Assert::isInstanceOf($order, OrderInterface::class);

        $this->orderPaymentProcessor->process($order);

        if (OrderInterface::STATE_CART === $order->getState()) {
            return;
        }

        // Get all order payments which are not persisted yet.
        $dummyPayments = $order->getPayments()->filter(function (PaymentInterface $payment): bool {
            return null === $payment->getId() && in_array($payment->getState(), $this->allowedPaymentStates, true);
        });

        foreach ($dummyPayments as $payment) {
            $order->removePayment($payment);
        }
    }
}
```
and register this decorator

```yaml
services:
    app_core.order_processing.remove_dummy_order_payment_processor:
        class: App\Nextgen\Bundle\CoreBundle\OrderProcessing\RemoveDummyOrderPaymentProcessor
        decorates: 'sylius.order_processing.order_payment_processor.checkout'
        arguments:
            - '@app_core.order_processing.remove_dummy_order_payment_processor.inner'

    app_core.order_processing.remove_dummy_order_payment_processor.after_checkout:
        class: App\Nextgen\Bundle\CoreBundle\OrderProcessing\RemoveDummyOrderPaymentProcessor
        decorates: 'sylius.order_processing.order_payment_processor.after_checkout'
        arguments:
            - '@app_core.order_processing.remove_dummy_order_payment_processor.after_checkout.inner'
```
