### ISSUE TITLE
Pre/post complete events are not triggered

### ISSUE THREAD

**Issue by LucaGallinari** [Sylius/Sylius#12541]
**Sylius docs version**: 1.8 / latest

**Description**
As stated in multiple issues (https://github.com/Sylius/Sylius/issues/8109, https://github.com/Sylius/Sylius/issues/8395) pre and post complete events are not triggered upon completing a payment. They are triggered only when you confirm the payment from the admin.
For this reason I think that the [Payment page in the docs](https://docs.sylius.com/en/latest/book/orders/payments.html#payment-complete-events) should alert about this or don't even mention that these event are called, as their use is inconsistent among the application. It must be preferred to listen the "pay" callback on the "sylius_order_payment" object, like this:

```
winzou_state_machine:
    sylius_order_payment:
        callbacks:
            after:
                my_custom_logic_name:
                    on: ["pay"]
                    do: ["@YOUR_SERVICE_ID", "THE_METHOD_TO_CALL"]
                    args: ["object"]

```

What do you think?
