### ISSUE TITLE
Order success, canceled or failed got same confirmation email

### ISSUE THREAD

**Issue by N445** [Sylius/Sylius#12576]
When a make an order, and testing a couple of return : success, canceled or failed

I got the same email : `order_confirmation`

with this content

```yaml
        order_confirmation:
            has_been_successfully_placed: 'has been successfully placed.'
            subject: 'Order confirmation'
            view_order_or_change_payment_method: 'View order or change payment method'
            thank_you: 'Thank you for shopping at our store!'
            your_order_number: 'Your order no.'
```

It's normal ? How can i custom after checkout email for canceled or failed ? 

Thanks :)
