### ISSUE TITLE
[RFC] Products - attributes, options, variants

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#1273]
Hey guys,

I was looking at merging VariableProduct & Product bundles into 1 component + 1 bundle set, with toggling the extra functionality. Like a switch on/off for variants and options.

We're doing a lot of BC breaks with the components, so I thought I could try one thing I was thinking about for a long time now.

Before you got scared, rationale behind these ideas, then ideas...
- Products are not the only objects that can have attributes.
- "Property" is much less clear and verbose than Attribute.
- Products are not the only objects that can have options and variations. Even shipping methods could have options.
- The benefit of splitting Product and Variable product is very low. Usually if you use Symfony2 for building a shop, you need even more than just options, so bare ProductBundle / Product component is not very useful, most of the time you go with VariableProductBundle.
- Separating them is annoying and not that easy.

My idea how to resolve these issues.
- SyliusAttributeBundle (+ Attribute component), a bundle used to handle entities with multiple attributes. Right now our handling of different property (attributes) is very basic, but I'd like to expand on this in future. The Attribute component should be right place for handling this. Basically, you configure the model which should have attributes support, define AttributeValue entity (and custom Attribute if needed as well) and voila. You can use form types to edit / add the attributes on any object. (yes, I'm talking here about multiple models support, not just one)

``` yaml
sylius_attribute:
    driver: doctrine/orm
    classes:
        player:
            subject: Acme\Bundle\CoreBundle\Entity\Player
            attribute:
                model: Acme\Bundle\CoreBundle\Entity\PlayerAttribute
            attribute_value:
                model: Acme\Bundle\CoreBundle\Entity\PlayerAttributeValue
        player:
            subject: Acme\Bundle\CoreBundle\Entity\Game
            attribute:
                model: Acme\Bundle\CoreBundle\Entity\GameAttribute
            attribute_value:
                model: Acme\Bundle\CoreBundle\Entity\GameAttributeValue
```

Keep in mind, only `attribute_value` is required. You can share all attributes across all objects using the default Attribute model provided by the bundle.

This configuration will automatically register `sylius.repository.player_attribute` and `sylius.repository.game_attribute` services. (along with others, usualy resource bundle stuff)

Game and Player need to implement basic `SubjectInterface` (better name?) which allows to manage the attributes. The associations between subject and attributes are handled automatically via doctrine listener from the bundle.
- SyliusVariableProductBundle and ProductBundle should be merged together. Also, there should be just one Product component.

Just like I said in the introduction to this RFC, I think it makes sense to just provide Sylius catalog as it is in main app, because if we separate options & attributes support to standalone bundles/components, the simple product model becomes so simple, that it is trivial to define your own entity to get the same basic product model. (and add options / attributes if needed)

So yeah, we merge VariableProductInterface into ProductInterface. One product component (using the 2 new components for attributes and variants) + one product bundle.
- SyliusVariationBundle + component.

Same story as with attributes. Options and Variants support for as many models as you need. Similar configuration like for SyliusAttributeBundle - `variant`, `option`, `option_value`. Again, you can share options for all models, or have option list per model. Like, product options, shipping method options or whatever else you need.

I bet code would tell you more and I already started working on this yesterday. I have functional AttributeBundle and almost working VariationBundle, but I need at least 1 day more to make it all pretty enough to push here. (and I'd say 1 more day to merge into components) 

That's why I am asking here to hear your opinion on this ideas.

My main point here is that I had a need for options/variants and attributes support in several projects already, yet it was very coupled to the product. I think this way we'll have very clear separation of concerns and 99% the same API as we have now, except for the Property -> Attribute renaming.

Please give your feedback ASAP, so we don't delay components any minute more than it is needed. Thank you!
