### ISSUE TITLE
Abilitiy to add roles to groups

### ISSUE THREAD

**Issue by JRomeoSalazar** [Sylius/Sylius#1293]
I'm thinking in add the posiblity to select roles at group form. I have this feature in one of my apps.
It would be necessary to add role hierarchy to security.yml.

Do you think it's interesting? In this case, what kind of roles would yo create?

In my case I have:

``` yml
role_hierarchy:
        ROLE_RESELLER:      [ROLE_USER]
        ROLE_SYLIUS_ADMIN:  [ROLE_RESELLER, ROLE_USER]
        ROLE_SUPER_ADMIN:   [ROLE_SYLIUS_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_RESELLER, ROLE_USER]
```

Of course, this is totally customizable.
Then we could link promotions to groups, for example.
