### ISSUE TITLE
Fetching Items of and order via API v2 fails, if one of the products in the order has attributes added

### ISSUE THREAD

**Issue by c4ll-m3-j4ck** [Sylius/Sylius#13023]
**Sylius version affected**: 1.10.1

**Description**  
Trying to get items associated with an order via api v2 causes an error, if a product has assigned attributes.

If i call the endpoint `/api/v2/shop/orders/{token}/items` on an order that has added products which have attributes, the response fails with the following error:

`A circular reference has been detected when serializing the object of class "Proxies\__CG__\App\Entity\Product\ProductAttribute" (configured limit: 1).`

If the order only contains products without attributes, a correct response is returned.

**Steps to reproduce**  
Add an item to an order via `PATCH /api/v2/shop/order/{token}/items` which has attributes added.

Any help would be appreciated!

**Comment by vvasiloi** [comment]
Quick workaround:
Add the following serialization metadata for ProductAttributeTranslation
```yaml
App\Entity\Product\ProductAttributeTranslation:
    attributes:
        translatable:
            ignore: true

```
