### ISSUE TITLE
Unable to extend Form TaxonTranslationTypeExtension

### ISSUE THREAD

**Issue by bellu** [Sylius/Sylius#13276]
**Sylius version affected**: 1.10.0

**Description**  
Following these docs:
[https://docs.sylius.com/en/latest/customization/form.html](https://docs.sylius.com/en/latest/customization/form.html)
[https://docs.sylius.com/en/latest/customization/model.html#how-to-customize-translatable-fields-of-a-translatable-model](https://docs.sylius.com/en/latest/customization/model.html#how-to-customize-translatable-fields-of-a-translatable-model)
I'm trying to add a new field to taxon translation form type, but i got this error:

Too few arguments to function Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType::__construct(), 0 passed in /srv/sylius/var/cache/dev/ContainerMMIjGmP/App_KernelDevDebugContainer.php on line 6071 and at least 1 expected

**Steps to reproduce**  
`services.yaml`

```
app.form.extension.type.taxon_translation:
        class: App\Form\Extension\TaxonTranslationTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonTranslationType }
```

`_sylius.yaml`

```
sylius_taxonomy:
    resources:
        taxon:
            classes:
                model: App\Entity\Taxonomy\Taxon
            translation:
                classes:
                    model: App\Entity\Taxonomy\TaxonTranslation
```

`TaxonTranslationTypeExtension.php`

```
namespace App\Form\Extension;

use Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonTranslationType;


class TaxonTranslationTypeExtension extends AbstractResourceType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('bottom_description', TextareaType::class, [
                'required' => false,
                'label' => 'sylius.form.taxon.bottom_description',
            ]);


    }

    public static function getExtendedTypes(): iterable
    {
        return [TaxonTranslationType::class];
    }
}
```

`TaxonTranslation.php`

```
namespace App\Entity\Taxonomy;

use Doctrine\ORM\Mapping as ORM;
use Sylius\Component\Taxonomy\Model\TaxonTranslation as BaseTaxonTranslation;

/**
 * @ORM\Entity
 * @ORM\Table(name="sylius_taxon_translation")
 */
class TaxonTranslation extends BaseTaxonTranslation
{
    /** @ORM\Column(type="string", nullable=true, name="bottom_description") */
    protected $bottomDescription;

    /**
     * @return string|null
     */
    public function getBottomDescription(): ?string
    {
        return $this->bottomDescription;
    }

    /**
     * @param string|null $bottomDescription
     */
    public function setBottomDescription(?string $bottomDescription): void
    {
        $this->bottomDescription = $bottomDescription;
    }
}

```

Any suggestion?
I have already extended other forms with success; but i can't understand this error.
