### ISSUE TITLE
Security bundle new version (5.4) problem

### ISSUE THREAD

**Issue by pawelkeska** [Sylius/Sylius#13342]
I tried install today Sylius and after installation i've got error:

The service "security.authorization_checker" has a dependency on a non-existent service "security.authentication_manager". Did you mean one of these:  "security.authorization_checker", "security.authentication_utils", "security.authentication.manager", "security.authentication.guard_handler"? 

When i downgrade package symfony/security-bundle to 5.3 version everything is ok.

**Comment by bigboss86** [comment]
@Zales0123 @lchrusciel

**Comment by Zales0123** [comment]
Hello @pawelkeska! We're already working on proper support for Symfony 5.4. Right now, indeed, it's safer to use Sylius with Symfony 5.2 & 5.3 🖖

**Comment by BigChicChicken** [comment]
@pawelkeska How did you downgrade "ymfony/security-bundle" ?

**Comment by BigChicChicken** [comment]
I found another incompatibility with "symfony/twig-bridge", so i downgrade all symfony's packages to 5.3
In composer.json:
`
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.3.*"
        }
    }
`

**Comment by wadjeroudi** [comment]
one possible solution for those who really need 5.4 support, remove from app security.yaml
```
always_authenticate_before_granting: true
```
not sure of all consequences, possibly if you change a user role, he will need to disconnect and reconnect to reload the roles.

**Comment by alwintje** [comment]
The following worked for me:

* Add an alias in services.yaml
```yaml
security.authentication_manager:
    alias: security.authentication.manager
```
* In security.yaml, encoders is replaced for password_hashers. So I added the following:
```yaml
security:
    password_hashers:
        Sylius\Component\User\Model\UserInterface: argon2i
```
* Symfony uses now the cache provider of Doctrine instead of their own. In config/packages/prod/doctrine.yaml:
```yaml
# Replace:
class: Symfony\Component\Cache\DoctrineProvider
# For:
class: Doctrine\Common\Cache\Psr6\DoctrineProvider
factory: ['Doctrine\Common\Cache\Psr6\DoctrineProvider', wrap]
```

* In composer.json I did the following:
```json
   "symfony/password-hasher": "^5",
   "symfony/twig-bridge": "^5"
```
