### ISSUE TITLE
[Admin] Products routes id requirements

### ISSUE THREAD

**Issue by bigboss86** [Sylius/Sylius#13359]
**Sylius version affected**: 1.9

**Description**  
In products admin routes, the id parameter has no requirements.

**Steps to reproduce**  
```
sylius_admin_product_update:
    path: /products/{id}/edit
    methods: [GET, PUT, PATCH]
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            section: admin
            permission: true
            redirect: referer
            template: "@SyliusAdmin/Crud/update.html.twig"
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
                templates:
                    form: "@SyliusAdmin/Product/_form.html.twig"
                    toolbar: "@SyliusAdmin/Product/Update/_toolbar.html.twig"

sylius_admin_product_show:
    path: /products/{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:showAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/Product/show.html.twig"
```

**Possible Solution**  
```
sylius_admin_product_update:
    path: /products/{id}/edit
    methods: [GET, PUT, PATCH]
    requirements:
        id: '\d+'
    defaults:
        _controller: sylius.controller.product:updateAction
        _sylius:
            section: admin
            permission: true
            redirect: referer
            template: "@SyliusAdmin/Crud/update.html.twig"
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube
                templates:
                    form: "@SyliusAdmin/Product/_form.html.twig"
                    toolbar: "@SyliusAdmin/Product/Update/_toolbar.html.twig"

sylius_admin_product_show:
    path: /products/{id}
    methods: [GET]
    requirements:
        id: '\d+'
    defaults:
        _controller: sylius.controller.product:showAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/Product/show.html.twig"
```
