### ISSUE TITLE
[Paypal] Request SecuredCaptureRequest{model: Payment} is not supported.

### ISSUE THREAD

**Issue by jackpf** [Sylius/Sylius#1337]
Hi,

Trying to implement the checkout with the paypal gateway, but I keep getting this error.

This is my Payum config, mostly copied from sylius standard:

```
payum:
    security:
        token_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken:
                doctrine:
                    driver: orm

    contexts:
        paypal_express_checkout:
            paypal_express_checkout_nvp:
                api:
                    options:
                        username:  %paypal.express_checkout.username%
                        password:  %paypal.express_checkout.password%
                        signature: %paypal.express_checkout.signature%
                        sandbox:   %paypal.express_checkout.sandbox%
                actions:
                    - sylius.payum.paypal.action.capture_order_using_express_checkout
                    - sylius.payum.paypal.action.notify_order
                    - sylius.payum.action.order_status

            storages:
                Sylius\Bundle\CoreBundle\Model\Order:
                    doctrine:
                        driver: orm
                Sylius\Bundle\PaymentsBundle\Model\Payment:
                    doctrine:
                        driver: orm
```

Is there something I'm missing or is this not fully working yet?

Thanks,
Jack
