### ISSUE TITLE
Confusing Doctrine Migrations configuration

### ISSUE THREAD

**Issue by stefantalen** [Sylius/Sylius#13395]
**Sylius version affected**: 1.8.0 and higher

**Description**  
While upgrading our 1.6 installation up to 1.9 I came across some confusing configuration.

When doing a clean install for 1.9.0 using the `sylius-standard` repo one gets the following [doctrine_migrations.yaml](https://github.com/Sylius/Sylius-Standard/blob/1.9/config/packages/doctrine_migrations.yaml):
```yaml
doctrine_migrations:
    storage:
        table_storage:
            table_name: sylius_migrations
    migrations_paths:
        'App\Migrations': "%kernel.project_dir%/src/Migrations"
```
However, when reading the [UPGRADE-1.8.md](https://github.com/Sylius/Sylius/blob/1.8/UPGRADE-1.8.md) guide the following configuration is suggested:

```yaml
doctrine_migrations:
    storage:
        table_storage:
            table_name: sylius_migrations
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
```

But when using the recipe provided by Composer for `doctrine/doctrine-migrations-bundle` the configuration looks likes this:
```yaml
doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
```
Which one is the right one?

**Possible Solution**  
Judging by the recipe the migrations should not be put within the `/src` folder, resulting in this configuration:
```yaml
doctrine_migrations:
    storage:
        table_storage:
            table_name: sylius_migrations
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
```
I guess that would require an extra change in `config/services.yaml` for `sylius/sylius-standard`:
```yaml
    App\:
        resource: '../src/*'
-        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'
+        exclude: '../src/{Entity,Tests,Kernel.php}'
```
This would also be in line with the recipe for `symfony/framework-bundle` which is this for Symfony > 4.4 
```yaml
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
```
