### ISSUE TITLE
RequestResetPasswordToken message is not being validated and its handler may cause internal server error

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#13871]
**Sylius version affected**: 1.11 and master

**Description**  
When requesting a password reset, the email address in the deserialized message is not being validated. However,the handler of this message has an assertion that the email is valid and a user exists: https://github.com/Sylius/Sylius/blob/98d1141e7fa43d3e19c3ee165885d822bc10e625/src/Sylius/Bundle/ApiBundle/CommandHandler/Account/RequestResetPasswordTokenHandler.php#L37-L40. This causes an error 500 when the submitted email address is not in the database or is simply invalid.

**Steps to reproduce**  
1. Expand https://demo.sylius.com/api/v2/#operations-tag-ResetPasswordRequest
2. Click on "Try it out"
3. Click on "Execute"

**Possible Solution**  
Either a `ShopUserExists` or similar validator should be added on the field, or some custom logic written to return early if the user does not exist (e.g. returning early, or triggering a custom exception which would be converted into a 4xx status code).

I personally went with the first option, wrote a validator (couldn't find one) and configured the validator like this:
```yaml
Sylius\Bundle\ApiBundle\Command\Account\RequestResetPasswordToken:
    properties:
        email:
            -   Sequentially:
                    groups: [ Default, sylius ]
                    constraints:
                        -   Email: ~
                        -   App\Validator\Constraints\ShopUserExists: ~
```
