### ISSUE TITLE
RegisteredUser constraint is named incorrectly

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#13872]
**Sylius version affected**: master

**Description**  
Typically constraints are named by what then enforce as opposed to what they prevent, e.g.:
- ShopUserNotVerified causes a violation if a given shop user is already verified
- ShopmentAlreadyShipped causes a violation if a shipment is not yet shipped
- OrderNotEmpty causes a violation if an order is empty

However, the RegisteredUser constraint acts differently: instead of causing a violation when the user with the given email is not registered, it causes a violation when the user with such email already exists:

https://github.com/Sylius/Sylius/blob/98d1141e7fa43d3e19c3ee165885d822bc10e625/src/Sylius/Bundle/CoreBundle/Validator/Constraints/RegisteredUserValidator.php#L36-L40

In addition, I'm not sure why you made this a class constraint for a specific class. As I understand it, class constraints typically use multiple properties of an object, or call specific methods. But looking at the validator, the only class-specific thing it does is calls `$value->getEmail()`. Why not just validate the email property itself instead?

**Steps to reproduce**  
No need for them.

**Possible Solution**  
I suggest deprecating this constraint/validator and adding a new one instead. The new validator could be properly named and used as a property constraint.

Also, since #13871 would require an opposite constraint, it might make sense for the new constraint to cover both cases with the help of a boolean flag, somewhat like this:
````yaml
SomeClass:
    properties:
        someProperty:
            -   ShopUserExists:
                    # default – asserts that the user is found
                    exists: true


SomeOtherClass:
    properties:
        someProperty:
            -   ShopUserExists:
                    # asserts that the user is not found
                    exists: false
```
