### ISSUE TITLE
[Docs][Cookbook][Payments] In "How to integrate a Payment Gateway as a Plugin" tutorial yaml example for plugin action service registration is missing a parameter

### ISSUE THREAD

**Issue by gigamarr** [Sylius/Sylius#13915]
**Sylius docs version**: 1.x / latest

**Description**

https://docs.sylius.com/en/1.11/cookbook/payments/custom-payment-gateway.html

```yaml
//src/Resources/config/services.yaml
Acme\SyliusExamplePlugin\Payum\Action\CaptureAction:
    arguments:
        - '@sylius.http_client'
    tags:
        - { name: payum.action, factory: sylius_payment, alias: payum.action.capture }
```

It should be declared as `public` otherwise it won't work. I will submit PR later
