### ISSUE TITLE
Can not extend CatalogPromotionRepository because of it's direct definition in sylius_fixtures.listener.catalog_promotion_executor

### ISSUE THREAD

**Issue by sabat24** [Sylius/Sylius#14003]
**Sylius version affected**: 1.1.11

**Description**  
I wanted to extend the resource related `CatalogPromotionRepository` class, to add some custom methods in it. 
I created my custom repository class and I added proper entry to `config/packages/_sylius.yaml`

```yaml
sylius_promotion:
    resources:
        catalog_promotion:
            classes:
                model: path_to_my_custom_entity_class
                repository: path_to_my_custom_repository_class
```

Then I received an error:

`The service "sylius_fixtures.listener.catalog_promotion_executor" has a dependency on a non-existent service "Sylius\Bundle\PromotionBundle\Doctrine\ORM\CatalogPromotionRepository"`

Probably because that class is directly provided as a service's argument `<argument type="service" id="Sylius\Bundle\PromotionBundle\Doctrine\ORM\CatalogPromotionRepository" />`

In my opinion there should: `<argument type="service" id="sylius.repository.catalog_promotion" />`
