### ISSUE TITLE
Enabling only one gateway

### ISSUE THREAD

**Issue by smarques** [Sylius/Sylius#1405]
I am still on 0.9 and I was trying to enable only one payment gateway (stripe), and so i set this in my config
```yml
sylius_payments:
     driver: doctrine/orm
     gateways:
            stripe: Stripe
```

Still I get this error:
```
ServiceNotFoundException: The service "sylius.payum.be2bill.action.notify" has a dependency on a non-existent service "payum.context.be2bill.api".
```
What is the correct way to remove the be2bill service (and any other gateway related services I am not going to use) from the payum bundle configuration?

Thank you so much
sergio
