### ISSUE TITLE
Unable to add custom repository for ProductImage

### ISSUE THREAD

**Issue by JanPietrzyk** [Sylius/Sylius#14119]
**Sylius version affected**: 1.11.0

**Description**  
I was trying to add a custom repository for`product_image` according to the documentation (https://docs.sylius.com/en/latest/customization/repository.html). This results in an error,

**Steps to reproduce**  
Try to add the following line to your `_sylius.yaml`

````yml
sylius_core:
    resources:
        product_image:
            classes:
                repository: App\Entity\Product\ProductImageRepository
````
This will result in an configuration error, because the field `repository` is actually not configured.

**Possible Solution**  

Add the option to `\Sylius\Bundle\CoreBundle\DependencyInjection\Configuration`, and maybe add a test to ensure all repositories can be overwritten ;)

**Comment by jbcr** [comment]
You can redefine the resource into the resource bundle configuration like:

```yaml
sylius_resource:
    resources:
        sylius.product_image:
            classes:
                repository: App\Entity\Product\ProductImageRepository
```
