### ISSUE TITLE
Sorting links are not parametered on PromotionCoupon grid

### ISSUE THREAD

**Issue by Geolim4** [Sylius/Sylius#14131]
**Sylius version affected**: All

**Description**  
The sorting is not working on PromotionCoupon grid because sorting link are not parametered.

**Steps to reproduce**  
Go to PromotionCoupon grid, try to sort by any column

**Possible Solution**  
Probable template issue related to `grid.parameter.all`

**Comment by Geolim4** [comment]
After some investigation I came to the following conclusion:

This fixes the issue:
```yaml
# promotion_coupon.yaml
sylius_grid:
    grids:
        sylius_admin_promotion_coupon:
            sorting:
                priority: desc
```

I investigated to the following vendor files by doing some comparisons:
`vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/config/grids/promotion.yml`
`vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/config/grids/promotion_coupon.yml`

And I found out that `promotion_coupon.yml` does not contains this piece of configuration code:
```yaml
            sorting:
                priority: desc
```
But `promotion.yml` does. This is why it's messing with  `\Sylius\Component\Grid\View\GridView::getSortingOrder` method that returns `null` and make the order parameters unavailable in `vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Resources/views/Macro/sorting.html.twig`.

Hope that help some of you folk to resolve this issue.
