### ISSUE TITLE
Missing route in admin bundle if shop is disabled

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/Sylius#14171]
**Sylius version affected**: 1.12

**Description**  
Disabling Sylius shop lead to a missing route in the admin bundle. This is due to this line: https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Bundle/AdminBundle/Resources/views/Layout/_channelLinks.html.twig#L9

**Steps to reproduce**  
If you remove the Sylius shop routing, there's an error because of the missing route.

**Possible Solution**  
I talked about this with @vvasiloi, we should check if the shop is disabled to use this shop path and use "/" in case it's disabled.

**Comment by NoResponseMate** [comment]
Hi @vasilvestre,
Thanks for the report, if you have time could you open a fix for this bug.
For reference it'll be the same way as in [this file](https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Bundle/AdminBundle/Resources/views/Product/_showInShopButton.html.twig).

**Comment by crydotsnake** [comment]
You mean this route defined in `config/routes/sylius_shop.yaml` am i correct?:

```
sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
```
