### ISSUE TITLE
Cannot change order item quantity more than once via API

### ISSUE THREAD

**Issue by Dragnucs** [Sylius/Sylius#14219]
| Q                | A      |
|------------------|--------|
| Bug report?      | yes |
| Feature request? | no |
| BC Break report? | no |
| RFC?             | no |
| Sylius version   | 1.11  |

Following [documentation](https://docs.sylius.com/en/latest/getting-started-with-sylius/using-api.html?highlight=place%20order#changing-product-quantity) to change a product quantity in a cart, only the first change is successful, subsequent changes systematically fail with an optimistic lock exception.

This is a simple scenario where a user clicks the increase quantity button multiple times to go from, for example, 1 to 2 then 3 then 4.

**Expected result:**
Changing an order item quantity via API runs successfully for first change, second, and so on

**Current result:**
Changing an order item quantity via API is successful on first change. A second change fails with error 500 "The optimistic lock on an entity failed."

**How to reproduce:**
Given a cart with item 59782 and quantity set to 1.

Query A:
```shell
curl -X 'PATCH' \
  'https://master.demo.sylius.com/api/v2/shop/orders/OPzFiAWefi/items/59782' \
  -H 'accept: application/ld+json' \
  -H 'Authorization: Bearer token' \
  -H 'Content-Type: application/merge-patch+json' \
  -d '{
  "quantity": 2 # notice quantity
}'
```

Query B:
```shell
curl -X 'PATCH' \
  'https://master.demo.sylius.com/api/v2/shop/orders/OPzFiAWefi/items/59782' \
  -H 'accept: application/ld+json' \
  -H 'Authorization: Bearer token' \
  -H 'Content-Type: application/merge-patch+json' \
  -d '{
  "quantity": 3 # notice quantity
}'
```

1. Change quantity via (query A) PATH /api/v2/shop/orders/{tokenValue}/items/{orderItemId} endpoint. Changes correctly.
2. Change quantity a second time via same endpoint above but with different quantity (query B). Changes fail with optimistic lock exception.
3. Running step 2 again (query A again) returns 200 OK since nothing really changed indeed.

**Stack trace**
```
Doctrine\ORM\OptimisticLockException:
The optimistic lock on an entity failed.

  at vendor/doctrine/orm/lib/Doctrine/ORM/OptimisticLockException.php:61
  at Doctrine\ORM\OptimisticLockException::lockFailed(object(OrderItem))
     (vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:515)
  at Doctrine\ORM\Persisters\Entity\BasicEntityPersister->updateTable(object(OrderItem), 'sylius_order_item', array('quantity' => 3, 'total' => 12000), true)
     (vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:399)
  at Doctrine\ORM\Persisters\Entity\BasicEntityPersister->update(object(OrderItem))
     (vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:1210)
  at Doctrine\ORM\UnitOfWork->executeUpdates(object(ClassMetadata))
     (vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:429)
  at Doctrine\ORM\UnitOfWork->commit(null)
     (vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:378)
  at Doctrine\ORM\EntityManager->flush(null)
     (var/cache/dev/ContainerJqUgDra/EntityManager_9a5be93.php:129)
  at ContainerJqUgDra\EntityManager_9a5be93->flush()
     (vendor/symfony/doctrine-bridge/Messenger/DoctrineTransactionMiddleware.php:32)
  at Symfony\Bridge\Doctrine\Messenger\DoctrineTransactionMiddleware->handleForManager(object(EntityManager_9a5be93), object(Envelope), object(TraceableStack))
     (vendor/symfony/doctrine-bridge/Messenger/AbstractDoctrineMiddleware.php:45)
  at Symfony\Bridge\Doctrine\Messenger\AbstractDoctrineMiddleware->handle(object(Envelope), object(TraceableStack))
     (vendor/symfony/messenger/Middleware/ValidationMiddleware.php:48)
  at Symfony\Component\Messenger\Middleware\ValidationMiddleware->handle(object(Envelope), object(TraceableStack))
     (vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php:34)
  at Symfony\Component\Messenger\Middleware\FailedMessageProcessingMiddleware->handle(object(Envelope), object(TraceableStack))
     (vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php:68)
  at Symfony\Component\Messenger\Middleware\DispatchAfterCurrentBusMiddleware->handle(object(Envelope), object(TraceableStack))
     (vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php:48)
  at Symfony\Component\Messenger\Middleware\RejectRedeliveredMessageMiddleware->handle(object(Envelope), object(TraceableStack))
     (vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php:37)
  at Symfony\Component\Messenger\Middleware\AddBusNameStampMiddleware->handle(object(Envelope), object(TraceableStack))
     (vendor/symfony/messenger/Middleware/TraceableMiddleware.php:43)
  at Symfony\Component\Messenger\Middleware\TraceableMiddleware->handle(object(Envelope), object(TraceableStack))
     (vendor/symfony/messenger/MessageBus.php:77)
  at Symfony\Component\Messenger\MessageBus->dispatch(object(Envelope), array())
     (vendor/symfony/messenger/TraceableMessageBus.php:41)
  at Symfony\Component\Messenger\TraceableMessageBus->dispatch(object(Envelope))
     (vendor/api-platform/core/src/Bridge/Symfony/Messenger/DispatchTrait.php:44)
  at ApiPlatform\Core\Bridge\Symfony\Messenger\DataPersister->dispatch(object(Envelope))
     (vendor/api-platform/core/src/Bridge/Symfony/Messenger/DataPersister.php:80)
  at ApiPlatform\Core\Bridge\Symfony\Messenger\DataPersister->persist(object(ChangeItemQuantityInCart), array('resource_class' => 'App\\Entity\\Order\\Order', 'has_composite_identifier' => false, 'identifiers' => array('tokenValue' => array('App\\Entity\\Order\\Order', 'tokenValue')), 'item_operation_name' => 'shop_change_quantity', 'previous_data' => object(Order), 'receive' => true, 'respond' => true, 'persist' => true))
     (vendor/api-platform/core/src/DataPersister/ChainDataPersister.php:59)
  at ApiPlatform\Core\DataPersister\ChainDataPersister->persist(object(ChangeItemQuantityInCart), array('resource_class' => 'App\\Entity\\Order\\Order', 'has_composite_identifier' => false, 'identifiers' => array('tokenValue' => array('App\\Entity\\Order\\Order', 'tokenValue')), 'item_operation_name' => 'shop_change_quantity', 'previous_data' => object(Order), 'receive' => true, 'respond' => true, 'persist' => true))
     (vendor/api-platform/core/src/Bridge/Symfony/Bundle/DataPersister/TraceableChainDataPersister.php:58)
  at ApiPlatform\Core\Bridge\Symfony\Bundle\DataPersister\TraceableChainDataPersister->persist(object(ChangeItemQuantityInCart), array('resource_class' => 'App\\Entity\\Order\\Order', 'has_composite_identifier' => false, 'identifiers' => array('tokenValue' => array('App\\Entity\\Order\\Order', 'tokenValue')), 'item_operation_name' => 'shop_change_quantity', 'previous_data' => object(Order), 'receive' => true, 'respond' => true, 'persist' => true))
     (vendor/api-platform/core/src/EventListener/WriteListener.php:76)
  at ApiPlatform\Core\EventListener\WriteListener->onKernelView(object(ViewEvent), 'kernel.view', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(ViewEvent), 'kernel.view', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.view', object(ViewEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(ViewEvent), 'kernel.view')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(ViewEvent), 'kernel.view')
     (vendor/symfony/http-kernel/HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:25)
```

Tracking down the error:
This doctrine query fails because doctrine runs the query with version 1 while it is actually 2 in database.
```sql
UPDATE sylius_order_item SET quantity = ?, total = ?, version = version + 1 WHERE id = ? AND version = ?
```

**Comment by Zales0123** [comment]
Thanks for the report @Dragnucs, we will try to reproduce it and come back to you with some feedback. @lchrusciel can you take a look at it?

**Comment by nicolalazzaro** [comment]
Hi @Dragnucs, I reproduced what you described from a clean install of Sylius (1.11.10) but the quantity update works fine. Can you tell us if you have made any changes that may have affected the behavior of this endpoint?

**Comment by TheMilek** [comment]
Hello @Dragnucs! 🚀 
I must agree with @nicolalazzaro I could not reproduce the problem 🤷🏽‍♂️.
Could you provide some additional information as @nicolalazzaro said and also which exact Sylius version you are using?
cheers 🍻

**Comment by Dragnucs** [comment]
I have of course enabled the API and added some serialization configuration:

```yaml
Sylius\Component\Product\Model\ProductOption:
  attributes:
    id:
      groups: [admin:product:read, shop:product:read]
    code:
      groups: [admin:product:read, shop:product:read]
    values:
      groups: [admin:product:read, shop:product:read]

Sylius\Component\Product\Model\ProductOptionValue:
  attributes:
    id:
      groups: [admin:product:read, shop:product:read]
    value:
      groups: [admin:product:read, shop:product:read]
    code:
      groups: [admin:product:read, shop:product:read]

Sylius\Component\Core\Model\ProductTaxon:
  attributes:
    id:
      groups: [admin:product:read, shop:product:read]
    taxon:
      groups: [admin:product:read, shop:product:read]

Sylius\Component\Core\Model\Taxon:
  attributes:
    id:
      groups: [admin:product:read, shop:product:read]
    code:
      groups: [admin:product:read, shop:product:read]
    name:
      groups: [admin:product:read, shop:product:read]
    slug:
      groups: [admin:product:read, shop:product:read]

Sylius\Component\Core\Model\ProductVariant:
  attributes:
    id:
      groups: [admin:product:read, shop:product:read]
    code:
      groups: [admin:product:read, shop:product:read]
    name:
      groups: [admin:product:read, shop:product:read]
    price:
      groups: [admin:product:read, shop:product:read]
    originalPrice:
      groups: [admin:product:read, shop:product:read]
    optionValues:
      groups: [admin:product:read, shop:product:read]


App\Entity\Channel\Channel:
  attributes:
    id: [shop:cart:read, shop:cart:update, shop:order:account:read, shop:address:read, shop:address:update, shop:order:account:read, shop:cart:read, shop:cart:update, shop:order_item:read]
    code: [shop:cart:read, shop:cart:update, shop:order:account:read, shop:address:read, shop:address:update, shop:order:account:read, shop:cart:read, shop:cart:update, shop:order_item:read]

Sylius\Component\Core\Model\Order:
  attributes:
    channel:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    promotionCoupon:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    promotions:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    shipments:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    pickupAddress:
      expose: true
      groups: [shop:cart:read, shop:cart:update, shop:order:account:read]
    pickupDateTime:
      expose: true
      groups: [shop:cart:read, shop:cart:update, shop:order:account:read, shop:address:read, shop:address:update, shop:order:account:read, shop:cart:read, shop:cart:update, shop:order_item:read]
    shippingDateTime:
      expose: true
      groups: [shop:cart:read, shop:cart:update, shop:order:account:read, shop:address:read, shop:address:update, shop:order:account:read, shop:cart:read, shop:cart:update, shop:order_item:read]
    state:
      groups: [shop:cart:read, shop:order:read, shop:order:account:read]
    createdAt:
      groups: [shop:order:read]
    checkoutCompletedAt:
      groups: [shop:order:read]
    zone:
      groups: [shop:cart:read, shop:order:read, shop:order:account:read]

App\Command\Checkout\UpdateCart:
  attributes:
    pickupAddress:
      groups: [shop:cart:read, shop:cart:update, shop:order:account:read]
    pickupDateTime:
      groups: [shop:cart:read, shop:cart:update, shop:order:account:read]
    shippingDateTime:
      groups: [shop:cart:read, shop:cart:update, shop:order:account:read]
    zone:
      groups: [shop:cart:read, shop:cart:update, shop:order:account:read]

App\Command\Checkout\CompelteOrder:
  attributes:
    couponCode:
      groups: [shop:cart:read, shop:cart:complete]

Sylius\Component\Core\Model\OrderItem:
  attributes:
    images:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    variantName:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    version:
      groups: [shop:cart:read, shop:cart:change_quantity, shop:order_item:read, shop:order:account:read]

Sylius\Component\Core\Model\ProductVariant:
  attributes:
    id:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    images:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    code:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    optionValues:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]

Sylius\Component\Product\Model\ProductOptionValue:
  attributes:
    id:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    value:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    code:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]

Sylius\Component\Core\Model\Image:
  attributes:
    path:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]

Sylius\Component\Core\Model\PromotionCoupon:
  attributes:
    id:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    code:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]

Sylius\Component\Core\Model\Promotion:
  attributes:
    id:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    code:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    name:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    couponBased:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]

Sylius\Component\Core\Model\PaymentMethod:
  attributes:
    id:
      groups: [shop:cart:read, shop:order_item:read]
    name:
      groups: [shop:cart:read, shop:order_item:read]
    code:
      groups: [shop:cart:read, shop:order_item:read]

Sylius\Component\Core\Model\ShippingMethod:
  attributes:
    id:
      groups: [shop:cart:read, shop:order_item:read]
    name:
      groups: [shop:cart:read, shop:order_item:read]
    code:
      groups: [shop:cart:read, shop:order_item:read]
    description:
      groups: [shop:cart:read, shop:order_item:read]
    price:
      groups: [shop:cart:read, shop:order_item:read]
    calculator:
      groups: [shop:cart:read, shop:order_item:read]
    configuration:
      groups: [shop:cart:read, shop:order_item:read]
    version:
      groups: [shop:cart:read, shop:order_item:read, shop:cart:change_quantity]

Sylius\Component\Core\Model\Payment:
  attributes:
    id:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    amount:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    currencyCode:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    state:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]

Sylius\Component\Core\Model\Shipment:
  attributes:
    id:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    tracking:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    shippedAt:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]
    state:
      groups: [shop:cart:read, shop:order_item:read, shop:order:account:read]

Sylius\Component\Core\Model\Address:
  attributes:
    longitude:
      groups: [shop:address:read, shop:address:update, shop:order:account:read, shop:cart:read, shop:cart:update, shop:order_item:read]
    latitude:
      groups: [shop:address:read, shop:address:update, shop:order:account:read, shop:cart:read, shop:cart:update, shop:order_item:read]
    phoneNumber:
      groups: [shop:address:read, shop:address:update, shop:order:account:read, shop:cart:read, shop:cart:update, shop:order_item:read]

Sylius\Component\Core\Model\Customer:
  attributes:
    defaultAddress:
      groups: [shop:address:read, shop:address:update, shop:order:account:read, shop:cart:read, shop:cart:update, shop:order_item:read]
```

```yaml
# config/packages/api_platform.yaml
api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Resources/config/api_resources'
            - '%kernel.project_dir%/config/api_platform'
            - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
      fetch_partial: false
```
