### ISSUE TITLE
Error when trying to add step to sylius_order_checkout state machine

### ISSUE THREAD

**Issue by Rayzen-dev** [Sylius/Sylius#14455]
When I try to customizing checkout process to add a step, I got this error : `Unable to generate a URL for the named route "sylius_order_index" as such route does not exist`. I have a correct flow to access my custom step, the action update my cart correctly BUT I can't go to the next step. So I have this config:
```
# state_machine.yaml
 sylius_order_checkout:
        states:
            company_selected: ~
        transitions:
            address:
                from: [ cart, addressed, company_selected, shipping_selected, shipping_skipped, payment_selected, payment_skipped ]
                to: addressed
            company:
                from: [ addressed, shipping_selected, shipping_skipped, payment_selected, payment_skipped ]
                to: company_selected
            skip_shipping:
                from: [ company_selected ]
                to: shipping_skipped
            select_shipping:
                from: [ company_selected, shipping_selected, payment_selected, payment_skipped ]
                to: shipping_selected
        callbacks:
            after:
                sylius_process_cart:
                    on: [ "select_shipping", "address", "company", "select_payment", "skip_shipping", "skip_payment" ]
                    do: [ "@sylius.order_processing.order_processor", "process" ]
                    args: [ "object" ]
                    priority: -200
                sylius_skip_shipping:
                    on: [ "company" ]
                    do: [ "@sylius.state_resolver.order_checkout", "resolve" ]
                    args: [ "object" ]
                    priority: -100
```

```
# _sylius.yaml
sylius_shop:
    checkout_resolver:
        route_map:
            addressed:
                route: sylius_shop_checkout_select_company
            company_selected:
                route: sylius_shop_checkout_select_shipping
    product_grid:
        include_all_descendants: true
    locale_switcher: storage
```
I tried to do [this solution](https://stackoverflow.com/a/60184895) but did not work.

So... I would like to know where is the mistake ?

Thanks in advance.

**Comment by GSadee** [comment]
Hi @Rayzen-dev, 
thank you for reporting an issue, but I have probably not enough information to reproduce that, I would encourage you to join to [our Slack](https://sylius-slackin.herokuapp.com/) and find help there as it is most probably the problem with your customization. Feel free to open a new issue if you find a problem with Sylius codebase.

**Comment by Prometee** [comment]
Hello @Rayzen-dev,

You covered all your needs with the state machine config, the resolver config and the addition of the service tag, maybe you didn't clear the cache after trying to add the additional tag.

Some tips though :

- All Symfony bundle configurations are merged at the end of the process, meaning you don't need to add the config already defined.
- Be aware of the fact that you can't replace the already defined array elements inside winzou state machine config, you will need to create a `CompilerPass` to edit manually the array contained inside the parameter `sm.configs`.

About your actual configuration, you can shrink it like this :

```yaml
# state_machine.yaml
 sylius_order_checkout:
        states:
            company_selected: ~
        transitions:
            address:
                from: [ company_selected ]
            company:
                from: [ addressed, shipping_selected, shipping_skipped, payment_selected, payment_skipped ]
                to: company_selected
            skip_shipping:
                from: [ company_selected ] # will be merge so the result will be [addressed, company_selected]
            select_shipping:
                from: [ company_selected ]
        callbacks:
            after:
                sylius_process_cart:
                    on: [ "select_shipping" ]
                sylius_skip_shipping:
                    on: [ "company" ] # will be merge so the result will be [addressed, company_selected]
```

Using a `CompilerPass` to add the required tags :

```php
<?php

declare(strict_types=1);

namespace App\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class SyliusCheckoutCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        // On post company checkout submit inform the checkout_redirecter that we can handle the redirection
        $definition = $container->getDefinition('sylius.listener.checkout_redirect');
        $definition->addTag('kernel.event_listener', [
            'event' => 'sylius.order.post_company',
            'method' => 'handleCheckoutRedirect',
        ]);

        // Override the winzou_state_machine config to reduce the transitions on "skip_shipping"
        // Not really needed in you case but here is an example
        /** @var array $parameter */
        // $parameter = $container->getParameter('sm.configs');
        // $skip_shipping_transitions = $container->getParameter('my_custom_app_company_transitions_override_parameter');
        // or set directly you array here
        // $skip_shipping_transitions = ['company_selected']
        // $parameter['sylius_order_checkout']['transitions']['skip_shipping']['from'] = $skip_shipping_transitions;
        // $parameter['sylius_order_checkout']['callbacks']['after']['sylius_skip_shipping']['on'] = $skip_shipping_transitions;
        // $container->setParameter('sm.configs', $parameter);
    }
}
```

To be sure you set the right config, use this command to see how your config is processed :

```bash
./bin/console debug:winzou:state-machine sylius_order_checkout
```
