### ISSUE TITLE
Slow order grid, paginator select with DISTINCT twice

### ISSUE THREAD

**Issue by gebi84** [Sylius/Sylius#15013]
**Sylius version affected**: 1.12.7

**Description**  
paginator generates slow query with 2 distinct

**Steps to reproduce**  
Install 1.12.7
Insert 850k orders and go to /admin/orders

this sql query needs 30 seconds to execute:
```sql
SELECT DISTINCT id_9 FROM (SELECT DISTINCT id_9, number_0 FROM (SELECT s0_.number AS number_0, s0_.notes AS notes_1, s0_.state AS state_2, s0_.checkout_completed_at AS checkout_completed_at_3, s0_.items_total AS items_total_4, s0_.adjustments_total AS adjustments_total_5, s0_.total AS total_6, s0_.created_at AS created_at_7, s0_.updated_at AS updated_at_8, s0_.id AS id_9, s0_.currency_code AS currency_code_10, s0_.locale_code AS locale_code_11, s0_.checkout_state AS checkout_state_12, s0_.payment_state AS payment_state_13, s0_.shipping_state AS shipping_state_14, s0_.created_by_guest AS created_by_guest_15, s0_.token_value AS token_value_16, s0_.customer_ip AS customer_ip_17, s1_.email AS email_18, s1_.email_canonical AS email_canonical_19, s1_.first_name AS first_name_20, s1_.last_name AS last_name_21, s1_.birthday AS birthday_22, s1_.gender AS gender_23, s1_.created_at AS created_at_24, s1_.updated_at AS updated_at_25, s1_.phone_number AS phone_number_26, s1_.subscribed_to_newsletter AS subscribed_to_newsletter_27, s1_.id AS id_28 FROM sylius_order s0_ LEFT JOIN sylius_customer s1_ ON s0_.customer_id = s1_.id LEFT JOIN sylius_order_item s2_ ON s0_.id = s2_.order_id LEFT JOIN sylius_product_variant s3_ ON s2_.variant_id = s3_.id LEFT JOIN sylius_product s4_ ON s3_.product_id = s4_.id WHERE s0_.state <> 'cart') dctrn_result_inner ORDER BY number_0 DESC, id_9 ASC) dctrn_result LIMIT 10;
```
![image](https://user-images.githubusercontent.com/805019/235915371-5b4b7652-31ff-4941-82a8-f8b4c7bd33f0.png)

I think the Problem is here: https://github.com/doctrine/orm/blob/1142a396d36e0c9b33ff13875f2833d8386d8f66/lib/Doctrine/ORM/Tools/Pagination/LimitSubqueryOutputWalker.php#L262

**Comment by shinyvision** [comment]
It looks like this behavior can be turned off in the grid configuration, but I'm not sure how much this will help.

```yaml
# config/packages/sylius_grid.yaml
sylius_grid:
    grids:
        sylius_admin_order:
            driver:
                options:
                    class: "%sylius.model.order.class%"
                    repository:
                        method: createSearchListQueryBuilder
                    pagination:
                        fetch_join_collection: false
                        use_output_walkers: false
```

I don't have 850k orders in my database yet, so maybe someone can test this out to see if this solves the problem (or maybe creates more problems?)
