### ISSUE TITLE
Image uploader

### ISSUE THREAD

**Issue by AlexandreGerault** [Sylius/Sylius#15082]
**Sylius docs version**: 1.12

**Description**
My goal is to add images to an entity that would get stored on a s3 storage. Thus I read [this page](https://docs.sylius.com/en/1.12/cookbook/images/images-on-entity.html) to get how to add images to an entity. I just had to do some tweaks to get a listener to run as I wasn't adding images to the persisted entity directly (I used [doctrine entity listener](https://symfony.com/doc/current/doctrine/events.html#doctrine-entity-listeners)). Thus, the `images.uploader` service got used to upload the image on the `sylius.storage` (had to deep in vendor files and play with service xml configuration and some `bin/console debug:container` command calls to figure it out). The `path` property then got set as `dd/xx/xxxx.jpg`.

My problem is that, I have no file corresponding there. I've this flysystem configuration:
```yaml
flysystem:
    storages:
        sylius.storage:
            adapter: 'aws'
            options:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET)%'
                prefix: "media/image"
                streamReads: true
```
I ensure you the s3 client is working well as being used by another flysystem storage. Then I wonder why there are no files at `my-bucket.s3-endpoint.com/media/image/dd/xx/xxxx.jpg`. There are a lot of images stored there (like men with a bike or motocycle etc), but none from the one I uploaded.

Thing is there is not much documentation about this and I tried to debug it also, but can't figure out if it's a bug or something undocumented not behaving as I would expect
