### ISSUE TITLE
API Product position sorting is not applied

### ISSUE THREAD

**Issue by Dragnucs** [Sylius/Sylius#15090]
**Sylius version affected**: 1.11

**Description**  
Using the API and customizing product positions for a particular taxon, they are not applied when querying products for given taxon.

**Steps to reproduce**  
1. Assign at least two products to a taxon
2. Set custom positions for products
3. Query products using API

**Possible Solution**  
N/A

**Comment by Dragnucs** [comment]
I was able to fix this by configuring an order filter service like this:
```yaml
sylius.api.product_order_filter:
    parent: 'api_platform.doctrine.orm.order_filter'
    arguments: [ { code: ~, createdAt: ~, productTaxons.position: 'ASC' } ]
    tags: ['api_platform.filter']
```
