### ISSUE TITLE
phpcr_backend default parameters.

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#1522]
When I composer install:

``` bash
$ composer install
Updating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
phpcr_backend ({ type: doctrinedbal, connection: default, caches: { meta: doctrine_cache.providers.phpcr_meta, nodes: doctrine_cache.providers.phpcr_nodes } }): 
phpcr_workspace (default): 
phpcr_user (admin): 
phpcr_pass (admin): 
```

Generated value

``` yml
phpcr_backend: "\e"
phpcr_workspace: default
phpcr_user: admin
phpcr_pass: admin
```

The error

```
  [Symfony\Component\Config\Definition\Exception\InvalidTypeException]                                     
  Invalid type for path "doctrine_phpcr.session.sessions.default.backend". Expected array, but got string  
```
