### ISSUE TITLE
[API] Disabling endpoints leads to error

### ISSUE THREAD

**Issue by dsbe-ak** [Sylius/Sylius#15448]
Sylius version affected: 1.12.11 (tested with this version, probably also older versions are affected)

**Description**  
Disabling the following shop API endpoints leads to warning _"foreach() argument must be of type array|object, null given"_ when calling **/api/v2/docs**
  
```
'%sylius.model.product_image.class%':
     itemOperations:
        shop_get:
            enabled: false

'%sylius.model.product.class%':
    itemOperations:
        shop_get_by_slug:
            enabled: false
```

Affected files:
vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Swagger/ProductImageDocumentationNormalizer.php
vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Swagger/ProductSlugDocumentationNormalizer.php

**Steps to reproduce**  

1. create **config.yaml** file in **config/api_platform/** with the disabled endpoints
2. clear cache
3. call **/api/v2/docs**

**Possible Solution**  
Check if path is set in docs array before foreach
