### ISSUE TITLE
SwaggerUiAction PKCE enabled not working

### ISSUE THREAD

**Issue by Prometee** [Sylius/Sylius#15459]
**Sylius version affected**: 1.12

**Description**  
When you enable OAuth configuration on api_platform, the replaced service : `api_platform.swagger.action.ui` is not handling PKCE configuration correctly. It avoid the Swagger UI displaying and handling pkce oauth connection properly.

**Steps to reproduce**
Use this kind of APIP OAuth configuration :

```yaml
api_platform:
    oauth:
        enabled: true
        clientId: '.........'
        pkce: true
        type: 'oauth2'
        flow: 'authorizationCode'
        tokenUrl: '/oauth/v2/token'
        authorizationUrl: '/oauth/v2/authorize'
        scopes:
            EMAIL: Request access to the email
```
Open `/api/v2` page and click authorize top right button, you won't be able to see any mention of PKCE usage.

**Possible Solution**

- Try to decorates the original APIP service
- Or update the replaced service with the latest version of the `ApiPlatform\Symfony\Bundle\SwaggerUi\SwaggerUiAction`
