### ISSUE TITLE
How do you make an existing Sylius resource translatable?

### ISSUE THREAD

**Issue by martynasjo** [Sylius/Sylius#15567]
I'm trying to add a translatable field to `ProductImage` resource, but I cannot register the newly created translation resource as a product image translation because the configuration tree of Sylius core bundle does not allow to add a `translation` field to `ProductImage`.

My `sylius_core` configuration:
```
sylius_core:
    resources:
        product_image:
            classes:
                model: App\Entity\ProductImage
            translation:
                classes:
                    model: App\Entity\ProductImageTranslation
```

Resulting in:
![image](https://github.com/Sylius/Sylius/assets/55277384/5fc07633-f9fd-47ca-8dcb-d716e49532c4)

How do I override the specified configuration tree?
