### ISSUE TITLE
Duplicated /ship route

### ISSUE THREAD

**Issue by Geolim4** [Sylius/Sylius#15790]
**Sylius version affected**: 1.12.x

**Description**  
Hello,

I noticed a duplicated `/ship` route in the admin area:
```yml
# order.yml
sylius_admin_order_shipment_ship:
    path: /orders/{id}/ship
    methods: [PUT]
    defaults:
        _controller: sylius.controller.shipment::updateAction
        _sylius:
            event: ship
            repository:
                method: findOneByOrderId
                arguments:
                    id: $id
                    orderId: $orderId
            state_machine:
                graph: sylius_shipment
                transition: ship
            redirect: referer
            section: admin
            permission: true
            form: Sylius\Bundle\ShippingBundle\Form\Type\ShipmentShipType
            vars:
                route:
                    parameters:
                        orderId: $orderId
                        id: $id
```

and

```yml
# shipment.yml
sylius_admin_shipment_ship:
    path: /shipments/{id}/ship
    methods: [PUT]
    defaults:
        _controller: sylius.controller.shipment::updateAction
        _sylius:
            event: ship
            section: admin
            permission: true
            state_machine:
                graph: sylius_shipment
                transition: ship
            redirect: referer
            flash: sylius.shipment.shipped
            form: Sylius\Bundle\ShippingBundle\Form\Type\ShipmentShipType
```

Is there any particular reason for this duplicate ?

**Comment by jakubtobiasz** [comment]
Hi @Geolim4,
1. It is created with different parts of the system in mind, so you can adjust it better if needed.
2. In the first one, you pass the **order id** and it ships the first shipment for it. In the second one you pass the **shipment id** to be shipped.

**Comment by Geolim4** [comment]
Hello,

I can understand that, but don't you think that duplicate could be removed in favor of the second one ?

They're both doing the same thing on different endpoint.

This could be unified to reduce maintenance debt :)

**Comment by jakubtobiasz** [comment]
It's not duplicated. Duplication is a situation when you have two things doing the same. Here we have two endpoints, doing the same, but in different ways (the first endpoint uses the order to find the shipment, the second one just gets the shipment id via the URL.

**Comment by Geolim4** [comment]
> It's not duplicated. Duplication is a situation when you have two things doing the same. Here we have two endpoints, doing the same, but in different ways (the first endpoint uses the order to find the shipment, the second one just gets the shipment id via the URL.

I think you did not had a look at the code 😇
Both the endpoint are running the `sylius_shipment:ship` transition.
Both endpoint are full-fulling the order in cascade by transitioning the shipment to "shipped".

**Comment by jakubtobiasz** [comment]
![CleanShot 2024-02-01 at 11 18 02@2x](https://github.com/Sylius/Sylius/assets/80641364/b6a8322d-407e-4b1d-ad93-21929ba01505)
The first one is using another repository method. They **are not** the same due to that fact. They do the same in the same way, but from the frontend (or UI) perspective, they are not the same. 

If you read the URL, you get:
1. Ship the shipment for the order with (id)
2. Ship the shipment with (id)

**Comment by jakubtobiasz** [comment]
@NoResponseMate pointed out to me the
```
            repository:
                method: findOneByOrderId
                arguments:
                    id: $id
                    orderId: $orderId
```
part is at least "weird". I missed the fact we pass the shipment id there too. We'll investigate the origin of these two endpoints, and discuss the existence of them. I bet the order's one is malformed, but I'll update you once we have something new to share.
