### ISSUE TITLE
Finite configuration issue

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#1591]
This may be the Finite issue, but I am posting it here first since maybe someone from our awesome community already faced it.

I have custom core bundle in my Sylius app, and have `src/Umpirsky/Bundle/CoreBundle/Resources/config/finite.yml` file where I override:

``` yml
finite_finite:
    sylius_order_shipping:
...
```

The problem is that `sylius_payment` callbacks are not loaded at all for some reason. And when I put:

``` yml
    sylius_payment:
        callbacks:
            after:
                sylius_update_order:
                    on:   'complete'
                    do:   [@sylius.callback.order_payment, 'updateOrderOnPayment']
                    args: ['object']
```

here it gets loaded twice, once under `sylius_update_order` key in array loader and once under `0` key. :confounded: So its called twice.

Am I doing something wrong or this is a bug in Finite?
