### ISSUE TITLE
products order in the front-end is not showing in descending order ( the latest to the oldest) of the createdAt date only in production.

### ISSUE THREAD

**Issue by Manasmd** [Sylius/Sylius#16217]
I am trying to sort orders by createdAt date and it is very weird that this configuration is not only working for the production environment but it seems to work for local and preprod. I am also using this filter plugin for the front-end and I am not sure if this is clashing with the configuration comin from the YAML file. Regardless, I think if local and preprod is working fine with the AsdoriaSyliusFacetFilterPlugin, it should work fine in production too. 
https://github.com/asdoria/AsdoriaSyliusFacetFilterPlugin

Here's what I have tried in production so far. 

1. Added this configuration in sylius_shop_product.yaml config > packages > sylius_shop_product.yaml:

```
sylius_grid:
    grids:
        sylius_shop_product:
            filters:
                facets_filters:
                    type: facets_filters
                    label: true
                    options:
                        owner: taxon
            sorting: //this was recently added so as to set the default order to be in desc of the createdAt date
                createdAt: desc      

```
After adding the "sorting: createdAt: desc" the default order on the E-shop catalogue page seems to be working only for local and preprod environments but not for production. 

2. I also ran the following commands to make sure the cache is properly cleared:
```
php bin/console cache:clear

 php bin/console doctrine:cache:clear-metadata 
 php bin/console doctrine:cache:clear-query  
 php bin/console doctrine:cache:clear-result
 
```

overall, What I am trying to achieve is to display the production in descending order of the createdAt date.
