### ISSUE TITLE
Cookbook error advanced-sylius-cloud-configuration.rst

### ISSUE THREAD

**Issue by TakesTheBiscuit** [Sylius/Sylius#16390]
**Sylius docs version**:  latest

**Description**
https://github.com/Sylius/Sylius/blob/1.14/docs/cookbook/deployment/advanced-sylius-cloud-configuration.rst

I think the CRONS section is wrong

```
crons:
    cancel-unpaid-orders:
        spec: "0 2 * * *"
        cmd: "php bin/console sylius:cancel-unpaid-orders"
    generate-promotion-coupons:
        spec: "0 2 * * *"
        cmd: "php bin/console sylius:promotion:generate-coupons"
    remove-expired-carts:
        spec: "0 2 * * *"
        cmd: "php bin/console sylius:cancel-unpaid-orders"
```

Should it be:
```
crons:
    cancel-unpaid-orders:
        spec: "0 2 * * *"
        cmd: "php bin/console sylius:cancel-unpaid-orders"
    generate-promotion-coupons:
        spec: "0 2 * * *"
        cmd: "php bin/console sylius:promotion:generate-coupons"
    remove-expired-carts:
        spec: "0 2 * * *"
        cmd: "php bin/console >??? sylius:remove-expired-carts ??? <"
```
