### ISSUE TITLE
Add API platform search filter for order.number

### ISSUE THREAD

**Issue by jaroslavtyc** [Sylius/Sylius#16503]
**Describe the proposed solution**
Add API platform search filter for `order.number`

**Describe alternatives you've considered**
Currently we need to make this by ourselves.

I have personally replaced original **order by** filter by **search by**
```yaml
# config/services.yaml
    'app.api.order_number_filter':
        decorates: 'sylius.api.order_number_filter'
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments:
            $properties: { 'number': 'exact' }
        tags: [ 'api_platform.filter' ]
```

**Additional context**
I consider this as a developer (easy to make) mistake because of confusing order meaning
- order => sort
- order => purchase
which led to `Order` **search** filters with a silently lurked **order by** filter `sylius.api.order_number_filter`
```xml
                <attribute name="filters">
                    <attribute>sylius.api.order_channel_filter</attribute>
                    <attribute>sylius.api.order_currency_filter</attribute>
                    <attribute>sylius.api.order_customer_filter</attribute>
                    <attribute>sylius.api.order_date_filter</attribute>
                    <attribute>sylius.api.order_number_filter</attribute>
                    <attribute>sylius.api.order_product_filter</attribute>
                    <attribute>sylius.api.order_shipping_method_filter</attribute>
                    <attribute>sylius.api.order_total_filter</attribute>
                    <attribute>sylius.api.order_variants_filter</attribute>
                </attribute>
```

To keep backward compatibility we should keep (still a bit confusing) `sylius.api.order_number_filter` untouched and add a new  `sylius.api.order_search_number_filter` with parent `api_platform.doctrine.orm.search_filter`
