### ISSUE TITLE
Unused config/api_platform/config.yaml

### ISSUE THREAD

**Issue by jaroslavtyc** [Sylius/Sylius#16504]
**Sylius version affected**: 1.10 ... 1.14

**Description**  
Sylius documentation clearly mentions `config/api_platform/config.yaml` API platform customization config file.

Another Sylius documentation indirectly says that `config/api_platform/config.yaml` should be used automatically for Sylius 1.11+

But that file is not used at all, until manual change of basic API platform config is made

```yaml
# config/packages/api_platform.yaml
api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
```

**Steps to reproduce**  
- install latest Sylius by `composer create-project sylius/sylius-standard MyFirstShop`
  - https://docs.sylius.com/en/1.12/getting-started-with-sylius/installation.html#project-setup
- change API platform configuration via `config/api_platform/config.yaml`
  - https://docs.sylius.com/en/1.13/customization/api/customizing_endpoints_using_yaml.html#configuring-endpoints-using-yaml
```yaml
'%sylius.model.zone.class%':
    collectionOperations:
        admin_get:
            enabled: false
```
- clear cache `rm -fr var/cache`
- run OpenAPI
```
symfony serve
open http://127.0.0.1:8000/api/v2
```
- check that `GET /api/v2/admin/zones` API endpoint still exists in OpenAPI
- check that `bin/console debug:router | grep /api/v2/admin/zones` endpoints still exist in routing

**Possible Solution**  
- add empty `config/api_platform/config.yaml` file **and** links the dir `config/packages/api_platform.yaml`
```yaml
api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
```
in sylius/sylius repository
