### ISSUE TITLE
[RFC] Adding filters form automatically into the indexAction

### ISSUE THREAD

**Issue by aRn0D** [Sylius/Sylius#1668]
We can not manage filter form automatically in the resource bundle. It is what I propose that we could introduce this feature into it. 

We can add an extra option named `filter` to the configuration of the resource bundle (if someone has better name, I listen), it should look like :

```yaml
sylius_resource:
    resources:
        sylius.user:
	    model: ...
            controller: ...
	    filter: My\Filter\Form\type # It could be define as a service too.
```

We could add an extra method to the `ResourceController` named `getFilterForm`. It will ask to the `Configuration` is the form is define, if it is the case it should create and bind request to it. It should be call in the `indexAction` and the form view need to assign to the view. It could look like :

```php
class ResourceController
{
    // ...

    public function indexAction(Request $request)
    {
        $view = $this
            ->view()
            ->setTemplate($this->config->getTemplate('index.html'))
            ->setData(array(
                $this->config->getPluralResourceName() => $resources,
                'filterForm' => $this->getFilterForm($request)->createView(),
            )
        ;
    }

    public function getFilterForm(Request $request = null)
    {
        if (null !== $formName = $this->config->getFilterForm() {
            return $this->createForm($formName)->submit($request);
        }
    }

    // ...
}
```
What do you think, guys ? It is not a priority and it could mark as "Easy pick" ?
