### ISSUE TITLE
How to extend user update form ?

### ISSUE THREAD

**Issue by patie** [Sylius/Sylius#1693]
Hi,

im trying extend user update form for backend,

in routes i have
```
app_backend_user_update:
    pattern: /update/{id}
    methods: [GET, PUT, POST]
    defaults:
        _controller: app_backend.controller.user:updateAction
        _sylius:
            template: BackendBundle:User:update.html.twig
            redirect: sylius_backend_user_show
            form: app_backend_user_update
```
but what else ? i think i need register my form as service with class argument %sylius.model.user.class%, anything else please ? thx
