### ISSUE TITLE
[Bug] Class 'Sylius\Component\Order\Model\OrderInterface' does not exist

### ISSUE THREAD

**Issue by emgiezet** [Sylius/Sylius#1700]
Hello!

I'm writing my some shop on sf2.3 and I decided to use the SyliusCartBundle.

The docs were kida a compleate but not for version 0.10.

I configured all bundles:

``` yaml

sylius_cart:
    resolver: bounce_store.item_resolver # The id of our newly created service.
    classes: ~
sylius_order:
    driver: doctrine/orm # Configure the doctrine orm driver used in documentation.
    classes:
        order: ~
        order_item:
            model: Bounce\StoreBundle\Entity\CartItem # If you have created a custom CartItem entity.

sylius_money:
    driver: doctrine/orm # Configure the doctrine orm driver used in documentation.

```

```
  [Doctrine\Common\Persistence\Mapping\MappingException]              
  Class 'Sylius\Component\Order\Model\OrderInterface' does not exist

```

Here is my Mapping:

```
Found 25 mapped entities:
[OK]   Bounce\StoreBundle\Entity\CartItem
[OK]   Gedmo\Translatable\Entity\MappedSuperclass\AbstractTranslation
[OK]   Gedmo\Translatable\Entity\MappedSuperclass\AbstractPersonalTranslation
[OK]   Gedmo\Translator\Entity\Translation
[OK]   Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry
[OK]   Gedmo\Tree\Entity\MappedSuperclass\AbstractClosure
[OK]   Bounce\CoreBundle\Entity\Product
[OK]   Bounce\CoreBundle\Entity\GalleryCategory
[OK]   Bounce\CoreBundle\Entity\User
[OK]   Bounce\CoreBundle\Entity\GalleryImage
[OK]   Bounce\CoreBundle\Entity\UserOrder
[OK]   Bounce\CoreBundle\Entity\UserOrderItem
[OK]   Bounce\CoreBundle\Entity\Color
[OK]   Bounce\CoreBundle\Entity\Category
[OK]   Bounce\CoreBundle\Entity\Group
[OK]   Sonata\UserBundle\Entity\BaseGroup
[OK]   Sonata\UserBundle\Entity\BaseUser
[OK]   FOS\UserBundle\Entity\Group
[OK]   FOS\UserBundle\Entity\User
[OK]   Sylius\Component\Money\Model\ExchangeRate
[OK]   Sylius\Component\Order\Model\OrderItem
[OK]   Sylius\Component\Order\Model\Order
[OK]   Sylius\Component\Order\Model\Adjustment
[OK]   Sylius\Component\Cart\Model\CartItem
[OK]   Sylius\Component\Cart\Model\Cart
```

And this is my CartItem entity:

``` php
<?php
/**
 * Created by PhpStorm.
 * User: mgz
 * Date: 7/5/14
 * Time: 2:52 PM
 */

namespace Bounce\StoreBundle\Entity;

use Bounce\CoreBundle\Entity\Product;
use Sylius\Component\Cart\Model\CartItem as BaseCartItem;
use Doctrine\ORM\Mapping as ORM;
use Sylius\Component\Order\Model\OrderItemInterface;
use Sylius\Component\Order\Model\OrderInterface;

/**
 * Class CartItem
 * @package Bounce\CoreBundle\Entity
 * @ORM\Entity()
 * @ORM\Table(name="cart_item")
 */
class CartItem extends BaseCartItem
{
    /**
     * @var Product
     * @ORM\ManyToOne(targetEntity="Bounce\CoreBundle\Entity\Product")
     * @ORM\JoinColumn(name="product_id", referencedColumnName="id")
     */
    private $product;


    /**
     * @return Product
     */
    public function getProduct()
    {
        return $this->product;
    }

    /**
     * @param Product $product
     * @return CartItem
     */
    public function setProduct(Product $product)
    {
        $this->product = $product;
        return $this;
    }

    /**
     * @param OrderItemInterface $orderItem
     * @return bool
     */
    public function equals(OrderItemInterface $orderItem)
    {
        return $this->product === $orderItem->getProduct();
    }

    public function setOrder(OrderInterface $order = null) {

        $this->order = $order;
        return $this;

    }
}
```

Overwrite of setOrder method was a try to workaround the problem. The `OrderInterface.php` file itself is in the vendors. PHPStorm also see this interface.

What I'm doing wrong?
