### ISSUE TITLE
Internal Server Error - NonUniqueResultException 

### ISSUE THREAD

**Issue by aguzmans** [Sylius/Sylius#1712]
Hi:
I am trying to start with Sylus resource. I managed to do the index page showing all the record on my table. But the show functionality does not work. these are my routes:
```
teamerp_job_index:
    pattern: /jobs/
    defaults:
        _controller: teamerp.controller.job:indexAction    

teamerp_job_show:
    pattern: /jobs/{idJob}
    methods: [GET]
    defaults:
        _controller: teamerp.controller.job:showAction
```
and then for the show I am get the following error:
URL: http://abel.ltu.sld.cu/app_dev.php/jobs/2
Error:  500 Internal Server Error - NonUniqueResultException 
my entity is:

```
<?php
namespace TeamERP\TransportBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
/**
 * @ORM\Entity
 * @ORM\Table(name="job")
 * @ORM\Entity(repositoryClass="TeamERP\TransportBundle\Entity\JobRepository")
 */
class Job
{
    /**
     * @ORM\Column(type="integer", name="id_job")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */

    protected $idJob;
    /**
     * @ORM\Column(type="string", length=20, name="delivery_number")
     */

    protected $deliveryNo; 
    /**
     * @ORM\Column(type="datetime", name="date_time")
     */

    protected $dateTime;
    /**
     * @ORM\Column(type="string", length=200, name="destination")
     */
    protected $destination;      
    /**
     * @ORM\Column(type="float", name="km_odo_start", nullable=true)
     */   
 
    protected $kmOdoStart;   
    /**
     * @ORM\Column(type="float", name="km_odo_end", nullable=true)
     */   
 
    protected $kmOdoEnd;      
(...)
```
I do not know what is going on as The field idJob it is a unique field.
