### ISSUE TITLE
CartCollector throws 'No locale has been set and current locale is undefined' exception with new Doctrine option

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#17316]
**Sylius version affected**: 1.12

**Description**  
I have this doctrine configuration:

```yaml
# config/packages/doctrine.yaml
doctrine:
    orm:
        enable_lazy_ghost_objects: true
```

When those are enabled the `\Sylius\Bundle\CoreBundle\Collector\CartCollector` will trigger an exception like this:

![image](https://github.com/user-attachments/assets/8d4db4cc-6d7d-4586-84ba-3c430519bee4)

Notice that it's a circular exception, but I figured out that it works when I set `enable_lazy_ghost_objects` to false.

I don't have much to go on here, and it may not be a bug in Sylius, but now I've reported it at least :|
