### ISSUE TITLE
You cannot define both "component" and "template" at the same time

### ISSUE THREAD

**Issue by UrbiJr** [Sylius/Sylius#17466]
**Sylius version affected**: 2.0.0

**Description**  
I get the error "`You cannot define both "component" and "template" at the same time.`" when trying to override `sylius_shop.base.header.navbar.menu`

**Steps to reproduce**  
Just paste this in `sylius_twig_hooks.yaml`
```
        'sylius_shop.base.header.navbar':
            menu:
                template: 'shop/layout/header/navbar/menu.html.twig'
                priority: 350
```
 and hit `bin/console cache:clear` from the cmd

**Comment by UrbiJr** [comment]
edit: this is the fix for anyone having the same issue:
```
        'sylius_shop.base.header.navbar':
            menu:
                props:
                    template: 'shop/layout/header/navbar/menu.html.twig'
                priority: 350
 ```
 
 guys the 2.0 docs are missing so many parts
