### ISSUE TITLE
[2.0][Admin] Differents error 500 when editing products with attributes

### ISSUE THREAD

**Issue by tidall87** [Sylius/Sylius#17668]
**Sylius version affected**: 2.0.3

**Description**  
After fresh installation of Sylius 2.0 (from sylius-standard), I test in DEV environment and everything is ok.
In PROD environment errors associated with product attributes occur.

**Steps to reproduce**  
After installing Sylius 2.0, I test in DEV environment and everything is ok.
In PROD environment, errors associated with product attributes occur.

1. With default fixtures, I go to the edition of a product, I click directly on "Update", error 500.
`Uncaught PHP Exception BadMethodCallException: \"The attribute is undefined, so you cannot access proxy methods.\" at AttributeValue.php line 203`
2. With blank fixtures, I create a product, I create an attribute. I go back to edit the product to associate the attribute, error 500.
`Call to a member function getAttribute() on null at FormComponent.php line 89`
3. With fixtures including attributes and products, I go to edit a product, I click directly on "Update", error 500.
`Uncaught PHP Exception Doctrine\\ORM\\ORMInvalidArgumentException: "A new entity was found through the relationship 'App\\Entity\\Product\\ProductAttributeValue#attribute' that was not configured to cascade persist operations for entity: Millésime. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).`

I compared the database structure in dev and prod mode and everything is 100% similar.

My custom fixtures in `/config/packages/sylius_fixtures.yaml`:
```yaml
sylius_fixtures:
    suites:
        master:
            listeners:
                orm_purger: ~
                images_purger: ~
                logger: ~

            fixtures:
                locale:
                    options:
                        locales:
                            - 'fr_FR'

                currency:
                    options:
                        currencies:
                            - 'EUR'

                geographical:
                    options:
                        countries:
                            - 'FR'
                        zones:
                            FR:
                                name: 'France'
                                countries:
                                    - 'FR'

                menu_taxon:
                    name: taxon
                    options:
                        custom:
                            menu_edition:
                                code: 'MENU_EDITION'
                                name: 'Edition'
                                description: 'Sections de menu pour la partie Edition'
                                translations:
                                    fr_FR:
                                        name: 'Edition'
                                        description: 'Sections de menu pour la partie Edition'
                                children:
                                    -   code: 'Collection'
                                        name: 'Collection'
                                        description: ''
                                        translations:
                                            fr_FR:
                                                name: 'Collection'
                                                description: ''

                edition_attribute:
                    name: product_attribute
                    options:
                        custom:
                            -   name: 'Millésime'
                                code: 'millesime'
                                type: 'text'
                                configuration:
                                    required: true

                            -   name: 'Numéro d'édition'
                                code: 'numero_edition'
                                type: 'integer'
                                configuration:
                                    required: true

                            -   name: 'Auteurs'
                                code: 'auteurs'
                                type: 'select'
                                configuration:
                                    required: true
                                    multiple: true

                edition_product:
                    name: product
                    options:
                        custom:
                            -   name: 'Produit A'
                                code: 'prod_a'
                                channels:
                                    - 'EDITION'
                                main_taxon: 'MENU_EDITION'
                                taxons:
                                    - 'Collection'
                                    - 'MENU_EDITION'
                                product_attributes:
                                    millesime: '2024'
```

A slack discussion is open [here](https://sylius-community.slack.com/archives/CBP79GKJS/p1739263679163419)
