### ISSUE TITLE
npm assets are distored and less functional

### ISSUE THREAD

**Issue by ucscode** [Sylius/Sylius#17701]
**Sylius version affected**: 2.0.2

**Description**  
Here's how the page looks in the online demo

![Demo Admin](https://i.ibb.co/P2Wf8hL/Screenshot-from-2025-02-27-01-24-36.png)

Here's how it looks when `make init` is used for docker

![Docker Admin](https://i.ibb.co/Z694rkrq/Screenshot-from-2025-02-27-01-24-53.png)

This doesn't just apply here but also in many other section. The admin-entry.{css, js} and also the shop's have many missing parts and error. Some buttons don't work, @hotwire produces errors, taxons fail to delete and some others.

I copied the css from the online demo and pasted it in the admin-entry.css and the design changed perfectly. Asserting that there is really an issue with the npm build process.

**Steps to reproduce**  
No specific reproduction code. Simply run the docker container with `make init` and boom! A free package error

---

> The issue seem to have been resolved in 2.0.4

Also, add the following css style to the admin to resolves the distorted buttons

```css
.btn-group-sm>.btn, .btn-sm {
    --tblr-btn-line-height: 1.5;
    --tblr-btn-icon-size: .75rem;
}
```

**Comment by tidall87** [comment]
Hi @ucscode I just updated to 2.0.4 and I still have the same problem with the buttons.

![Image](https://github.com/user-attachments/assets/7dca1e62-6950-43be-a599-2a7c78b3bb3d)

I confirm that if I modify the css

```css
.btn-group-sm>.btn, .btn-sm {
--tblr-btn-line-height: 1.5;
--tblr-btn-icon-size: .75rem;
}
```

I get more stylish buttons

![Image](https://github.com/user-attachments/assets/c942a0b3-0101-4242-af25-b5c5889a9b9f)
