### ISSUE TITLE
InvalidFieldNameException : Unknown column 's0_.code' in 'field list'

### ISSUE THREAD

**Issue by blacxi** [Sylius/Sylius#17712]
Hello,

I need help about my entity Booking, i tried to add logique for CRUD but i have this error, i think the problem from my declaration of DoctrineBookingProductRepository and how to work with ResourcesCollectionProvider.

**Error :** 
```
/admin/bookings
An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 's0_.code' in 'field list'

/admin/bookings/new
An error occurred during rendering the "form" hook in the "sylius_admin.common.create.content" hookable. An exception has been thrown during the rendering of a template ("No locale has been set and current locale is undefined.").
```

**app\config\packages\sylius_resource.yaml :** 
```
app.sylius.admin.booking:
    driver: doctrine/orm
    classes:
        model: Domain\Booking\Entity\BookingProduct
        form: Domain\Booking\Form\Type\Admin\BookingProductFormType
        factory: Domain\Booking\Factory\BookingProductFactory
        repository: Infrastructure\Repository\Booking\DoctrineBookingProductRepository
        controller: App\Controller\Booking\Admin\BookingProductController

...

sylius_grid:
    grids:
        app_sylius_admin_booking:
            driver:
                name: doctrine/orm
                options:
                    class: Domain\Booking\Entity\BookingProduct
            fields:
...

app_sylius_admin_booking:
    resource: |
        alias: app.sylius.admin.booking
        section: admin        
        templates: "@SyliusAdmin\\shared\\crud"
        path: bookings
        grid: app_sylius_admin_booking
        redirect: index
        vars:
            all:
                header: admin.ui.booking.header
                subheader: admin.ui.booking.subheader
                breadcrumb: admin.ui.booking.header
            index:
                icon: 'file image outline'
    type: sylius.resource
    prefix: /admin
...

```

**app\src\Domain\Booking\Entity\BookingProduct.php:**
```
use Domain\Sylius\Entity\Product\Product;

#[ORM\Entity]
#[ORM\Table(name: 'booking_product')]
class BookingProduct extends Product
{ ... }
```

**app\src\Domain\Sylius\Entity\Product\Product.php**
```
use Doctrine\ORM\Mapping as ORM;
use Sylius\Component\Core\Model\Product as BaseProduct;
use Sylius\Component\Product\Model\ProductTranslationInterface;

#[ORM\Entity]
#[ORM\Table(name: 'sylius_product')]
class Product extends BaseProduct
{
    protected function createTranslation(): ProductTranslationInterface
    {
        return new ProductTranslation();
    }
}
```

I see many solution to tell me i can created a specific `BookingProductCollectionProvider extends ResourcesCollectionProvider` or use the yaml configuration route but nothing working

```
app_admin_sylius.admin.booking_index:
    path: /admin/bookings/
    defaults:        
        _controller: App\Controller\Booking\Admin\BookingProductController::indexAction
        _sylius:
            repository:
                method: findBy
```

So if someone can help please.

**Comment by diimpp** [comment]
@blacxi Hi, please use slack for support requests -- https://sylius.com/slack

1. Your code example doesn't show `sylius_product` bundle configuration, which should specify your new `app\src\Domain\Sylius\Entity\Product\Product.php` as product resource.
Here is an example.

```yaml
sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Product\Product
                repository: App\Doctrine\ORM\Product\ProductRepository
            translation:
                classes:
                    model: App\Entity\Product\ProductTranslation
```

2. Try `php bin/console doctrine:schema:validate` and `php bin/console doctrine:mapping:info` to see what's wrong with your mappings.

**Comment by blacxi** [comment]
@diimpp hi, 
thanks you for your answer but i tried this before, i have all configuration about Sylius : 

**app\config\packages\_sylius.yaml**
```

sylius_product:
    resources:
        product:
            classes:
                model: Domain\Sylius\Entity\Product\Product
            translation:
                classes:
                    model: Domain\Sylius\Entity\Product\ProductTranslation
        product_variant
...
```

![Image](https://github.com/user-attachments/assets/50daf271-186c-4197-9c77-12c6d77e20f7)

And about command `bin/console doctrine:schema:validate` and `bin/console doctrine:mapping:info` everything it's ok

![Image](https://github.com/user-attachments/assets/24e9b8a0-e456-42b7-a36a-d636ac58a80b)

I'm gonna ask help in the frenc channel on slack.

Thanks you
