### ISSUE TITLE
[2.0] Custom admin page errors

### ISSUE THREAD

**Issue by jbcr** [Sylius/Sylius#17733]
**Sylius version affected**: 2.0.5

**Description**  
Unable to make an admin custom page without resource.

```An error occurred during rendering the "breadcrumbs" hook in the "sylius_admin.my_page.index.content.header" hookable. Impossible to access an attribute ("applicationName") on a null variable.```

**Steps to reproduce**  
1. Add a Symfony controller with render our own template.
2. The template is like: 
```twig
{% extends '@SyliusAdmin/shared/layout/base.html.twig' %}
{% set title = 'test title' %}
{% block body %}
    {% hook ['sylius_admin.my_page.index', 'sylius_admin.common.index'] %}
{% endblock %}
```
3. Configure Twig Hooks:
```yaml
sylius_twig_hooks:
  hooks:
      'sylius_admin.my_page.index':
          sidebar:
            template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
            priority: 200
          navbar:
            template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
            priority: 100
          content:
            template: '@SyliusAdmin/shared/crud/common/content.html.twig'
            priority: 0

      'sylius_admin.my_page.index.content':
        flashes:
          template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
          priority: 300
        header:
          template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
          priority: 200
        footer:
          template: '@SynoliaSyliusGDPRPlugin/Gdpr/part/footer.html.twig'
          priority: -100

      'sylius_admin.my_page.index.content.header':
        breadcrumbs:
          template: '@SyliusAdmin/shared/crud/index/content/header/breadcrumbs.html.twig'
          priority: 100
        title_block:
          template: '@SyliusAdmin/shared/crud/common/content/header/title_block.html.twig'
          priority: 0

      'sylius_admin.my_page.index.content.header.title_block':
        title:
          template: '@SyliusAdmin/shared/crud/common/content/header/title_block/title.html.twig'
          priority: 100
        actions:
          template: '@SyliusAdmin/shared/crud/common/content/header/title_block/actions.html.twig'
          priority: 0
```

**Possible Solution**  

Change the file: `src/Sylius/Bundle/AdminBundle/templates/shared/crud/index/content/header/breadcrumbs.html.twig`

```diff
- {% set title = title_from_context|default(resource_metadata.applicationName~'.ui.'~resource_metadata.pluralName) %}
+ {% set title = title_from_context ?? (resource_metadata.applicationName~'.ui.'~resource_metadata.pluralName) %}
```
