### ISSUE TITLE
Cannot proceed to shipping methods at checkout when localized URLs are disabled

### ISSUE THREAD

**Issue by jamierichsmith** [Sylius/Sylius#17859]
### Sylius version(s) affected

2.0.6

### Description

Cannot proceed to shipping methods at checkout when localized URLs are disabled as it return the following error

`Unable to generate a URL for the named route "sylius_order_index" as such route does not exist.`

### How to reproduce

Follow the guide from the cookbook (https://docs.sylius.com/the-cookbook-2.0/how-to-disable-localized-urls) and attempt the checkout journey, you can enter an address but cannot proceed to the shipping methods as it returns the error no such route "sylius_order_index" 

You can visit the select shipping URL directly but not proceed through the address form

**Comment by jamierichsmith** [comment]
A temporary fix was adding

````yaml
sylius_shop:
    checkout_resolver:
        pattern: "/checkout/.+"
````

Which overrides the default

````yaml
sylius_shop:
    checkout_resolver:
        pattern: "%sylius.security.shop_regex%/checkout/.+"
````


Not sure if this is a ideal fix but it resolves the issue!
