### ISSUE TITLE
Transition from YAML grids to grids as service

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#18136]
### Description

Using a service to configure your grids is the new way that has been introduced a long time ago.
In Sylius 2.2, we would like to introduce a smooth transition during the 2.x period to prepare removal of YAML grids in Sylius 3.0.

Example of YAML Grid
```yaml
sylius_grid:
    grids:
        app_admin_supplier:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Supplier
            fields:
                name:
                    type: string
                    label: app.ui.name
                enabled:
                    type: twig
                    label: app.ui.enabled
                    options:
                        template: '@SyliusBootstrapAdminUi/shared/grid/field/boolean.html.twig' # This will be a checkbox field
```

Example of Grid as service
```php
<?php

declare(strict_types=1);

namespace App\Grid;

use App\Entity\Supplier;
use Sylius\Component\Grid\Attribute\AsGrid;
use Sylius\Bundle\GridBundle\Builder\Field\StringField;
use Sylius\Bundle\GridBundle\Builder\Field\TwigField;
use Sylius\Bundle\GridBundle\Builder\GridBuilderInterface;
use Sylius\Bundle\GridBundle\Grid\AbstractGrid;

#[AsGrid(resourceClass: Supplier::class, name: 'app_admin_supplier')]
final class AdminSupplierGrid extends AbstractGrid
{
    // You can inject everything you need
    public function __construct() {}

    public function __invoke(GridBuilderInterface $gridBuilder): void
    {
        $gridBuilder
            ->addField(
                StringField::create('name')
                    ->setLabel('app.ui.name')
            )
            ->addField(
                TwigField::create('enabled', '@SyliusBootstrapAdminUi/shared/grid/field/boolean.html.twig')
                    ->setLabel('app.ui.enabled')
            )
        ;
    }
}
```

### Example of grid customization
```yaml
# config/packages/_sylius.yaml
sylius_core:
    grid:
        use_legacy_config: false
```

```php
namespace App\Grid;

use Sylius\Bundle\AdminBundle\Grid\ProductGridInterface;
use Sylius\Bundle\GridBundle\Builder\GridBuilderInterface;
use Sylius\Bundle\GridBundle\Grid\AbstractGrid;
use Sylius\Component\Grid\Attribute\AsGrid;
use Symfony\Component\DependencyInjection\Attribute\AsDecorator;

#[AsDecorator('sylius_admin.grid.product')]
#[AsGrid(name: 'sylius_admin_product')]
final class AdminProductGrid extends AbstractGrid implements ProductGridInterface
{
    public function __construct(private readonly ProductGridInterface $productGrid)
    {
    }

    public function __invoke(GridBuilderInterface $gridBuilder): void
    {
        ($this->productGrid)($gridBuilder);

        $gridBuilder
            ->orderBy('name', 'desc')
            ->removeField('code')
            ->setLimits([5, 10])
        ;
    }
}
```

<img width="1680" height="1222" alt="Image" src="https://github.com/user-attachments/assets/d6fa5d3a-9385-4bb4-9e87-a189fdc7c504" />

### Grid mutators

It could be interesting to introduce grid mutators to help customizing the built-in grids.

```php

namespace App\Grid\Mutator;

use Sylius\Bundle\GridBundle\Builder\GridBuilderInterface;

#[AsGridMutator(name: 'sylius_admin_order')]
final class OrderGridMutator implements GridMutatorInterface
{
    public function __invoke(GridBuilderInterface $gridBuilder): void
    {
        $gridBuilder
            ->orderBy('name', 'desc')
            ->removeField('code')
            ->setLimits([5, 10])
        ;
    }
}
```

### Tools
A pretty good starting point on converting a grid is to use the grid converter tool: https://github.com/mamazu/grid-config-converter

### Progress
- [x] https://github.com/Sylius/Sylius/pull/17675
- [x] https://github.com/Sylius/Sylius/pull/15419
- [x]  #18489
- [x] #18519
- [x] https://github.com/Sylius/Sylius/pull/18531
- [x] https://github.com/Sylius/Sylius/pull/18530
- [x] https://github.com/Sylius/Sylius/pull/18529
- [x] https://github.com/Sylius/Sylius/pull/18528
- [x] https://github.com/Sylius/Sylius/pull/18527
- [x] https://github.com/Sylius/Sylius/pull/18526
- [x] https://github.com/Sylius/Sylius/pull/18525
- [x] https://github.com/Sylius/Sylius/pull/18524
- [x] https://github.com/Sylius/Sylius/pull/18523
- [x] https://github.com/Sylius/Sylius/pull/18532
- [x] https://github.com/Sylius/Sylius/pull/18533
- [x] https://github.com/Sylius/Sylius/pull/18535
- [x] https://github.com/Sylius/Sylius/pull/18538
- [x] https://github.com/Sylius/Sylius/pull/18539
- [x] https://github.com/Sylius/Sylius/pull/18540
- [x] https://github.com/Sylius/Sylius/pull/18543
- [x] https://github.com/Sylius/Sylius/pull/18536
- [x] https://github.com/Sylius/Sylius/pull/18537
- [x] https://github.com/Sylius/Sylius/pull/18559
- [x] https://github.com/Sylius/Sylius/pull/18560
- [x] https://github.com/Sylius/Sylius/pull/18575
- [x] https://github.com/Sylius/Sylius/pull/18578
- [x] https://github.com/Sylius/Sylius/pull/18585
- [ ] Introduce Grid mutators?
