### ISSUE TITLE
ApiPlatform  - Splitting "admin" and "shop" endpoints.

### ISSUE THREAD

**Issue by pawellen** [Sylius/Sylius#18190]
### Description

We are creating application based on sylius API. Frontend is a separate application written in VUE.  It seems that we are one of the first that us this full API approach :)

Api platform endpoints are defind in two separate directories:
```
src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/admin/*
sylius/sylius/src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources/shop/*
```

whitch is very cool, unfortunatelty they are loaded as a whole with perent folder, like: 
```
api_platform:
   mapping:
       paths:
          - 'sylius/sylius/src/Sylius/Bundle/ApiBundle/Resources/config/api_platform/resources'
```
We will use only "shop" endpoints and we don't wont to expose all the admin endpoints. It would be very usfull to be able to enable/disable "shop" and "admin" endpoints separately for sake of optimization and security.
