### ISSUE TITLE
[ResourceBundle] PATCH update.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#1883]
@Sylius, Is possible to update all `sylius_*_update` routes to support `PATCH` request by default?

``` yaml
sylius_*_update:
    pattern: /{id}/edit
    methods: [GET, PUT, PATCH]
```
