### ISSUE TITLE
Order Transition `on confirm` does not make sense.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#2044]
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/state-machine.yml#L85

``` yaml
    sylius_order:
        callbacks:
            after:
                ...
                sylius_update_shipment:
                    on:   'confirm'
                    do:   [@sm.callback.cascade_transition, 'apply']
                    args: ['object.getShipments()', 'event', '"prepare"', '"sylius_shipment"']
```

This transition will make shipment's state to `ready`. I think it does not make sense because some case order's state can be `backorder,..`. So shipment's state should not be `ready` in this case.

ping @stloyd
