### ISSUE TITLE
Standard Sylius install through composer fos_rest.format_listener.rules.1 error

### ISSUE THREAD

**Issue by MateuszKoguc** [Sylius/Sylius#2095]
After installing Sylius Standard Edition through composer I am getting error:

```
composer create-project sylius/sylius-standard -s dev

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized options "stop" under "fos_rest.format_listener.rules.1"

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command.
```

In file:
*vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resources/config/app/main.yml*
```
fos_rest:
    disable_csrf_role: ROLE_API
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }
```
there is "stop" used in rules, which is available since FriendsOfSymfony/FOSRestBundle 1.5 [(docs)](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/3-listener-support.md#disabling-the-format-listener-via-rules), but 1.4.2 was installed.
