### ISSUE TITLE
Problems with using DPS via Omnipay bridge 

### ISSUE THREAD

**Issue by antipodes1010** [Sylius/Sylius#2146]
Greetings, I'd like to add PaymentExpress PxPay gateway to my payment gateways, by using Omnipay bridge, as it is a suggested way. But it does not behave as I expected. It seems to me a bug in the bundle. Would anyone help me on this please? Much appreciated!

Here's the config.yml 
````
sylius_payment:
    classes:
        payment:
            model: Sylius\Component\Core\Model\Payment
            controller: Sylius\Bundle\CoreBundle\Controller\PaymentController
    gateways:
        paymentExpress: 'DPS'


payum:
    contexts:
        paymentExpress:
            omnipay:
                type: PaymentExpress_PxPay
                options:
                    username: %username%
                    password: %password%
```

Then I looked up the container file, which includes the 'payum.context.paymentexpress.payment' service,
``` /**
     * Gets the 'payum.context.paymentexpress.payment' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * @return \Payum\Core\Payment A Payum\Core\Payment instance.
     */
    protected function getPayum_Context_Paymentexpress_PaymentService()
    {
        $this->services['payum.context.paymentexpress.payment'] = $instance = new \Payum\Core\Payment();

        $instance->addApi($this->get('payum.context.paymentexpress.gateway'));
        $instance->addExtension($this->get('payum.extension.endless_cycle_detector'));
        $instance->addExtension($this->get('payum.extension.log_executed_actions'));
        $instance->addExtension($this->get('payum.extension.logger'));
        $instance->addAction($this->get('sylius.payum.stripe.action.capture_payment_using_credit_card'), false);
        $instance->addAction($this->get('sylius.payum.action.payment_status'), false);
        $instance->addAction($this->get('sylius.payum.action.generic_capture_payment'), false);
        $instance->addAction($this->get('sylius.payum.action.execute_same_request_with_payment_details'), false);
        $instance->addAction($this->get('payum.action.capture_order'), false);
        $instance->addAction($this->get('payum.action.execute_same_request_with_model_details'), false);
        $instance->addAction($this->get('payum.action.get_http_request'), false);
        $instance->addAction($this->get('payum.action.obtain_credit_card'), false);
        $instance->addAction($this->get('payum.action.render_template'), false);
        $instance->addAction($this->get('payum.omnipay_bridge.action.capture'), false);
        $instance->addAction($this->get('payum.omnipay_bridge.action.fill_order_details'), false);
        $instance->addAction($this->get('payum.omnipay_bridge.action.status'), false);
        $instance->addExtension($this->get('payum.extension.storage.sylius_component_core_model_order'), false);
        $instance->addExtension($this->get('payum.extension.storage.sylius_component_core_model_payment'), false);

        return $instance;
    }
````

You might spot that this services added a bunch of actions that seem unrelated, such as ` $instance->addAction($this->get('sylius.payum.stripe.action.capture_payment_using_credit_card'), false);`, should definitely not to be added.

I am really having a hard time on time. Please halp!!
