### ISSUE TITLE
[ResourceBundle] Criteria only works if filterable is enabled

### ISSUE THREAD

**Issue by LewisW** [Sylius/Sylius#2206]
Specifying ```criteria``` in the routing only works if ```filterable``` is enabled, which means that the following documentation example doesn't work by default:

```
# routing.yml

app_user_show:
    path: /users/{username}
    methods: [GET]
    defaults:
        _controller: app.controller.user:showAction
        _sylius:
            criteria:
                username: $username
                enabled:  true
```

I believe it's due to this line in ```Controller\Configuration.php```:

```
        if ($this->isFilterable()) {
            return $this->request->get('criteria', $this->parameters->get('criteria', $criteria));
        }
```

This behaviour means that routing ```criteria``` is disabled when ```filterable``` is disabled... is this the intended behaviour? My guess is that ```filterable``` is only meant to prevent users from using ```criteria```, and not prevent the routing from using ```criteria```.

I'm happy to submit a PR with a fix, if this is actually a bug.
