### ISSUE TITLE
[SyliusResourceBundle] sylius_resource_paginate is not working

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#2216]
Hi

sylius_resource_paginate is not displaying html code for selector of number of elements per page.
If I'm to remove check in this extension, selector will be displayed alright, but generated links are dead (querystrings like ?paginate=20).

I'm using SyliusResouceBundle with symfony-standard

Here is my route.

```
acme_backend_administrator_index:
    path: /
    methods: [GET]
    defaults:
        _controller: acme.controller.employee:indexAction
        _sylius:
            template: AcmeWebBundle:Backend/Administrator:index.html.twig
            paginate: 10
            #allowed_paginate: [15, 25, 35]
            sortable: true
```

ResourceBundle config

```
sylius_resource:
     resources:
         acme.employee:
             driver: doctrine/orm
             templates: AcmeWebBundle:Backend/Administrator
             classes:
                 model: Acme\Bundle\CoreBundle\Entity\UserEmployee
                 interface: Acme\Bundle\CoreBundle\Entity\UserEmployeeInterface
                 controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                 repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
```

After little debug I see that a check in question

```
// sylius/resource-bundle/Twig/ResourceExtension.php
$parameterName = $this->parameters->get('parameter_name');
if (false !== $this->parameters->get('paginate') && isset($parameterName['paginate'])) 
// Do the magic
```

has this values

```
var_dump( $this->parameters->get('paginate'));
int(10) 
var_dump($parameterName);
array(1) { ["allowed_paginate"]=> array(0) { } }
```

I'm suspicious with second one. it's not consistent with bundle defaults.

```
$node
            ->children()
                ->arrayNode('settings')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->variableNode('paginate')->defaultNull()->end()
                        ->variableNode('limit')->defaultNull()->end()
                        ->arrayNode('allowed_paginate')
                            ->prototype('integer')->end()
                            ->defaultValue(array(10, 20, 30))
                        ->end()
                        ->integerNode('default_page_size')->defaultValue(10)->end()
                        ->booleanNode('sortable')->defaultFalse()->end()
                        ->variableNode('sorting')->defaultNull()->end()
                        ->booleanNode('filterable')->defaultFalse()->end()
                        ->variableNode('criteria')->defaultNull()->end()
                    ->end()
                ->end()
            ->end()
```

So did I misconfigured something?
Or is it a bug?

Regards.
