### ISSUE TITLE
There's no way to use a custom product entity using SyliusProductBundle

### ISSUE THREAD

**Issue by vihuvac** [Sylius/Sylius#2257]
Hello guys, I am trying to use my product entity with model of SyliusProductBundle, I configured it following the steps mentioned at the documentation but I get the following error:

![Sylius Product Error](http://f.cl.ly/items/3f2q45312j2R0i0c2P1k/sylius.repository.product_attribute.png "Sylius Product Error")

### My entity looks like:

```
<?php

namespace Acme\MyBundle\Entity;

use Sylius\Component\Product\Model\Product;

class MyProduct extends Product
{
    // My stuff...

    public function getName()
    {
        return $this->name;
    }
}
```

### My settings looks like:

```
sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Acme\MyBundle\Entity\MyProduct
```

Can someone help me please?
