### ISSUE TITLE
[ResourceBundle] Wrong redirect with subitem routes

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#2259]
So I'm getting redirected from acme_partner_subaccount_create to acme_partner_index, what is not supposed to happen.

I'm using resource bundle v0.11 as standalone and have two sets of index/create routes like this:

``` yml
acme_partner_index:
     path: /
     methods: [GET]
     defaults:
         _controller: acme.controller.customer:indexAction
         _sylius:
             template: AcmeWebBundle:Backend/Partner:index.html.twig
             method: createPartnerFilterPaginator
             arguments: [$criteria, $sorting]
             sortable: true
             paginate: $paginate
acme_partner_create:
     path: /new
     methods: [GET, POST]
     defaults:
         _controller: acme.controller.customer:createAction
         _sylius:
             factory: createNewEnabledPartner
             template: AcmeWebBundle:Backend/Partner:create.html.twig
             form: acme_customer_partner
             redirect: acme_partner_index

acme_partner_subaccount_index:
     path: /{id}/subaccount
     methods: [GET]
     defaults:
         _controller: acme.controller.customer:indexAction
         _sylius:
             template: AcmeWebBundle:Backend/Partner:index.html.twig
             method: createSubPartnerFilterPaginator
             arguments: [$id, $criteria, $sorting]
             sortable: true
             paginate: $paginate
 acme_partner_subaccount_create:
     path: /{id}/subaccount/new
     methods: [GET, POST]
     defaults:
         _controller: acme.controller.customer:createAction
         _sylius:
             template: AcmeWebBundle:Backend/Partner:create.html.twig
             factory:
                 method: createNewSubPartner
                 arguments: [$id]
             form: acme_customer_partner
             redirect:
                 route: acme_partner_subaccount_index
                 parameters: {'id': $id }
```

So basically difference only in repo methods and route definition, otherwise all is the same.

In debugging I've tried to dump values from 

``` php
// Controller/Configuration.php
     public function getRedirectParameters($resource = null)
     {
         $redirect = $this->parameters->get('redirect');
         var_dump($redirect);

         if (null === $redirect || !is_array($redirect)) {
             $redirect = array('parameters' => array());
         }
         var_dump($redirect);

         $parameters = $redirect['parameters'];
         var_dump($parameters);

         if (null !== $resource) {
             $parameters = $this->parser->process($parameters, $resource);
         }
         var_dump($parameters);

         exit;
         return $parameters;
     }
```

and got this _wrong_ route and possibly wrong id.

```
string(28) "acme_partner_index"
array(1) { ["parameters"]=> array(0) { } }
array(0) { }
array(1) { ["id"]=> int(28) } 
```

In this request Id of partner was 10 and of created subpartner 28.
Is it correct to have id of newly created resource? Shouldn't I in redirect id have initial request value?

Regards.
