### ISSUE TITLE
Search in home page failed

### ISSUE THREAD

**Issue by ngtienhy** [Sylius/Sylius#2276]
I have installed Sylius/Sylius yesterday. On home page, I put some text to "search term" with "All".

Here is an exception:
"An exception occurred while executing 'SELECT s0_.item_id AS item_id0, s0_.tags AS tags1, s0_.entity AS entity2 FROM sylius_search_index s0_ WHERE MATCH (s0_.value) AGAINST (?) > 0' with params ["Paper from tree Yang"]:

SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list"

Must I do something after running "php app/console sylius:install" before searching ?

Nguyen Tien Hy, Vietnam.

**Comment by stloyd** [comment]
@pjedrzejewski I guess this was fixed by #2279.

**Comment by ngtienhy** [comment]
Hi,


I have re-run with fixed code. Everything OK.


Thanks,


Nguyen Tien Hy,






Sent from Windows Mail





From: Joseph Bielawski
Sent: ‎Monday‎, ‎January‎ ‎5‎, ‎2015 ‎7‎:‎12‎ ‎PM
To: Sylius/Sylius
Cc: ngtienhy





@pjedrzejewski I guess this was fixed by #2279.

**Comment by madc** [comment]
@agounaris any hints?

**Comment by agounaris** [comment]
Hello @madc 

I just checked out latest sylius and at least the initial setup works fine. Can you give any more information? Application logs? Mysql version?

Search on sylius demo http://demo.sylius.org/search/?search_param=all&q=shirt looks like it works fine.

**Comment by madc** [comment]
Hm, i also checked out a clean install of the sylius master and it works. My other installation is based on sylius-standard. I'll investigate this and report back. Thanks for looking into it!!

**Comment by madc** [comment]
@agounaris you can reproduce the issue when checking out the current master of sylius-standard. That still uses "sylius/sylius": "0.12.*@dev", is it possible, that this is the issue? Where there any fixes afterwards?

**Comment by madc** [comment]
OK, i found it. The following configuration is missing in Sylius < 0.13

```
doctrine:
    [...]
    orm:
        [...]
        entity_managers:
            default:
                [...]
                dql:
                    string_functions:
                        MATCH: Sylius\Bundle\SearchBundle\Extension\Doctrine\MatchAgainstFunction
```
