### ISSUE TITLE
 Unrecognized option "driver" under "sylius_money"

### ISSUE THREAD

**Issue by sruj** [Sylius/Sylius#2396]
Hi all. I have installed SyliusCartBundle following the docs  and when I run "php app/console doctrine:schema:update --force" I get the following error:
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
Unrecognized option "driver" under "sylius_money"
```
```
#\app\config\config.yml   
sylius_cart:
    resolver: app.cart_item_resolver # The id of our newly created service.
    classes: ~ # This key can be empty but it must be present in the configuration.

sylius_order:
    driver: doctrine/orm 

sylius_money:
    driver: doctrine/orm 
```
