### ISSUE TITLE
How to override the User entity?

### ISSUE THREAD

**Issue by geoffrey-brier** [Sylius/Sylius#2430]
This may be a dumb question but how do you do it ?

I'm trying to, but the only thing I get when trying to generate a diff is :`The table with name 'xxx.sylius_user' already exists.`

Here is my config.yml:

```yaml
sylius_core:
    classes:
        user:
            model: XXX\CoreBundle\Entity\User

sylius_api:
    classes:
        api_user:
            model: %sylius.model.user.class%
```

Here is my user class:
```php
//...
use Sylius\Component\Core\Model\User as SyliusUser;

/**
 * @ORM\Entity
 * @ORM\Table(name = "sylius_user")
 */
class User extends SyliusUser
{
//..
}
```
