### ISSUE TITLE
POST issue in API

### ISSUE THREAD

**Issue by criolit** [Sylius/Sylius#2443]
Hi,
I can't do POST requests to API routes. I get error about validation error and CSRF token. I didn't found any solution. Anyone knows how to solve that or in what version it's working?
Thanks!

**Comment by michalmarcinkowski** [comment]
What API routes are not working?

**Comment by criolit** [comment]
POST "/api/users"
Actually I've did a hack by implementing my UserType with option "csrf_protection" => false. I saw, that user should have ROLE_API role to make FOSRestBundle turn off csrf_protection but I didn't found how to assign that role to current user and how to make authentication for API.

Also, related to that path, what is strange after clean installation of sylius like:
```
composer.phar create-project -s dev sylius/sylius-standard
```
I've got route not found error for

    POST "/api/users"

I've checked

    "/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Resources/config/routing/user.yml"

and there are only:

```
sylius_api_user_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.user:indexAction
        _sylius:
            filterable: true
            sortable: true
            sorting:
                id: desc

sylius_api_user_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.user:deleteAction

sylius_api_user_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.user:showAction
```

So I've copied from github

```
sylius_api_user_create:
    path: /api/users
    methods: [POST]
    defaults:
        _controller: sylius.controller.user:createAction

sylius_api_user_update:
    path: /api/users/{id}
    methods: [PUT, PATCH]
    defaults:
        _controller: sylius.controller.user:updateAction
```
to my routing.yml to make these actions work.
