### ISSUE TITLE
InvalidArgumentException: sylius.model.product_archetype.class does not exist

### ISSUE THREAD

**Issue by pyrech** [Sylius/Sylius#2478]
Currently trying to install some Sylius bundles (ProductBundle, CartBundle, OrderBundle, PromotionBundle) and I'm stuck with this exception:

```
[InvalidArgumentException]                                      
The class sylius.model.product_archetype.class does not exist.
```

Those bundles and their dependencies are registered before DoctrineBundle:

```php
//...
new FOS\RestBundle\FOSRestBundle(),
new JMS\SerializerBundle\JMSSerializerBundle($this),
new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle(),
new WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle(),
new Sylius\Bundle\ProductBundle\SyliusProductBundle(),
new Sylius\Bundle\ResourceBundle\SyliusResourceBundle(),
new Sylius\Bundle\AttributeBundle\SyliusAttributeBundle(),
new Sylius\Bundle\VariationBundle\SyliusVariationBundle(),
new Sylius\Bundle\TranslationBundle\SyliusTranslationBundle(),
new Sylius\Bundle\CartBundle\SyliusCartBundle(),
new Sylius\Bundle\OrderBundle\SyliusOrderBundle(),
new Sylius\Bundle\MoneyBundle\SyliusMoneyBundle(),
new Sylius\Bundle\PromotionBundle\SyliusPromotionBundle(), 

new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
//...
```

And I added the required conf to my app/config/config.yml
```yml
#Sylius
sylius_product:
    driver: doctrine/orm
    classes: ~
sylius_attribute:
    driver: doctrine/orm
sylius_variation:
    driver: doctrine/orm
sylius_cart:
    resolver: app.cart_item_resolver
    classes: ~
sylius_order:
    driver: doctrine/orm
sylius_money: ~
sylius_promotion:
    driver: doctrine/orm
sylius_translation:
    default_mapping:
        translatable:
            field: translations
            currentLocale: currentLocale
            fallbackLocale: fallbackLocale
        translation:
            field: translatable
            locale: locale

# Sylius dependencies
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

```

Am i missing something else? Thank for your help.
