### ISSUE TITLE
SyliusResource not work in stand-alone mode

### ISSUE THREAD

**Issue by Shine-neko** [Sylius/Sylius#2491]
Should take stock of the dependencies. Actually this is nonsense. 

SyliusResourceBundle need SyliusTranslationBundle
SyliusTranslationBundle need SyliusResourceBundle
SyliusResourceBundle need SyliusLocalBundle
SyliusLocalBundle need SyliusResourceBundle

**Comment by Shine-neko** [comment]
@pjedrzejewski  @stloyd @aRn0D

**Comment by pjedrzejewski** [comment]
@Shine-neko Yes, I will be taking care of this today/tomorrow!

**Comment by amenophis** [comment]
@pjedrzejewski some news ??

**Comment by jimbocoder** [comment]
For now, this seems to do the trick:

```yaml
parameters:
    sylius.locale: "%locale%"
    sylius.translation.default.mapping:
      translatable: []
      translation: []
```
