### ISSUE TITLE
Confirmation order email not sending

### ISSUE THREAD

**Issue by dslipcev** [Sylius/Sylius#2514]
Hi,

I have problems with sending confirmation order emails. Swiftmailer is configured and working normally. Sylius version is 0.14.

Sylius.yml (in SyliusCoreBundle) contains the configuration for emails;
  ```
sylius_mailer:
    templates:
        sylius.email.order_confirmation.name: SyliusWebBundle:Email:orderConfirmation.html.twig
        sylius.email.order_comment.name: SyliusWebBundle:Email:orderComment.html.twig
        sylius.email.user_confirmation.name: SyliusWebBundle:Email:userConfirmation.html.twig
    sender:
        name: Potato.com
        address: no-reply@potato.com
    emails:
        enabled: true
        order_confirmation:
            enabled: true
            subject: sylius.emails.order_confirmation.subject
            template: SyliusWebBundle:Email:orderConfirmation.html.twig
        order_comment:
            subject: sylius.emails.order_comment.subject
            template: SyliusWebBundle:Email:orderComment.html.twig
        user_confirmation:
            subject: sylius.emails.user_confirmation.subject
            template: SyliusWebBundle:Email:userConfirmation.html.twig
```

What am I doing wrong?

Thanx.
