### ISSUE TITLE
One error leading to another

### ISSUE THREAD

**Issue by cordonmedia** [Sylius/Sylius#2524]
I have not been able to figure out a solution after 1.5 days of working with sylius. I know there are a million bugs in there. But I do hope there will be some help.

I am running into the following error:

[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                              
  The service "sylius.translatable.listener" has a dependency on a non-existent parameter "sylius.locale". 

Look at issue #2478. I've posted a few comments there. But since it was closed I figured I should open a new one.

Please help!

**Comment by adamelso** [comment]
You can either add this to `app/config/parameters.yml` and  `app/config/parameters.yml.dist`:

```yaml
sylius.locale: en
```

Or add it to `app/config/services.yml`. If you have Symfony 2.6. If you have an older version, add it to `app/config/config.yml`:

```yaml
parameters:
    #...
    sylius.locale: en
```

Alternatively you can alias the `locale` set by default in standard editions of Symfony.

```yaml
parameters:
    #...
    sylius.locale: "%locale%"
```
