### ISSUE TITLE
[SearchBundle] Override current mappings return always 0

### ISSUE THREAD

**Issue by psyray** [Sylius/Sylius#2532]
Hi,

@agounaris

When i want to override current product mappings and populate index with `sylius:search:index`, i'm facing a strange problem.

I want to add the sku as mapping in the product class.
My sylius product class is already override, so `%sylius.model.product.class%` point to my product class in my own bundle.

When i left defaut product mapping as is, no problem. But each time i try to override mapping to put my own, values added return always (see capture below)

![var-dump](https://cloud.githubusercontent.com/assets/1230954/6458929/abd493c4-c189-11e4-87a6-f06735de8d6c.jpg)

In this capture 0 should be sku.

Here's my override config
```
sylius_search:
    orm_indexes:
        product:
            mappings:
                sku: ~

    filters:
        pre_search_filter:
            enabled: true
            taxonomy: catégories
        facet_groups:
            search_set:
                values: [taxons, types, sexe,  forme, matière textile, grammage, marque, coloris, price]
...
```
When I remove my override and put the sku mappings in the sylius config file, no problem it's working fine, index was correctly populated.
```
    orm_indexes:
        product:
            class: %sylius.model.product.class%
            mappings:
                id: ~
                name: ~
                description: ~
                sku: ~
```

When I remove this mapping entirely from the sylius config file, and put only in my config file, no problem, it's working fine too.

In summary, when the mappings config is in the two config files (defaut sylius one and mine), added mapping value return 0 in array key instead of sku.
So, when I populate index, it complains about 

```
Fatal error: Call to undefined method LVP\Bundle\CoreBundle\Entity\Product::get0() in /opt/data/Eclipse/LVP/src/Sylius/Bundle/SearchBundle/Indexer/OrmIndexer.php on line 245
```
The faulty method
```
    public function compileSearchableContent(array $fields, $element)
    {
        // TODO maybe I can use the property accessor here
        $content = '';
        foreach (array_keys(array_slice($fields, 1)) as $field) {
            $func = 'get' . ucfirst($field);
            $content .= $element->$func() . self::SPACER;
        }

        return $content;
    }
```

I am doing something wrong ?
Or is this a bug ?

Thanks for your help
