### ISSUE TITLE
[RFC][ResourceBundle]Route configuration consistency 

### ISSUE THREAD

**Issue by aRn0D** [Sylius/Sylius#2552]
In our routes we define our factory like that
```yaml
            factory:
                method: createNew
                arguments: []
```
and you repository like that :
```yaml
            method: findActiveProduct
            arguments: []
```

It is not consistent and explicit, we should use 
```yaml
            repository:
                method: findActiveProduct
                arguments: []
```

@Sylius/core-team What do you think?
