### ISSUE TITLE
[Question] How can I use a custom action?

### ISSUE THREAD

**Issue by JRomeoSalazar** [Sylius/Sylius#257]
I have been reading the documentation but "Custom Actions" is not yet written.

Inside SyliusProductBundle there is a file "PrototypeController.php" which extends "ResourceController" and ads the "buildAction" in order to build products based on Prototype.

I'm trying to use this custom action but it is not working:

The error:

```
Bundle "sylius.controller.prototype" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file?
```

The route:

``` yaml
sylius_prototype_build:
    pattern: /{id}/build
    methods: [GET, POST]
    defaults:
        _controller:  sylius.controller.prototype:buildAction, id: 1
        _sylius:
            template: SyliusProductBundle:Prototype:build.html.twig
            redirect: sylius_product_show
```

And this is PrototypeController.php 

https://github.com/Sylius/SyliusProductBundle/blob/master/Controller/PrototypeController.php

Thanks.
