### ISSUE TITLE
AttributeValue not using SyliusResource system

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#2578]
It looks like we cannot overload the AttributeValue model. Any reason on this?

**Comment by nicolasricci** [comment]
Reason I am asking is that I have overloaded the Attribute model to add a new field but when I try to save my entity I have the following error

`Found entity of type Sylius\Component\Product\Model\Attribute on association Zegg\ShopBundle\Entity\AttributeValue#attribute, but expecting Zegg\ShopBundle\Entity\Attribute`

**Comment by nicolasricci** [comment]
OK problem was I was trying to add an archetype product and the config was not updated. Posting it below in case it can help someone

```yml
sylius_archetype:
    classes:
        product:
            subject: Zegg\ShopBundle\Entity\Product
            attribute: Zegg\ShopBundle\Entity\Attribute
```
