### ISSUE TITLE
price filter facets values merged

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#2591]
I have overloaded the sylius_search configuration such as 

```yml
sylius_search:
    engine: elasticsearch
    filters:
        facets:
            price:
                display_name: 'Price'
                type: range
                values:
                    - { from: 0, to: 10000}
                    - { from: 10001, to: 30000}
                    - { from: 30001, to: 50000}
                    - { from: 50001, to: 100000}
```
But the values from the default sylius_search values are merged and the `$config['filters']['facets']['price']` returns the following array in `ElasticsearchFinder`

```php
array (size=3)
  'display_name' => string 'Price' (length=16)
  'type' => string 'range' (length=5)
  'values' => 
    array (size=7)
      0 => 
        array (size=2)
          'from' => int 0
          'to' => int 2000
      1 => 
        array (size=2)
          'from' => int 2001
          'to' => int 5000
      2 => 
        array (size=2)
          'from' => int 5001
          'to' => int 10000
      3 => 
        array (size=2)
          'from' => int 0
          'to' => int 1000000
      4 => 
        array (size=2)
          'from' => int 1000100
          'to' => int 3000000
      5 => 
        array (size=2)
          'from' => int 3000100
          'to' => int 5000000
      6 => 
        array (size=2)
          'from' => int 5000100
          'to' => int 10000000
```

Any insight on this? 

Thanks
