### ISSUE TITLE
[RBACBundle] Adding permission in my own bundle don't work

### ISSUE THREAD

**Issue by psyray** [Sylius/Sylius#2624]
Hi,

When I try to add permissions in my yml config file, and launch `sylius:rbac:initialize`, the following log is returned :
```
Initializing Sylius RBAC roles and permissions.
RBAC already initialized
Completed!
```
And no permission is added to the database.

my config file (lvp.yml) contains the following
```
sylius_rbac:
    permissions:
        lvp.manage.quotation: Manage quotations
        lvp.quotation.show: Show quotation
        lvp.quotation.index: List quotations
        lvp.quotation.create: Create quotation
        lvp.quotation.update: Edit quotation
        lvp.quotation.delete: Delete quotation
        lvp.quotation: Manage quotations
    permissions_hierarchy:
        lvp.manage.quotation: [lvp.quotation.show, lvp.quotation.index, lvp.quotation.create, lvp.quotation.update, lvp.quotation.delete]
        lvp.quotation: [lvp.manage.quotation]
    roles:
        quotation_manager:
            name: Quotation Manager
            description: Users responsible for quotation management
            permissions: [lvp.quotation]
            security_roles: [ROLE_ADMINISTRATION_ACCESS]
        lvp:
            name: LVP
            description: LVP Team
            security_roles: [ROLE_ADMINISTRATION_ACCESS]
    roles_hierarchy:
        lvp: [quotation_manager]
```
and is included in the main `app/config/config.yml` like this
```
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: migrations.yml }    
    - { resource: @SyliusCoreBundle/Resources/config/app/main.yml }
    - { resource: lvp.yml }
```

I've truncated all datas in the rbac tables with this query 
```
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE sylius_role;
TRUNCATE TABLE sylius_role_permission;
TRUNCATE TABLE sylius_permission;
TRUNCATE TABLE sylius_user_role;
SET FOREIGN_KEY_CHECKS=1;
```
Launch again the initialize command and the following error is returned
`
Fatal error: Call to a member function addChild() on a non-object in /opt/data/Eclipse/LVP/src/Sylius/Bundle/RbacBundle/Doctrine/RbacInitializer.php on line 103
`
Before the error in the console log there was
```
...
Adding permission "Manage site security". (sylius.security)
Adding permission "Manage user accounts". (sylius.accounts)
Adding permission "Manage taxes". (sylius.taxes)
Adding permission "Manage customer support". (sylius.support)
Adding permission "Show quotation". (1)
Adding permission "List quotations". (2)
Adding permission "Create quotation". (3)
Adding permission "Edit quotation". (4)
Adding permission "Delete quotation". (5)
Adding permission "Manage quotations". (6)
```
As you can see my config doesn't contains the right code.
There is 1,2,... instead of lvp.quotation.show,lvp.quotation.list...
And the first permission (lvp.manage.quotation) is not listed (???)

I try to add my rbac section directly in the `app/config/config.yml`, same result.

But when I add my config directly in the `CoreBundle/Resources/config/app/sylius.yml` config file in the rbac section, everything is fine.
All my rbac config is in the db and the backend working fine.

Here's the result :
```
...
Adding permission "Manage user accounts". (sylius.accounts)
Adding permission "Manage taxes". (sylius.taxes)
Adding permission "Manage customer support". (sylius.support)
Adding permission "Manage quotations". (lvp.manage.quotation)
Adding permission "Show quotation". (lvp.quotation.show)
Adding permission "List quotations". (lvp.quotation.index)
Adding permission "Create quotation". (lvp.quotation.create)
Adding permission "Edit quotation". (lvp.quotation.update)
Adding permission "Delete quotation". (lvp.quotation.delete)
Adding permission "Manage quotations". (lvp.quotation)
Adding role "Administrator". (administrator)
Adding role "Catalog Manager". (catalog_manager)
Adding role "Sales Manager". (sales_manager)
Adding role "Marketing Manager". (marketing_manager)
Adding role "Accounts Manager". (accounts_manager)
Adding role "Shipping Manager". (shipping_manager)
Adding role "Content Editor". (content_editor)
Adding role "Tax Manager". (tax_manager)
Adding role "IT". (it)
Adding role "Security Auditor". (security_auditor)
Adding role "Developer". (developer)
Adding role "Support". (support)
Adding role "Quotation Manager". (quotation_manager)
Adding role "LVP". (lvp)
Completed!
```

So what I am doing wrong ?
Is this a bug ?
Why initialize doesn't work when adding permission after a first initialization ?

Thanks for reply
