### ISSUE TITLE
Search facets cannot be removed

### ISSUE THREAD

**Issue by rtuin** [Sylius/Sylius#2626]
Hi there,

Just started utilising the SearchBundle and I'm running into the problem that I can't remove the preset search facets that are configured in sylius.yml in the CoreBundle (in a sane way).

My current solution is not importing the sylius.yml from the CoreBundle at all and copying its contents to our own repo. But this makes it harder to upgrade when a new version is released.

So in CoreBundle's sylius.yml the following is defined:
```yaml
sylius_search:
    filters:
        facets:
            taxons:
                display_name: 'Basic categories'
                type: terms
                value: ~
            price:
                display_name: 'Available prices'
                type: range
                values:
                    - { from: 0, to: 2000}
                    - { from: 2001, to: 5000}
                    - { from: 5001, to: 10000}
            made_of:
                display_name: 'Material'
                type: terms
                value: ~
            color:
                display_name: 'Available colors'
                type: terms
                value: ~
```

The `made_of` and `color` facets are not in our system, so I want them out of there.

My questions are:
1. Is my current solution the best way?
2. How can we optimise this?

Of course, I'm willing to do the coding, but I'm unsure what's the best way to solve this.
