### ISSUE TITLE
Paypal IPN problem with sylius 0.10

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#2659]
Hie

I'm using sylius 0.10 in a project and can't change the version o sylius. Worked it arround to send a request backe to paypal. It worked in some cases but now I got a problem with FOSResBundle

This are the log I got when I test with the IPN simulator.

[2015-04-14 11:59:22] request.INFO: Matched route "payum_notify_do" (parameters: "_controller": "Payum\Bundle\PayumBundle\Controller\NotifyController::doAction", "payum_token": "VCqPoulSVGtau7Gk54eiAiqt0ggrJIgkaxS50ZACwaI", "_route": "payum_notify_do") [] []
[2015-04-14 11:59:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException: "No matching accepted Response format could be determined" at /var/www/opos/shared/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/FormatListener.php line 67 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotAcceptableHttpException(code: 0): No matching accepted Response format could be determined at /vhosts/project/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/FormatListener.php:67)"} []

Why do I get an error from RestBundle? Any Suggestion?

Thanks

**Comment by kayue** [comment]
@jdeveloper Do you have any custom configuration related to fos_rest in `config.yml`?

```
fos_rest:
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/administration/something', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
```
