### ISSUE TITLE
[CartBundle] Exception updating database schema

### ISSUE THREAD

**Issue by JRomeoSalazar** [Sylius/Sylius#266]
Hi all. I have installed SyliusCartBundle (standalone) following the docs and when I run "php app/console doctrine:schema:update --force" I get the following error:

```
Unrecognized options "model" under "sylius_cart.classes.item"
```

It seems like is a config.yml error or typo but I think it's all fine. This is my config.yml:

``` yml
sylius_cart:
    driver: doctrine/orm
    resolver: ktsport.cart_item_resolver
    classes:
        item:
            model: KTSport\WebBundle\Entity\CartItem
```
