### ISSUE TITLE
PromotionSubjectInterface hasn't got getPromotionSubjectItemTotal

### ISSUE THREAD

**Issue by rvanlaak** [Sylius/Sylius#2661]
The documentation of the `SyliusPromotionBundle` states that the `PromotionSubjectInterface` uses `getPromotionSubjectItemTotal()` to check the minimum amount.

http://docs.sylius.org/en/latest/bundles/SyliusPromotionBundle/rule_checker.html

But, the interface doesn't have such method. It was removed by https://github.com/Sylius/Promotion/commit/c17255eac6666f1e0954f774406bdf670fe0a2a6 but how does checking Rules work on `dev`, or `0.13` right now? 

We're getting the following error while trying to implement the bundle into our Sf2 standard application:

    Service of type "fixed_discount" does not exist.

[The configured class](https://github.com/Sylius/Sylius/blob/4e408af950f2d6987cbe1851e6bea722f166ff87/src/Sylius/Bundle/CoreBundle/Resources/config/services.xml#L65) does [not exist](https://github.com/Sylius/Promotion/tree/master/Action) in the Promotion repo, but [is in the Core folder](https://github.com/Sylius/Sylius/tree/master/src/Sylius/Component/Core/Promotion/Action) so this service should not be used in the `PromotionBundle`, right @pjedrzejewski ?

**Comment by Rvanlaak** [comment]
Something for the docs: after making a stub implementation of the `fixed_discount` action, everything was fine:

```yml
    fixed_discount_action:
        class: AppBundle\Action\FixedDiscountAction
        tags:
            - { name: sylius.promotion_action, type: fixed_discount, label: fixed_discount }
```
