### ISSUE TITLE
sylius_product table not create after schema:update - Standalone install

### ISSUE THREAD

**Issue by khyor** [Sylius/Sylius#2700]
Hello,

I try to install sylius product-bundle 0.14 standalone for my project.

for now, i test a basic install with base model from bundle
In my config/sylius.yml :

```yml
sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Sylius\Component\Product\Model\Product
            controller: Sylius\Bundle\ProductBundle\Controller\ProductController
            repository: Sylius\Bundle\ProductBundle\Doctrine\ORM\ProductRepository
            form:
                default: Sylius\Bundle\ProductBundle\Form\Type\ProductType
            translation:
                model: Sylius\Component\Product\Model\ProductTranslation
                form:
                    default: Sylius\Bundle\ProductBundle\Form\Type\ProductTranslationType

sylius_archetype:
    classes:
        product:
            subject: Sylius\Component\Product\Model\Product
            attribute: Sylius\Component\Product\Model\Attribute
            option: Sylius\Component\Product\Model\Option
            archetype:
                model: Sylius\Component\Product\Model\Archetype
                translation:
                    model: Sylius\Component\Product\Model\ArchetypeTranslation

sylius_attribute: ~

sylius_variation:
    classes:
        product:
            variant:
                model: Sylius\Component\Product\Model\Variant
                repository: Sylius\Bundle\ProductBundle\Doctrine\ORM\VariantRepository
                form: Sylius\Bundle\ProductBundle\Form\Type\VariantType

```
All tables except sylius_product are create !

this is my mapping info : 
```console
\>php app/console doctrine:mapping:info
Found 30 mapped entities:
[OK]   Gedmo\Tree\Entity\MappedSuperclass\AbstractClosure
[OK]   Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry
[OK]   Gedmo\Loggable\Entity\LogEntry
[OK]   Sylius\Component\Product\Model\Archetype
[OK]   Sylius\Component\Product\Model\ArchetypeTranslation
[OK]   Sylius\Component\Product\Model\Attribute
[OK]   Sylius\Component\Product\Model\AttributeTranslation
[OK]   Sylius\Component\Product\Model\AttributeValue
[OK]   Sylius\Component\Product\Model\Option
[OK]   Sylius\Component\Product\Model\OptionTranslation
[OK]   Sylius\Component\Product\Model\OptionValue
[OK]   Sylius\Component\Product\Model\Product
[OK]   Sylius\Component\Product\Model\ProductTranslation
[OK]   Sylius\Component\Product\Model\Variant
[OK]   Sylius\Component\Archetype\Model\Archetype
[OK]   Sylius\Component\Archetype\Model\ArchetypeTranslation
[OK]   Sylius\Component\Attribute\Model\Attribute
[OK]   Sylius\Component\Attribute\Model\AttributeTranslation
[OK]   Sylius\Component\Attribute\Model\AttributeValue
[OK]   Sylius\Component\Variation\Model\Option
[OK]   Sylius\Component\Variation\Model\OptionTranslation
[OK]   Sylius\Component\Variation\Model\OptionValue
[OK]   Sylius\Component\Variation\Model\Variant
[OK]   Sylius\Component\Translation\Model\AbstractTranslatable
[OK]   Sylius\Component\Translation\Model\AbstractTranslation
[OK]   Sylius\Bundle\SettingsBundle\Model\Parameter
[OK]   Sylius\Component\Taxonomy\Model\Taxon
[OK]   Sylius\Component\Taxonomy\Model\Taxonomy
[OK]   Sylius\Component\Taxonomy\Model\TaxonomyTranslation
[OK]   Sylius\Component\Taxonomy\Model\TaxonTranslation
```
But I don't understand why table sylius_product isn't create with  a base configuration ?
Someone could guide me ?
Thanks
