### ISSUE TITLE
[SearchBundle] Cannot override price facets

### ISSUE THREAD

**Issue by liquorvicar** [Sylius/Sylius#2742]
The price facet as per the SearchBundle is as follows
```
            price:
                display_name: 'Available prices'
                type: range
                values:
                    - { from: 0, to: 2000}
                    - { from: 2001, to: 5000}
                    - { from: 5001, to: 10000}
```
If add custom price ranges in app/config.yml as follows:
```
            price:
                display_name: 'Available prices'
                type: range
                values:
                    - { from: 0, to: 1000}
                    - { from: 1001, to: 2500}
                    - { from: 2501, to: 10000}
```
Then both sets of ranges appear in the faceted search. I would have expected my custom ranges to override the default ranges (or there to be an option to override or not but I don't know if Symfony has that feature).
