### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#2801]
I am trying to override some products with translation

I am getting this error

Loading sample data...
PHP Fatal error:  Uncaught exception 'Doctrine\ORM\ORMException' with message 'Found entity of type Sylius\Component\Core\Model\ProductTranslation on association Locastic\Bundle\CoreBundle\Entity\Product#translations, but expecting Locastic\Bundle\CoreBundle\Entity\ProductTranslation' in /vagrant/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:791
Stack trace:
#0 /vagrant/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(687): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Doctrine\ORM\PersistentCollection))
#1 /vagrant/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(404): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(Locastic\Bundle\CoreBundle\Entity\Product))
#2 /vagrant/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(711): Doctrine\ORM\UnitOfWork->computeScheduleInsertsChangeSets()
#3 /vagrant/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(297): Doctrine\ORM\UnitOfWork->computeChangeSets()
#4 /vagrant/vendor/doctrine/orm/lib/Doctrine/ORM/Ent in /vagrant/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 791
vagrant@precise64:/vagrant$ 

my config

    sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Locastic\Bundle\CoreBundle\Entity\Product
            form:
                default: Locastic\Bundle\CoreBundle\Form\Type\ProductType
            translation:
                model: Locastic\Bundle\CoreBundle\Entity\ProductTranslation
                form:
                    default: Locastic\Bundle\CoreBundle\Form\Type\ProductTranslationType
                mapping:
                    fields: ['name', 'slug', 'description', 'meta_keywords', 'meta_description', 'short_description', 'ingredients', 'qa', 'research', 'certificates']

**Comment by jimbocoder** [comment]
@antonioperic You probably need to set the parameter `sylius.model.product_translation.class` , and then use it instead of the actual class name.  This is because the parameter may be used by other parts of Sylius and the default value is likely what is causing your issue.

e.g.
```yml
parameters:
    sylius.model.product.class: Locastic\Bundle\CoreBundle\Entity\Product
    sylius.model.product_translation.class: Locastic\Bundle\CoreBundle\Entity\ProductTranslation

...

sylius_product:
    classes:
        product:
            model: %sylius.model.product.class%
            translation:
                model: %sylius.model.product_translation.class%
```

Use this pattern in general for overriding Sylius models.
