### ISSUE TITLE
Error on command "sylius:install:sample-data"

### ISSUE THREAD

**Issue by Andyroid1978** [Sylius/Sylius#2898]
Hello,
i installed to today the "contributing version" of sylius with the command `composer create-project -s dev sylius/sylius` but when i launch the command for installing some sample-data, i got the following error:
```
PHP Catchable fatal error:  Argument 1 passed to Sylius\Component\Core\Model
\User::hasAuthorizationRole() must implement interface Sylius\Component\Rbac\Model\RoleInterface, 
null given, called in /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Component
/Core/Model/User.php on line 48 and defined in /home/andy/Projects/OB_Works/sylius/sylius.demo
/src/Sylius/Component/Core/Model/User.php on line 66
```
i guess it's something related to fixtures data, but i'm not sure.

**Comment by michalmarcinkowski** [comment]
@Andyroid1978 did you run sylius:install:database before? I can't reproduce it on my local env... Could give me exact steps I should do in order to encounter this issue?

**Comment by Andyroid1978** [comment]
First, after composer finished,  i launched just `sylius:install`, and the error comes out when i tried to load sample data.  Then i try launch every single command run inside by this command and then error comes out again on sylius:install:sample.data. 

If i skip this command, everything works fine and i get a working sylius web site but without products.

Here is the full stack tracke from command line:
```
PHP Catchable fatal error:  Argument 1 passed to Sylius\Component\Core\Model\User::addAuthorizationRole() must implement interface Sylius\Component\Rbac\Model\RoleInterface, null given, called in /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadApiData.php on line 40 and defined in /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Component/Core/Model/User.php on line 46
PHP Stack trace:
PHP   1. {main}() /home/andy/Projects/OB_Works/sylius/sylius.demo/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/andy/Projects/OB_Works/sylius/sylius.demo/app/console:26
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
PHP   4. Symfony\Component\Console\Application->doRun() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
PHP   6. Symfony\Component\Console\Command\Command->run() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:900
PHP   7. Sylius\Bundle\InstallerBundle\Command\InstallCommand->execute() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:249
PHP   8. Sylius\Bundle\InstallerBundle\Command\CommandExecutor->runCommand() /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Bundle/InstallerBundle/Command/InstallCommand.php:48
PHP   9. Symfony\Component\Console\Application->run() /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Bundle/InstallerBundle/Command/CommandExecutor.php:74
PHP  10. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
PHP  11. Symfony\Component\Console\Application->doRun() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
PHP  12. Symfony\Component\Console\Application->doRunCommand() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
PHP  13. Symfony\Component\Console\Command\Command->run() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:900
PHP  14. Sylius\Bundle\InstallerBundle\Command\InstallDatabaseCommand->execute() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:249
PHP  15. Sylius\Bundle\InstallerBundle\Command\CommandExecutor->runCommand() /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Bundle/InstallerBundle/Command/InstallDatabaseCommand.php:90
PHP  16. Symfony\Component\Console\Application->run() /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Bundle/InstallerBundle/Command/CommandExecutor.php:74
PHP  17. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
PHP  18. Symfony\Component\Console\Application->doRun() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
PHP  19. Symfony\Component\Console\Application->doRunCommand() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
PHP  20. Symfony\Component\Console\Command\Command->run() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:900
PHP  21. Sylius\Bundle\InstallerBundle\Command\InstallSampleDataCommand->execute() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:249
PHP  22. Sylius\Bundle\InstallerBundle\Command\AbstractInstallCommand->runCommands() /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Bundle/InstallerBundle/Command/InstallSampleDataCommand.php:65
PHP  23. Sylius\Bundle\InstallerBundle\Command\CommandExecutor->runCommand() /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Bundle/InstallerBundle/Command/AbstractInstallCommand.php:122
PHP  24. Symfony\Component\Console\Application->run() /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Bundle/InstallerBundle/Command/CommandExecutor.php:74
PHP  25. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:121
PHP  26. Symfony\Component\Console\Application->doRun() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
PHP  27. Symfony\Component\Console\Application->doRunCommand() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
PHP  28. Symfony\Component\Console\Command\Command->run() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:900
PHP  29. Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand->execute() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:249
PHP  30. Doctrine\Common\DataFixtures\Executor\ORMExecutor->execute() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/doctrine/doctrine-fixtures-bundle/Doctrine/Bundle/FixturesBundle/Command/LoadDataFixturesDoctrineCommand.php:106
PHP  31. Doctrine\ORM\EntityManager->transactional() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:85
PHP  32. call_user_func:{/home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:217}() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:217
PHP  33. Doctrine\Common\DataFixtures\Executor\ORMExecutor->Doctrine\Common\DataFixtures\Executor\{closure}() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:217
PHP  34. Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/ORMExecutor.php:83
PHP  35. Sylius\Bundle\FixturesBundle\DataFixtures\ORM\LoadApiData->load() /home/andy/Projects/OB_Works/sylius/sylius.demo/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:121
PHP  36. Sylius\Component\Core\Model\User->addAuthorizationRole() /home/andy/Projects/OB_Works/sylius/sylius.demo/src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadApiData.php:40
```

**Comment by michalmarcinkowski** [comment]
Run ``` sylius:rbac:initialize ``` and then try to load data. Let me know if it worked.

**Comment by Andyroid1978** [comment]
No. It doesn't work. sorry.

**Comment by michalmarcinkowski** [comment]
Do you have any records in ``` sylius_role ``` table in the database?

**Comment by Andyroid1978** [comment]
Yes, there are 13 records. I tried to drop the database and re-launch the command but i still got the same issue. Maybe there is something wrong in my configuration file? Here is my `parameters.yml`:

```
parameters:
    sylius.database.driver: pdo_mysql
    sylius.database.host: 127.0.0.1
    sylius.database.port: null
    sylius.database.name: sylius_db
    sylius.database.path: null
    sylius.database.user: sylius_db
    sylius.database.password: sylius_db
    sylius.mailer.transport: smtp
    sylius.mailer.host: 127.0.0.1
    sylius.mailer.port: null
    sylius.mailer.user: null
    sylius.mailer.password: null
    sylius.secret: EDITME
    sylius.locale: en_US
    sylius.currency: EUR
    sylius.cache:
        type: file_system
    sylius.phpcr.backend:
        type: doctrinedbal
        connection: default
        caches:
            meta: doctrine_cache.providers.phpcr_meta
            nodes: doctrine_cache.providers.phpcr_nodes
    sylius.phpcr.workspace: default
    sylius.phpcr.user: EDITME
    sylius.phpcr.pass: EDITME
    sylius.uploader.filesystem: sylius_image
    sylius.currency_importer.open_exchange_rates: EDITME
    sylius.currency_importer.ecb.base_currency: EUR
    paypal.express_checkout.username: EDITME
    paypal.express_checkout.password: EDITME
    paypal.express_checkout.signature: EDITME
    paypal.express_checkout.sandbox: true
    stripe.publishable_key: EDITME
    stripe.secret_key: EDITME
    stripe.test_mode: true
    be2bill.identifier: EDITME
    be2bill.password: EDITME
    be2bill.sandbox: true
    sylius.oauth.amazon.clientid: EDITME
    sylius.oauth.amazon.clientsecret: EDITME
    sylius.oauth.facebook.clientid: EDITME
    sylius.oauth.facebook.clientsecret: EDITME
    sylius.oauth.google.clientid: EDITME
    sylius.oauth.google.clientsecret: EDITME
    sylius.inventory.backorders_enabled: true
    sylius.inventory.tracking_enabled: true
    sylius.inventory.holding.duration: '15 minutes'
    sylius.promotion.item_based: false
    sylius.order.allow_guest_order: false
    sylius.order.pending.duration: '3 hours'

```
