### ISSUE TITLE
UserBundle is not available on packagist

### ISSUE THREAD

**Issue by bigfoot90** [Sylius/Sylius#2906]
command: ```composer.phar require sylius/user-bundle```

I've set ```"minimum-stability": "dev"``` in my composer.json

output:
```
  [InvalidArgumentException]                                                                                                                       
  Could not find package sylius/user-bundle at any version for your minimum-stability (dev). Check the package spelling or your minimum-stability 
```

**Comment by steffenbrem** [comment]
:+1: I have this issue too @pjedrzejewski Could you put it on packagist please?

**Comment by steffenbrem** [comment]
@bigfoot90 You will get that error because the package is not on packagist

**Comment by steffenbrem** [comment]
@bigfoot90 As a temporary solution you can add the repository manually to your composer file, like this:

```json
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/Sylius/SyliusUserBundle"
        }
    ],
```

**Comment by bigfoot90** [comment]
@steffenbrem thank you for your answer, but your settings doesn't work for me.
I'm using this:
```yml
    "repositories": [
      {
        "type": "vcs",
        "url": "git@github.com:Sylius/SyliusUserBundle.git"
      }
    ]
```
