### ISSUE TITLE
Adding a custom payment method

### ISSUE THREAD

**Issue by tameribrahim** [Sylius/Sylius#2938]
I'm trying to add a custom payment method that linked to a local gateway ( not exist in Payum nor Omnipay)
Payum.yml

```
payum:
    storages:
        Sylius\Component\Core\Model\Order: { doctrine: orm }
        Sylius\Component\Core\Model\Payment: { doctrine: orm }

    security:
        token_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken: { doctrine: orm }

    dynamic_payments:
        config_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentConfig: { doctrine: orm }

    payments:
        XXXX:
            custom:
                actions:
                    - sylius.payum.XXXX.action.capture_payment
                    - sylius.payum.XXXX.action.payment_status
```

Sylius.yml

```
sylius_payment:
    classes:
        payment:
            model: Sylius\Component\Core\Model\Payment
            controller: Sylius\Bundle\CoreBundle\Controller\PaymentController
    gateways:
        XXXX: Pay Now
```

Now I created the directory for XXXX in PayumBundle with the 2 classes ( CapturePaymentUsingXXXXAction, NotifyAction ) that suppose to prepare the payment details and handle the return from the gateway -if I understand this right- , My problem here is where should I define the URL of the gateway to redirect the payment to?
I can see that there's a token object that has a `targetUrl`, object is saved at "sylius_payment_security_token" table , is this the object that carry the gateway url? if yes, where to customize it?
I saw a question at stackoverflow , @makasim said that the return-url should be to the capture page which is something like http://xyz.home.dev/payment/capture/{TOKEN}
Is this the page that the gateway should redirect to it after payment process?
Thanks in advance.
