### ISSUE TITLE
Locale edition missing routes

### ISSUE THREAD

**Issue by lcetinsoy** [Sylius/Sylius#3159]
Sylius version : 543a77709ce5414d73b7f62fb999c56d7d74f875

When trying to go to the locale section (http://communio.fr/administration/locales/) in the backend the following error are thrown :

"An exception has been thrown during the rendering of a template ("None of the chained routers were able to generate route: Route 'sylius_backend_locale_update' not found") in SyliusWebBundle:Backend/Locale:index.html.twig at line 24.  "

Same with 'sylius_backend_locale_delete'

I have added 

```yaml

sylius_backend_locale_update:
    path: /{id}/update
    methods: [GET]
    defaults:
        _controller: sylius.controller.locale:updateAction
        _sylius:
            redirect: sylius_backend_locale_index

sylius_backend_locale_delete:
    path: /{id}/delete
    methods: [PATCH]
    defaults:
        _controller: sylius.controller.locale:deleteAction
        _sylius:
            redirect: sylius_backend_locale_index

```

The page  then render properly listing locales but editing a given locale does not work : 
Unable to find template "::update.html.twig". 

Kind regards
