### ISSUE TITLE
Overriding User

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#336]
Hi, i have problem with overriding user

I have new class for user, and XML for ORM

``` php
use Sylius\Bundle\CoreBundle\Model\User as BaseUser;

class User extends BaseUser
{
...
}
```

Also i have overridden Sylius.yml like this

``` yaml
sylius_resource:
    resources:
        sylius.user:
            classes:
                model: Locastic\CoreBundle\Entity\User

sylius_installer:
    classes:
        user:
            model: Locastic\CoreBundle\Entity\User   
```

But still get:

```
  [Doctrine\DBAL\Schema\SchemaException]                                  
  The table with name 'sylius_dev.sylius_user' already exists.  
```

This was working pretty well until I updated Sylius to new version and moved files to SRC folder

TY,
Antonio
