### ISSUE TITLE
[Doctrine\Common\Persistence\Mapping\MappingException] Class 'Sylius\Component\Product\Model\AttributeValueInterface' does not exist

### ISSUE THREAD

**Issue by DarioSwain** [Sylius/Sylius#3429]
Hi guys,

I try to use Sylius product bundles (0.15.* version). And receive this error:
```
  [Doctrine\Common\Persistence\Mapping\MappingException]
  Class 'Sylius\Component\Product\Model\AttributeValueInterface' does not exist
```

after i am execute ```php app/console doctrine:schema:validate```:
```
[Mapping]  FAIL - The entity-class 'Sylius\Component\Product\Model\Product' mapping is invalid:
* The target entity 'Sylius\Component\Product\Model\AttributeValueInterface' specified on Sylius\Component\Product\Model\Product#attributes is unknown or not an entity.

  [Doctrine\Common\Persistence\Mapping\MappingException]
  Class 'Sylius\Component\Product\Model\AttributeValueInterface' does not exist
```

My composer.json:
```json
    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.3.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "sylius/product-bundle": "0.15.*"
    },
```

And I try to configure it:
```yaml
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

sylius_product:
    classes:
        product:
            model: Sylius\Component\Product\Model\Product
            controller: Sylius\Bundle\ProductBundle\Controller\ProductController
            repository: Sylius\Bundle\ProductBundle\Doctrine\ORM\ProductRepository

sylius_archetype:
    classes:
        product:
            subject: Sylius\Component\Product\Model\Product
            attribute: Sylius\Component\Product\Model\Attribute
            option: Sylius\Component\Product\Model\Option
            archetype:
                model: Sylius\Component\Product\Model\Archetype

sylius_attribute:
    classes:
        product:
            subject: Sylius\Component\Product\Model\Product
            attribute:
                model: Sylius\Component\Product\Model\Attribute
            attribute_value:
                model: Sylius\Component\Attribute\Model\AttributeValue

sylius_variation:
    classes:
        product:
            variable: Sylius\Component\Product\Model\Product
            variant:
                model: Sylius\Component\Product\Model\Variant
                repository: Sylius\Bundle\ProductBundle\Doctrine\ORM\VariantRepository

sylius_translation:
    default_locale: %locale%
```

Seems like a problem with mapping AttributeValueInterface to AttributeValue model.

**Comment by michalmarcinkowski** [comment]
Have you tried using Sylius\Component\**Product**\Model\AttributeValue?

```yml
sylius_attribute:
    classes:
        product:
            subject: Sylius\Component\Product\Model\Product
            attribute:
                model: Sylius\Component\Product\Model\Attribute
            attribute_value:
                model: Sylius\Component\Product\Model\AttributeValue
```
