### ISSUE TITLE
Different entity manager for RbacBundle

### ISSUE THREAD

**Issue by danielrestrepo** [Sylius/Sylius#3477]
I've been trying to configure RbacBundle in a different EntityManager to no avail. Is there any way to do this properly?

Here is what I got right now

```yml
entity_managers:
   default:
         ...
   dynamic:
         ... 
         mappings:
            OtherBundlesMappings...
            SyliusRbac:
              mapping: true
              type: annotation
              dir:  "%kernel.root_dir%/../vendor/sylius/rbac/Model"
              alias: ~
              prefix: Sylius\Component\Rbac\Model
              is_bundle: false
```

In that way it throws the following exeption:
```
[Doctrine\ORM\Mapping\MappingException]                                      
  Class "Sylius\Component\Rbac\Model\Role" is not a valid entity or mapped su  
  per class.
```

Thanks
