### ISSUE TITLE
changing product urls to prepend maintaxon

### ISSUE THREAD

**Issue by Sp0ng3b0b** [Sylius/Sylius#3618]
As we now have the main taxon attribute for a product, it would make sense to change the default url shop.com/p/product-slug to something more seo appealing like shop.com/taxonomy/taxon/subtaxon/product-slug. 
I guess this is an easy change, but i werent able to wrap my head around the routegenerator.

**Comment by okwinza** [comment]
At the moment it is relatively easy to come up with something like "maintaxon/product-slug" -- without nested taxons in url. I'd gladly share the solution but i am missing some details.

I think it will be useful for many projects.
@pjedrzejewski would you guys be interested in a PR and/or cookbook arcticle on this?

**Comment by Sp0ng3b0b** [comment]
That would be really nice :+1:

**Comment by okwinza** [comment]
Anyway, if anyone would like to share any insight about where this "field:" thingy comes from in sylius.yml it would be cool.

```
routing:
        %sylius.model.product.class%:
            field: slug
            prefix: /p
            defaults:
                controller: sylius.controller.product:detailsAction
                repository: sylius.repository.product
                sylius:
                    template: SyliusWebBundle:Frontend/Product:show.html.twig
                    criteria: {slug: $slug}
                    permission: false
```

https://github.com/Sylius/Sylius/blob/466b42fa6ec124068e7984c6910eb6540c3080f7/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml#L4
@pjedrzejewski
