### ISSUE TITLE
Extend contact form

### ISSUE THREAD

**Issue by ufik** [Sylius/Sylius#3757]
Trying to extend contact form (add new fields), first step I made was change of form type, I have created new Type in my src folder and tried to change parameters 

```
sylius.form.type.contact_request.class: ContactBundle\Form\Type\RequestType
```

But it's not overriding, it seems like this is not done via service.

**Comment by pamil** [comment]
Putting it in your `config.yml` should help :)

```yaml
sylius_contact:
    resources:
        contact_request:
            form:
                default: ContactBundle\Form\Type\RequestType
```

**Comment by ufik** [comment]
Unfortunately not
```
Unrecognized option "resources" under "sylius_contact"
```

**Comment by pamil** [comment]
It seems like you don't have the latest Sylius version, try to update.

**Comment by ufik** [comment]
I took a look into the contact bundle and it should be like this 

```
sylius_contact:
        classes:
            contact_request:
                    form:
                        default: ContactBundle\Form\Type\RequestType
```
