### ISSUE TITLE
Cannot load provinces for the country

### ISSUE THREAD

**Issue by ufik** [Sylius/Sylius#3787]
After upgrade to the newest master version loading of provinces for specific country doesn't work anymore.

When calling this URL /province/choice-form?countryId=175, I've got this response.
```
Controller "sylius.controller.province:choiceFormAction" for URI "/province/choice-form" is not callable.
```

This is our configuration of route, which is the same as you have in the sylius.

```
sylius_province_choice_form:
    path: /province/choice-form
    defaults:
        _controller: sylius.controller.province:choiceFormAction
        _sylius:
            template: SyliusAddressingBundle:Province:_provinceChoiceForm.html.twig
```

I have noticed, templates have been removed recently, but even if I add this specific template, there is same error.

And as it seems from the source code, templates are still in the use, even though they have been deleted.

```
$form = $this->createProvinceChoiceForm($country);

        $content = $this->renderView($this->getConfiguration()->getTemplate('_provinceChoiceForm.html'), array(
            'form' => $form->createView(),
        ));

        return new JsonResponse(array(
            'content' => $content,
        ));
```
