### ISSUE TITLE
[ResourceBundle] Multiple object managers bug.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#3806]
For now we can't custom `object_manager` per resource. To support this feature for `resource-bundle` i thinks we should modify `Sylius\Bundle\ResourceBundle\DependencyInjection\Driver\Doctrine\DoctrineXXXDriver` like this:

```php
    // Sylius\Bundle\ResourceBundle\DependencyInjection\Driver\Doctrine\DoctrineORMDriver
    
    /**
     * {@inheritdoc}
     */
    protected function getManagerServiceId(MetadataInterface $metadata)
    {
        $name = $metadata->hasParameter('object_manager')
            ? $metadata->getParameter('object_manager')
            : 'default'
        ;

        return sprintf('doctrine.orm.%s_entity_manager', $name);
    }
```

#### The bundle that using resource-bundle.
```yaml
awsome_bundle:
    resources:
        resource_model:
            classes: ....
            object_manager: custom_manager
```

ping @pjedrzejewski
