### ISSUE TITLE
Is it possible define form type in resource, when it is a service?

### ISSUE THREAD

**Issue by ufik** [Sylius/Sylius#3843]
I have form type, which uses db, so I defined this form as a service and in my controller I am getting this form type via $container->get(). And now I would like to define this form type in resource

```
sylius_resource:
    resources:
            classes:
                form:
                    default: @service
```

But it's expecting only string, is there any way to do this?

**Comment by pjedrzejewski** [comment]
@ufik You just define a service with same name, so ``app.form.type.book`` for example and give it an alias ``app_book``. Sylius will use it from now. :) Please reopen if this does not help. If you have a moment, would be great to add this to the docs, thanks!

**Comment by ufik** [comment]
Well I have defined it like this:

```
services:
    zdg.form.type.registration:
        class: ZDG\EGBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: zdg_registration }
        arguments: [@doctrine, @sylius.context.locale]
```

config
```
sylius_resource:
    resources:
        zdg.registration:
            templates: EGBundle:Backend/Registration
            classes:
                model: ZDG\EGBundle\Entity\Registration
```

But it's still doesn't work.

**Comment by ufik** [comment]
Not sure if you have noticed the last message @pjedrzejewski ?

**Comment by pjedrzejewski** [comment]
@ufik I did and will try to reproduce it today before tagging v0.16.0. :+1: I will get back to you soon.

**Comment by bendavies** [comment]
i'm doing this, works for me.

**Comment by pjedrzejewski** [comment]
@ufik Are you sure you are loading the definition **after** SyliusResourceBundle?

**Comment by ufik** [comment]
@bendavies Can you please give an example, how you use this?

**Comment by ufik** [comment]
@pjedrzejewski Well you mean order of the bundles, right? We are loading our bundles after bundles from Sylius.

**Comment by bendavies** [comment]
@ufik looks the same as you, but i use xml
```
<service id="app.form.type.foo" class="App\Bundle\FooBundle\Form\Type\FooType">
    <argument type="service" id="service.whatever" />
    <tag name="form.type" alias="app_foo" />
</service>
```
```
app.foo:
    classes:
        model: App\Bundle\FooBundle\Entity\Foo
```

**Comment by lchrusciel** [comment]
@ufik do you have proper order of resource importing in config file? 
```yml
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @SyliusCoreBundle/Resources/config/app/main.yml }
    - { resource: resources.yml }
    - { resource: services.yml }
```
You should thing about keeping resource definition in a separated yaml file.

**Comment by ufik** [comment]
@lchrusciel @pjedrzejewski Well I have configuration of the service in the bundle. And configuration of the resource is almost at the end of the config file...

**Comment by lchrusciel** [comment]
@ufik can you show your config file?

**Comment by ufik** [comment]
@lchrusciel 
```
imports:
    - { resource: parameters.yml }
    - { resource: zdg/security.yml }
    - { resource: @SyliusCoreBundle/Resources/config/app/main.yml }
    - { resource: @CoreBundle/Resources/config/services.xml }
    - { resource: @CoreBundle/Resources/config/config.yml }
...
...
    - { resource: zdg/sylius_resource.yml }

    - { resource: zdg/eg.yml }
```
Important is the zdg/eg.yml, where is definition of resources.
```
sylius_resource:
    resources:
        zdg.registration:
            templates: EGBundle:Backend/Registration
            classes:
                model: ZDG\EGBundle\Entity\Registration
```

And finally in my bundle services.yml

```
services:
    zdg.eg.type.registration:
        class: ZDG\EGBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: zdg_registration }
        arguments: [@doctrine, @sylius.context.locale]

```
