### ISSUE TITLE
Problem extending Product bundle The form's view data is expected to be an instance of class...

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#3861]
I get error **The form's view data is expected to be an instance of class SyliusCustom\Bundle\ProductBundle\Entity\ProductVariant, but is an instance of class Sylius\Component\Core\Model\ProductVariant. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class Sylius\Component\Core\Model\ProductVariant to an instance of SyliusCustom\Bundle\ProductBundle\Entity\ProductVariant.**

In config file I have 

```
sylius_variation:
    classes:
        product:
            variant:
                model: SyliusCustom\Bundle\ProductBundle\Entity\ProductVariant
                form:
                    default: SyliusCustom\Bundle\ProductBundle\Form\Type\ProductVariantType
```

My extended Variant entity look like:
```
namespace SyliusCustom\Bundle\ProductBundle\Form\Type;

use Symfony\Component\Form\FormBuilderInterface;
use Sylius\Bundle\CoreBundle\Form\Type\ProductVariantType as BaseVariantType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ProductVariantType extends BaseVariantType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver);
        $resolver->setDefaults(array(
            'data_class' => 'SyliusCustom\Bundle\ProductBundle\Entity\ProductVariant',
        ));
    }
}
```
I think that problem from https://github.com/Sylius/Sylius/issues/277 stiil exist.
**Last composer update on project was yesterday(11.01.2016)**

Please help me!
Thanks in advance!

**Comment by michalmarcinkowski** [comment]
Your yaml config is incorrect. You should have:
```yml
sylius_variation:
    resources:
        product:
            variant:
                classes:
                    model: Sylius\Component\Core\Model\ProductVariant
                    form:
                        default: SyliusCustom\Bundle\ProductBundle\Form\Type\ProductVariantType
```
Take a look at the Core config https://github.com/Sylius/Sylius/blob/cd46a90b9ebcbe96c5dc30711c0f4e9de11d6be5/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml#L123.

**Comment by yopop666** [comment]
After I changed my configuration from:
```
sylius_variation:
    classes:
        product:
            variant:
                model: SyliusCustom\Bundle\ProductBundle\Entity\ProductVariant
                form:
                    default: SyliusCustom\Bundle\ProductBundle\Form\Type\ProductVariantType
```
into
```
sylius_variation:
    resources:
        product:
            variant:
                classes:
                    model: SyliusCustom\Bundle\ProductBundle\Entity\ProductVariant
                    form:
                        default: SyliusCustom\Bundle\ProductBundle\Form\Type\ProductVariantType
```
I get **Unrecognized option "resources" under "sylius_variation"**

The config for sylius_variation in 
**src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml** file in Core is:
```
sylius_variation:
    classes:
        product:
            variant:
                model: Sylius\Component\Core\Model\ProductVariant
                repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\ProductVariantRepository
                form:
                    default: Sylius\Bundle\CoreBundle\Form\Type\ProductVariantType
```
the **resource** child of **sylius_variation** doesn't exist.

I think that I miss something and I don't know what.
