### ISSUE TITLE
[ProductBundle] Override the form type in the config

### ISSUE THREAD

**Issue by JulienPradet** [Sylius/Sylius#3888]
Hi,

I tried to use the ProductBundle as a standalone, and to configure the FormType in order to add the translation fields.

However, the `getForm` of the `ResourceController` seems to always use the defaultFormFactory instead of using the form in the `sylius_product` configuration. I guess that's because my Form is not registered or referenced in the `form.registry`. But I can't find any sort of documentation on the web about this service.

And I've done the exact same steps with the ResourceBundle, and it worked. Is it truly a bug ? Or did I miss something ? There's a "[override form chapter](http://docs.sylius.org/en/latest/bundles/SyliusProductBundle/forms.html#miscellaneous-fields)" mentionned in the doc of Sylius, but I couldn't find the page.

Here is my config :
```yml
sylius_product:
    resources:
        product:
            classes:
                model: Sylius\Component\Product\Model\Product
                controller: Sylius\Bundle\ProductBundle\Controller\ProductController
                repository: Sylius\Bundle\ProductBundle\Doctrine\ORM\ProductRepository
                form:
                    default: App\CoreBundle\Form\Type\ProductType
            translation:
                classes:
                    model: Sylius\Component\Product\Model\ProductTranslation
                    form:
                        default: Sylius\Bundle\ProductBundle\Form\Type\ProductTranslationType
```

I'm still a bit noobish. But if it's truly a bug (and not misconfiguration of mine), I'd be happy to fix it myself, if it helps/saves some time. However I'm stuck for now and I would need help.

As a workaround, I created a new controller that extends the `ProductController` and have overriden the `getForm` method.

Anyway, thanks for the awesome work on Sylius!
