### ISSUE TITLE
[SyliusResourceBundle] rename sortable_position to sortable_property

### ISSUE THREAD

**Issue by gseidel** [Sylius/Sylius#3930]
In ResourceController for the moveUp and moveDown action, you are able to change the name of the property by using the ``sortable_position`` config option. The name just confuse me, cause if i read position as a config option i would except a number. But here we want to define the name of the property that will be used by the action. So my suggestion is to simply rename it to ``sortable_property``.

Here is an example of the renamed option:

```
my_route_move_up:
    pattern: /{id}/move-up
    methods: [PUT]
    defaults:
        _controller: sylius.controller.resource:moveUpAction
        _sylius:
            redirect: referer
            sortable_property: priority # the default value is position
````
