### ISSUE TITLE
Configuring translatable resources

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3962]
I'm working through an upgrade to master from today and something seems to have changed in the last 7 days that I can't work out around configuring resources.

I'm fairly sure that last week this worked:

```
        reiss.size:
            driver: doctrine/orm
            classes:
                model: Reiss\ProductBundle\Entity\Size
                repository: Sylius\Bundle\TranslationBundle\Doctrine\ORM\TranslatableResourceRepository
            translation:
                classes:
                    model: Reiss\ProductBundle\Entity\SizeTranslation
                fields:
                    - presentation
```

However now I'm getting the following exception:
 
```                                                          
  [InvalidArgumentException]                               
  Resource "reiss.size_translation" does not exist.  
```
      
Which seems to require me to configure the translation resource separately. Is this correct? I've tried it with a few resources and it seems to be the same.

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/TranslationBundle/EventListener/ORMTranslatableListener.php#L82

It seems a bit odd...

**Comment by peteward** [comment]
I'm getting this exception for anything accessing doctrine metadata (trying to create migrations in this case).

If I configured all 5 translatable resources independently of their subject it worked but this isn't intentional right?:

```
        reiss.size:
            driver: doctrine/orm
            classes:
                model: Reiss\ProductBundle\Entity\Size
                repository: Sylius\Bundle\TranslationBundle\Doctrine\ORM\TranslatableResourceRepository
            translation:
                classes:
                    model: Reiss\ProductBundle\Entity\SizeTranslation
                fields:
                    - presentation
        reiss.size_translation:
            classes:
                model: Reiss\ProductBundle\Entity\SizeTranslation
```
