### ISSUE TITLE
[Bug] Error "This value is not valid" when tried to create a new page route

### ISSUE THREAD

**Issue by achristodoulou** [Sylius/Sylius#3963]
I cloned and installed Sylius on my machine.

1. I created a new page.

2. When I tried to create a route for the specified page I got the following error:

```
Message:
This value is not valid.

Origin:
parent

Cause:

Symfony\Component\Validator\ConstraintViolation
Object(Symfony\Component\Form\Form).children[parent] = /cms/routes

Caused by:

Symfony\Component\Form\Exception\TransformationFailedException
Unable to reverse value for property path "parent": Could not transform path "/cms/routes" to document. Path not found.

Caused by:

Symfony\Component\Form\Exception\TransformationFailedException
Could not transform path "/cms/routes" to document. Path not found.
```

**Comment by okwinza** [comment]
Related issue: Sylius/Sylius-Standard#78

Running `app/console doctrine:phpcr:repository:init` should solve this.

**Comment by kedves** [comment]
After updating the `composer.json` with `"symfony-cmf/routing-bundle": "1.4.*@dev"` should I re-init the project with `sylius:install`? Because the `doctrine:phpcr:repository:init` still doesn't initialize the CmfRoutingBundle.

**Comment by okwinza** [comment]
Ok so here is a temp fix untill #3967 is merged:

1) Ensure you have latest version of RoutingBundle as dep: 
`"symfony-cmf/routing-bundle": "1.4.*@dev"`

2) run `composer update`

3) Add this to your app config:
```
cmf_routing:
    chain:
        routers_by_id:
            router.default: 100
            sylius.dynamic_router: 50
            cmf_routing.dynamic_router: 20
    dynamic:
        generic_controller: cmf_content.controller:indexAction
        persistence:
            phpcr:
                enabled: true
                enable_initializer: true
                route_basepath: /cms/routes
```
4) Run `doctrine:phpcr:repository:init`
