### ISSUE TITLE
[RFC] Product and taxon permalinks + slugs

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3977]
Another round of brainstorm! Currently our handling of permalinks and slugs is a bit broken. Ideally we have all this editable in the backend etc. but this takes few things to resolve first.

I'd like to propose the following approach as the first step to get it handled properly:
- ProductTranslation
  - Has `name` property;
  - Has `slug` property, which is **always** slugified name, no matter what;
  - Has `permalink` property, which is generated by `ProductPermalinkGeneratorInterface` implementation;
- TaxonTranslation
  - Has `name` property;
  - Has `slug` property, which is **always** slugified name, no matter what;
  - Has `permalink` property, which is generated by `TaxonPermalinkGeneratorInterface` implementation;

We could provide different generator implementations by default, for example:
- One that simply uses "slug"
- One that uses "locale/slug" or "locale-slug", etc.
- One that uses "mainTaxon permalink/product slug", etc.
- One that does not generate any permalink and allows user to enter it manually
- And of course you could implement custom

Routing to display products / taxons would look:

``` yaml
sylius_shop_product_show:
    path: /products/{permalink}
    defaults:
        _controller: sylius.controller.product:showAction
        _sylius:
            repository:
                method: findOneByPermalink
                arguments: [$permalink]

sylius_shop_product_index_by_taxon:
    path: /{permalink}
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            grid: sylius_shop_product_by_taxon
```

Grid would take care of filtering products by taxon with given permalink, etc. And would use Doctrine/ORM or ElasticSearch driver. :D

Things to figure out:
- How to keep permalinks sync? First thought would be a Doctrine listener but I'd like to avoid that whenever possible. I think we could process permalink in the form. That would also allow us to have something like "lock permalink" checkbox to avoid regenerating it, etc.

Of course there is much more to handle, like rewrites and so on but first things first.

Let me hear your thoughts!
