### ISSUE TITLE
'Unrecognized option "classes" under "sylius_attribute.resources.attribute"' 

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#3981]
Hi,

After I extend AttributeBundle, I  want to extend the model from it with configuration:
```
sylius_attribute:
    driver: doctrine/orm
    resources:
        attribute:
            classes:
                model: SyliusCustom\Bundle\AttributeBundle\Entity\Attribute
```
 and I recive error **'Unrecognized option "classes" under "sylius_attribute.resources.attribute"'**

what is wrong?

Please Help me!
