### ISSUE TITLE
AttributeValue still coupled to product (i think)

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3984]
`AttributeController::renderAttributesAction` decouples quite nicely to allow any attribute type, but it then renders the following template:

```
return $this->render('SyliusAttributeBundle::attributeChoice.html.twig', array('form' => $form->createView()));
```

This uses a hard-coded route:

```
 <form action="{{ path('sylius_backend_render_attribute_forms') }}" method="GET" id="attributeChoice">
```

Which is set to the product attribute controller:
```
sylius_backend_render_attribute_forms:
    path: /attribute-forms
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_attribute:renderAttributeValueFormsAction
```

Any ideas ?

Will try working around by overriding more of it in the meantime.
