### ISSUE TITLE
Can't extend ProductAttribute Entity

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#3997]
Hi,

I don't know how to extend ProductAttribute Entity
In Attribute class I have:
```
<?php
namespace SyliusCustom\Bundle\ProductBundle\Entity;

use Sylius\Component\Product\Model\Attribute as BaseEntity;

class Attribute extends BaseEntity
{
}
```
and xml mapping look like:
```
<?xml version="1.0" encoding="UTF-8" ?>

<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
									xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
									xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
																			http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

    <entity name="SyliusCustom\Bundle\ProductBundle\Entity\Attribute" table="sylius_product_attribute" >
	</entity>
</doctrine-mapping>
```
I don't know what to put in config file.
When i run:
```
php app/console doctrine:migrations:diff
```
I receive **The table with name 'sylius_product_option' already exists.**

Thanks in advance.

**Comment by michalmarcinkowski** [comment]
In the docs it is described how to override models ([overrding models](http://docs.sylius.org/en/latest/bundles/general/overriding_models.html)).

How did you register the entity? The following should work:

```yml
sylius_attribute:
    resources:
        product:
        attribute: 
            classes:
                model: SyliusCustom\Bundle\AttributeBundle\Entity\Attribute
```

**Comment by yopop666** [comment]
@michalmarcinkowski with your configuration I get:
**[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "classes" under "sylius_attribute.resources.attribute"**

I tried also with:
```
sylius_attribute:
    driver: doctrine/orm
    resources:
            product:
                subject: Sylius\Component\Core\Model\Product
                attribute:
                    classes:
                        model: SyliusCustom\Bundle\ProductBundle\Entity\Attribute
```

but I get
**The table with name 'subscriberly_edev_xyz_andreip.sylius_product_option' already exists.**

**Comment by michalmarcinkowski** [comment]
Wrong indents, sorry. Please try `mapped-superclass` instead of `entity` in your entity mapping config.

**Comment by yopop666** [comment]
It works with ```mapped-supperclass```.

Thank you very much @michalmarcinkowski.

 I have some entity mapping config extended with  ```entity``` like sylius example, and another's with ```mapped-superclass```. Why this anomaly?

**Comment by michalmarcinkowski** [comment]
Option is from VariationBundle. Try:
```yml
sylius_variation:
    resources:
        option:
            classes:
                model: SyliusCustom\Bundle\ProductBundle\Entity\Option
```
