### ISSUE TITLE
Access denied to "sylius.contact_request.create" 

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#4017]
Hi,

In my site frontend I tried to access contact page, I get error **Access denied to "sylius.contact_request.create" for "user@email.com". 

In Sylius package the [route is registered](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/config/routing/frontend/contact.yml).

If I try to access [demo url](http://demo.sylius.org/contact/) I get **Oops! An Error Occurred.The server returned a "500 Internal Server Error".**

**Comment by pjedrzejewski** [comment]
The contact stuff is a bit broken right now but will be fixed in #3164.

**Comment by antonioperic** [comment]
Just noticed the same :)

**Comment by antonioperic** [comment]
@yopop666 try set permission to false
    sylius_contact:
    path: /
    defaults:
        _controller: sylius.controller.contact_request:createAction
        _sylius:
            template: SyliusWebBundle:Frontend:contact.html.twig
            redirect: sylius_contact
            permission: false

**Comment by antonioperic** [comment]
```
sylius_contact:
    path: /
    defaults:
        _controller: sylius.controller.contact_request:createAction
        _sylius:
            template: SyliusWebBundle:Frontend:contact.html.twig
            redirect: sylius_contact
            permission: false
```
