### ISSUE TITLE
[API] Use Behat to test api

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#4020]
What is the benefit of using PHPUnit over Behat when testing the API? I am using Behat to test my own API layer that uses Sylius. In my opinion it is much easier to read/follow.

I only introduced a special syntax for the request body and the request uri. You can use `{@id [resource].[property]=<value>}` in order to get the id of that resource. This has worked very well for me.

An example feature of my project:

```gherkin
@products
Feature: Products
    As an API user
    I want to view products
    So that I know what products there are

    Background:
        Given there is a default workspace
        And there is a default channel
        And there are following locales configured:
            | code  | enabled |
            | en_US | yes     |
            | nl_NL | yes     |
        And there are following taxonomies defined:
            | name     |
            | Category |
        And taxonomy "Category" has following taxons:
            | Clothing > T-Shirts     |
            | Clothing > PHP T-Shirts |
            | Clothing > Gloves       |
        And there are following options:
            | name          | presentation | values           |
            | T-Shirt color | Color        | Red, Blue, Green |
            | T-Shirt size  | Size         | S, M, L, XL, XXL |
        And the following products exits:
            | name             | price | options                     | taxons       |
            | Super T-Shirt    | 19.99 | T-Shirt size, T-Shirt color | T-Shirts     |
            | Black T-Shirt    | 18.99 | T-Shirt size                | T-Shirts     |
            | Mango Tee        | 12.99 | T-Shirt size, T-Shirt color | PHP T-Shirts |
            | Symfony T-Shirt  | 15.00 |                             | PHP T-Shirts |
            | Doctrine T-Shirt | 15.00 |                             | PHP T-Shirts |
        And product "Mango Tee" is available in all variations
        And I am logged in as administrator

    Scenario: Viewing a list of products
        When I make a "GET" request to "/api/products"
        Then the response code should be 200
        And the response should be JSON
        And the response data has 5 items

    Scenario: Creating a new product
        When I make a "POST" request to "/api/products" with the following payload:
        """
        {
            "variantSelectionMethod": "choice",
            "availableOn": "2015-11-11 12:00:00",
            "workspace": {@id default_workspace},
            "masterVariant": {
                "price": "18.99",
                "sku": "my-product-sku-1",
                "onHand": 10,
                "availableOn": "2016-01-01 12:00:00",
                "width": 100,
                "height": 100,
                "depth": 100,
                "weight": 5
            },
            "translations": {
                "en_US": {
                    "name": "My product",
                    "description": "English description",
                    "slug": "my-product"
                },
                "nl_NL": {
                    "name": "Mijn product",
                    "description": "Nederlandse omschrijving",
                    "slug": "mijn-product"
                }
            },
            "attributes": {

            }
        }
        """
        Then the response code should be 201
        And the response should be JSON
        And there are 6 products
        And there is a product named "My product"

    Scenario: Viewing a single product
        When I make a "GET" request to "/api/products/{@id product.name='Mango Tee'}"
        Then the response should be JSON
        And the response code should be 200
        And the product name is "Mango Tee"

    Scenario: View all variants of a product
        When I make a "GET" request to "/api/products/{@id product.name='Mango Tee'}/variants"
        Then the response should be JSON
        And the response code should be 200
        And the response data has 15 items

    Scenario: View all translations of a product
        When I make a "GET" request to "/api/products/{@id product.name='Mango Tee'}/translations"
        Then the response should be JSON
        And the response code should be 200
        And the response data has 1 item

    Scenario: Update a product
        When I make a "PATCH" request to "/api/products/{@id product.name='Mango Tee'}" with the following payload:
        """
        {
            "name": "Mango Coffee",
            "variantSelectionMethod": "choice",
            "availableOn": "2015-11-11 12:00:00",
            "masterVariant": {
                "price": "18.99",
                "sku": "mango-coffee-1",
                "onHand": 10
            },
            "translations": {
                "en_US": {
                    "name": "Mango Coffee",
                    "description": "Delicious coffee made of the best Mango's"
                },
                "nl_NL": {
                    "name": "Mango Koffie",
                    "description": "Lekkere koffie, gemaakt van de beste mangos!"
                }
            }
        }
        """
        Then the response code should be 200
        And the response should be JSON
        And there are 5 products
        And there is a product named "Mango Coffee"
        And there is no product named "Mango Tee"

    Scenario: Delete a product
        When I make a "DELETE" request to "/api/products/{@id product.name='Super T-Shirt'}"
        Then the response code should be 204
        And there is no product named "Super T-Shirt"
```

**Comment by pjedrzejewski** [comment]
If we write scenario as in your example, following things happen:

* We do not really benefit from the main purpose of Gherkin scenario
* Yet we get all the overhead of writing step definitions, etc.

That being said, we want to describe our API using Behat, but:

* For simple CRUD we will keep PHPUnit, it is simpler and can use Alice fixtures, etc.
* For non-crud stuff, like the card, checkout and so on, we will use exactly the same scenarios but with different suites, ultimate goal is to have:
    * "domain" suite, which will opereate on domain level and describe zone matching logic for example;
    * "ui" suite, which interacts with Sylius UI through emulated or real (selenium) browser;
    * "api" suite, which will execute same scenarios for cart and other non-crud stuff but will interact with the API, not UI.

I find PHPUnit tests for API more readable compared to Behat scenarios describing expected response content and codes.

@steffenbrem What do you think?

**Comment by steffenbrem** [comment]
@pjedrzejewski I've been thinking about what you've said and I am currently reworking my api acceptance tests, and I think I will use https://github.com/Lakion/ApiTestCase for the CRUD calls. I will post back in this issue what I will end up using :+1:

**Comment by pjedrzejewski** [comment]
@steffenbrem I have been looking at JSON API, but it seemed complicated to implemented with JMS (at first glance at least) but it's great you have a bundle for that! I will definitely have a look, thanks! I like experimental. :D

**Comment by steffenbrem** [comment]
@pjedrzejewski It's quite neat, in the bundle you also have an `include` parameter, where you can `sideload` relationships in a single request. If you want to make it work with Sylius it would be just add the bundle and add a few lines of YAML for every resource. All JMS stuff will keep working :+1:

**Comment by steffenbrem** [comment]
@pjedrzejewski I ended up still using Behat to test the API. I can write the tests much faster that way and me and my team can use the features as API docs, I did use some of the functionality you provided in `ApiTestCase`, such as the `PHPMatcher`. The `channels.feature` file of my project looks like this now:

```yml
@channels
Feature: Channel management
    In order to sell through different entry points
    As a store owner
    I want to configure channels

    Background:
        Given store has default configuration
        And there are following users:
            | email                 | enabled |
            | admin@shopblender.com | yes     |
        And there are following customers:
            | email                 |
            | admin@shopblender.com |

    Scenario: Create new channel validation fail
        Given I am authorized as "admin@shopblender.com"
        When I make a "POST" request to "/api/channels" with body:
        """
            {}
        """
        Then the response code is 400

    Scenario: Create new channel
        Given I am authorized as "admin@shopblender.com"
        When I make a "POST" request to "/api/channels" with body:
        """
            {
                "workspace": "@workspace_1@.id",
                "name": "A new channel",
                "code": "C-NEW"
            }
        """
        Then the response code is 201

    Scenario: Get list of channels
        Given I am authorized as "admin@shopblender.com"
        When I make a "GET" request to "/api/channels"
        Then the response code is 200
        And the response equals:
        """
            {
                "jsonapi": {
                    "version": "1.0"
                },
                "meta": {
                    "page": 1,
                    "limit": 10,
                    "pages": 1,
                    "total": 1
                },
                "links": "@*@",
                "data": [
                    {
                        "type": "channels",
                        "id": "@integer@",
                        "attributes": {
                            "code": "DEFAULT-WEB",
                            "name": "@string@",
                            "description": "@null@",
                            "url": "@string@",
                            "color": "@null@",
                            "created-at": "@string@.isDateTime()",
                            "updated-at": "@string@.isDateTime()",
                            "enabled": true
                        },
                        "relationships": {
                            "workspace": "@*@",
                            "locales": "@*@",
                            "currencies": "@*@",
                            "products": "@*@",
                            "tags": "@*@",
                            "theme": "@*@",
                            "themes": "@*@",
                            "taxonomies": "@*@",
                            "payment-methods": "@*@",
                            "shipping-methods": "@*@",
                            "default-currency": "@*@",
                            "default-locale": "@*@"
                        },
                        "links": "@*@"
                    }
                ],
                "included": "@*@"
            }
        """
```

I really think Sylius would benefit a lot if the acceptance tests of the API are in Behat too. Not sure if this issue can be closed or not?
