### ISSUE TITLE
[RFC] When should order be completed?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4022]
I've been using `order.completedAt` as one way of determining if an order passed checkout (checking state machine is probably more accurate but in cases where you want a simple and fast check in queries this should be a good marker).

However this seems to be set when an order is `created` (which seems like a strange name since the order has already existed for a while before that, but that's a side issue!)

In the state machine configuration (https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/OrderBundle/Resources/config/state-machine.yml#L24) we have:

```
            create:
                from: [cart]
                to:   pending
            release:
                from: [pending]
                to:   released
            confirm:
                from: [cart, pending, released]
                to:   confirmed
```

 with callbacks defined as:

```
        callbacks:
            after:
                sylius_complete: { on: 'create', do: [@sylius.callback.complete_order,           'completeOrder'], args: ['object'] }
                sylius_number:   { on: 'create', do: [@sylius.sequence.doctrine_number_listener, 'enableEntity'],  args: ['object'] }
```

`completeOrder()` only does setting the `completedAt` date. It feels like this should be done on `confirm` not on `create`?  This attribute also might then have been better named as `confirmedAt`, 'completed' always makes me think of something at the end of it's lifecycle, whereas this determines the date at which the order passes checkout and enters the fulfilment process.

Obviously this needs thought and you have to be careful. Lots of processing happens at `confirm` time that might require this date, so it would probably need to be run first out of all of the callbacks.

Unless I'm missing the reason for setting this date here?
