### ISSUE TITLE
[RFC] Order state machine

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4060]
Hello!

Current states and state machine of Order is pretty confusing. This RFC aims to solve following problems:

* Clarifying all states that we have on the order;
* Making the checkout process cleaner;
* Making it easier to identify what is cart and what is order;

I will be talking about the following states and field:

* Order.state
* Order.checkoutState
* Order.shippingState
* Order.paymentState
* Order.completedAt

We currently use ``Order.completedAt`` to decide whether it is a Cart or Order. That's annoying. As suggested in another PR/issue, I think we should rename it to ``orderCheckoutCompletedAt`` and use it for information purposes when exactly the checkout has been completed.

## Checkout state

Now, to the states. Let's start from ``checkoutState``, which is pretty clear and reworked already in #3918. I will paste the configuration overview for reference:

```yaml
winzou_state_machine:
    sylius_order_checkout:
        class: %sylius.model.order.class%
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: %sylius.state_machine.class%
        states:
            cart: ~
            started: ~
            addressed: ~
            shipping_selected: ~
            payment_selected: ~
            completed: ~
        transitions:
            start:
                from: [cart]
                to: started
            address:
                from: [started]
                to: addressed
            readdress:
                from: [payment_selected, shipping_selected, addressed]
                to: started
            select_shipping:
                from: [addressed]
                to: shipping_selected
            reselect_shipping:
                from: [payment_selected, shipping_selected]
                to: addressed
            select_payment:
                from: [shipping_selected]
                to: payment_selected
            reselect_payment:
                from: [payment_selected]
                to: shipping_selected
            complete:
                from: [payment_selected]
                to: completed
```

This is pretty much self-explanatory and covers the whole checkout process. If you customize it, you will need to rework this state-machine, but this gives us clean way of executing callbacks, recalculations, etc.

## State

Next state is ``Order.state``, this one is a bit tricky, but it should represent the overall state of the order and also we should use it to identify if Order is a cart. Here is the state machine I propose as initial implementation:

```yaml
winzou_state_machine:
    sylius_order:
        class: %sylius.model.order.class%
        property_path: state
        graph: sylius_order
        state_machine_class: %sylius.state_machine.class%
        states:
            cart: ~
            new: ~
            abandoned: ~
            cancelled: ~
            closed: ~
        transitions:
            create:
                from: [cart]
                to: new 
            abandon:
                from: [new]
                to: abandoned
            cancel:
                from: [new]
                to: cancelled
            retry:
                from: [cancelled, abandoned]
                to: new
            close:
                from: [new]
                to: closed
```

Explanation of the states:

* ``cart`` - This is default state of the order and we use it to differentiate between Orders and Carts. Basically, everything that is not in state ``cart`` is an Order that should show up in the admin.
* ``new`` - Order goes into this state as soon as the checkout is completed. "New" orders appears in the backend.
* ``abandoned`` - If someone completes the checkout, but does not pay after X time, order goes into ``abandoned`` state, inventory is released, etc.
* ``cancelled`` - Cancelled via admin.
* ``closed`` - Final state of the order. When the order is paid and shipped, it becomes "closed". You can't modify it and that's end of the story.

Transitions are self-explanatory. Later we want to give the ability to "retry" an abandoned/cancelled order, that's why I added this transition.

## Payment state

This one represents the status of all payments on the order. We already partially support multiple payments per order, that's why I want to have this separate state.

```yaml
winzou_state_machine:
    sylius_order_shipping:
        class: %sylius.model.order.class%
        property_path: paymentState
        graph: sylius_order_payment
        state_machine_class: %sylius.state_machine.class%
        states:
            cart: ~
            awaiting_payment: ~
            partially_paid: ~
            cancelled: ~
            paid: ~
        transitions:
            request:
                from: [cart]
                to: awaiting_payment
            partially_pay:
                from: [awaiting_payment]
                to: partially_paid
            cancel:
                from: [awaiting_payment]
                to: cancelled
            pay:
                from: [awaiting_payment, partially_paid]
                to: paid
```

This one is very rough, I am sure we will need more transitions or even maybe states. I am unsure about the ``partially_paid`` state, perhaps we should have just one ``amount_due`` state or something like that.
One thing I want to avoid is discussing these longer than until next weekend because we really need to clean this up and get rid of remaining event listeners to regain control of the whole order processing.

## Shipping state

Sylius Order can have multiple shipments too, so we need to know what is the overall status of the order.

```yaml
winzou_state_machine:
    sylius_order_shipping:
        class: %sylius.model.order.class%
        property_path: shippingState 
        graph: sylius_order_shipping
        state_machine_class: %sylius.state_machine.class%
        states:
            cart: ~
            abandoned: ~
            new: ~
            ready: ~
            cancelled: ~
            partially_shipped: ~
            shipped: ~
        transitions:
            request:
                from: [cart]
                to: new
            abandon:
                from: [new]
                to: abandoned
            prepare:
                from: [new, pending]
                to: ready
            cancel:
                from: [new, pending]
                to: cancelled
            partially_ship:
                from: [ready, pending]
                to: partially_shipped
            ship:
                from: [ready, partially_shipped]
                to: shipped
```

I am not entirely sure about this one, so just throwing it here. I think we could safely skip ``partially_shipped`` state and transitions for now, because Sylius does not handle multiple shipments now. Except in the checkout.

## Summary

Some of these are already there, but not properly used or not in use at all. Let's brainstorm a bit and finally put this state machine into action!

**Comment by peteward** [comment]
* Checkout State :+1:  Very easy to customise anyway and there's nothing contentious there.
* Payment State :+1:  Makes sense to me.
* State
  * What's the use-case for completing checkout but then not paying for it?
  * I would have thought abandoned is more a term for people who don't make it to completing checkout.
  * Is an order really ever `closed`? It's very difficult to call an order closed if you support returns/refunds. The only way that I could think of an order being closed is if it's fully refunded or after X number of days when refund possibilities have expired. I know Sylius doesn't support refunds yet but this naming would become confusing as soon as it does. I think something like `shipped` or `fulfilled` is the better state than `closed`.

We merged `order.state` and `order.shippingState` and only use `order.state`, because of the above reason that the shipping becomes a core part of the order lifecycle and it became difficult to separate their meaning without contention. 

We have quite a long state machine definition, but it reflects a long chain of events around the order that includes a fraud review process where orders are `approved` or `rejected`, and subsequently transmitted to our stock system. There's also some sylius legacy stuff around locked carts in there:

```
        states:
            payment_unknown: ~
            cart:            ~
            cart_locked:     ~
            pending:         ~
            released:        ~
            abandoned:       ~
            confirmed:       ~
            rejected:        ~
            cancelled:       ~
            approved:        ~
            transmitted:     ~
            packed:          ~
            shipped:         ~
            returned:        ~
        transitions:
            payment_unknown:
                from: [cart, cart_locked, pending, released, confirmed]
                to:   payment_unknown
            lock_cart:
                from: [cart]
                to:   cart_locked
            unlock_cart:
                from: [cart_locked]
                to:   cart
            abandon:
                from: [cart, pending]
                to:   abandoned
            create:
                from: [cart]
                to:   pending
            release:
                from: [pending]
                to:   released
            confirm:
                from: [cart, pending, released]
                to:   confirmed
            approve:
                from: [confirmed]
                to:   approved
            reject:
                from: [confirmed]
                to:   rejected
            transmit:
                from: [approved]
                to:   transmitted
            cancel:
                # NOTE: When we change to Merret we might need to remove transmitted from here.
                from: [confirmed, approved, transmitted]
                to:   cancelled
            pack:
                from: [transmitted]
                to:   packed
            ship:
                from: [confirmed, packed]
                to:   shipped
            return:
                from: [shipped]
                to:   returned
```

**Comment by michalmarcinkowski** [comment]
* Checkout state :+1: - as for `completedAt` field I would rename it to simply `checkoutCompletedAt`
* Payment state :+1: 
* Shipping state
 * IMO there shouldn't be `cart` state, what does it mean `cart` in terms of shipping? Maybe we should have `none` state until the order qualifies for shipping (e.g. is paid) and then `new`? Same for `abandoned`, the shipping can be abandoned? When the order is abandoned the shipping should be cancelled. I would suggest:

```yaml
winzou_state_machine:
    sylius_order_shipping:
        class: %sylius.model.order.class%
        property_path: shippingState 
        graph: sylius_order_shipping
        state_machine_class: %sylius.state_machine.class%
        states:
            none: ~
            new: ~
            ready: ~
            cancelled: ~
            partially_shipped: ~
            shipped: ~
        transitions:
            request:
                from: [none]
                to: new
            prepare:
                from: [new]
                to: ready
            cancel:
                from: [new, ready]
                to: cancelled
            partially_ship:
                from: [ready]
                to: partially_shipped
            ship:
                from: [ready, partially_shipped]
                to: shipped
```

* Order state - it should represent the overall state of the order, but shouldn't represent any of payment or shipping state (it's redundant).
```yaml
winzou_state_machine:
    sylius_order:
        class: %sylius.model.order.class%
        property_path: state
        graph: sylius_order
        state_machine_class: %sylius.state_machine.class%
        states:
            cart: ~
            new: ~
            pending: ~
            abandoned: ~
            cancelled: ~
            completed: ~
        transitions:
            create:
                from: [cart]
                to: new
            process:
                from: [new]
                to: pending
            abandon:
                from: [new]
                to: abandoned
            cancel:
                from: [new, pending]
                to: cancelled
            complete:
                from: [pending]
                to: completed
```

Let me explain the differences:
 * `new` - After the checkout is completed
 * `pending` - the order is ready to be processed, e.g. if someone has fraud review process, there can be other states before `pending` e.g. `verified`, `approved` etc. The default implementation can be that when the order is paid, then it becomes `pending`.
 * `completed` - the order is 'done'. The default implementation can represent 'done' as paid and shipped.

Then when someone supports returns there can be two more states after `completed`:
 * `partially_returned` - only few items were returned (not everything)
 * `returned` - whole order was returned.

This way we have pretty flexible flow and do not have any redundant states.
