### ISSUE TITLE
Omnipay gateways not working with PayumBundle

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#4069]
I am trying to implement some Omnipay gateways (Mollie to be exact) in Sylius, but I can't get them to work. I keep getting `Your payment was declined.` after the purchase step. I want to make sure, before I dig into everything, if this even should work in Sylius? 

@makasim Is it possible to enforce a specific payment method (like Visa) through the Mollie gateway? As in that you have a `Visa` payment method in Sylius and then in the background it is handled by the `Mollie` gateway of Omnipay? Currently I do not see a way to accomplish this.

**Comment by makasim** [comment]
I have some experience with omnipay in general but any with the Mollie gateway nor the Mollie omnipay extension in particular. Sorry, I am afraid I am not able to help you much. Though you can provide us with more details and I'll do my best to help you.

**Comment by steffenbrem** [comment]
Well, first I would like to make the Omnipay bridge work, according to [this blog post](http://sylius.org/blog/payments-support) it isn't integrated in Sylius yet. 

As far as I know the `ActionInterface` is used in Sylius to set the correct data for the payment gateway, such as what items, total price etc. Should I implement the necessary `ActionInterface` (as it is done for Be2Bill with `ConvertPaymentToBe2BillAction`)? I think that is the reason why I get `Your payment was declined` in Sylius, could this be the case?

**Comment by makasim** [comment]
> Should I implement the necessary ActionInterface (as it is done for Be2Bill with ConvertPaymentToBe2BillAction)?

The built in action has to do the job: https://github.com/Payum/OmnipayBridge/blob/master/src/Action/ConvertPaymentAction.php

Though if it is not enough you can add your own converter.

**Comment by steffenbrem** [comment]
@makasim Hmm okay, Sylius has one too, I will try and use that one. I see currently it is only used for the `offline` factory. I think that is why my `omnipay` factory is failing the payment.

These are currently activated, I think I need to add my own entry for my configured factories. I will test it out soon, I am currently not at home.

```xml
<!-- PayPal -->
<service id="sylius.payum.action.convert_payment_to_paypal_express" class="Sylius\Bundle\PayumBundle\Action\ConvertPaymentToPaypalExpressAction">
    <tag name="payum.action" factory="paypal_express_checkout_nvp" alias="sylius.convert_payment" />
</service>

<!-- Be2bill -->
<service id="sylius.payum.action.convert_payment_to_be2bill" class="Sylius\Bundle\PayumBundle\Action\ConvertPaymentToBe2BillAction">
    <tag name="payum.action" factory="be2bill_direct" alias="sylius.convert_payment" />
    <tag name="payum.action" factory="be2bill_offsite" alias="sylius.convert_payment" />
</service>

<!-- Offline -->
<service id="sylius.payum.offline.action.convert_payment" class="Sylius\Bundle\PayumBundle\Action\ConvertPaymentToOfflineAction">
    <tag name="payum.action" factory="offline" alias="sylius.convert_payment" />
</service>
```

**Comment by steffenbrem** [comment]
While Payum now does use the `CapturePaymentAction` of the Sylius Payum Bundle, it still gives back the same error (not sure what is wrong). This is the request hat is being send, is this okay or is something missing?

[XDebug](http://puu.sh/mWZwn/4810b5c0ac.png)

**Comment by makasim** [comment]
Could you please post payum bundle config from the app/config/config.yml

**Comment by steffenbrem** [comment]
@makasim Sorry for my late reaction, it was carnaval here in Holland! This is how I have payum configured in my app:

```yml
payum:
    storages:
        Mango\Component\Core\Model\Order: { doctrine: orm }
        Mango\Component\Core\Model\Payment: { doctrine: orm }

    security:
        token_storage:
            Sylius\Bundle\PayumBundle\Model\PaymentSecurityToken: { doctrine: orm }

    dynamic_gateways:
        config_storage:
            Mango\Component\Core\Model\PaymentGateway: { doctrine: orm }

    gateways:
        mollie_ideal:
            omnipay:
                type: Mollie
                options:
                    apiKey: test_Xkt7MWKjcvHi4BCZNDiYJsQwFdZTtT
                    testMode: true
```

**Comment by steffenbrem** [comment]
I am still trying to get this to work, I have a better understanding of Payum now. But what I don't understand is why we need to implement capture and convert actions for all different gateways. Isn't that what Omnipay + Payum elliminate? Or am I wrong?

**Comment by makasim** [comment]
post the configuration of `Multisafepay` please

**Comment by steffenbrem** [comment]
@makasim My configuration:

```yml
gateways:
        multisafepay:
            omnipay:
                type: MultiSafepay
                options:
                    accountId: 10338365
                    siteId: 39063
                    siteCode: 041487
                    testMode: true
```
