### ISSUE TITLE
[Resource] sorting via routing doesn't work with pagination and limit disabled

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4072]
This doesn't sort:

```
reiss_backend_store_list:
    path: /
    methods: [GET]
    defaults:
        _controller: reiss.controller.store:indexAction
        _sylius:
            template: ReissStoreLocatorBundle:Backend/Store:index.html.twig
            paginate: false
            limit: false
            sorting:
                name: asc
```

A workaround is to set an arbitrarily high limit:

```
reiss_backend_store_list:
    path: /
    methods: [GET]
    defaults:
        _controller: reiss.controller.store:indexAction
        _sylius:
            template: ReissStoreLocatorBundle:Backend/Store:index.html.twig
            paginate: false
            limit: 2000
            sorting:
                name: asc
```
