### ISSUE TITLE
Unrecognized option "classes" under "sylius_cart"

### ISSUE THREAD

**Issue by barth7** [Sylius/Sylius#4155]
Hi Guys. I am trying to install sylius/cart-bundle (of course following the docs->http://docs.sylius.org/en/latest/bundles/SyliusCartBundle/installation.html)

In point "1.6. Updating database schema" after run:
`"php app/console doctrine:schema:update --force"`

I get the error:
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "classes" under "sylius_cart"
```

My config.yml:
```
...
 sylius_cart:
     resolver: app.cart_item_resolver # The id of our newly created service.
     classes: ~
 
 sylius_order:
     driver: doctrine/orm # Configure the doctrine orm driver used in documentation.
 
 sylius_money: ~
```

My Services.yml:

```
 services:
       app.cart_item_resolver:
                 class: AppBundle\Cart\ItemResolver
                 arguments: ['@doctrine.orm.entity_manager']
```

I was searching for similar error but with no luck...
