### ISSUE TITLE
[Support Request][0.16] Behat usage for sylius standard edition

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#4209]
Hello guys,

I'm trying to setup behat testing over sylius standard edition and I've a few issues.

I've copied parts of `@product` suite with product_attributes.feature into my application.

- javascript authorization. For some reason I can't authorize and go beyond login page.
```behat
  @javascript
  Scenario: Accessing attribute creation form
    Given I am on the product attribute index page
      │ string(23) "product attribute index"
      │ string(38) "sylius_backend_product_attribute_index"
      │ array(0) {
      │ }
      │ 
      Current page is "/administration/login", but "sylius_backend_product_attribute_index" expected. (Behat\Mink\Exception\ExpectationException)
    When I click button "Create"
    And I choose "checkbox" attribute type
    Then I should be on the product attribute creation page for "checkbox" type
    And I should see select "Type" with "Checkbox" option selected
    And I should not be able to edit "Type" select
```
No errors whatsoever, it proceeds to next scenario step, like it was success.
- rbac permissions. My javascript calls fails, because default administrator user doesn't have permissions assigned to him. Solved by hooking into scenario with rbac initialize. Not cool, but what is a correct solution?
- behat.yml.dist `javascript` section doesn't work at all. I've moved js configuration under default `extensions` section.

My `behat.yml.dist`

```
 default:
     formatters:
         pretty:
             verbose:  true
             paths:    false
             snippets: false
 
     suites:
         products:
             contexts:
                 - Behat\MinkExtension\Context\MinkContext
                 #- Sylius\Bundle\CoreBundle\Behat\HookContext
                 - Acme\Bundle\CoreBundle\Behat\HookContext
                 - Sylius\Bundle\CoreBundle\Behat\CoreContext
                 - Sylius\Bundle\MoneyBundle\Behat\MoneyContext
                 #- Sylius\Bundle\ProductBundle\Behat\ProductContext
                 - Acme\Bundle\CoreBundle\Behat\ProductContext
                 - Sylius\Bundle\ResourceBundle\Behat\FixtureContext
                 - Sylius\Bundle\TaxationBundle\Behat\TaxationContext
                 - Sylius\Bundle\TaxonomyBundle\Behat\TaxonomyContext
                 #- Sylius\Bundle\WebBundle\Behat\WebContext
                 - Acme\Bundle\CoreBundle\Behat\WebContext
                 - Sylius\Bundle\ChannelBundle\Behat\ChannelContext
             filters:
                 tags: "@products"
 
     extensions:
         Lakion\Behat\MinkDebugExtension:
             directory: etc/build
             screenshot: true
         Behat\MinkExtension:
             sessions:
                 default:
                     symfony2: ~
                 javascript:
                     selenium2: ~
         Behat\Symfony2Extension: ~
 
     #gherkin:
     #    filters:
     #        tags: "~@javascript"
 
javascript:
     extensions:
         Lakion\Behat\MinkDebugExtension:
             screenshot: true
         Behat\MinkExtension:
             base_url: http://localhost:8080/
             selenium2:
                 capabilities:
                     browserName: chrome
                     browser: chrome
                     version: ""
                     chrome:
                         switches:
                             - "start-fullscreen"
                             - "no-sandbox"
             browser_name: chrome
             show_auto: false
 
     gherkin:
         filters:
             tags: "@javascript"
```

I think my mink configuration is at fault here, but have no idea how to fix that.

/cc @pamil 

Thank you for any help.

Dmitri.
