### ISSUE TITLE
[RFC] [DX] Consistent factory decoration

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#4226]
Factories has been introduced to Sylius with refactoring of ResourceBundle. It was a must-have feature and it is great that finally we have decoupled this logic. But factories overriding isn't as easy as other resource-related stuff. We have to change theirs definition in extensions of each bundle, because we decide to use decorator pattern. It makes spec much cleaner, but there is one problem. We have a few different convention around Sylius how to override them. And new ones are coming. Right now I have noticed following implementations:
1. [Taxonomy](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/TaxonomyBundle/DependencyInjection/SyliusTaxonomyExtension.php#L49)
2. [Attribute](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AttributeBundle/DependencyInjection/Compiler/RegisterAttributeFactoryPass.php)
And another 2 in PRs:
1. [Payment] Adding PaymentFactory #4214 
2. [Promotion] Implement custom promotion action factory #4223

When it is obvious, that attribute needs a different approach, because of it genericness, most of bundles extend factories pretty straightforward. I just want to hear your opinion which implementation is the most readable for you and which one should we use.

**Comment by michalmarcinkowski** [comment]
For simple decoration in extensions I see two options there:

1) Creating two new definitions:
```
$baseFactoryDefinition = new Definition(Factory::class, [new Parameter('sylius.model.promotion_action.class')]);
$promotionActionFactoryClass = $container->getParameter('sylius.factory.promotion_action.class');
$decoratedPromotionActionFactoryDefinition = new Definition($promotionActionFactoryClass, [$baseFactoryDefinition]);
$container->setDefinition('sylius.factory.promotion_action', $decoratedPromotionActionFactoryDefinition);

$container->setDefinition('sylius.factory.promotion_action', $decoratedPromotionActionFactoryDefinition);
```
2) Changing class of base definition and creating only one new definition:
```
$couponFactoryDefinition = $container->getDefinition('sylius.factory.promotion_coupon');
$couponFactoryClass = $couponFactoryDefinition->getClass();
$couponFactoryDefinition->setClass(Factory::class);
$decoratedCouponFactoryDefinition = new Definition($couponFactoryClass);

$container->setDefinition('sylius.factory.promotion_coupon', $decoratedCouponFactoryDefinition);
```

Which approach seems better for you guys?

**Comment by pamil** [comment]
Why can't we define decorators at bundles' `services.xml`?

```xml
<service id="sylius.factory.product.extended" class="ProductFactory" decorates="sylius.factory.product">
    <argument type="service" id="sylius.factory.product.extended.inner" />
</service>
```

1. `ResourceBundle` builds default or translatable model factory at `sylius.factory.product`
2. We decorate it in XML

Am I missing something?

**Comment by pjedrzejewski** [comment]
@pamil :+1: except for cases where we use compiler passes in Sylius bundles, but hopefully we can get rid of that.

**Comment by michalmarcinkowski** [comment]
Will it work correctly? In the `Configuration` class we will have to specify `Factory:class` always, so the parameter `sylius.factory.banan.class` will have `Factory::class` value, not `BananFactory::class`. Unless the `decorates` option replaces the class parameter also?

**Comment by pamil** [comment]
@michalmarcinkowski 

3) Using built-in decorators, one another definition and less magic than 2.

```php
$factoryDefinition = new Definition(
    $container->getParameter('sylius.factory.product.class'), 
    [new Reference('decorated_service')]
);
$factoryDefinition->setDecoratedService('sylius.factory.product', 'decorated_service');

$container->setDefinition('sylius.factory.product.decorating', $factoryDefinition);
```

**Comment by pamil** [comment]
@michalmarcinkowski I forgot about that `ResourceBundle`'s logic. IMHO we should look for a support for decorating factories in RB itself.

I'm thinking of 3 possible levels of factories:
1. Base RB's Factory (or custom class in case if constructor needs some parameter)
2. (optional) Decorator that handles translatable entities, that sets current and fallback locale on them, with priority below 0
3. (optional) Decorator that adds all the custom build methods, `createNamed` etc., with priority or higher

**Comment by next-sentence** [comment]
How can I override `sylius.factory.product` with an additional argument?

**Comment by nakashu** [comment]
I'm struggling when trying to define my own factory for a regular resource, not overriding the core classes. For me it seems there probably a bug in defining factories for own resource.

I use a workaround see below, but it seems really unnecessary to define 2 services for a simple factory override.

resource config:
```yaml
sylius_resource:
    resources:
        acme.model:
            classes:
                factory: Acme\Factory\ModelFactory
```

This is what I would expect to work for defining a custom factory, but it passes arguments for the inner factory eg.: FQCN/TranslationProvider...
```yaml
acme.extended.factory.model:
    class: Acme\Factory\ModelFactory
    decorates: acme.factory.model
    arguments:
        - "@acme.extended.factory.model.inner"
        - "@acme.repository.menu"
```

This is what I have to define.

```yaml
acme.base.factory.model:
    class: Sylius\Component\Resource\Factory\Factory
    public: false
    arguments:
        - Acme\Model

acme.factory.model:
    class: Acme\Factory\ModelFactory
    arguments:
        - "@acme.base.factory.model"
        - "@acme.repository.model"
```
