### ISSUE TITLE
[Resource] - route configuration validation and exclusive parameters

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#4240]
Route attribute configuration for resources under the "_sylius" key are currently not validated

You can have something like this there and everything is "valid"

``` yml
sylius_backend_product_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Product:index.html.twig
            spaghetti: delicious
```

This start to be a problem when you got conflicting configurations there or just plain typos, and try to debug why it doesn't work.

Conflicting or exclusive configuration is having configured custom repository method, with criteria and sorting.

``` yml
sylius_backend_product_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Product:index.html.twig
            sortable: true
            repository:
                method: createFilterPaginator
                arguments: [$criteria, $sorting, $deleted]
            criteria:
                mainTaxon: 1
                deleted: 0
            sorting:
                createdAt: desc
```

Based on documentation and reference for route configuration, people can assume that those arguments can be set all together. But after you define `repository.method`, `criteria` and `sorting` won't be applied.

Because of the missing validation there are also some misconfigured routes in the project now.

`payment.yml`

``` yml
sylius_backend_payment_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.payment:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Payment:index.html.twig
            method: createFilterPaginator # this wont be called, not valid configuration
            arguments: [$criteria, $sorting, $deleted] # this wont be passed, not valid configuration
            paginate: 20
            sortable: true
            sorting:
                updatedAt: desc
```

`inventory.yml`

``` yml
sylius_backend_inventory_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Inventory:index.html.twig
            repository:
                method: createFilterPaginator
                arguments: [$criteria, $sorting, false]
            sortable: true
            sorting: # this will be skipped as customer repository method is defined
                updatedAt: asc
```
