### ISSUE TITLE
[SearchBundle] Fatal error when using elasticsearch engine

### ISSUE THREAD

**Issue by okwinza** [Sylius/Sylius#4274]
When `engine: elasticsearch` then
> php app/console sylius:search:index -v

is failing with

>PHP Fatal error:  Call to a member function get() on null in /var/www/home/sylius.okwinza.ru/src/Sylius/Component/Translation/Model/AbstractTranslatable.php on line 133

Works fine with `engine: orm` though. 
Digging further. Any clues are welcome in the meantime.

**Comment by youmad** [comment]
Changing model class in
```
fos_elastica:
    indexes:
        sylius:
            types:
                product:
                    persistence:
                        model: Sylius\Component\Core\Model\Product
```
to
```
                        model: AppBundle\Entity\Product
```
solve same issue.
