### ISSUE TITLE
[RFC][SearchBundle] Wich way to handle multilingual in elasticsearch engine

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#4312]
Hi,

I have to manage multilingual search, depending on locale.

Have a look on https://www.elastic.co/guide/en/elasticsearch/guide/current/language-pitfalls.html already mentionned in #3080.

Especially this part : 

> 
User searches also come in three main varieties:
    1 - Users search for words in their main language.
    2 - Users search for words in a different language, but expect results in their main language.
    3 - Users search for words in a different language, and expect results in that language (for example, a bilingual person, or a foreign visitor in a web cafe). 

My current problem is that translations are not indexed for products. That can be easily done with a mapping like this in products : 
```yaml
              product:
                     mappings:
                         id: { type: integer, index: not_analyzed }
                         name: { type: string }
                         description: { type: string }
                         slug: { type: string, index: not_analyzed }
                         translations:
                             type: object
                             properties:
                                 locale: { type: string, index: not_analyzed }
                                 name: { type: string }
```

After that, i can filter or not the elastic query as mentioned in #3080.

It depends on use case, i think, maybe it is a setting ?

The default behaviour, without any change will be almost "Users search for words in a different language, but expect results in their main language" (results will be in administrator language)
