### ISSUE TITLE
Error "sylius_product.driver" cannot be overwritten

### ISSUE THREAD

**Issue by ghost** [Sylius/Sylius#432]
Hi !

I've a lot of difficulties to start a clean new project using Sylius-standard : 

https://github.com/Sylius/Sylius-Standard/issues/3

Today, I try to get the sylius-standard, and update the vendor before using it, I thought maybe it fix the problems I've got, so I do : 

```
cd sylius-standard
composer update
```

But at the end I've got : 

```
<code>
 [Symfony\Component\Config\Definition\Exception\ForbiddenOverwriteException]  
  Configuration path "sylius_product.driver" cannot be overwritten. You have   
  to define all options for this path, and any of its sub-paths in one config  
  uration section.  
</code>
```

In fact, I've to delete the following part of code in sylius.yml : 

```
<code>
sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Sylius\Bundle\CoreBundle\Model\Product
            controller: Sylius\Bundle\CoreBundle\Controller\ProductController
            repository: Sylius\Bundle\CoreBundle\Repository\ProductRepository
            form: Sylius\Bundle\CoreBundle\Form\Type\ProductType
</code>
```

But then I've got other errors and errors and errors :/ ...

Did somebody have got few moments to help on that standard edition ?

Thanks a lot ;)
