### ISSUE TITLE
AdjustmentFactory service decoration - why? 

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4339]
Some recent changes have added the following config:

```
<parameter key="sylius.custom_factory.adjustment.class">Sylius\Component\Order\Factory\AdjustmentFactory</parameter>

<service id="sylius.custom_factory.adjustment" class="%sylius.custom_factory.adjustment.class%" decorates="sylius.factory.adjustment" public="false">
      <argument type="service" id="sylius.custom_factory.adjustment.inner" />
 </service>
```

I'm just wondering what this achieves? From what I understand, service decoration allows you access to the original service, but I don't see the use-case in getting the default Resource Factory?

The downside of the above changes means that the following doesn't work anymore:

```
sylius_order:
    resources:
        adjustment:
            classes:
                model: Reiss\OrderBundle\Entity\Adjustment
                factory: Reiss\OrderBundle\Entity\Factory\AdjustmentFactory
```

As the decorating service definition is overriding my override. 

Sylius config, while wonderfully powerful isn't exactly for the coding novice. When you start having to worry about alternative methods of overriding the services which are overriding your overridden services then you're really down the rabbit-hole...

The solution wasn't exactly complex, just feels ugly to have an inconsistence here unless it's really required:

```
parameters:
    sylius.custom_factory.adjustment.class: Reiss\OrderBundle\Entity\Factory\AdjustmentFactory
```
