### ISSUE TITLE
Stripe via OmniPay - ObtainCreditCardAction

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#4405]
I have just upgraded to 0.17 and just cannot get Stripe to work (Paypal Express Checkout works). I have spent the last few hours debugging, but can't get this to work and any help would be appreciated.

The problem seems to be that the ObtainCreditCardAction is never added to the gateway. Do I have to do something extra for that to be a step?

My payum configuration:
```
payum:
    gateways:
        stripe:
            omnipay:
                type: Stripe
                options:
                    apiKey: %stripe.secret_key%
                    testMode: %stripe.test_mode%
```

The above previously worked fine for 0.16 without any additional configuration.
