### ISSUE TITLE
[order][core] - cannot override order model, gedmo versioned on address

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#4427]
When trying to override Order class undefined index on shippingAddress and billingAddress occurs:

> [Symfony\Component\Debug\Exception\ContextErrorException]
  Notice: Undefined index: shippingAddress

It is somehow caused by the gedmo:versioned in the supperclass mapping.

```yml
Amce\AppBundle\Entity\Order\Order:
    type: entity
    table: sylius_order
    fields:
        stuff:
            type: string
            column: stuff
```

```yml
sylius_order:
    resources:
        order:
            classes:
                model: Acme\AppBundle\Entity\Order\Order
```

```php
namespace Acme\AppBundle\Entity\Order;

use Sylius\Component\Core\Model\Order as BaseOrder;

class Order extends BaseOrder
{
    /**
     * @var string
     */
    protected $stuff;
```

If <gedmo:versioned /> is removed from the superclass mapping everything work fine.
```xml
  <one-to-one field="shippingAddress" target-entity="Sylius\Component\Addressing\Model\AddressInterface">
            <join-column name="shipping_address_id" referenced-column-name="id" nullable="true" />
            <cascade>
                <cascade-persist/>
                <cascade-remove/>
            </cascade>
            <gedmo:versioned /> <!-- REMOVE and works -->
        </one-to-one>

        <one-to-one field="billingAddress" target-entity="Sylius\Component\Addressing\Model\AddressInterface">
            <join-column name="billing_address_id" referenced-column-name="id" nullable="true" />
            <cascade>
                <cascade-persist/>
                <cascade-remove/>
            </cascade>
            <gedmo:versioned /> <!-- REMOVE and works -->
        </one-to-one>
```
