### ISSUE TITLE
[ThemeBundle] Enabling local theme fails

### ISSUE THREAD

**Issue by kielabokkie** [Sylius/Sylius#4497]
I'm trying to setup a local theme using the new ThemeBundle but I'm struggling to get my theme to load. I've created a `themes` folder in the `app` directory and placed the required files and folders. The part that I can't get to work is loading the theme using the kernel request listener.

This is my `services.yml` file:
```yml
services:
  listener.request:
    class: AppBundle\EventListener\RequestListener
    arguments: ['@sylius.theme.repository.in_memory', '@sylius.context.theme']
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

```

 And my `RequestListener.php`:
```php
<?php

namespace AppBundle\EventListener;

use Sylius\Bundle\ThemeBundle\Context\ThemeContextInterface;
use Sylius\Bundle\ThemeBundle\Repository\ThemeRepositoryInterface;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\HttpKernelInterface;

class RequestListener
{
    /**
     * @var ThemeRepositoryInterface
     */
    private $themeRepository;

    /**
     * @var ThemeContextInterface
     */
    private $themeContext;

    /**
     * @param ThemeRepositoryInterface $themeRepository
     * @param ThemeContextInterface $themeContext
     */
    public function __construct(ThemeRepositoryInterface $themeRepository, ThemeContextInterface $themeContext)
    {
        $this->themeRepository = $themeRepository;
        $this->themeContext = $themeContext;
    }

    /**
     * @param GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        if (HttpKernelInterface::MASTER_REQUEST !== $event->getRequestType()) {
            // don't do anything if it's not the master request
            return;
        }

        $this->themeContext->setTheme(
            $this->themeRepository->findOneByName('pixelfusion/ubiq-theme')
        );
    }
}
```

The error that's being thrown when I load the frontend is:
```
Fatal error: Call to undefined method Sylius\Component\Core\Theme\ChannelBasedThemeContext::setTheme()
```

So the theme context resolves to the `ChannelBasedThemeContext` class but this doesn't a have method to set the theme. Any pointers to what I'm doing wrong here are appreciated!
