### ISSUE TITLE
Attribute translations on archetype listing is null

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#4599]
I have installed Sylius-standard version 17 
After I create an archetype I get this error:
![error](https://cloud.githubusercontent.com/assets/5624862/13958784/19aeae52-f05a-11e5-8bc1-2abc2898aaa0.png)

On attributes listing I don't get errors

Thanks in advance for any help!

**Comment by tuka217** [comment]
You probably not set a translation for your archetype for given locale. 
Please, check in documentation how to work with translations:
http://docs.sylius.org/en/latest/components/Translation/basic_usage.html?highlight=translation
I hope it will help :)

**Comment by yopop666** [comment]
I don't change anything on archetype bundle and his views.
The listing of attributes is ok on attributes page.
On archetype page  when is called attribute name, in **Sylius\Component\Translation\Model\AbstractTranslatable**, **translate** method, the parameter ```$this->translations``` is null instead of ArrayCollection.

**Comment by sfriel** [comment]
I received this error after extending 'sylius_attribute'. I needed to update 'sylius_archetype' configuration to point to my new Attribute class like: 
`
sylius_attribute:
    driver: doctrine/orm
    resources:
        product:
            attribute:
                classes:
                    model: Acs\Component\Attribute\Model\Attribute
                translation:
                    classes:
                        model: Acs\Component\Attribute\Model\AttributeTranslation
sylius_archetype:
    resources:
        product:
            attribute: Acs\Component\Attribute\Model\Attribute`

**Comment by ylastapis** [comment]
Hello @yopop666 

I got the exact same problem. Any clue about this issue ?
Link to documentation is outdated : http://docs.sylius.org/en/latest/components/Resource/translation.html

Thanks !

**Comment by yopop666** [comment]
Hello @ylastapis  curent configuration is:
```
sylius_attribute:
    driver: doctrine/orm
    resources:
            product:
                subject: SyliusCustom\Bundle\ProductBundle\Entity\Product
                attribute:
                    classes:
                        model: SyliusCustom\Bundle\ProductBundle\Entity\Attribute
                        controller: SyliusCustom\Bundle\AttributeBundle\Controller\AttributeController
```
Hope it helps
