### ISSUE TITLE
[BlogBundle] Resource related questions

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#4632]
I am attempting to write a BlogBundle the Sylius way, but I have been running into many problems, mostly from lack of documentation (which is very understandable). I have been able to figure most things out from reading the code, but I am still stuck on a few things.

I want to take advantage of the Resource bundle, and I am 95% of the way there (setup two sections, admin and frontend), and everything is going well so far.

Question:
My frontend routes still require anonymous users to have permissions to the roles (app.post.index, app.post.show). How do I give all anonymous users permissions to do those things?

I have tried to find the answer to this in the source code, but I don't think we do that yet.

**Comment by liverbool** [comment]
Did you mean `disable permission`?

```yaml
route_name:
    path: /
    defaults:
        _controller: ...
        _sylius:
            permission: false
````

**Comment by inssein** [comment]
@liverbool ah totally didn't see that. That said, I cannot figure out how to do the above when defining an entire resource.

In the example:
```
app_post:
    resource: |
        alias: app.post
        only: ['show', 'index']
        section: library
    type: sylius.resource
```

I have tried a few variations of putting ```permission: false``` in there with no luck.
