### ISSUE TITLE
[RFC] Replacing SearchBundle with Grid Elastica driver

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4659]
Helloes,

SearchBundle has been great and provided us with search functionality when there was none, but it has some issues:
- MySQL implementation of faceted search is quite complex and not very efficient
- Finder is stateful and not clean
- ProductController indexByTaxon method is quite messy

Goals:

Maintaining SQL implementation of search is a lot of work and most stores use ElasticaBundle and integrate search manually (which is quite simple) or use our not-so-perfect Elastic engine for SearchBundle. I'd like to simplify the whole thing.

Solution:

Product list by category and default product search would be handled by our GridBundle. Because search is really just a grid of products with filtering and sorting. All this can be handled by Grid component now. Default Sylius would ship with Doctrine ORM grid configured, which would provide basic search functionality (no faceted search):

Routing:

```
sylius_shop_product_index:
     path: /products/{taxonPermalink}
     defaults:
         _controller: sylius.controller.product:indexAction
         _sylius:
             template: SyliusShopBundle:Product:index.html.twig
             grid: sylius_shop_product
```

Grid (Doctrine/ORM):

```
sylius_grid:
    grids:
        sylius_shop_product:
            driver:
                name: doctrine/orm
                options:
                    class: %sylius.model.product.class%
                    repository:
                        method: createByChannelAndTaxonPermalinkQueryBuilder
                        arguments:
                            - 'expr:service('sylius.context.channel').getChannel()'
                            - $taxonPermalink
            filters:
                search:
                    type: string
                    options:
                        fields: [translation.name, translation.description]
                 ### Other simple filters totally possible, just without facets and with worse perf. compared to ElasticSearch of course.
            sorting:
                translation.name: asc
```

Grid (Elastica)

```
sylius_grid:
    grids:
        sylius_shop_product:
            driver:
                name: elastica
                options:
                    index: sylius
                    type: product
                    terms: # ???
                        channels: 'expr:service('sylius.context.channel').getChannel()'
                        taxons: $taxonPermalink
            filters:
                search:
                    type: ??? string or elastica (depends on how we can implement it)
                 ### Your facets configurations go here
                 tshirt_color:
                     type: sylius_product_attribute
                     options:
                          code: tshirt_color
```

As you can see, using Grids allows us to reuse the whole system of filters and forms, if we implement Elastica driver, we can use the same system and make it work with both Doctrine ORM and Elastica. Sounds crazy but I already did that for Doctrine DBAL and Doctrine ORM. :dancer: 

Pagerfanta supports Elastica and FOSElasticaBundle supports Pagerfanta, so that makes whole thing even easier.

@NeverResponse will be working on Elastica driver for grids. :)

Steps to implement new driver in Sylius grids:
1. Implement ElasticaDriver, which implements DriverInterface, example for ORM: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/GridBundle/Doctrine/ORM/Driver.php
2. Implement DataSource for this driver: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/GridBundle/Doctrine/ORM/DataSource.php
3. Implement ExpressionBuilder: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/GridBundle/Doctrine/ORM/ExpressionBuilder.php
4. Register in container with tag `sylius.grid_driver`: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/GridBundle/Resources/config/drivers.xml
5. Configure in your Grid :dancer: 

Things to note:
1. Grid bundle should not depend on FOSElasticaBundle, the driver should be only enabled if FOSElasticaBundle is in Kernel.
2. **Initial implementation needs to do only one thing: Search by string with pagination (`findPaginated`) method should be helpful here, we do not need facets in the PoC**

Things to figure out in the future:
1. How to pass Aggregates information to filters.
2. How to take over the world with YAML programming.

Helpful links:
- Elastica documentation: http://elastica.io/getting-started/search-documents.html
- FOSElasticaBundle usage guide: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/usage.md
- Pagerfanta with ElasticaAdapter usage: https://github.com/whiteoctober/Pagerfanta
