### ISSUE TITLE
[SyliusApiBundle] Api-Calls bypasses token based authentication and always redirects to /connect

### ISSUE THREAD

**Issue by itinance** [Sylius/Sylius#4707]
As described in the API-related Docs [for Authentication](http://docs.sylius.org/en/latest/api/authorization.html), everything works fine when it comes to register a new api client and to retrieve an access token for an existing user.

Anyway, it is not possible to execute any API-call with the access_token passed as "Authentication"-Header. Every api call will be responded with a 301-redirect to the /connect-Route, which offers 3 links to connect with amazon, google and facebook and which seems to come from HWI-OAuth-Bundle.
Also it does not matter weather an Authentication-Header is passed or not or if it contains valid characters or not.

While investigating this issue i stumbled upon this [question](http://stackoverflow.com/questions/36452661/sylius-api-call-with-oauth-token-always-redirects-to-connect-route?noredirect=1#comment60527214_36452661) at stackoverflow which describes nearly the same behaviour.

I also tried this out with a completely new sylius installation based on 0.17.0.

### I. api client creation with all grant types:

`php app/console sylius:oauth-server:create-client --grant-type="password" --grant-type="refresh_token" --grant-type="token" 
`
_Output:_

> A new client with public id 1vfmrpbwbkjooksgwo0s8sowck08skww4o8o0c4ccgg88o04sw, secret 22oew12ifockko4skogw0kc80g0084w8s8swock0kocccg8scc has been added

> 

### II. retrieve access token

```
curl http://www.example.dev/oauth/v2/token \
    -d "client_id"=1vfmrpbwbkjooksgwo0s8sowck08skww4o8o0c4ccgg88o04sw \
    -d "client_secret"=22oew12ifockko4skogw0kc80g0084w8s8swock0kocccg8scc \
    -d "grant_type"=password \
    -d "username"=mail@example.com \
    -d "password"=example

```
This is a valid user which is able to being logged in. More concretely this user is the admin user which was created at the installation process of sylius.

_Output:_

`{"access_token":"OWY5MjZhMzdlMzc0ZTBiMWIyMTQzMjdiMTFlOTI5NzBiYmFjYzYwZTEyMGU1NmZhZTViMjY5OThmYmY3NGIzNw","expires_in":3600,"token_type":"bearer","scope":null,"refresh_token":"ZjBiOTkwZjFjMjA4M2NjYzRmZDhjM2Q5NzdmYjE1MDA1MGE5N2ZjY2UxYTJmZmI5NmEwNzBjOTAyMTQ4N2I5Ng"}
`
### III. use the access token for any api request:

`curl http://www.example.dev/api/users -H "Authorization: Bearer OWY5MjZhMzdlMzc0ZTBiMWIyMTQzMjdiMTFlOTI5NzBiYmFjYzYwZTEyMGU1NmZhZTViMjY5OThmYmY3NGIzNw"
`
The Response is a redirect 301 to the http://www.example.dev/connect

This is my security.yml:

```
# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

security:
    providers:
        sylius_user_provider:
            id: sylius.user_provider.name_or_email
    encoders:
        Sylius\Component\User\Model\UserInterface: sha512
    firewalls:
        administration:
            switch_user: true
            context:     user
            pattern:     /administration/.*
            form_login:
                provider:     sylius_user_provider
                login_path:   /administration/login
                check_path:   /administration/login-check
                failure_path: /administration/login
                default_target_path: /administration/dashboard
                use_forward:  false
                use_referer:  true
            logout:
                path:   /administration/logout
                target: /administration/login
            anonymous: true

        main:
            switch_user: { role: ROLE_SYLIUS_ADMIN }
            context:     user
            pattern:     /.*
            form_login:
                provider: sylius_user_provider
                login_path: /login
                check_path: /login_check
                failure_path: /login
                default_target_path: /
                use_forward:  false
                use_referer: true
            remember_me:
                key: %sylius.secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            oauth:
                resource_owners:
                    amazon:   "/login/check-amazon"
                    facebook: "/login/check-facebook"
                    google:   "/login/check-google"
                login_path:   /connect
                failure_path: /connect
                oauth_user_provider:
                    service: sylius.oauth.user_provider
            logout: true
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api, role: ROLE_API }
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/administration/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/administration.*", role: ROLE_ADMINISTRATION_ACCESS }

        - { path: "/account.*", role: ROLE_USER }

        - { path: "/_partial.*", ip: 127.0.0.1 }

```

And the roles of the user are: 

`a:2:{i:0;s:9:"ROLE_USER";i:1;s:8:"ROLE_API";}`
