### ISSUE TITLE
[Mailer] - admin mail configuration weird inconsistencies

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#4766]
Having this configuration

``` yml
sylius_mailer:
    templates:
        test.email.name: TestEmail.html.twig
    emails:
        test_email:
            subject: CONFIG test subject
            template: TestEmail.html.twig
            sender:
                name: CONFIG test sender
                address: config@example.com
```

and this record in db:

| code | subject | template | sender_name | sender_address |
| --- | --- | --- | --- | --- |
| test_email | DB subject | TestEmail.html.twig | DB sender name | db@example.com |

Generated Email is this:
subject: **CONFIG** test subject
sender name: **DB** sender name
sender address: **db**@example.com

If template in DB is set to use Custom template (null) -- mail got all data from db record.
### Whats the intended behaviour ?
1. when using pre-defined template, allow to override all fields with user defined values from storage (maybe except content, but that could be pass to template as variable as well)
2. when using pre-defined template, allow to override only `enabled`, `sender name`, `sender email`. (current implementation - but is confusing and fields should be hidden when not applicable)
3. when using pre-defined template, allow to override only `enabled`.
