### ISSUE TITLE
Template not found with new resource/entity/model in ResourceBundle

### ISSUE THREAD

**Issue by itinance** [Sylius/Sylius#4800]
I setup a new entity as a resource for ResourceBundle and got stuck while using custom templates for CRUD-operations in backend. For more details you'll find my [question at SO](http://stackoverflow.com/questions/36634718/using-a-custom-template-for-a-new-entity-in-sylius-with-its-resourcebundle) and also the simple [project](https://github.com/itinance/sylius_new_entity) for documentation purposes  at github including necessary steps in the readme.md to setup the project and the database.

Automatic routing thru the ResourceBundle works quite fine. But only the template for update-operation will be found and successfully rendered as expected. Not the others for "index" and "create" ("template not found", even they are present at same location).

Here's how i did it after creating the entity "book" as found in documentation of ResourceBundle:

**app/config/config.yml:**
```
sylius_resource:
    resources:
        app.book:
            templates: AppBundle:Book:Backend
            classes:
                model: AppBundle\Entity\Book
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
```

**app/config/routing.yml:**
```
app_book:
   resource: |
       alias: app.book
       section: admin
   type: sylius.resource
   prefix: /administration
   defaults:
        _sylius:
            permission: false
```

Running php app/console debug:router will list the new routes for my new entity Book:

```
app_book_index                                        GET              ANY      ANY    /administration/books/                                                                   
app_book_create                                       GET|POST         ANY      ANY    /administration/books/new                                                                
app_book_update                                       GET|PUT|PATCH    ANY      ANY    /administration/books/{id}/edit                                                          
app_book_show                                         GET              ANY      ANY    /administration/books/{id}                                                               
app_book_delete                                       DELETE           ANY      ANY    /administration/books/{id}                                                               
```

But when i login into the backend (while everything works fine), and call explicitly the URL "/administration/books", this error occurs:

> Unable to find template "AppBundle:Book:Backend:index.twig".
> 
> CRITICAL - Uncaught PHP Exception InvalidArgumentException: "Unable to find template "AppBundle:Book/Backend:index.twig"." at sylius/acme/vendor/symfony/symfony/src/Symfony/Bridge/Twig/TwigEngine.php line 128
> 

When entering an **edit operation**, everything works **as expected**:

OK: the URL "/administration/books/1/edit" renderes my template written in update.html.twig.

My directory structure looks like so:

```
$ tree src/AppBundle/
src/AppBundle/
├── AppBundle.php
├── DependencyInjection
│   ├── AppExtension.php
│   └── Configuration.php
├── Entity
│   └── Book.php
└── Resources
    ├── config
    │   └── services.yml
    └── views
        └── Book
            └── Backend
                ├── create.html.twig
                ├── index.html.twig
                ├── macros.html.twig
                ├── show.html.twig
                └── update.html.twig

7 directories, 10 files
```

I am not sure why "index.twig" will be search instead of "index.html.twig". A rename of the file to "index.twig" is not a solution, i already tried out.

I am also wondering why the update-operation works quite fine but not the index-creation and also not the create-operation, which ends up in the same "template not found"-error

**Comment by lchrusciel** [comment]
blind shot `templates: AppBundle:Book\Backend`

**Comment by itinance** [comment]
@lchrusciel unfortunatley not, it results in "Unable to find template "AppBundle:Book\Backend:index.twig".

**Comment by dantleech** [comment]
Same issue here when trying to use ResourceBundle standalone.

As a nasty workaround: using `templates: @AcmeBasicCms/Crud` seems to work if you name your templates `Crud:index.twig`.

**Comment by mheki** [comment]
Hi @itinance 
there was indeed a bug in the code. I've made a PR with the fix.
Alternatively you could have used a separate routing for each action:
```
app_admin_book_index:
    path: /administration/books/
    methods: [GET]
    defaults:
        _controller: app.controller.book:indexAction
        _sylius:
            permission: false
            template: book/Backend/index.html.twig
```
Passing a template into  `_sylius` `template` option was not affected by the bug.
