### ISSUE TITLE
Upgrade database from 0.14 to 0.17

### ISSUE THREAD

**Issue by xavilondo** [Sylius/Sylius#4803]
Hi,

Im trying to upgrade my old database with sylius 0.14 to 0.17 but i can't find any documentation about how to execute de commands to migrate and transform the db.

https://github.com/Sylius/Sylius/blob/master/UPGRADE.md

> **From 0.14.0 to 0.15.x**

> Execute migration script to migrate your data into the new model schema.

I tried php app/console doctrine:migrations:migrate but it says that can't find migrations to execute.

Thank you.

**Comment by nakashu** [comment]
The problem is that default  command `php app/console doctrine:migrations:migrate` is looking inside your own `app/migrations` .. and when you are using sylius-standar this directory is empty so you can add you own application specific migrations.

To run sylius migration separatelly you can use this setup:

create sylius_migrations.yml inside your `app/config`
```yml
migrations_namespace:  Sylius\Migrations
migrations_directory:  ./vendor/sylius/sylius/app/migrations // assumes default vendor directory
table_name: sylius_migrations
name:       Sylius Migrations
```

run to test and see if there are any migrations detected:
`php app/console doctrine:migrations:status --configuration=./app/config/sylius_migrations.yml``

run to execute migrations:
`php app/console doctrine:migrations:migrate --configuration=./app/config/sylius_migrations.yml``

Still you will have probably quite a few places where the migration will fail, because of unique indexes. As current migration files does not yet handle also data migrations (only in some places), and mostly handle only pure schema migrations.
