### ISSUE TITLE
Support jsonapi specification

### ISSUE THREAD

**Issue by andreasschacht** [Sylius/Sylius#4823]
Hi Guys,

are you planning to support jsonapi specs (http://jsonapi.org)? Like @steffenbrem mentioned in https://github.com/Sylius/Sylius/issues/1356#issuecomment-46341922 it's the default in Frameworks like Ember and it would be nice, if it would work with sylius out of the box.

**Comment by steffenbrem** [comment]
I have written a bundle for it, since I needed it too for Ember and Sylius integration. This is the repo: https://github.com/steffenbrem/JsonApiBundle

I am currently not very active to maintain it, since I have some strict deadlines that I need to finish in the coming weeks. But I am planning to reserve some time to polish it. For me it is working great, almost no mappings required and it integrates well with JMS serializer, groups, exclusion policies etc. all works with it.

I am not sure if Sylius wants to depend on my library since I do not have that much time to maintain it. If so, it would be very easy and it would not require people to install my bundle. It may be a good idea to only include the proper mappings on those resources.

**Comment by steffenbrem** [comment]
To give an example, this is how the serialization mapping for a Sylius Product looks like in one of my projects:

```yml
Mango\Component\Core\Model\Product:
    resource:
        type: ~

    exclusion_policy: ALL

    virtual_properties:
        getMasterVariant:
            serialized_name: master-variant
        getName:
            serialized_name: name
        getDescription:
            serialized_name: description
        getShortDescription:
            serialized_name: short-description
        getSlug:
            serialized_name: slug

    properties:
        workspace:
            expose: true
        media:
            expose: true

    relations:
        workspace: ~
        channels:
            showLinkRelated: true
        translations:
            includeByDefault: true
        attributes:
            showLinkRelated: true
        options:
            showLinkRelated: true
        variants:
            showLinkRelated: true
        masterVariant:
            includeByDefault: true
        taxons:
            showLinkRelated: true
        media:
            showLinkRelated: true
        associations:
            showLinkRelated: true
        restrictedZone: ~
```
