### ISSUE TITLE
Can't override the default search homepage parameters to paginate more products

### ISSUE THREAD

**Issue by bettinasir88** [Sylius/Sylius#4828]
I'm trying to override the number of products per page when searching for products.

I'm currently trying this:
```
sylius_search_homepage:
    path: /
    defaults:
      _controller: sylius.controller.search:indexAction
      sylius:
        paginate: 24
```
When debugging I see that the parameter is there, but I'm not sure how it should be structured so the parameter is actually used, or if this is the right place to override it.

If someone can help, I would really appreciate it.

**Comment by michalmarcinkowski** [comment]
You should prefix `sylius` with `_`, try this:
```yml
sylius_search_homepage:
    path: /
    defaults:
      _controller: sylius.controller.search:indexAction
      _sylius:
        paginate: 24
```
