### ISSUE TITLE
The class sylius.model.product_archetype.class does not exist.

### ISSUE THREAD

**Issue by alejobit** [Sylius/Sylius#4928]
Following the instructions for installation of **SyliusProductBundle** when updating the database schema return this exception.

**Comment by gorkalaucirica** [comment]
Same issue here.

Steps to reproduce:

    $ symfony new sylius-product-archetype-issue 2.7
    $ cd sylius-product-archetype-issue
    $ composer require sylius/product-bundle 

Follow doc install steps: http://docs.sylius.org/en/latest/bundles/SyliusProductBundle/installation.html

Maybe the issue is related to docs? Something missing?

**Comment by gorkalaucirica** [comment]
Basic configuration for ProductBundle, I guess it's not posible to avoid using archetypes, associations and translations.

`config.yml`

```
sylius_product: ~

sylius_archetype:
    resources:
        product:
            subject: Sylius\Component\Core\Model\Product
            attribute: Sylius\Component\Product\Model\Attribute
            option: Sylius\Component\Product\Model\Option
            archetype:
                classes:
                    model: Sylius\Component\Product\Model\Archetype

sylius_association:
    resources:
        product:
            subject: %sylius.model.product.class%
            association:
                classes:
                    model: Sylius\Component\Product\Model\ProductAssociation

sylius_translation:
    default_locale: en

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true
```

`AppKernel.php`

```
$bundles = [
            new FOS\RestBundle\FOSRestBundle(),
            new JMS\SerializerBundle\JMSSerializerBundle($this),
            new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle(),
            new WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle(),
            new Sylius\Bundle\ResourceBundle\SyliusResourceBundle(),
            new Sylius\Bundle\ArchetypeBundle\SyliusArchetypeBundle(),
            new Sylius\Bundle\ProductBundle\SyliusProductBundle(),
            new Sylius\Bundle\AttributeBundle\SyliusAttributeBundle(),
            new Sylius\Bundle\VariationBundle\SyliusVariationBundle(),
            new Sylius\Bundle\AssociationBundle\SyliusAssociationBundle(),
            new Sylius\Bundle\TranslationBundle\SyliusTranslationBundle(),

            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new AppBundle\AppBundle(),
        ];
```

In case someone has a similar issue [sylius.yml](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml) may help a lot.
