### ISSUE TITLE
Property "x" was already declared with doctrine

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#4930]
hi,

i try to override model on Taxon, this is my entity

```
<?php

namespace St\AppBundle\Entity;

use Sylius\Component\Core\Model\Taxon as BaseTaxon;

/**
* Class Taxon
* @package St\AppBundle\Entity
*/
class Taxon extends BaseTaxon
{

/**
 * @param $locale
 * @return mixed
 */
public function setDefaultLocale($locale)
{
    return $locale;
}
}
```

my config.yml

```
sylius_taxonomy:
driver: doctrine/orm
resources:
    taxonomy:
        classes:
            model: St\AppBundle\Entity\Taxon
```

and the Taxon.orm.xml

```
<?xml version="1.0" encoding="UTF-8"?>

<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                                  http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

<entity name="St\AppBundle\Entity\Taxon" table="sylius_taxon"></entity>
```

</doctrine-mapping>

doctrine:mapping:info command give:

```
[FAIL] St\AppBundle\Entity\Taxon
Property "translations" in "St\AppBundle\Entity\Taxon" was already declared, but it must be declared only once
```
