### ISSUE TITLE
SyliusResourceBundle template name guessing changed

### ISSUE THREAD

**Issue by jrobeson** [Sylius/Sylius#4959]
This change wasn't mentioned in the changelog for the ResourceBundle. 

I was using SyliusResourceBundle v0.14 and then upgraded to 0.17  and my templates named like `Resources/views/update.html.twig` no longer work. The system seems to want them to be `Resources/views/update.html`.  

It seems like now, only routes defined like:

``` yml
app_book:
    resource: |
        alias: app.book
    type: sylius.resource
```

end up getting their internal names translated to action.html.twig due to the code here: https://github.com/Sylius/Sylius/blob/v0.17.0/src/Sylius/Bundle/ResourceBundle/Routing/ResourceLoader.php#L152 and here https://github.com/Sylius/Sylius/blob/v0.17.0/src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php#L99

Which means manually defined routes without the template key never get their names translated.

``` yml
app_book_index:                                                                                                             
    path: /books                                                                                                                   
   methods: [GET]                                                                                                                 
   defaults:                                                                                                                      
       _controller: app.controller.book:indexAction                                                                        
      _sylius:                                                                                                                   
          paginate: 20                                                                                                           
          sortable: true                                                                                                         
          sorting:                                                                                                               
         id: asc   
```

Previously, this name translation was done at runtime, but it can't seem to do that now.

On another note: The code in https://github.com/Sylius/Sylius/blob/v0.17.0/src/Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php#L99 also means you can't use Twig namespaced paths due to the embedded colon

I'm not what folks want to do about this, but I'd prefer not having to rename my templates (and also to be able to use twig namespaced paths)
