### ISSUE TITLE
why it doesn't work when using   the contexts_as_services  and the context  together in Sylius Behat?

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#5064]
why it doesn't work when using   the contexts_as_services  and the contexts  together?
```
default:
    suites:
        example:
                contexts_as_services:
                    - sylius.behat.context.domain.order
                   
                contexts:
                    - Sylius\Bundle\TaxonomyBundle\Behat\TaxonomyContext
                filters:
                    tags: @managing_orders && @domain
```
