### ISSUE TITLE
[SettingsBundle] Handle multiple settings form in controller

### ISSUE THREAD

**Issue by majidgolshadi** [Sylius/Sylius#5093]
What do you think if we can path multiple schemas to controller so that we have only one route for many settings? For the sake of better UX.

``` yml
sample_route_settings:
    path: /settings
    defaults:
        _controller: sylius.controller.settings:updateAction
        schema: [sylius_general, sylius_taxation]
        template: AppBundle:Admin:settings.html.twig
```
