### ISSUE TITLE
[nested] failed to find nested object under path [variants]

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#5146]
hi,

on v0.18 + ES 1.7.3

when i try to do a search, got his error:

    [nested] failed to find nested object under path [variants]

Don't got this error in 0.17

here my conf

    fos_elastica:
    clients:
        default: { host: %service_elastic_host%, port: %service_elastic_port%, logger: true }
    indexes:
        sylius:
            index_name: msb_%kernel.environment%
            client: default
            finder: ~
            settings:
                index:
                    analysis:
                          analyzer:
                              default:
                                  type: custom
                                  tokenizer: standard
                                  filter: [asciifolding, lowercase, my_ngram, my_filter, worddelimiter, en_stemmer]
                              my_analyzer_autocomplete:
                                  type: snowball
                                  tokenizer: lowercase
                                  filter: [my_ngram, my_filter, asciifolding]
                          filter:
                              my_ngram:
                                  type: nGram
                                  min_gram: 4
                                  max_gram: 15
                              my_filter:
                                  type: length
                                  min: 0
                                  max: 2000
                              en_stemmer:
                                  type: stemmer
                                  language: light_english
                              worddelimiter:
                                  type: word_delimiter
            types:
               product:
                   mappings:
                       name:
                           type: string
                       description: ~
                       slug: ~
                       color: ~
                       price:
                          type: integer
                       channels:
                          type: string
                          index: not_analyzed
                       taxons:
                          type: string
                          index: not_analyzed
                       size: ~
                   persistence:
                       driver: orm
                       model: Sylius\Component\Core\Model\Product
                       model_to_elastica_transformer:
                          service: sylius.search.transformers.model.product
                       provider: ~
                       listener: ~
                       finder: ~

               search_log:
                  mappings:
                      search_term: ~
                      ip_address: ~

and here the config.yml

    sylius_search:
    engine: elasticsearch #orm
    filters:
           pre_search_filter: # the small drop down menu on the side of the search field
               enabled: true
               taxon: category # possible values are taxons codes (category, brand for sylius)
           facet_groups: # possible facet groups, you assign them in a finder object
               search_set:
                   values: [taxons, price, color, size]
               categories_set:
                   values: [price, color, size]
               all_set:
                   values: [taxons, price, size]
           facets: # possible facets, as long as a model exposes attributes, options or getters with the given name, it will be used as a facet
               taxons:
                   display_name: 'Categories'
                   type: terms
                   value: ~
               price:
                   display_name: 'Available prices'
                   type: range
                   values:
                       - { from: 0, to: 50}
                       - { from: 51, to: 100}
                       - { from: 101, to: 200}
               color:
                   display_name: 'color'
                   type: terms
                   value: ~
               size:
                   display_name: 'Taille'
                   type: terms
                   value: ~

**Comment by ibasaw** [comment]
here the complete log error:

    SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[IJ8KPgCvTfyiMcxDk_rYlw][msb_dev][0]: SearchParseException[[msb_dev][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"query_string":{"query":"maillot"}},"filter":{"bool":{"must":[{"term":{"enabled":true}},{"or":[{"nested":{"path":"variants","query":{"bool":{"minimum_number_should_match":1,"must":[{"range":{"variants.availableOn":{"lte":"now"}}},{"filtered":{"filter":{"or":[{"missing":{"field":"variants.availableUntil"}},{"range":{"variants.availableUntil":{"gte":1464622915}}}]}}}],"should":[{"term":{"variants.availableOnDemand":true}},{"range":{"variants.onHand":{"gt":0}}}]}}}},{"nested":{"path":"masterVariant","query":{"bool":{"minimum_number_should_match":1,"must":[{"range":{"masterVariant.availableOn":{"lte":"now"}}},{"filtered":{"filter":{"or":[{"missing":{"field":"masterVariant.availableUntil"}},{"range":{"masterVariant.availableUntil":{"gte":1464622915}}}]}}}],"should":[{"term":{"masterVariant.availableOnDemand":true}},{"range":{"masterVariant.onHand":{"gt":0}}}]}}}}]},{"type":{"value":"product"}},{"terms":{"channels":["Default"]}}]}}}},"aggs":{"taxons":{"terms":{"field":"taxons","size":550}},"price":{"range":{"field":"price","ranges":[{"from":0,"to":50},{"from":51,"to":100},{"from":101,"to":200}]}},"color":{"terms":{"field":"color","size":550}},"size":{"terms":{"field":"size","size":550}}},"size":100}]]]; nested: QueryParsingException[[msb_dev] [nested] failed to find nested object under path [variants]]; }{[IJ8KPgCvTfyiMcxDk_rYlw][msb_dev][1]: SearchParseException[[msb_dev][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"query_string":{"query":"maillot"}},"filter":{"bool":{"must":[{"term":{"enabled":true}},{"or":[{"nested":{"path":"variants","query":{"bool":{"minimum_number_should_match":1,"must":[{"range":{"variants.availableOn":{"lte":"now"}}},{"filtered":{"filter":{"or":[{"missing":{"field":"variants.availableUntil"}},{"range":{"variants.availableUntil":{"gte":1464622915}}}]}}}],"should":[{"term":{"variants.availableOnDemand":true}},{"range":{"variants.onHand":{"gt":0}}}]}}}},{"nested":{"path":"masterVariant","query":{"bool":{"minimum_number_should_match":1,"must":[{"range":{"masterVariant.availableOn":{"lte":"now"}}},{"filtered":{"filter":{"or":[{"missing":{"field":"masterVariant.availableUntil"}},{"range":{"masterVariant.availableUntil":{"gte":1464622915}}}]}}}],"should":[{"term":{"masterVariant.availableOnDemand":true}},{"range":{"masterVariant.onHand":{"gt":0}}}]}}}}]},{"type":{"value":"product"}},{"terms":{"channels":["Default"]}}]}}}},"aggs":{"taxons":{"terms":{"field":"taxons","size":550}},"price":{"range":{"field":"price","ranges":[{"from":0,"to":50},{"from":51,"to":100},{"from":101,"to":200}]}},"color":{"terms":{"field":"color","size":550}},"size":{"terms":{"field":"size","size":550}}},"size":100}]]]; nested: QueryParsingException[[msb_dev] [nested] failed to find nested object under path [variants]]; }{[IJ8KPgCvTfyiMcxDk_rYlw][msb_dev][2]: SearchParseException[[msb_dev][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"query_string":{"query":"maillot"}},"filter":{"bool":{"must":[{"term":{"enabled":true}},{"or":[{"nested":{"path":"variants","query":{"bool":{"minimum_number_should_match":1,"must":[{"range":{"variants.availableOn":{"lte":"now"}}},{"filtered":{"filter":{"or":[{"missing":{"field":"variants.availableUntil"}},{"range":{"variants.availableUntil":{"gte":1464622915}}}]}}}],"should":[{"term":{"variants.availableOnDemand":true}},{"range":{"variants.onHand":{"gt":0}}}]}}}},{"nested":{"path":"masterVariant","query":{"bool":{"minimum_number_should_match":1,"must":[{"range":{"masterVariant.availableOn":{"lte":"now"}}},{"filtered":{"filter":{"or":[{"missing":{"field":"masterVariant.availableUntil"}},{"range":{"masterVariant.availableUntil":{"gte":1464622915}}}]}}}],"should":[{"term":{"masterVariant.availableOnDemand":true}},{"range":{"masterVariant.onHand":{"gt":0}}}]}}}}]},{"type":{"value":"product"}},{"terms":{"channels":["Default"]}}]}}}},"aggs":{"taxons":{"terms":{"field":"taxons","size":550}},"price":{"range":{"field":"price","ranges":[{"from":0,"to":50},{"from":51,"to":100},{"from":101,"to":200}]}},"color":{"terms":{"field":"color","size":550}},"size":{"terms":{"field":"size","size":550}}},"size":100}]]]; nested: QueryParsingException[[msb_dev] [nested] failed to find nested object under path [variants]]; }{[IJ8KPgCvTfyiMcxDk_rYlw][msb_dev][3]: SearchParseException[[msb_dev][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"query_string":{"query":"maillot"}},"filter":{"bool":{"must":[{"term":{"enabled":true}},{"or":[{"nested":{"path":"variants","query":{"bool":{"minimum_number_should_match":1,"must":[{"range":{"variants.availableOn":{"lte":"now"}}},{"filtered":{"filter":{"or":[{"missing":{"field":"variants.availableUntil"}},{"range":{"variants.availableUntil":{"gte":1464622915}}}]}}}],"should":[{"term":{"variants.availableOnDemand":true}},{"range":{"variants.onHand":{"gt":0}}}]}}}},{"nested":{"path":"masterVariant","query":{"bool":{"minimum_number_should_match":1,"must":[{"range":{"masterVariant.availableOn":{"lte":"now"}}},{"filtered":{"filter":{"or":[{"missing":{"field":"masterVariant.availableUntil"}},{"range":{"masterVariant.availableUntil":{"gte":1464622915}}}]}}}],"should":[{"term":{"masterVariant.availableOnDemand":true}},{"range":{"masterVariant.onHand":{"gt":0}}}]}}}}]},{"type":{"value":"product"}},{"terms":{"channels":["Default"]}}]}}}},"aggs":{"taxons":{"terms":{"field":"taxons","size":550}},"price":{"range":{"field":"price","ranges":[{"from":0,"to":50},{"from":51,"to":100},{"from":101,"to":200}]}},"color":{"terms":{"field":"color","size":550}},"size":{"terms":{"field":"size","size":550}}},"size":100}]]]; nested: QueryParsingException[[msb_dev] [nested] failed to find nested object under path [variants]]; }{[IJ8KPgCvTfyiMcxDk_rYlw][msb_dev][4]: SearchParseException[[msb_dev][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"filtered":{"query":{"query_string":{"query":"maillot"}},"filter":{"bool":{"must":[{"term":{"enabled":true}},{"or":[{"nested":{"path":"variants","query":{"bool":{"minimum_number_should_match":1,"must":[{"range":{"variants.availableOn":{"lte":"now"}}},{"filtered":{"filter":{"or":[{"missing":{"field":"variants.availableUntil"}},{"range":{"variants.availableUntil":{"gte":1464622915}}}]}}}],"should":[{"term":{"variants.availableOnDemand":true}},{"range":{"variants.onHand":{"gt":0}}}]}}}},{"nested":{"path":"masterVariant","query":{"bool":{"minimum_number_should_match":1,"must":[{"range":{"masterVariant.availableOn":{"lte":"now"}}},{"filtered":{"filter":{"or":[{"missing":{"field":"masterVariant.availableUntil"}},{"range":{"masterVariant.availableUntil":{"gte":1464622915}}}]}}}],"should":[{"term":{"masterVariant.availableOnDemand":true}},{"range":{"masterVariant.onHand":{"gt":0}}}]}}}}]},{"type":{"value":"product"}},{"terms":{"channels":["Default"]}}]}}}},"aggs":{"taxons":{"terms":{"field":"taxons","size":550}},"price":{"range":{"field":"price","ranges":[{"from":0,"to":50},{"from":51,"to":100},{"from":101,"to":200}]}},"color":{"terms":{"field":"color","size":550}},"size":{"terms":{"field":"size","size":550}}},"size":100}]]]; nested: QueryParsingException[[msb_dev] [nested] failed to find nested object under path [variants]]; }]

**Comment by Niiko** [comment]
It's because in your configuration mapping, this fields are missing.

Try one like this : 

```yml
                   mappings:
                         id: { type: integer, index: not_analyzed }
                         name: { type: string }
                         description: { type: string }
                         shortDescription: { type: string }
                         slug: { type: string, index: not_analyzed }
                         translations:
                             type: nested
                             properties:
                                 locale: { type: string, index: not_analyzed }
                                 name: { type: string }
                                 metaKeywords: { type: string }
                                 metaDescription: { type: string }
                         masterVariant:
                             type: nested
                             properties:
                                 code: { type: string }
                                 availableOn: { type: date, index: not_analyzed }
                                 availableUntil: { type: date }
                                 availableOnDemand: { type: boolean }
                                 presentation: { type: string }
                                 onHand: { type: integer, index: not_analyzed }
                                 onHold: { type: integer, index: not_analyzed }
                         variants:
                             type: nested
                             properties:
                                 code: { type: string }
                                 availableOn: { type: date, index: not_analyzed }
                                 availableUntil: { type: date }
                                 availableOnDemand: { type: boolean }
                                 presentation: { type: string }
                                 onHand: { type: integer, index: not_analyzed }
                                 onHold: { type: integer, index: not_analyzed }
                         attributes:
                             type: nested
                             properties:
                                 value: { type: string }
                         channels: { type: string, index: not_analyzed }
                         taxons: { type: string, index: not_analyzed }
                         enabled: { type: boolean }
```
