### ISSUE TITLE
how to add another payment method ?

### ISSUE THREAD

**Issue by samanmohamadi** [Sylius/Sylius#5239]
Hi I want to add another payment method like be2bill so:

```
payum:
    gateways:
        be2bill_offsite:
            be2bill_offsite:
                identifier: %be2bill.identifier%
                password: %be2bill.password%
                sandbox: true

sylius_payment:
    gateways:
        be2bill_offsite: be2bill

```

I add be2bill in admin panel but it doesn't show in checkout process ? is there any other config that I must  to do?
