### ISSUE TITLE
[Grid] Default options / options vaidation.

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5244]
Currently

``` php
sylius_grid:
    grids:
            fields:
                date:
                    type: datetime
```

Produces a twig error:

```
Expected the key "format" to exist
```

And I can specify unknown keys in the options, for example:

```

                date:
                    type: datetime
                    label: sylius.ui.date
                    options:
                        asd: asd
```

Would it be possible to use the Symfony OptionsResolver here?

``` php
$optionsResolver = new OptionsResolver();
$options->setDefault('format', 'Y-m-d H:m:s');
```
