### ISSUE TITLE
[Flow] Checkout step configuration?

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5250]
I am assuming that in order to create a new checkout step it is expected that you need to [override the DI definition](http://stackoverflow.com/questions/22046881/how-to-overriding-corebundle-checkout).

When extending Sylius with multiple bundles it may make more sense to configure slow steps in configuration rather than creating a new class:

```
sylius_core
    checkout:
        steps:
            foobar: ~  # step aliases
            address:
                template: Foobar:foo.html.twig
            payment:
                template: Barfoo:bar.html.twig
```

Steps could then be dynamically added to the checkout scenario.

This would make it easy, for exmaple, for the user to add two new bundles and insert two new steps without overriding container parameters / creating new classes.
