### ISSUE TITLE
Resource image upload

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5282]
Hi,
I created a new custom resource entity `Book implements ResourceInterface` and the corresponding backend menu + forms to manage the instances in the backend. Everything works perfectly and I can create/update/delete my instances in the backend.

Now I want to add an Image to this `Book` entity class, like this _(as per http://symfony.com/doc/2.8/cookbook/controller/upload_file.html)_: 

```php
    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Please, upload the book cover as a PNG/JPEG/GIF file.")
     * @Assert\File(mimeTypes={ "image/png", "image/jpeg", "image/gif" })
     */
    private $image;
```

The form shows an upload button correctly, but when I submit the form, the file doesn't get uploaded and I get an error for the form widget stating that the file does not exist.

Do I have to configure something else for this to work ?

Thanks a lot

**Comment by tchapi** [comment]
Anyone ? I haven't found anything in the fixtures and the doc is outdated it seems, so I'm blocked here ;(

**Comment by pjedrzejewski** [comment]
Hi @tchapi! Are you handling the upload itself somehow? You could use our ImageUploader, but nothing will be done automatically here. Have a look at ImageUploadListener in core. This is what triggers the upload for taxons and variants.

**Comment by tchapi** [comment]
Thanks,
I did mimick **ImageUploaderListener** + service declaration, but somehow it never gets used. 

``` 
my_bundle.listener.image_upload:
        class: My\Bundle\EventListener\ImageUploadListener
        arguments: [@sylius.image_uploader]
        tags:
            - { name: kernel.event_listener, event: my_bundle.my_entity.pre_create, method: uploadImage }
            - { name: kernel.event_listener, event: my_bundle.my_entity.pre_update, method: uploadImage }
```

My entity implements _ResourceInterface_.

How do I "link" this service to the events emitted by the resource ? That' s the part I don't understand — I don't want to create a controller especially for that upload logic, or must I ? I had in mind that the uploadListener could take care of that by himself in registering for pre_create and pre_update, no ?

Thanks

**Comment by okwinza** [comment]
Hey @tchapi! You're correct with the listeners, here the docs about ResourceBundle emitted events: http://docs.sylius.org/en/latest/bundles/general/events.html

Also, could you post your `sylius_resource:` node from resource declaration config?

**Comment by tchapi** [comment]
Here it goes for the `sylius_resource` : 
``` 
sylius_resource:
    resources:
        my_bundle.my_entity:
            classes:
                model: My\Bundle\Entity\MyEntity
            templates: MyBundle:Backend/MyEntity
```
