### ISSUE TITLE
[Resource] Services instead of overriding classes

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5296]
Currently you can define a single form type in the routing:

```
foo_thing:
    resource: |
        # ...
        form: transaction_type
```

Or a form _class_ in the `resource` configuration, I think something like:

``` yaml
sylius_resource:
    resources:
        locastic.loyalty_rule:
            classes:
                model: RuleBundle\Entity\Rule
                form: 
                    create: RuleBundle\Form\RuleCreateType
                    update: RuleBundle\Form\RuleUpdateType
```

The `resource` configuration does not allow the specification of a service (it
just uses a factory to create the named class), and routing does not allow the
diferentiation between update and create.

So questions:
1. Why are forms defined in two places?
2. Should one be deprecated in favor of the other? (and then allow specification of type rather than class).

**Comment by pjedrzejewski** [comment]
The configuration in routing generator is just for routing generation. If you need different forms for update and create, you will need to define the routes manually. I do not want to make the generation too powerful, it is mostly for simple use-cases and demo/testing purposes. With more advanced use-cases you will define routing manually most of the time.

The configuration in resources should also be as simple as possible, thus you have only one form. The "main" form.

In your case, I see 2 options:

* Use form options on the main form type to apply differences between the two:

```yaml
app_admin_book_update:
    ...
    defaults:
        _sylius:
             form:
                 type: app_book
                 options:
                     include_title: false # Based on this option, add (or not) the title field.
```

* Simply create new form type and use it in your manually defined routing for update action.

If we continue adding more options to the generator it can end up really ugly and overpowered. WDYT?

**Comment by dantleech** [comment]
ok that makes sense.

But on the other hand, we do seem to allow the specification of form classes (`default`, `update`, `create`) in the `resource` configuration (as opposed to routing configuration) - and it is not possible to use a service.

Is there duplication of respondiblity here? Would it make sense to not use a factory to create the form types (see also #5243)

**Comment by dantleech** [comment]
I am now in situation where I want to use a customized controller for a resource, and I feel uncomfortable in setting the class - as it seems like an anti-pattern (about 12 services are injected and then the container is also injected).

Could we consider replaces the `classes` option with something like:

```yaml
sylius_resource:
    resources:
        acme.post_folder:
            driver: doctrine/phpcr-odm
            controller: my.controller  # class or service
            form: my.form.service      # class or service
            factory: my.factory.servce # class or service
            class: Namespace\MyModel   # class
            interface: MyInterface     # interface
```
