### ISSUE TITLE
[Fixtures] Replace parameters in fixtures / listeners configuration

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#5304]
Given config file:

```yaml
parameters:
  parameter: foobar

sylius_fixtures:
  suites:
    default:
      listeners:
        listener:
          options:
            option: "%parameter%"
      fixtures:
        fixture:
          options:
            option: "%parameter%"
```

`%parameter%` should be replaced with `foobar`, but it's not. This issue only applicable for nodes below `options`.
