### ISSUE TITLE
Pb OrderRepository

### ISSUE THREAD

**Issue by MattZ9** [Sylius/Sylius#5308]
Hello,

I created a OrderRepository which extends EntityRepository, like this :
```
use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

class OrderRepository extends EntityRepository
{
	...
}
```

And in my config.yml I put this:
```
sylius_cart:
    resources:
        cart:
            classes:
                controller: AppcartBundle\Controller\CartController
            validation_groups:
                default: [ sylius ]
        cart_item:
            classes:
                controller: Sylius\Bundle\CartBundle\Controller\CartItemController
            validation_groups:
                default: [ sylius ]

sylius_order:
    driver: doctrine/orm
    resources:
        order:
            classes:
                model: Sylius\Component\Core\Model\Product
                interface: Sylius\Component\Core\Repository\OrderRepositoryInterface
                repository: AppBundle\Entity\OrderRepository
```

On the site, when I want to add an item to the cart, I get the following error :
`Catchable Fatal Error: Argument 1 passed to Sylius\Component\Cart\Context\CartContext::setCurrentCartIdentifier() must implement interface Sylius\Component\Cart\Model\CartInterface, instance of Sylius\Component\Core\Model\Product given, called in C:\wamp\www\myproject\vendor\sylius\sylius\src\Sylius\Bundle\CartBundle\Provider\CartProvider.php on line 132 and defined`

Can you help me please ?

I don't know if my config is good, if I forgot something or if the problem is elsewhere.

Thank you

**Comment by MattZ9** [comment]
Before that I had in my config.yml :

```
sylius_order:
    driver: doctrine/orm
    resources:
        order:
            classes:
                repository: AppBundle\Entity\OrderRepository
```

And I had the following error:
`Catchable Fatal Error: Argument 2 passed to Sylius\Component\Core\Promotion\Checker\CouponsEligibilityChecker::__construct() must be an instance of Sylius\Component\Core\Repository\OrderRepositoryInterface, instance of AppBundle\Entity\OrderRepository given, called in C:\wamp\www\myproject\app\cache\dev\appDevDebugProjectContainer.php on line 16206 and defined`

That's why I added :
```
model: Sylius\Component\Core\Model\Product
interface: Sylius\Component\Core\Repository\OrderRepositoryInterface
```

**Comment by okwinza** [comment]
In your config
```
sylius_order:
    driver: doctrine/orm
    resources:
        order:
            classes:
                model: Sylius\Component\Core\Model\Product
                interface: Sylius\Component\Core\Repository\OrderRepositoryInterface
                repository: AppBundle\Entity\OrderRepository
```
These lines
```
                model: Sylius\Component\Core\Model\Product
                interface: Sylius\Component\Core\Repository\OrderRepositoryInterface
                repository: AppBundle\Entity\OrderRepository
```
Are wrong.

1. You're telling `sylius_order` resource to use `Product` model for unknown reason(WTF lol), don't do that.
2. `interface` is also wrong. It should be model interface not a repository.
3. Since your repository `AppBundle\Entity\OrderRepository` doesn't extend the Sylius' one -- you're missing all its content so errors and exceptions are inevitable.

Seems like you missing the core Sylius concepts, so i'd be best to [read the docs](http://docs.sylius.org/en/latest/).

**Comment by MattZ9** [comment]
Ok Thank you for your help. It's been a month that I use Sylius, that's why I make mistakes..
I was using the doc http://docs.sylius.org/en/latest/bundles/general/overriding_repositories.html
I will see my code with what you said.

**Comment by okwinza** [comment]
@MattZ9 meh, my bad, i forgot that docs are THAT outdated.

Anyway, if you want to override a repo -- do it using `extend` the base one like this:

```
use Sylius\Bundle\CoreBundle\Doctrine\ORM\OrderRepository as BaseRepository;

class OrderRepository extends BaseRepository
{
    ...
}
```
then
```
sylius_order:
    driver: doctrine/orm
    resources:
        order:
            classes:
                repository: AppBundle\Entity\OrderRepository
```
