### ISSUE TITLE
[ReviewBundle] Remove 'sylius.' prefix

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#5340]
I'm developping a multiStore bundle, and add a review on "store" (multitenancy #2941 ?).

I choose to use review model for that, but it appears that every services are prefixed.

Exemple in RegisterReviewFactoryPass : 

``` php
    public function process(ContainerBuilder $container)
    {
        foreach ($container->getParameter('sylius.review.subjects') as $subject => $configuration) {
            $factory = $container->findDefinition('sylius.factory.'.$subject.'_review');
            $reviewFactoryDefinition = new Definition(ReviewFactory::class);

            $reviewFactory = $container->setDefinition(sprintf('sylius.factory.'.$subject.'_review'), $reviewFactoryDefinition);
            $reviewFactory->addArgument($factory);
            $reviewFactory->addArgument($container->findDefinition('sylius.repository.'.$subject));
        }
    }
```

I had to add an alias to manage with that (repository)

Maybe, we can add a parameter in config like "prefix" or another one.

Example :

``` yaml
sylius_review:
    resources:
        product:
            subject: "%sylius.model.product.class%"
            prefix: sylius
```

Or add a "applicationName" like in Behat contexts.

I don't know how to do it, if you have any hint, i will be happy to contribute.
