### ISSUE TITLE
Override translations for a specific resource

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5347]
Hi,

I would like to override a translation for a specific resource. Namely, these translations :
```yml
sylius:
    resource:
        create: '%resource% a bien été créé.'
        update: '%resource% a bien été mis à jour.'
 # etc ...
```

Is there a way to override them for a specific `Resource` like `MyEntity` ? There is nothing in the docs about the translation configuration (http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/reference.html) and diving in the source code I found nothing about that. 

Thanks a lot !
