### ISSUE TITLE
API : The client credentials are invalid

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#5352]
hi,

sylius 0.18, SF 2.8.7

i try to use the API and try to get my token with postman

i use the admin user with role: ROLE_API, ROLE_API_ACCESS in the sylius_user table

i use this url: 
`/oauth/v2/token`

and send my query in POST

```
client_id:618v912wv6kggwcgwsoswcwc84ws040o4g48c00o8sw0wgwgks
client_secret:2v5xi0vu18g0kg0csoko8wc0kg8k4gcws4cs8ccgg8gwc44og4
grant_type:password
username:myemail
password:xxx
```

but i always got this response:

```
{"error":"invalid_client","error_description":"The client credentials are invalid"}
```

i tried 3 times to recreate the credentials like this

```
php app/console sylius:oauth-server:create-client
```

the allowed_grant_type in the DB

```
a:3:{i:0;s:8:"password";i:1;s:13:"refresh_token";i:2;s:5:"token";}
```

but always same response

here my security conf file

```
security:
    providers:
        sylius_user_provider:
            id: sylius.user_provider.name_or_email
    encoders:
        Sylius\Component\User\Model\UserInterface: bcrypt
    firewalls:
        admin:
            switch_user: true
            context: user
            pattern: /admin/.*
            form_login:
                provider: sylius_user_provider
                login_path: sylius_admin_login
                check_path: sylius_admin_login_check
                failure_path: sylius_admin_login
                default_target_path: sylius_admin_dashboard
                use_forward: false
                use_referer: true
            logout:
                path: sylius_admin_logout
                target: sylius_admin_login
            anonymous: true

        administration:
            switch_user: true
            context:     user
            pattern:     /administration/.*
            form_login:
                provider:     sylius_user_provider
                login_path:   /administration/login
                check_path:   /administration/login-check
                failure_path: /administration/login
                default_target_path: /administration/dashboard
                use_forward:  false
                use_referer:  true
            logout:
                path:   /logout
                target: /administration/login
            anonymous: true

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true

        main:
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }
            context:     user
            pattern:     /.*
            form_login:
                provider: sylius_user_provider
                login_path: /login
                check_path: /login_check
                failure_path: /login
                default_target_path: /
                use_forward:  false
                use_referer: true
            remember_me:
                key: %secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout: true
            anonymous: true

        oauth_token:
            pattern:  ^/oauth/v2/token
            security: false

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/account.*", role: ROLE_USER }

        - { path: ^/administration/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/administration/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/administration.*", role: ROLE_ADMINISTRATION_ACCESS }

        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/admin.*", role: ROLE_ADMINISTRATION_ACCESS }

        - { path: ^/api, role: ROLE_API_ACCESS }

        - { path: "/_partial.*", ip: 127.0.0.1 }
```
