### ISSUE TITLE
Facebook login, no firstname and no last name

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#5372]
hi,

here my config for facebook oauth API 2.6

```
hwi_oauth:
    firewall_name: main
    resource_owners:
        facebook:
            type: facebook
            client_id: %facebook.app.id%
            client_secret: %facebook.app.secret%
            scope: "email, public_profile"
            infos_url: "https://graph.facebook.com/me?fields=id,first_name,last_name,email"
```

the problem is that the customer save in DB has no firstname and no lastname

my Facebook graph api return it well

Is it a sylius issue or a HWIOAuthBundle issue ?

If i put in the infos_url the parameter name, it concatain the name and fistrname in one single field firstname
