### ISSUE TITLE
Unrecognized option "classes" under "sylius_order" 

### ISSUE THREAD

**Issue by adnen-chouibi** [Sylius/Sylius#5380]
Hi there, I have installed SyliusOrderBundle following the docs (http://docs.sylius.org/en/latest/bundles/SyliusOrderBundle/installation.html)
and when i run php app/console doctrine:schema:update --force
`  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "classes" under "sylius_order"   `
I put this configuration inside app/config/config.yml

`
 sylius_order:
    driver: doctrine/orm # Configure the doctrine orm driver used in documentation.
    classes:
        order:
            model: Total\BackendBundle\Entity\Order # The order entity.
`

**Comment by michalmarcinkowski** [comment]
The configuration should be the following:
```
sylius_order:
    resources:
        order:
            classes:
                model: Total\BackendBundle\Entity\Order
```

We should definitely update the docs.
