### ISSUE TITLE
[FixturesBundle] Allow to use the same fixtures multiple times in one suite

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#5401]
It will allow for the following scenario:
 - add 5 random, enabled admin users
 - add 50 random, 90% enabled / 10% disabled regular users

```yaml
sylius_fixtures:
    suites:
        suite:
            fixtures:
                # Add 5 random, enabled admin users 
                - user:
                    random: 5
                    prototype:
                        admin: true
                        enabled: true

                # Add 50 random, 90% enabled / 10% disabled regular users
                - user:
                    random: 50
                    prototype:
                        admin: false
```

We need to replace configuration from `'fixtures' => ['user' => ...]` with `'fixtures' => [['user' => ...], ['user' => ...]]` and enhance suite factory.
