### ISSUE TITLE
[Product] Creating product from archetype doesn't save it

### ISSUE THREAD

**Issue by starspire** [Sylius/Sylius#5448]
When I'm creating a product from archetype (`sylius_backend_product_create_from_archetype` route) everything goes fine except archetype isn't save to product model (`$product->getArchetype` is null). It's a bug or deliberate action?

**Comment by starspire** [comment]
@pjedrzejewski I fixed it by adding additional row to form (archetype). Maybe this with hidden param will be enough?

**Comment by MatthieuG9** [comment]
Same problem, I solved by following this steps : 

- Copy the file Sylius/Bundle/WebBundle/Resources/views/Backend/Product/create.html.twig into app/Resources/SyliusWebBundle/views/Backend/Product
- In create.html.twig replace `action="{{ path('sylius_backend_product_create', {'archetype': app.request.get('archetype')}) }}"` by `action="{{ path(app.request.attributes.get('_route'), {'archetype': app.request.get('archetype')}) }}"`

After changing the template, there is a redirection problem on submit, to solve it, you have to add a redirect param on route `sylius_backend_product_create_from_archetype` : 
- Copy the file Sylius/Bundle/WebBundle/Resources/config/routing/main.yml as app/config/sylius.yml
- Copy the files  Sylius/Bundle/WebBundle/Resources/config/routing/backend/main.yml and Sylius/Bundle/WebBundle/Resources/config/routing/backend/product.yml into the folder app/config/backend
- In the main routing file, edit routes : 

```
sylius_api:
    resource: "sylius.yml"
    prefix: /api

sylius_web:
    resource: "sylius.yml"
```

- In the sylius.yml, link sylius_backend to new backend/main.yml file : 
```
sylius_backend:
    resource: "backend/main.yml"
    prefix: /administration
```

- In backend/main.yml : 
```
sylius_backend_product:
    resource: product.yml
    prefix: /products
```

- And in backend/product.yml edit `sylius_backend_product_create_from_archetype` to add `redirect` : 
sylius_backend_product_create_from_archetype:
```
    path: /new-from-archetype
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            factory:
                method: createFromArchetype
                arguments: $archetype
            template: SyliusWebBundle:Backend/Product:create.html.twig
            redirect: sylius_backend_product_show
```
