### ISSUE TITLE
Overriding Core\Customer configuration doesn't seem to work

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5519]
Hi,

Trying to override Customer and following every step in http://docs.sylius.org/en/latest/customization/model.html leads to  :

    [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
    Unrecognized option "customer" under "sylius_core.resources"

when trying to override the **Core** `Customer` class.
It seems to be the same problem for every model that is extended in **Core**.

It seems that the `sylius_core` namespace does not accept this kind of thing :

```yml
sylius_core:
    resources:
        customer:
            classes:
                model: My\OwnBundle\Entity\Customer
```
How do I do to override a model extended in Core ?

Thanks

**Comment by tchapi** [comment]
Ok — so apparently after a lot of fiddling, I guess it's because one should override the not-Core namespace for this to work, namely (note the `sylius_user` instead of `sylius_core`) :  

```yml 
sylius_user:
    resources:
        customer:
            classes:
                model: My\OwnBundle\Entity\Customer
```

This should be added in the doc I presume ?
