### ISSUE TITLE
[ResourceBundle] Template not found in API-Request

### ISSUE THREAD

**Issue by psren** [Sylius/Sylius#5528]
I tried to use ResourceBundle standalone in a SF2.8.8 project.
I strictly followed the docs given at http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/configuration.html

Now i want to add a "book" vie CURL like mentioned in the docs.

```curl -i -X POST -H "Content-Type: application/json" -d '{"title": "Lord of The Rings", "author": "J. R. R. Tolkien", "description": "Amazing!"}' http://localhost:8000/books/```

I'm getting the following error.

> Unable to find template "/create.html.twig"

Since I'm using the following route-configuration there are possibilities.
1. The docs have an error, I need a template (which i should't?)
2. There is an error in the code

```yaml
app_book:
    resource: |
        alias: app.book
    type: sylius.resource_api
```
