### ISSUE TITLE
[supportRequest] Help, no metadataInterface for new controller. Extending AdminBundle.

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5540]
So, i'm trying to add some collection data like in atrributeBundle\Controller\AttributeController
- i'm copying it, changing to OptionController.
- new routes
```
sylius_admin_render_option_forms:
    path: /admin/option-forms
    methods: [GET]
    defaults:
        _controller: AppBundle:ProductOption:renderOptionValueForms
        template: AppBundle:Product/Option:optionValues.html.twig
```

And then error shows:
`Type error: Argument 1 passed to Sylius\Bundle\ResourceBundle\Controller\ResourceController::__construct() must implement interface Sylius\Component\Resource\Metadata\MetadataInterface, none given, called in /Applications/XAMPP/xamppfiles/htdocs/smaki/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 166`

So my question is, where is defined metadata for atrributeBundle\Controller\AttributeController ?
How to defined it?
