### ISSUE TITLE
Extend Taxon Form type error constructor

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#5558]
i try to extend the Taxon Form type

i add my service with the constructor in my class TaxonType but always get an error:

```
    private $tools;

    public function __construct(Tools $tools)
    {
        $this->tools = $tools;
    }
```

the service:

```
    a_taxon.form.type:
        class: St\AppBundle\Form\Type\TaxonType
        tags:
          - { name: form.type, alias: sylius_taxon }
        arguments: ['@a_tools']
```

when i try to edit the taxon, i got this error

```
Catchable Fatal Error: Argument 1 passed to St\AppBundle\Form\Type\TaxonType::__construct() must be an instance of St\AppBundle\Service\Tools, string given... TaxonType ->__construct ('St\AppBundle\Entity\Taxon', array('Default', 'sylius')) 
```

How to extend a Form type and use a custom service in it ?
