### ISSUE TITLE
[ThemeBundle] Namespaced paths not overridden

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#5560]
Just playing around with master right now, and instead of overriding the shop bundle templates, I decided to try out the Theme bundle.

I got pretty far until I realized that the Theme bundle doesn't seem to be able to override namespaced paths (http://symfony.com/doc/current/cookbook/templating/namespaced_paths.html).

For example, the shop bundles `views/Homepage/index.html.twig` has `{% extends '@SyliusShop/layout.html.twig' %}`. I cannot override layout.html.twig via a theme until I change to to use `{% extends 'SyliusShopBundle::layout.html.twig' %}`.

Am I missing something, is this a bug, or a limitation? (If it's a limitation, maybe the ShopBundle shouldn't use namespaced paths?)

**Comment by inssein** [comment]
Any ideas @pamil? I am trying to figure out how one would try and implement this. Not having a lot of luck right now. If it does end up being a limitation, Sylius should probably stop using namspaced paths.

**Comment by inssein** [comment]
Found a way to do it @pamil @pjedrzejewski. Is there a better idea, if not I can wrap this up in a PR.
```php
<?php
namespace AppBundle\EventListener;

use Sylius\Bundle\CoreBundle\Theme\ChannelBasedThemeContext;
use Twig_Loader_Filesystem;

class RequestListener
{
    /** @var Twig_Loader_Filesystem */
    private $loader;

    /** @var string[] */
    private $bundles;

    /** @var ChannelBasedThemeContext */
    private $context;

    /**
     * RequestListener constructor.
     * @param $bundles
     * @param Twig_Loader_Filesystem $loader
     * @param ChannelBasedThemeContext $context
     */
    public function __construct(array $bundles, Twig_Loader_Filesystem $loader, ChannelBasedThemeContext $context)
    {

        $this->loader = $loader;
        $this->bundles = $bundles;
        $this->context = $context;
    }

    public function onKernelRequest()
    {
        $path = $this->context->getTheme()->getPath();

        foreach ($this->bundles as $bundle => $class) {
            $dir = $path . '/' . $bundle . '/views';

            if (is_dir($dir)) {
                if ('Bundle' === substr($bundle, -6)) {
                    $bundle = substr($bundle, 0, -6);
                }

                $this->loader->prependPath($dir, $bundle);
            }
        }
    }
}
```

```yml
  app.event_listener.request_listener:
    class: AppBundle\EventListener\RequestListener
    arguments: ['%kernel.bundles%', '@twig.loader', '@sylius.theme.context.channel_based']
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: -255}
```
