### ISSUE TITLE
[BUG] `children` option on Core TaxonFIxture not working.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#5572]
I try to use a beautiful FixtureBundle with YAML config follow by core bundle as example, i found small bug in taxon fixture.

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Fixture/TaxonFixture.php#L39

For now we have definition like this:
```php
# This will return `children` with empty array `[]` when load from YAML file.
->arrayNode('children')->ignoreExtraKeys()->end()
```

To fix it, i change to:
```php
->variableNode('children')->end()
```

But in correct way maybe we need some thing like this: https://github.com/symfony/symfony/issues/10024#issuecomment-32346312

### PS. Example Yaml config.

```yaml
sylius_fixtures:
    suites:
        taxon:
            fixtures:
                taxon:
                    options:
                        custom:
                            -
                                code: web-01
                                name: XXX
                                description: ...
                                children:
                                    -
                                        code: web-01-a
                                        name: AAAA
                                        description:  ...
                                        children:
                                            -
                                                code: web-01-a-b
                                                name: BBB
                                                description: ...
```

cc. @pamil
