### ISSUE TITLE
Setting up Paypal Express with Payum

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#5623]
Can anyone explain to me how to get Paypal Express to work in Sylius. I'm having so many problems trying to get it to work! 

```
payum:
    gateways:
        paypal_express_checkout:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox:   %paypal.express_checkout.sandbox%
sylius_payment:
    gateways:
        paypal_express_checkout: Paypal Express Checkout
```

That's my config.yml 

I can add a payment gateway in the Admin area. But when i select it in the checkout i get the following error

Gateway config must have factory set in it and it must not be empty

What settings am i missing, i didn't think i'd have to set up much considering it's built in. 
If anyone could please point me in the right direction i will be forever grateful
