### ISSUE TITLE
support request - disabling payment step in checkout process

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5723]
```
winzou_state_machine:
    sylius_order_checkout:
        class: "%sylius.model.order.class%"
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            addressed: ~
            shipping_selected: ~
            completed: ~
        transitions:
            address:
                from: [cart]
                to: addressed
            readdress:
                from: [shipping_selected, addressed]
                to: cart
            select_shipping:
                from: [addressed]
                to: shipping_selected
            reselect_shipping:
                from: [shipping_selected]
                to: addressed
            complete:
                from: [shipping_selected]
                to: completed
        callbacks:

```
i changed state machine to disable payment step, and it is not working, payment step is showing, what i'm missing?
