### ISSUE TITLE
how to force recalculation of item? after editing one of cart_item 

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5725]
I edit some cart_item, and send it to database, it is properly stored, but price of elements are not changing until i change quantity of this item in cart, how to "force it" to recalculate?
is there function on cartItem to do it? or better way

**Comment by pjedrzejewski** [comment]
How do you edit the cart item? Call order recalculator (see the service) on the order to have everything recalculated properly.

**Comment by Mr-Negative** [comment]
Thank you! it's working. 

Maybe somebody find it usefull so:
I've done basic version of flexible variants, and there is page for editing chosen options and quantities of them.

How to force recalculation?
- new event listener service
```
app.listener.order_recalculation:
        class: AppBundle\EventListener\OrderItemRecalculationListener
        arguments: ["@sylius.order_processing.order_recalculator"]
        tags:
            - {name: kernel.event_listener, event: sylius.cart_item.pre_update, method: recalculateOrder}
```

and event listener

```
/**
     * @param GenericEvent $event
     *
     * @throws UnexpectedTypeException
     */
    public function recalculateOrder(GenericEvent $event)
    {
        $orderItem = $event->getSubject();

        if (!$orderItem instanceof OrderItem) {
            throw new UnexpectedTypeException($orderItem, OrderItem::class);
        }
        $order = $orderItem->getOrder();
        $this->orderRecalculator->recalculate($order);
    }
```

I think it is a bit excessive to recalculate whole order every time, but it's working great and it's fantastic starting point. Thanks
