### ISSUE TITLE
Bug in ResourcesResolver for unpaginated sorting

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#5857]
I'm not sure if you're even using this anymore (might be using the Grid version exclusively), but this doesn't work:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourcesResolver.php#L33

If you have a routing configuration such as:

```
        _sylius:
            template: SyliusWebBundle:Backend/Permission:index.html.twig
            paginate: false
            sorting:
                left: asc
```

The `sorting` will not be applied.

I think the `findAll()` use here isn't required, since this just wraps `findBy()` anyway, the case below should catch everything.
