### ISSUE TITLE
[RFC] [BUG] [Cart] Objects depend on request data are created before form validation

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#5895]
As in a title, some of factories create object based on send data. The problem is, that these factories are called before a form validation. This results in 500 error, during request.

``` yml
sylius_shop_cart_item_add:
    path: /add
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.cart_item:addAction
        _sylius:
            factory:
                method: createForProduct
                arguments: [expr:service('sylius.repository.product').find($productId)]
```

It is not a problem of cart adding only. Expression language is also not a problem. 

Feel free, to share your ideas how to solve it or prepare any POC or ready PR :)
