### ISSUE TITLE
Override Resource Bundle for some routes

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#5908]
Hi All. I'm really hoping someone can point me in the right direction. 

I'm trying to allow Users of the shop (with certain permissions) to add products in the Account area. 

I'm attempting to still use the ResourceController to achieve this as it handles all the image saving and what not. 

I can't figure out how to get it to load a different controller for some routes. I have it loading a new controller but then it doesn't find the Metadata for it

`Catchable Fatal Error: Argument 1 passed to Sylius\Bundle\ResourceBundle\Controller\ResourceController::__construct() must implement interface Sylius\Component\Resource\Metadata\MetadataInterface, none given, called in C:\Users\brett\workspace\adsup\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Controller\ControllerResolver.php on line 166 and defined `

How do i override the resource controller for a route

```
led_account_product:
    resource: |
        section: account
        alias: sylius.product
        except: ['delete', 'show']
    type: sylius.resource
    prefix: /account
```

I did modify the ResourceLoader to allow me to pass a controller in through the route configuration, but that gives me the error above because it doesn't load it using sylius service. 

Can anyone point me in the right direction please!!??

**Comment by bretto36** [comment]
So after completely bamboozling myself. I decided to make a new resource named what i wanted it to be named and it just extends the same classes as the default product definition. And i was able to achieve this. 

For other people if they have the same issue. 

config.yml

```
sylius_resource:
    resources:
        app.product:
            classes:
                model: AppBundle\Entity\Product
                controller: AppBundle\Controller\AccountProductController
                form:
                    default: AppBundle\Form\Type\ProductType
```
routing.yml
```
app_account_product:
    resource: |
        section: account
        alias: app.product
        except: ['delete', 'show']
    type: sylius.resource
    prefix: /account
```
