### ISSUE TITLE
Write Entity with Translations

### ISSUE THREAD

**Issue by sprik** [Sylius/Sylius#5936]
Hi,

I'm trying to write a new entity with its translation fields in this way:

```
class MyEntity implements TranslatableInterface {
    use TranslatableTrait;
   
    public function __construct()
    {
        $this->initializeTranslationsCollection();
    }
```

`class MyEntityTranslation extends AbstractTranslation implements ResourceInterface {
`

```
<mapped-superclass name="MyEntity" table="my_entity">
      <id name="id" type="integer">
          <generator strategy="AUTO" />
      </id>
      <field name="name" column="name" type="string" nullable="true" />
      <field name="code" column="code" type="string" nullable="true" />

      <field name="createdAt" column="created_at" type="datetime">
          <gedmo:timestampable on="create"/>
      </field>
    </mapped-superclass>
```

```
<mapped-superclass name="MyEntityTranslation" table="my_entity_translation">
      <id name="id" type="integer">
          <generator strategy="AUTO" />
      </id>
      
      <field name="title" column="title" type="string" nullable="true">
      </field>
      <field name="description" column="description" type="text" nullable="true">
      </field>
    </mapped-superclass>
```

```
class MyEntityType extends AbstractResourceType
{

    public function __construct($dataClass, $validationGroups)
    {
        parent::__construct($dataClass, $validationGroups);
    }
    
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text', [
                'required' => true,
                'label' => 'sylius.form.myentity.name',
            ])
            ->add('code', 'text', [
                'required' => true,
                'label' => 'sylius.form.myentity.code',
            ])
            ->add('translations', 'sylius_translations', [
                'type' =>  'sylius_myentity_translation',
                'label' => 'sylius.form.myentity.translations',
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'sylius_myentity';
    }
}
```

```
class MyEntityTranslationType extends AbstractResourceType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', 'text', [
                'required' => true,
                'label' => 'sylius.form.myentity.title',
            ])
            ->add('description', 'text', [
                'required' => false,
                'label' => 'sylius.form.myentity.description',
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'sylius_myentity_translation';
    }
}

```

```
services:
  sylius.myentity.translations:
    class: MyEntityTranslationType
    arguments: ['MyEntityTranslation']
    tags:
      - { name: form.type, alias: sylius_myentity_translation }
```

I inserted the one-to-many and many-to-one but I don't know if it is the correnct way or I have to extend something else

```
<one-to-many field="translations" target-entity="MyEntityTranslation" mapped-by="translatable">
        <cascade>
            <cascade-persist/>
        </cascade>
      </one-to-many>
```

When I save the new entity all works fine and in database the values are correct, but when I would like to update I have back something like this

![schermata 2016-08-31 alle 11 01 59]
(https://cloud.githubusercontent.com/assets/4373852/18122596/82950198-6f6a-11e6-88dd-0480ffe97454.png)

is something like the locale is not set, in reality it is set correctly.

I forget something to implement??

Thanks

**Comment by ylastapis** [comment]
It seems you are using the old way :)

Try to check how PaymentMethod is implemented (Product is a little bit complicated :))
What about something like 

```
sylius_resource:
        app.product_category:
            classes:
                model: AppBundle\Entity\ProductCategory
                interface: AppBundle\Entity\ProductCategoryInterface
                repository: AppBundle\Entity\Repository\ProductCategoryRepository
                form:
                    default: AppBundle\Form\Type\ProductCategoryType
            translation:
                classes:
                    model: AppBundle\Entity\ProductCategoryTranslation
                    interface: AppBundle\Entity\ProductCategoryTranslationInterface
                    form:
                        default: AppBundle\Form\Type\ProductCategoryTranslationType
```

I'll try to post a complete gist tomorrow

**Comment by sprik** [comment]
Thanks @ylastapis 

I resolve the problem adding this code

```
sylius_resource:
    resources:
        app.myentity:
            classes:
                model: MyEntity
                form: 
                    default: MyEntityType
            translation:
                classes:
                    model: MyEntityTranslation
                    form: 
                        default: MyEntityTranslationType
```

By the way...the old method is deprecated? or the correct way is the union between the two part of codes that I wrote?
