### ISSUE TITLE
It's possible to use sylius_image type for custom entity forms?

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#5947]
I'm trying to configure a new entity that have an Image field.

Will great to still the look and feel administrator for all forms.

I try to set sylius_image as type on my form but on submit i got this error:

> Expected argument of type "SplFileInfo", "Sylius\Component\Core\Model\ProductVariantImage" given

My entity got two fields, `path` and `file` and this methods:

```
/**
 * {@inheritdoc}
 */
public function hasFile()
{
    return null !== $this->file;
}

/**
 * {@inheritdoc}
 */
public function getFile()
{
    return $this->file;
}

/**
 * {@inheritdoc}
 */
public function setFile(\SplFileInfo $file)
{
    $this->file = $file;
}

/**
 * {@inheritdoc}
 */
public function hasPath()
{
    return null !== $this->path;
}

/**
 * {@inheritdoc}
 */
public function getPath()
{
    return $this->path;
}

/**
 * {@inheritdoc}
 */
public function setPath($path)
{
    $this->path = $path;
}
```

I'm doing anything wrong?

**Comment by bretto36** [comment]
I would go through and look how the Product form does it. I was doing the same thing and found i missed adding my own image upload listener. You need to add your own listener like the ones below and handle the imageupload in that file `$this->uploader->upload($subject)`

```
sylius.listener.image_upload:
        class: %sylius.listener.image_upload.class%
        tags:
            - { name: kernel.event_listener, event: sylius.product.pre_create, method: uploadProductImage }
            - { name: kernel.event_listener, event: sylius.product.pre_update, method: uploadProductImage }
```

**Comment by bnd170** [comment]
@bretto36 thanks for your response, but I can't understand it :( Can you explain it a bit more detailed?

**Comment by bretto36** [comment]
Please upload the config for your resource and the orm.yml model file too so we can see it. I think you've missed something in the configuration.

**Comment by bnd170** [comment]
Hi @bretto36 sorry for the delay in answering, was weekend.

My config for the resource looks like this:


```
sylius_resource:
    resources:
        dinamic.post:
            classes:
                model: Dinamic\Bundle\SyliusBlogBundle\Entity\Post
                form:
                    default: Dinamic\Bundle\SyliusBlogBundle\Form\PostType
```

And I'm using annotations not yml for ORM configuration on my entities:

```
class Post implements ResourceInterface
{
    use TimestampableEntity;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="Sylius\Component\Core\Model\AdminUser")
     * @ORM\JoinColumn(name="admin_user_id", referencedColumnName="id")
     */
    private $author;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text")
     */
    private $content;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var \SplFileInfo
     */
    protected $file;

    /**
     * @var string
     *
     * @ORM\Column(name="path", nullable=true)
     */
    protected $path;

    /**
     * @var int
     *
     * @ORM\ManyToOne(targetEntity="Sylius\Component\Core\Model\AdminUser")
     * @ORM\JoinColumn(name="admin_user_editor_id", referencedColumnName="id")
     */
    private $editor;

    /**
     * @var int
     *
     * @ORM\Column(name="published", type="boolean")
     */
    private $published = false;


    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=200, unique=true)
     */
    private $slug;
```
