### ISSUE TITLE
Events for custom resources?

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#5949]
I've created a new entity with [ResourcesBundle](http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/index.html) but on the profiler I can't see the [Events](http://docs.sylius.org/en/latest/bundles/general/events.html).

Must I create manualy?

Creating an EventListener for `sylius.book.pre_create` doesn't do nothing.

**Comment by bretto36** [comment]
Can you post your code on how you created the event listener? Did you add the subscriber config like this 
```
sylius.listener.image_upload:
        class: %sylius.listener.image_upload.class%
        tags:
            - { name: kernel.event_listener, event: sylius.product.pre_create, method: uploadProductImage }
            - { name: kernel.event_listener, event: sylius.product.pre_update, method: uploadProductImage }
```
The events will be there if you used the resources bundle. It's more than likely a missed configuration. 

Also post how you declared the resource

**Comment by lchrusciel** [comment]
I have post some response on stackoverflow. This issue can be closed, I suppose.

**Comment by bnd170** [comment]
Hi guys, thanks for your answers.

Yes @lchrusciel the stackoverflow question is mine too, always i create an issue here and a post on stackoverflow.

I got declarated my custom resource like docs suggest:

I have created these routes:

```
dinamic_sylius_post:
    resource: |
        alias: dinamic.post
        path: blog/post
    type: sylius.resource

dinamic_sylius_admin_post:
    resource: |
        alias: dinamic.post
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show', 'delete']
        redirect: index
        grid: dinamic_sylius_blog_post
    type: sylius.resource
    prefix: admin/
```

And on my bundle config I have this:

```
sylius_resource:
    resources:
        dinamic.post:
            classes:
                model: Dinamic\Bundle\SyliusBlogBundle\Entity\Post
                form:
                    default: Dinamic\Bundle\SyliusBlogBundle\Form\PostType
```

What I'm doing wrong then?
