### ISSUE TITLE
[RFC][DX] Cannot add a custom OrderProcessor

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#5986]
Due to some requirements in the checkout process I am interested in adding a custom OrderProcessor but I can't.

The problem is related to the way the processors are added in [order_processor.xml](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/order_processor.xml#L26) using method calls instead of service tags.

Is there any way to do it? I can't do it using a CompilerPass as I don't have access to `@sylius.order_processing.order_processor` in `AppBundle` 

If there is no other way to do it, I'm open to submit a PR implementing tag based approach. 

WDYT?

**Comment by tchapi** [comment]
For what it's worth, I did it a bit differently by subscribing to events :

```yaml
services:
    my_bundle.item_preprocessor:
        class: My\WebBundle\Service\OrderItemPreprocessor
        arguments:
            - "@request_stack"
            - "@sylius.context.cart"
        tags:
            - { name: kernel.event_listener, event: sylius.cart_item.pre_create, method: preprocess, priority: 200 }
            - { name: kernel.event_listener, event: sylius.cart_item.pre_update, method: preprocess, priority: 200 }
```


```php
<?php

namespace My\WebBundle\Service;

use Sylius\Component\Cart\Context\CartContextInterface;
use Symfony\Component\EventDispatcher\GenericEvent;
use Symfony\Component\HttpFoundation\RequestStack;
use Webmozart\Assert;

class OrderItemPreprocessor
{
    private $cartContext;
    private $requestStack;

    /**
     * @param RequestStack                  $requestStack
     * @param CartContextInterface          $cartContext
     */
    public function __construct(
        RequestStack $requestStack,
        CartContextInterface $cartContext
    ) {
        $this->requestStack = $requestStack;
        $this->cartContext = $cartContext;
    }

    /**
     * @param GenericEvent $event
     */
    public function preprocess(GenericEvent $event)
    {
        $item = $event->getSubject();
        $request = $this->requestStack->getCurrentRequest();

        Assert($item instanceof OrderItem);

        $product = $item->getProduct();
        $customer = $this->cartContext->getCart()->getCustomer();

       // Do you thing
    }
}
```
