### ISSUE TITLE
Add Factory Method for custom form with relationship?

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#6011]
I'm trying to save a form of my comment entity. Comment entity is related with post entity.

I can't preset the ID of the post in the CommentType then I read in the docs about to [create a custom Factory Method](http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/create_resource.html#using-custom-factory-method). But is not explained how to create, just how to configure. I think about i need make one method to take the Post Slug's and save when the form is send.

**Comment by bnd170** [comment]
I was looking into the code of your bundles and I find an example.

I made my own Factory and FactoryInterface.

My Factory looks like this:

```
class CommentFactory implements CommentFactoryInterface
{
    /**
     * @var FactoryInterface
     */
     private $factory;

    /**
     * @param FactoryInterface $factory
     */
    public function __construct(FactoryInterface $factory)
    {
        $this->factory = $factory;
    }

    /**
     * {@inheritDoc}
     */
    public function createNew()
    {
        return $this->factory->createNew();
    }

    public function createWithPost($postId)
    {
        $comment = $this->createNew();
        $comment->setPost($postId);

        return $comment;
    }
}
```

Now I can't find how to inject the FactoryInterface of Sylius ResourceBundle.

Any tip?

**Comment by isometriks** [comment]
```yaml
comment_create:
    path: /new/{postId}
    methods: [GET, POST]
    defaults:
        _controller: acme.controller.comment:createAction
        _sylius:
            template: "..."
            factory:
                method: createWithPost
                arguments: [$postId]
```

Does that work for you in routing?
