### ISSUE TITLE
Identity map issues with new sylius fixture loader

### ISSUE THREAD

**Issue by koemeet** [Sylius/Sylius#6051]
The `AbstractResourceFixture::load` clears the entire entity manager, this will clear and detach any existing references that happen outside the current fixture. In my case I have a listener that sets a relationship on a product when it is pre persisted. But because the entity manager is cleared the reference is gone and a `A new entity was found through the relationship` error is triggered. Is it really necessary to clear the entity manager for fixtures?

**Comment by steffenbrem** [comment]
I would like to address this again, since I saw this is still present. How do you think about making it at least configurable to clear the whole entity manager after loading 10 entities. Right now you cannot hold state between those cycles since entities become detached.

**Comment by steffenbrem** [comment]
How about an options like this?

```yml
sylius_fixtures:
    clear_object_manager: false
    suites:
        default:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                locale: ~
                currency:
                    options:
                        currencies: ['USD']
```
