### ISSUE TITLE
Overriding CartItemType breaks the Product show view

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#6069]
## Sylius 1.0.0-dev

I'm trying to modify the Quantity field of CartItemType.

Following the old docs I have created a new FormType on my Bundle and extends from original in `Symfony/Bundle/CartBundle/Form/Type/CartItemType`.

My custom CartItemType shows like this:

```
use Sylius\Bundle\CartBundle\Form\Type\CartItemType as BaseType;
use Symfony\Component\Form\FormBuilderInterface;


class CartItemType extends BaseType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->remove('quantity')
            ->add('quantity', 'hidden', [
                'attr' => ['min' => 1, 'max' => 1],
                'data' => '1',
                'label' => 'sylius.form.cart_item.quantity',
            ])
            ->setDataMapper($this->orderItemQuantityDataMapper);
    }
}
```
I want you can't buy more than one product quantity per order.

My config seems liike this:

```
sylius_cart:
    resources:
        cart_item:
            classes:
                form:
                    default: Dinamic\Bundle\SyliusRibBundle\Form\Type\CartItemType
```

When I open some product view i'm getting this error:

> The option "product" does not exist. [...] in @SyliusShop/Product/Show/_inventory.html.twig at line 4

Any idea about why this is happening?
