### ISSUE TITLE
Redirects with `?id=XXX`

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6130]
Hi all
At the end of the checkout process, when I arrive at the thank you page, I still get the order id in the url as a parameter. Is there any way to remove that ? I understand it may be linked to https://github.com/Sylius/Sylius/pull/6101 but I'm not sure.

> This is also true when creating a user in the frontend, I get redirect to my account with an`?id=XXX` which I would like to remove.

Thanks !

**Comment by bretto36** [comment]
I think that's part of the ResourceBundle redirect handler. It always sends the id as a parameter (in case the redirect path was to the product page in the case of an admin product edit.)

**Comment by tchapi** [comment]
Yes it is — but then how to desactivate it on a _per-route_ basis ? the `parameters: {}` doesn't seem to work really well

**Comment by bretto36** [comment]
Hmm, i'm tracing back the code from the RedirectHandler in the ResourceBundle. Trying to find where it gets the parameters from in the beginning. Seems to be using something from the RequestConfiguration to get the values

**Comment by bretto36** [comment]
Can you add in the entire route configuration you are adding the `parameters: {}` to

**Comment by tchapi** [comment]
For instance, for the "thank you" page :

```yml
# See https://github.com/Sylius/Sylius/issues/6058#issuecomment-247150684
# and https://github.com/Sylius/Sylius/pull/5945 as well
sylius_shop_thank_you:
    path: /merci
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:thankYouAction
        _sylius:
            template: MyBundle:Frontend/Checkout/Step:thankYou.html.twig
            parameters: {}
```

**Comment by bretto36** [comment]
I would have thought you would override this one

```
sylius_shop_checkout_complete:
    path: /complete
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.order:updateAction
        _sylius:
            event: summary
            flash: false
            template: SyliusShopBundle:Checkout:complete.html.twig
            repository:
                method: find
                arguments: [expr:service('sylius.context.cart').getCart()]
            state_machine:
                graph: sylius_order_checkout
                transition: complete
            **redirect: sylius_shop_thank_you**
            **parameters: {}**
            form:
                type: sylius_checkout_complete
                options:
                    validation_groups: 'sylius_checkout_complete'
```
