### ISSUE TITLE
When not "admin-logged", /admin redirects to /login

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6168]
... I guess it should rather redirect to `/admin/login`, no ?

It's the case on the demo site, too.

**Comment by Zales0123** [comment]
Unfortunately, Symfony is incredibly strict with its firewalls paths patterns and [as it's configured now](https://github.com/Sylius/Sylius/blob/master/app/config/security.yml#L16), you will be redirected to ``/admin/login`` after accessing ``/admin/`` not ``/admin``.

**Comment by michalmarcinkowski** [comment]
How about creating a redirect route?
```
sylius_admin_panel:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_admin_dashboard
        permanent: true
```
