### ISSUE TITLE
Generalize acknowledged Fileloaders

### ISSUE THREAD

**Issue by alexseik** [Sylius/Sylius#618]
I would know if it is possible permit configure new entities in yml or annotation way ? 

For example, in SyliusResourceExtension::configure()

change

``` php
$loader = new XmlFileLoader($container, new FileLocator($this->configDir));
```

to

```
wherever ... $loader = new ... (yml,xml,annotation)
```

admitting a new optional config parameter (loader) in Configuration.php that allow :

``` yaml
sylius_product:
    driver: doctrine/orm 
    loader: yml
    classes:
        product:
            model: Garribouk\Bundle\CajaBundle\Model\Product

```
