### ISSUE TITLE
[DOCS] How to create more than one Form for a resource

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#6200]
Hi guys!

How are you? 👍 

I'm trying to configure multiple forms to Order entity, i added a custom field to entity, then I need create a form to fill just that field.

I have already tried this, but throws me an error:
```
sylius_order:
    resources:
        order:
            classes:
                model: Dinamic\Bundle\SyliusRibBundle\Entity\Order
                form:
                    dedication: Dinamic\Bundle\SyliusRibBundle\\Form\Type\OrderDedicationType
```

The error is:

> Unrecognized option "dedication" under "sylius_order.resources.order.classes.form"

I know about the docs for version 1.0 is under construction, thats why i ask it here.

Someone of you can explain me it please?

Thanks a lot!

BTW: I'm enjoying while i work with Sylius, i'll recommend it to all of my teammates 👍

**Comment by bretto36** [comment]
I think if you want to use a different form you specify it in the route declaration. 

```
led_shop_account_company_update:
    path:     /account/company-profile/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.customer:updateAction
        _sylius:
            template: LedBundle:Account:companyProfileUpdate.html.twig
            form: sylius_customer_company_profile
            repository:
                method: find
                arguments: [expr:service('sylius.context.customer').getCustomer()]
            redirect: led_shop_account_company_update
```
