### ISSUE TITLE
It's possible to use custom messages when a form is successfuly sumbitted?

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#6218]
Hi Syliusers, I'm asking about is possible to change the preseted messages about a form save data successfully.

**Comment by tchapi** [comment]
I guess you're looking for the `Resources/translations/flashes.[locale].yml` files of your bundle, where you can put something like : 

    sylius.customer.create: "Your account was successfully created !"

if you want to override the message when a customer is created for instance. Does that help ?

**Comment by bnd170** [comment]
Uhm, maybe but i cant do it work.

I want to change de flash message showed when my cart has changed.

**Comment by TheMadeleine** [comment]
http://docs.sylius.org/en/latest/customization/translation.html

All the flashes connected to card changes are here:
```
# SyliusOrderBundle:Resources/translations/flashes.en.yml
sylius:
    cart:
        cart_save_completed: The cart has been successfully updated.
        cart_clear_completed: The cart has been successfully cleared.
        item_add_completed: Item has been added to cart.
        item_remove_completed: Item has been removed from cart.
        item_add_error: Error occurred while adding item to cart.
        item_remove_error: Error occurred while removing item from cart.
```
