### ISSUE TITLE
How to acces to static content?

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#6241]
Hi guys, i can't find on docs how to access to the static content that i create in admin section.

**Comment by bnd170** [comment]
I found it.

The route is based on the Name of the static page:

```
sylius_shop_static_content_show:
    path: /{name}
    methods: [GET]
    defaults:
        _controller: sylius.controller.static_content:showAction
        _sylius:
            template: SyliusShopBundle:StaticContent:show.html.twig
            repository:
                method: findPublishedOneByName
                arguments: [$name]
```

I hope this helps someone.
