### ISSUE TITLE
Creating payment methods

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#6256]
Hi guys, i'm getting problems to create additional payment methods.

I need to add Paypal express checkout and Redsys gateways.

I did this config

```
payum:
    gateways:
        paypal_express_checkout:
            factory: "paypal_express_checkout"
            payum.http_client: "@sylius.payum.http_client"
            username: "***"
            password: "***"
            signature: "***"
            sandbox: "true"


sylius_payment:
    gateways:
        cc: Redsys
        paypal_express_checkout: Paypal Express Checkout
```

Now i can add both gateways on admin section but i didn't see those on select payment method in cart steps.

I'm doing something wrong?
