### ISSUE TITLE
[RFC] GetResponseEvent for ResourceController

### ISSUE THREAD

**Issue by isometriks** [Sylius/Sylius#6339]
Something like this at least for show actions:

``` php
$event = $this->eventDispatcher->dispatch(ResourceActions::SHOW, $configuration, $resource);

if ($response = $event->getResponse()) {
    return $response;
}
```

This could allow for some other events to render a response such as some other kind of security, or a caching mechanism. I had played around with my own implementation of adding a cache parameter to `_sylius` in routing:

``` yaml
route_name:
    _controller: ....
    _sylius:
        cache:
            last_modified: resource.updatedAt
            public: true
            max_age: 100
```

Using parameter parser to replace with resources values so then the listener could do `$response->isNotModified()` and set the response on the event so it doesn't need to be rendered again. I suppose it would still work for API request if you set the vary on the content-type so json / html responses can be cached separately.
