### ISSUE TITLE
Current order cancellation doesn't support refund well, no proper way to add refund logic

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#6392]
I try to add refund logic to the order cancellation, when a paid order is cancelled,  but I have no idea about how to mark the payment state as  `refunded` using current related entities, such as Payment,   a paid cancelled order has  its `paymentState` property value as `cancelled`, and it has a payment which has changed from `processing` to `cancelled`,  I have few questions in mind:
1. how do we mark this payment as `refunded`?  
     I can make another entity , such as Refund to track the refund  states, but if so, we have two ways to mark the payment  refunded state, it seems unreasonable,  
2.  what does `processing`, `payedout`,`void` , `completed` states mean? 
   can you add document for these states  ? I might misunderstand  the  meaning of these states.  from these code below ,   both  `processing` and `completed` states implies  the order is paid,  but only when payment state is `processing`  or `new`, the payment can be cancelled, if I set its state as `completed` when the order is paid, then the payment can't be cancelled any more,  which confuses me a lot.  So I think the solution for this is that  we need to decide whether to call refund or cancel a payment when order is being cancelled. 

```
  sylius_payment:
        transitions:
            create:
                from: [cart]
                to: new
            process:
                from: [new]
                to: processing
            complete:
                from: [new, processing]
                to: completed
            fail:
                from: [new, processing]
                to: failed
            cancel:
                from: [new, processing]
                to: cancelled
            refund:
                from: [completed]
                to: refunded
            void:
                from: [new, processing]
                to: void
```

Sylius might not support refund in version 1 release ,  but I think it import to refactor the code to support refund logic . 

Related issues：
#6144 ,
