### ISSUE TITLE
Question and exclamation marks in translations for spanish language

### ISSUE THREAD

**Issue by enekochan** [Sylius/Sylius#6513]
Some translations don't have the question or exclamation marks included and those are placed directly in the template. This is the case for `sylius.ui.need_assistance`, `sylius.ui.call_us` or `sylius.ui.forgot_password` for example, but there are probably more.

``` twig
{{ 'sylius.ui.need_assistance'|trans }}? {{ 'sylius.ui.call_us'|trans }}!
```

``` yaml
sylius:
    ui:
        need_assistance: 'Need assistance'
        call_us: 'Call us'
        forgot_password: 'Forgot password'
```

This is OK for english but not for spanish where we use both opening and closing marks. This is how it should look like:

``` twig
{{ 'sylius.ui.need_assistance'|trans }} {{ 'sylius.ui.call_us'|trans }}
```

``` yaml
sylius:
    ui:
        need_assistance: 'Need assistance?'
        call_us: 'Call us!'
        forgot_password: 'Forgot password?'
```

And for spanish translations would be:

``` yaml
sylius:
    ui:
        need_assistance: '¿Necesitas ayuda?'
        call_us: '¡Llámanos!'
        forgot_password: '¿Contraseña olvidada?'
```

May be there are more scenarios like this one.
