### ISSUE TITLE
[Resource] How to pass services to factory methods?

### ISSUE THREAD

**Issue by sweoggy** [Sylius/Sylius#6535]
Hi all,

I am trying to add different type of products which should have some default product attributes specified. The most logical place to specify these attributes seem to be in a custom factory method for each product type. In order to specify which default attributes I want I need access to Doctrine's entity manager so that I don't try to create already existing attributes. So my question is, is it currently possible to pass services to factory methods, if yes, how? 

I have tried tried to pass '@doctrine.orm.entity_manager' just like one does with regular Symfony services, but that just passes the service name as text to the factory method.

A route for one of the product types currently looks like this:
```
app_admin_product_create_fabric_colour:
    path: /products/new/fabric-colour
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            section: admin
            factory:
                method: createFabric
                arguments: [@doctrine.orm.entity_manager] # <- This is where I want to pass the service
            template: SyliusAdminBundle:Crud:create.html.twig
            redirect: sylius_admin_product_update
            permission: true
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                templates:
                    form: SyliusAdminBundle:Product:_form.html.twig
                route:
                    name: app_admin_product_create_fabric_colour
```
