### ISSUE TITLE
1.0.0@alpha Override on state does not work

### ISSUE THREAD

**Issue by xavren** [Sylius/Sylius#6614]
I tried the 1.0.0@alpha and tried to remove the shipping state of the checkout process.
Reading the code, i found that there may be a bug in the bundle StateMachineBundle that you use https://github.com/winzou/StateMachineBundle/issues/32

I don't know if this is known but i will try to fix it

**Comment by TheMadeleine** [comment]
Were you doing it [this way](http://docs.sylius.org/en/latest/cookbook/checkout.html#how-to-remove-a-step-from-checkout)?

**Comment by xavren** [comment]
Yes

**Comment by TheMadeleine** [comment]
While writing these docs that I've asked you about, I've been testing this behaviour and I'm sure it works :)

**Comment by lchrusciel** [comment]
I have succeeded also with this configuration. Can you show your code snippet?

**Comment by xavren** [comment]
Here is my state that i tried to load before and after the core


```
#app/config/config.yml
imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusShopBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusApiBundle/Resources/config/app/config.yml" }
    - { resource: "@PanelBundle/Resources/config/services.yml" }

    - { resource: "parameters.yml" }
    - { resource: "security.yml" }
    - { resource: "resources.yml" }
    - { resource: "grids/grids.yml" }
    - { resource: "state_machine.yml" }

#app/config/state_machine.yml
winzou_state_machine:
    sylius_order_checkout:
        class: "%sylius.model.order.class%"
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            addressed: ~
            payment_selected: ~
            completed: ~
        transitions:
            address:
                from: [cart, addressed, payment_selected]
                to: addressed
            select_payment:
                from: [addressed, payment_selected]
                to: payment_selected
            complete:
                from: [payment_selected]
                to: completed
        callbacks:
            after:
                sylius_process_cart:
                    on: ["address", "select_payment"]
                    do: ["@sylius.order_processing.order_processor", "process"]
                    args: ["object"]
                sylius_create_order:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'create'", "'sylius_order'"]
                sylius_hold_inventory:
                    on: ["complete"]
                    do: ["@sylius.inventory.order_inventory_operator", "hold"]
                    args: ["object"]
                sylius_assign_token:
                    on: ["complete"]
                    do: ["@sylius.unique_id_based_order_token_assigner", "assignTokenValue"]
                    args: ["object"]
                sylius_increment_promotions_usages:
                    on: ["complete"]
                    do: ["@sylius.promotion_usage_modifier", "increment"]
                    args: ["object"]
```

Dumping the configuration running `php app/console debug:config winzou_state_machine`
```
winzou_state_machine:
    sylius_order_checkout:
        class: Sylius\Component\Core\Model\Order
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: Sylius\Component\Resource\StateMachine\StateMachine
        states:
            cart: null
            addressed: null
            payment_selected: null
            completed: null
            shipping_selected: null
        transitions:
            address:
                from:
                    - cart
                    - addressed
                    - payment_selected
                    - cart
                    - addressed
                    - shipping_selected
                    - payment_selected
                to: addressed
            select_payment:
                from:
                    - addressed
                    - payment_selected
                    - payment_selected
                    - shipping_selected
                to: payment_selected
            complete:
                from:
                    - payment_selected
                    - payment_selected
                to: completed
            select_shipping:
                from:
                    - addressed
                    - shipping_selected
                    - payment_selected
                to: shipping_selected
        callbacks:
            after:
                sylius_process_cart:
                    'on':
                        - address
                        - select_shipping
                        - select_payment
                    do:
                        - '@sylius.order_processing.order_processor'
                        - process
                    args:
                        - object
                    disabled: false
                    priority: 0
                sylius_create_order:
                    'on':
                        - complete
                    do:
                        - '@sm.callback.cascade_transition'
                        - apply
                    args:
                        - object
                        - event
                        - '''create'''
                        - '''sylius_order'''
                    disabled: false
                    priority: 0
                sylius_hold_inventory:
                    'on':
                        - complete
                    do:
                        - '@sylius.inventory.order_inventory_operator'
                        - hold
                    args:
                        - object
                    disabled: false
                    priority: 0
                sylius_assign_token:
                    'on':
                        - complete
                    do:
                        - '@sylius.unique_id_based_order_token_assigner'
                        - assignTokenValue
                    args:
                        - object
                    disabled: false
                    priority: 0
                sylius_increment_promotions_usages:
                    'on':
                        - complete
                    do:
                        - '@sylius.promotion_usage_modifier'
                        - increment
                    args:
                        - object
                    disabled: false
                    priority: 0
            before: {  }
```

**Comment by xavren** [comment]
And to show you that my file is read

```
states:
            cart: ~
            addressed: ~
            payment_selected: ~
            completed: ~
            test: ~
            toto: ~
```
will generate
```
states:
            cart: null
            addressed: null
            payment_selected: null
            completed: null
            test: null
            toto: null
            shipping_selected: null
```
