### ISSUE TITLE
[ResourceBundle] entities with phpcr-odm driver [v0.19]

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#6624]
How can I use doctrine/phpcr-odm driver on custom entities with sylius resources ?

My configuration is like this:
```
sylius_resource:
    resources:
        app.article_document:
            driver: doctrine/phpcr-odm
            classes:
                model: AppBundle\Document\ArticleDocument
                factory: AppBundle\Factory\ArticleDocumentFactory
                repository: AppBundle\Repository\StaticContentRepository
                form:
                    default: AppBundle\Form\Type\ArticleDocumentType
```

But I have this error message:

> Resource "app.article_document" uses driver "doctrine/phpcr-odm", but this driver has not been enabled.

**Comment by Raptek** [comment]
You have to enable it in your `config.yml`

```yaml
sylius_resource:
    drivers:
        - doctrine/orm
        - doctrine/phpcr-odm
```

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/config/app/config.yml#L27
