### ISSUE TITLE
Extend CartItemType from CoreBundle (v1.0.0-alpha)

### ISSUE THREAD

**Issue by leogout** [Sylius/Sylius#6635]
Hi (again), I'd like to extend the CartItemType to add some fields to it.

Before, I had to override the `sylius_cart` config, but it's not available anymore since v1.0.0-alpha. Do I have to use the CompilerPass to override the CoreBundle's services ? Or is there an option that I missed ?

Shouldn't this be possible under the `sylius_order` config ?

**Comment by tchapi** [comment]
As far as I understand your question, you want to override **OrderItem** :
```
sylius_order:
    resources:
        order_item:
            classes:
                model: My\WebBundle\Entity\OrderItem
                form:
                    default: My\WebBundle\Form\Type\OrderItemType
```
