### ISSUE TITLE
How to customize/override products grid?

### ISSUE THREAD

**Issue by castwayalldc** [Sylius/Sylius#6637]
Hello people, i am trying to customize the product grid on the admin panel to add id and created_at fields and make them sortable. 

I could make it to add the new fields like this:

app\config\grids\admin\product.yml
`sylius_grid:
    grids:
        sylius_admin_product:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            sorting:
                id: desc
            fields:
                id:
                    type: string
                    label: ID
                    path: id
                    sortable: ~
                created_at:
                    type: datetime
                    label: app.ui.created_at
                    options:
                        format: 'Y:m:d H:i:s'
                    path: created_at
                    sortable: ~
`

but the default sorting is still the product code and i would also like to re-arrange fields to put the id on 1st column for example. But when i try to add the other fields i get this error:

"An exception has been thrown during the rendering of a template ("The option "0" does not exist. Defined options are: "template", "vars".") in @SyliusAdmin\Grid\_default.html.twig at line 43. "

Thanks in advance.

**Comment by ylastapis** [comment]
@castwayalldc @pjedrzejewski got the same problem trying to override

**Comment by gpekz** [comment]
Hello everyone,

I got a similar problem trying to add links to a main action 

```
# AppBundle/Resources/config/grids/admin/product.yml
sylius_grid:
    grids:
        sylius_admin_product:
            actions:
                main:
                    create:
                        type: links
                        label: sylius.ui.create
                        options:
                            class: primary
                            icon: plus
                            header:
                                icon: cube
                                label: sylius.ui.type
                            links:
                                simple:
                                    label: sylius.ui.simple_product
                                    icon: plus
                                    route: sylius_admin_product_create_simple
                                configurable:
                                    label: sylius.ui.configurable_product
                                    icon: plus
                                    route: sylius_admin_product_create
                                # want to add new links
                                enabled:
                                    label: sylius.ui.enabled_product
                                    icon: plus
                                    route: sylius_admin_product_create_enabled
                                disabled:
                                    label: sylius.ui.disabled_product
                                    icon: plus
                                    route: sylius_admin_product_create_disabled
```

The links are not added to the action, so I tried to dump the grid in a listener

```
namespace AppBundle\Grid;

use Sylius\Component\Grid\Event\GridDefinitionConverterEvent;

final class AdminProductGridListener
{
    public function addMainActions(GridDefinitionConverterEvent $event)
    {
        dump($event->getGrid()->getActionGroup('main')->getAction('create')->getOptions());
    }
}
```

And got 

```
array:8
    "class" => "primary"
    "icon" => "plus"
    "header" => array:2 
    "links" => array:2 
        "simple" => array:3 
        "configurable" => array:3 
    ]
    0 => "primary"
    1 => "plus"
    2 => array:2 
        "icon" => "cube"
        "label" => "sylius.ui.type"
    ]
    3 => array:4
        "simple" => array:3
        "configurable" => array:3 
        "enabled" => array:3 
        "disabled" => array:3
    ]
]
```

But it works when I override the entire grid in "app/Resources"

Is that a bug ?

Thanks in advance.
