### ISSUE TITLE
New orderBundle in alpha -  old ItemResolver. 

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#6784]
I notice that sylius now is using other structure of cart and order, what is the flow of adding to cart, or more specific:
what acts like an Item Resolver?

**Comment by tchapi** [comment]
You want to have a look at **OrderProcessor**s, something along those lines : 
```php
final class MyCartPreprocessor implements OrderProcessorInterface
{
    public function process(OrderInterface $order)
    {
        // Do stuff with $order
    }
```

```yml
services:
    my_bundle.cart_preprocessor:
        class: My\WebBundle\Service\MyCartPreprocessor
        tags:
            - { name: sylius.order_processor }
```

Hope that helps
