### ISSUE TITLE
How to enable CustomerGroupRuleChecker / CustomerGroupType ?

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6871]
This was working before but now gives us a 500 on `/admin/promotions/new`
```yml
    my_bundle.sylius_promotion_rule_customer_group_configuration:
        class: Sylius\Bundle\CoreBundle\Form\Type\Promotion\Rule\CustomerGroupType
        arguments: ["@sylius.repository.customer_group"]
        tags:
            - { name: form.type, alias: sylius_promotion_rule_customer_group_configuration }
    my_bundle.customer_group_rule_checker:
        class: Sylius\Component\Core\Promotion\Checker\Rule\CustomerGroupRuleChecker
        tags:
            - { name: sylius.promotion_rule_checker, type: customer_group, label: "Customer is in group" }
```

What should change in the previous code ?
