### ISSUE TITLE
Overriding ShopUser Model

### ISSUE THREAD

**Issue by samanmohamadi** [Sylius/Sylius#6879]
I want to override shop_user model of SyliusCoreBundle, I have followed the [instructions](http://docs.sylius.org/en/latest/customization/model.html) but there are 2 problems.

- In doctrine config file when I use "sylius_shop_user" as table name, it says that this table already exists.  
`The table with name 'sylius_dev.sylius_shop_user' already exists.`

-  when I want to override shop_user model's class, I get this error:  
` Unrecognized option "shop_user" under "sylius_core.resources" `

**Comment by NeverResponse** [comment]
Pretty sure fixing the second problem will also resolve the first.
And that's simply pointing in the wrong configuration, so instead of:
``` yml
sylius_core:
    resources:
        .... and so on
```
try:
``` yml
sylius_user:
    resources:
        shop:
            user:
                classes:
                    model: #Your class
```
