### ISSUE TITLE
Customizing sylius_customer_registration 

### ISSUE THREAD

**Issue by velikanov** [Sylius/Sylius#6894]
Is there any recipe?

I need to make Phone Number field required.

I'm trying to override it following the "Customizing Forms" topic, but it appears that things are not that simple with this form type.

The only way that I can specify something in config.yml looks like this:
```yml
sylius_user:
    resources:
        whatever: # need to specify it here, because it uses attribute name as key in array prototype configuration
            user:
                classes:
                    form:
                        registration: AppBundle\Form\Type\CustomerRegistrationType
```

It ends with `sylius.form.type.customer_user_registration` form type in `debug:container`

But routing describes `sylius_shop_register` with `sylius_customer_registration` form type…

It appears that I can't specify something for neither `sylius_customer` nor `sylius_core`.
Customer bundle doesn't have a registration form in config. Core bundle also doesn't have anything like this.

I'm out of ideas 😓
