### ISSUE TITLE
Unrecognized options "driver" under "sylius_cart"

### ISSUE THREAD

**Issue by KunwarSiddharthSingh** [Sylius/Sylius#693]
Hi all. I have installed SyliusCartBundle  following the docs ( http://docs.sylius.org/en/latest/bundles/SyliusCartBundle/installation.html ) and when I run "php app/console doctrine:schema:update --force" I get the following error:

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
Unrecognized options "model" under "sylius_cart.classes.item" 
```

It seems like is a config.yml error So I changed my config.yml like sylius main app (https://github.com/Sylius/Sylius/blob/master/app/config/sylius.yml):

```
sylius_cart:
     resolver: sylius.cart_item_resolver.default
     classes:
         item:
             form: Sylius\Bundle\CoreBundle\Form\Type\CartItemType
         cart:
             form: Sylius\Bundle\CoreBundle\Form\Type\CartType
```

Instead:

```
    sylius_cart:
         driver: doctrine/orm
         resolver: app.cart_item_resolver
         classes:
             item:
                 model: App\CartBundle\Entity\CartItem
```

But again get the following error :

```
 [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
 You have requested a non-existent parameter "sylius_order.driver".
```

I think it's all fine in my config.
