### ISSUE TITLE
GridBundle filters label ignored when type is boolean 

### ISSUE THREAD

**Issue by leogout** [Sylius/Sylius#6946]
Hi, when I use this grid configuration for a custom resource, my label is ignored and the `required:` is used instead in my template.
```yml
# ...
    filters:
        required: # <- this one is rendered
            type: boolean
            #type: string
            label: sylius.ui.required
```
It isn't ignored when i do this
```yml
# ...
    filters:
        required:
            #type: boolean
            type: string
            label: sylius.ui.required # <- this one is rendered
```

Am I missing something ?
