### ISSUE TITLE
[Bug][Critical] Bug on dashboard after fresh installation

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#6961]
![zrzut ekranu 2016-12-01 o 08 40 02](https://cloud.githubusercontent.com/assets/6212718/20785704/e0f7df88-b7a1-11e6-9200-ce728013dc9c.png)

Related: https://github.com/Sylius/Sylius/pull/6958

**Comment by Zales0123** [comment]
Working on fixing this ASAP

**Comment by Zales0123** [comment]
What was the problem with previous implementation?
```yml
sylius_shop_partial_cart_summary:
    path: /summary
    methods: [GET]
    defaults:
        _controller: sylius.controller.order:summaryAction
        _sylius:
            template: $template
            form: Sylius\Bundle\OrderBundle\Form\Type\CartType
```
