### ISSUE TITLE
[Doc] Can't override sylius_order_checkout states

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius#7095]
Hello. i'm having problems to override states in sylius_order_checkout process. First thing i tried is  [follow instructions](http://docs.sylius.org/en/latest/cookbook/checkout.html), but placing the file where it says, it doesn't seem to have any effect in the configurations...

Second thing i tried is to override this from my own bundle. so, i added a sylius_checkout_order.yml there and imported it from my config.yml. Just for testing purposes i added dummy values to the file. The plan is remove the `shipping_selected` state, so i went like 
```yaml
winzou_state_machine:
    sylius_order_checkout:
        class: my_class
        property_path: checkoutState
        graph: sylius_order_checkout_my_graph
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            addressed: ~
            payment_selected: ~
            completed: ~
```

Now the problem: While the class and graph values are overrided, it looks i cannot delete that shipping_selected stated. doing a debug:container i can see this
```yaml
winzou_state_machine:
    sylius_order_checkout:
        class: my_class
        property_path: checkoutState
        graph: sylius_order_checkout_my_graph
        state_machine_class: Sylius\Component\Resource\StateMachine\StateMachine
        states:
            cart: null
            addressed: null
            shipping_selected: null
            payment_selected: null
            completed: null
```

As you see, shipping_selected is there and i can't find the way to remove it. just for testing i modified my yml to be like 
```yaml
winzou_state_machine:
    sylius_order_checkout:
        class: my_class
        property_path: checkoutState
        graph: sylius_order_checkout_my_graph
        state_machine_class: "%sylius.state_machine.class%"
        states:
            a_dummy_state: ~
```

Doing the debug again i can see
```yaml
winzou_state_machine:
    sylius_order_checkout:
        class: my_class
        property_path: checkoutState
        graph: sylius_order_checkout_my_graph
        state_machine_class: Sylius\Component\Resource\StateMachine\StateMachine
        states:
            cart: null
            addressed: null
            shipping_selected: null
            payment_selected: null
            completed: null
            a_dummy_state: null
```

So, looks that's something, and maybe not in the Sylius side,  is *merging* the states isteand of replacing them? 
Or am i missing something here?

Thanks a lot.

**Comment by TheMadeleine** [comment]
Yes. This is a known issue. We are not able to fully override state machines. The configurations are merged. And the problem lays rather in the state machine bundle than in Sylius itself :<

Although you can disable existing callbacks to certain transitions, and modify the graph, the old graph with its states and transition will still be there.

**Comment by michalmarcinkowski** [comment]
@TheMadeleine but if we "override" the whole file, placing it in `app/...` (as described [here](http://docs.sylius.org/en/latest/cookbook/checkout.html#overwrite-the-state-machine-of-checkout)) shouldn't it work?

**Comment by crevillo** [comment]
@michalmarcinkowski it doesn't as far i see. By the way, in the documentation your are told to that because is a [standard procedure of overriding configs in Symfony](http://symfony.com/doc/current/bundles/inheritance.html#overriding-resources-templates-routing-etc), but if you open the symfony doc, in that page you are told to create a bundle having a parent in order to customize settings like this... don't you?

**Comment by ePav** [comment]
@crevillo I had the same issue. This is my way of solution. I overwrite the getContainerLoader method in app/AppKernel.php like this:

```
protected function getContainerLoader(ContainerInterface $container)
    {
        $locator = new FileLocator($this, $this->getRootDir() . '/Resources');
        $resolver = new LoaderResolver(array(
            new XmlFileLoader($container, $locator),
            new YamlFileLoader($container, $locator),
            new IniFileLoader($container, $locator),
            new PhpFileLoader($container, $locator),
            new DirectoryLoader($container, $locator),
            new ClosureLoader($container),
        ));

        return new DelegatingLoader($resolver);
    }
```

**Comment by crevillo** [comment]
this indeed seems to work. can we be sure this has no unwanted side effects?

**Comment by yosriMekni** [comment]
i've followed this [docs](http://docs.sylius.org/en/latest/cookbook/checkout.html) to remove shipping step , and when i submit the form in adressing step it kepps redirect me to adressing ?! what can be the problem

**Comment by yosriMekni** [comment]
hi , i've did all the instructions and i've overrided the getContainerLoader method in app/AppKernel.php and when i click next in the payment step it keeps redirect me to payment step ? what can be the problem

**Comment by c-revillo** [comment]
hmm, overriding the the getContainerLoaded and following the instructions worked for me perfectly....

**Comment by yosriMekni** [comment]
i'm using sylius beta

**Comment by velikanov** [comment]
@yosriMekni, are you sure you haven't any state machine overrides?

**Comment by c-revillo** [comment]
let me add something. i have indeed to change some things from the doc, even i don't know if this is related where the problem @yosriMekni is having. 

First, in the `app/Resources/SyliusShopBundle/config/routing/checkout.yml` i needed to change the form definitions. for instance, where it reads
```yaml
form:
    type: sylius_checkout_address
``` 
i had to add the full form type class type there to make it work. 

Second, in the last part of this file, when trying to make the payment (i'm using a custom payum gateway, btw) 
```yaml
redirect:
                route: sylius_shop_order_pay
                parameters:
                    paymentId: expr:service('sylius.context.cart').getCart().getLastNewPayment().getId()
```

i had to modify the parameters part leaving it like 
```yaml
redirect:
                route: sylius_shop_order_pay
                parameters:
                    tokenValue: resource.tokenValue
```
