### ISSUE TITLE
Make codes utf8mb4-great again

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#7131]
Hi,

There is currently a limitation / nasty bug because we are forced to use `utf8` as the table charset to accomodate for the `code`'s unique indexes that are stored in a length of 255 chars.

The utf8 charset means that we cannot store in the DB a lot of characters such as **emojis**, or special characters outside the [BMP](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane).

The problem is that a large part of the unicode characters would then break the functionality with a nasty and silent error truncating stored text.

Switching to the recommended `utf8mb4` character and relevant collation is not possible since the vast majority of `code` properties are mapped to `VARCHAR 255 UNIQUE` that is too big for the max InnoDB index length which is `767 bytes > 4*255  = 1020 bytes`

```
  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

The solution would be to lower the field size to get into that limit. It would be something like 191 instead of 255.

See https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by sweoggy** [comment]
Instead of lowering the key length you can just configure your database properly. Specifically use row format dynamic and the following InnoDB settings (my.cnf or my.ini):

```
innodb_file_format=barracuda
innodb_file_per_table=1
innodb_large_prefix=1
```

I use the following Doctrine settings (config.yml):
```
doctrine:
    dbal:
        # host, port etc.
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
            row_format: dynamic
```
