### ISSUE TITLE
TranslationTypeExtension doesn't work

### ISSUE THREAD

**Issue by alexchuin** [Sylius/Sylius#7172]
Hi All !

I'm trying to add a field in the TaxonTranslation model.

```
sylius_taxonomy:
    resources:
        taxon:
            translation:
                classes:
                    model: AppBundle\Entity\TaxonTranslation
                    form: AppBundle\Form\Extension\TaxonTranslationTypeExtension
```

The model works fine, not the form.

The services.yml:

```
    app.form.extension.type.taxon_translation:
        class: AppBundle\Form\Extension\TaxonTranslationTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonTranslationType }
```

And my extension:

```
<?php

namespace AppBundle\Form\Extension;

use Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonTranslationType;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;

final class TaxonTranslationTypeExtension extends AbstractTypeExtension
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('newField', TextareaType::class, [
                'required' => true,
                'label' => 'sylius.form.taxon.newField',
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getExtendedType()
    {
        return TaxonTranslationType::class;
    }
}
```

I don't know if it's a bug or an error from me...

Thanks !

**Comment by jurv** [comment]
Hi @alexchuin !

I never managed to customize forms this way, even though it is the method suggested in the documentation. I've always had to extend the formType to get it to work.

You should try something like this:

```php
<?php

namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Sylius\Bundle\TaxonomyBundle\Form\Type\TaxonTranslationType as BaseTaxonTranslationType;

final class TaxonTranslation extends AbstractType
{

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('newField', TextareaType::class, [
                'required' => true,
                'label' => 'sylius.form.taxon.newField',
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return BaseTaxonTranslationType::class;
    }
}

```

Then in `app/config/config.yml`
```yaml
sylius_taxonomy:
    resources: 
        taxon:
           translation:
                   classes:
                       form: AppBundle\Form\Type\TaxonTranslationType
```

But with translations, you also have to override the main object type (in this case TaxonType), as its code contain a hardcoded reference to Sylius' TaxonTranslationType:

```php
        $builder
            ->add('translations', ResourceTranslationsType::class, [
                'entry_type' => TaxonTranslationType::class,
                'label' => 'sylius.form.taxon.name',
            ])
```

So when you override it, you have to do something like:
```php
        $builder
            ->remove('translations')
            ->add('translations', ResourceTranslationsType::class, [
                'entry_type' => AppBundle\Form\Type\TaxonTranslationType::class,
                'label' => 'sylius.form.taxon.name',
            ])
```

I hope this helps !
