### ISSUE TITLE
Unable to set validation_groups to override default validation rules

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#7197]
What the title says, in my case I can't override a ProductImage to allow uploads of more than 2MB

validation.xml
```yml
Sylius\Component\Product\Model\ProductImage:
    properties:
        file:
            - Image:
                maxSize: 10M
                groups: [app_product]
```

config.yml
```yml
sylius_product:
    resources:
        product:
            classes:
                repository: AppBundle\Repository\ProductRepository
            validation_groups:
                default: [app_product]
```

Gives an error:
```
InvalidConfigurationException in ArrayNode.php line 317:
Unrecognized option "validation_groups" under "sylius_product.resources.product"
```
