### ISSUE TITLE
[Taxons] Translated slugs are not working, product names in taxon product listing are not translated

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#7199]
1. When multiple languages are used, only the default english slug is used - you cannot access a taxon via any other language slug.
2. Taxon catalog menu on front-end uses english taxons regardless if there are translations or not.
3. Product names do not use translated names in the taxon listings.

**Comment by pjedrzejewski** [comment]
Are you using Beta 1 tag? I believe we have fixed this already, cc @GSadee.

**Comment by psihius** [comment]
Yes, Beta 1

**Comment by smashou** [comment]
I'm experiencing something quite different about Taxon Locale.

When Sylius is building the Taxon menu, the slugs don't depends on the selected locale but depends on the Channel default locale. 

And if I want to access to a slug associated with the default channel locale, it works well, but if the slug is in a different locale, it does not work.

For the second point it seems to come from this file:
```
#vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/config/grids/product.yml
sylius_grid:
  grids:
      sylius_shop_product:
          driver:
              name: doctrine/orm
              options:
                  class: "%sylius.model.product.class%"
                  repository:
                      method: createQueryBuilderByChannelAndTaxonSlug
                      arguments:
                          channel: "expr:service('sylius.context.channel').getChannel()"
                          taxonId: $slug
                          locale: "expr:service('sylius.context.channel').getChannel().getDefaultLocale().getCode()"
```
Which was previously:
```
sylius_grid:
  grids:
      sylius_shop_product:
          driver:
              name: doctrine/orm
              options:
                  class: "%sylius.model.product.class%"
                  repository:
                      method: createQueryBuilderByChannelAndTaxonSlug
                      arguments:
                          channel: "expr:service('sylius.context.channel').getChannel()"
                          taxonId: $slug
                          locale: '%locale%'
```

**Comment by psihius** [comment]
I my case I have a multi-language store, single channel, so I expect when I switch the language, translated slugs are used to navigate and set a proper language for the user. Because we don't have language in the URL. Also, this is important SEO stuff.

**Comment by psihius** [comment]
@smashou by the way,

locale: "expr:service('sylius.context.channel').getChannel().getDefaultLocale().getCode()"

But how do you select current active language here?

**Comment by smashou** [comment]
@psihius it's sylius code, In fact I don't know how to select current active language here

**Comment by psihius** [comment]
Found it: 
```yml
- "expr:service('sylius.context.locale').getLocaleCode()"
```

**Comment by jurv** [comment]
@pjedrzejewski Shouldn't the argument given by @psihius be the one used in the grid's repository argument ? Using the channel's default locale as it currently is implemented leads to translation issues in the shop.

If I change the grid definition to:
```yaml
sylius_grid:
  grids:
      sylius_shop_product:
          driver:
              name: doctrine/orm
              options:
                  class: "%sylius.model.product.class%"
                  repository:
                      method: createQueryBuilderByChannelAndTaxonSlug
                      arguments:
                          channel: "expr:service('sylius.context.channel').getChannel()"
                          taxonId: $slug
                          # Modified line : use current locale instead of default locale
                          locale: "expr:service('sylius.context.locale').getLocaleCode()"
```

everything works fine, products names and slugs are correctly translated.

I tried to override this in my own config, but as stated in issues #7292 and #7095, it is not possible to override anything from the "driver" sections of grid definition. Plus it really makes sense to me that everything that is locale related should use the current locale and not the channel default locale.

Am I missing something ? There must be a good reason as to why it was implemented this way in the first place ?
