### ISSUE TITLE
Allow frontend and backend layouts to be configurable

### ISSUE THREAD

**Issue by emodric** [Sylius/Sylius#7223]
It would be nice to be able to configure which layouts are used in Admin and Shop bundles via configuration, without need for overriding entire template in `app/Resources` folder or via bundle inheritance.

Usecases are integrating Sylius admin UI in other administration interfaces (for example, we integrate Sylius into eZ Platform and its legacy version of admin UI, to form a single admin experience) or replacing the entire layouting of the frontend with our custom built layouting solution.

**Comment by pjedrzejewski** [comment]
Great idea Edi! What would be your suggestion, a simple parameter used as global Twig variable sounds like the simplest solution, although not the most elegant.

**Comment by emodric** [comment]
It's not elegant, I agree, but it works :) We use a similar approach on some of our bundles with similar needs. A global Twig variable registered as a service, which has a default page layout injected and used in Twig template with a getter, and the new page layout is injected to the global variable with an event listener in certain conditions. In this case, it would be triggered if route name prefix is for example `sylius_admin_` or `sylius_shop_`.

The default layout can be injected to global variable in numerous ways, but most probably the easiest solution would just be defining a container param.

It looks however that checkout process uses a completely different layout, not based on `@SyliusShop/layout.html.twig`, so we would probably need to work with a set of layouts, rather than only one.

**Comment by pjedrzejewski** [comment]
I guess this should be configurable like this:

``` yaml
sylius_admin:
        twig:
             layout: foo.html.twig
```

---

``` yaml
sylius_shop:
        twig:
             layouts: 
                 main: foo.html.twig
                 checkout: bar.html.twig
                 account: baz.html.twig
```

Something along these lines, and prepending ``twig`` configuration to set some global variables ``{% extends sylius_admin_layout %}`` and ``{% extends sylius_shop_checkout_layout %}``.

This probably requires some improvement, but will definitely work. I'd skip the route checking part for now and keep things simple.

Thoughts?
