### ISSUE TITLE
[API] [RFC] Serialization of Sylius product

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#7268]
# Hello folks! ✋ 

As you could see, we have started upgrading our API. One of the parts of this upgrade is to finalize the serialization of entities. As my colleague @tuka217 the product's API upgrade (#7238) recently, we should come up with proper serialization for products(and maybe a product variants) for this moment.

My proposal is to have something like this
 * Detailed view:
    ```json
    {
        "id": 1,
        "code": "theme-mug-sku",
        "average_rating": 4.5,
        "attributes": [
              {}
        ],
        "options": [
              {}
        ],
        "product_taxons": [
              {}
        ],
        "main_taxon": {
        },
        "channels": {
            "id": 1,
            "code": "WEB",
            "_links": {
                "self": {
                    "href": "https://sylius.dev/api/v1/channels/1"
                },
            }
        },
        "created_at": "017-01-16T11:44:53+0100",
        "updated_at": "017-01-16T11:44:53+0100",
        "availableOn": "017-01-16T11:44:53+0100",
        "availableUntil": "017-01-16T11:44:53+0100",
        "translations": {
            "en_US": {
                "id": 1,
                "locale": "en",
                "name": "Theme Mug",
                "slug": "theme-mug"
            }
        },
        "_links": {
            "self": {
                "href": "/api/v1/products/1"
            },
            "collection": {
                "href": "/api/v1/products/"
            },
            "variants": {
                "href": "/api/v1/products/1/variants/"
            },
            "reviews": {
                "href": "/api/v1/products/1/reviews/"
            },
            "associations": {
                "href": "/api/v1/products/1/associations/"
            },
            "images": {
                "href": "/api/v1/products/1/images/"
            }
        }
    }
    ```
 * Default view:
    ```json
    {
        "id": 1,
        "code": "theme-mug-sku",
        "average_rating": 4.5,
        "main_taxon": {
        },
        "channels": {
            "id": 1,
            "code": "WEB",
            "_links": {
                "self": {
                    "href": "https://sylius.dev/api/v1/channels/1"
                },
            }
        },
        "availableOn": "017-01-16T11:44:53+0100",
        "availableUntil": "017-01-16T11:44:53+0100",
        "translations": {
            "en_US": {
                "id": 1,
                "locale": "en",
                "name": "Theme Mug",
                "slug": "theme-mug"
            }
        },
        "_links": {
            "self": {
                "href": "/api/v1/products/1"
            },
            "collection": {
                "href": "/api/v1/products/"
            },
            "variants": {
                "href": "/api/v1/products/1/variants/"
            },
            "reviews": {
                "href": "/api/v1/products/1/reviews/"
            },
            "associations": {
                "href": "/api/v1/products/1/associations/"
            },
            "images": {
                "href": "/api/v1/products/1/images/"
            },
            "attributes": {
                "href": "/api/v1/products/1/attributes/"
            },
            "options": {
                "href": "/api/v1/products/1/options/"
            },
            "product_taxons": {
                "href": "/api/v1/taxons/?productId=1"
            }
        }
    }
    ```
 * A default view would be displayed on a paginated list, whole product pagination would look like this:
    ```json
    {
        "page": 1,
        "limit": 10,
        "pages": 1,
        "total": 1,
        "_links": {
            "self": {
                "href": "/api/v1/products/?page=1&limit=10"
            },
            "first": {
                "href": "/api/v1/products/?page=1&limit=10"
            },
            "last": {
                "href": "/api/v1/products/?page=1&limit=10"
            },
            "next": {
                "href": "/api/v1/products/?page=1&limit=10"
            }
        },
        "_embedded": {
            "items": [
                {
                    "id": 1,
                    "code": "theme-mug-sku",
                    "average_rating": 4.5,
                    "main_taxon": {
                    },
                    "channels": {
                        "id": 1,
                        "code": "WEB",
                        "_links": {
                            "self": {
                                "href": "https://sylius.dev/api/v1/channels/1"
                            },
                        }
                    },
                    "availableOn": "017-01-16T11:44:53+0100",
                    "availableUntil": "017-01-16T11:44:53+0100",
                    "translations": {
                        "en_US": {
                            "id": 1,
                            "locale": "en",
                            "name": "Theme Mug",
                            "slug": "theme-mug"
                        }
                    },
                    "_links": {
                        "self": {
                            "href": "/api/v1/products/1"
                        },
                        "collection": {
                            "href": "/api/v1/products/"
                        },
                        "variants": {
                            "href": "/api/v1/products/1/variants/"
                        },
                        "reviews": {
                            "href": "/api/v1/products/1/reviews/"
                        },
                        "associations": {
                            "href": "/api/v1/products/1/associations/"
                        },
                        "images": {
                            "href": "/api/v1/products/1/images/"
                        },
                        "attributes": {
                            "href": "/api/v1/products/1/attributes/"
                        },
                        "options": {
                            "href": "/api/v1/products/1/options/"
                        },
                        "product_taxons": {
                            "href": "/api/v1/taxons/?productId=1"
                        }
                    }
                }
            ]
        }
    }
    ```

### Why like this? 
Because variants, associations and reviews can contain a lot of depending resources that should be paginated.

### What does it look like in other e-commerce systems?

 * [WooCommerce](http://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-product)
 * [Magento](http://devdocs.magento.com/swagger/index_20.html)
 * [Moltin](https://docs.moltin.com/products/)

## Related reading:
 * [Something about hypermedia](https://www.narwhl.com/hypermedia-linking/)
 * [Default hypermedia relation types](https://www.iana.org/assignments/link-relations/link-relations.xhtml)

**Comment by steffenbrem** [comment]
I wanted to mention this again since I think it is very important to have a proper JSON specification. It would be really good if Sylius uses the JSON-API (http://jsonapi.org) spec right from the beginning. When working with lots of relationships this spec really starts to shine. Read this for example: http://jsonapi.org/faq/#why-not-use-the-hal-specification. More and more APIs and client SDKs are using this spec and I feel it would empower the Sylius API greatly if implemented correctly.

If you guys are interested in this I could help supporting this spec pretty easily. There are lots of implementations of that spec already. Also I made a simplistic bundle that fully supports JSON-API serialisation (I use JMS internally). It is a very simple bundle without any tests and serves more as a proof of concept, although I use it successfully in production. If necessary I could further improve my own json-api bundle.

**Comment by lchrusciel** [comment]
@steffenbrem This one of concepts that I am considering right now, but wasn't too sure about that. It will make whole our api totally different to what we used to have. We will have to declare our own content type and handle versioning with it. I also haven't been aware of your solution.

But on the other hand a lot of links suggest to use it this way. As I have read, [orocrm](https://www.orocrm.com/blog/product-updates/new-oro-web-api-now-available) also decide to use this specification. I would be awesome if we shared a common specification with them. And following some common specification is probably wise decision.

I have to dig into it more deeply.

**Comment by lchrusciel** [comment]
@steffenbrem it would be really nice to have such a standard for our API, but for us it is not a way we can go. We have to support both xml and json. So probably it would be good opportunity to create a plugin, which will provide JSONAPI standard out-of-the-box. We will stay with current api format. The question is should we move collection and depending resources as a links, or just serialized arrays... Or how to determine which should go where. I still keep my proposal.

**Comment by steffenbrem** [comment]
@lchrusciel Regarding your issue with including or linking related resources. In my Sylius API I never fetch related objects when you for example call `GET /products/1`, but when you pass in the `include`_[1]_ parameter e.g. `GET /products/1?include=variants,attributes` it will sideload the related objects within the same request. This way you leave the API consumer with full control on how much data you would need.

In the current state of https://github.com/steffenbrem/JsonApiBundle it will do all that out of the box. It can handle pagination (Pagerfanta instances) and sideloaded resources perfectly. It would require almost no extra work to implement this in Sylius. You could still use XML serialisation without extra overhead since JsonApiBundle also uses JMS Serializer.

[1] http://jsonapi.org/format/#fetching-includes

This is my `Model.Product.yml` for example:
```yml
Mango\Component\Core\Model\Product:
    resource:
        type: ~ # same as "products" (pluralisation of the short class name)

    exclusion_policy: ALL

    virtual_properties:
        getName:
            serialized_name: name
        getDescription:
            serialized_name: description
        getShortDescription:
            serialized_name: short-description
        getSlug:
            serialized_name: slug

    properties:
        workspace: ~
        media: ~
        attachments: ~
        position: ~
        replenishable: ~

    relations:
        translations:
            includeByDefault: true
        variants:
            includeByDefault: true
        masterVariant:
            includeByDefault: true
        channels:
            showLinkRelated: true
        attributes:
            showLinkRelated: true
        options:
            showLinkRelated: true
        taxons:
            showLinkRelated: true
        media:
            showLinkRelated: true
        attachments:
            showLinkRelated: true
        associations:
            showLinkRelated: true
        shippingCategory: ~ # belongs to doesn't need links, the id is enough to fetch it
        mainTaxon: ~
```

I don't want to push Sylius into using JSON-API specifically, since it may be a big switch to make in the beta fase. But just some ideas to leave here, maybe it helps you in making a decision 😄 .
