### ISSUE TITLE
[Resources] Error when overriding form

### ISSUE THREAD

**Issue by PyRowMan** [Sylius/Sylius#7364]
Hey guys, i don't really know if it's a bug or just me doing it wrong, but as far as i read about it; it's not a normal behavior : 

I'm trying to add a virtual currency to the Currency form by interpreting theses docs to my needs :

http://sylius-try.readthedocs.io/en/latest/bundles/general/overriding_forms.html
http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/forms.html

After a time to struggle I found someone willing to do something similar here : http://stackoverflow.com/questions/34881358/sylius-resourcebundle-how-to-override-a-form-service

The issue was solved, but in my case, it doesn't work.

Here are the classes, configuration and error : 
```
namespace RiftBundle\Form\Type;

use \Symfony\Component\Form\Extension\Core\Type\CurrencyType as MainCurrencyType;


class CurrencyType extends MainCurrencyType
{
    /**
     * Currency loaded choice list.
     *
     * The choices are lazy loaded and generated from the Intl component.
     *
     * {@link \Symfony\Component\Intl\Intl::getCurrencyBundle()}.
     *
     * @var \Symfony\Component\Form\ChoiceList\ArrayChoiceList
     */
    private $choiceList;

    /**
     * {@inheritdoc}
     */
    public function loadChoiceList($value = null)
    {
        if (null !== $this->choiceList) {
            return $this->choiceList;
        }
        return $this->choiceList = new \Symfony\Component\Form\ChoiceList\ArrayChoiceList(array_flip(\RiftBundle\Intl\Intl::getCurrencyBundle()->getCurrencyNames()), $value);
    }
}
```

```
sylius_resource:
   drivers:
       - doctrine/orm
   resources:
       sylius.currency:
             classes:
                 model: '%sylius.model.currency.class%'
                 form: RiftBundle\Form\CurrencyType
```
```
services:
    sylius.form.type.currency:
        class: RiftBundle\Form\CurrencyType
        tags:
            - { name: form.type, alias: sylius_currency }
        arguments: ['%sylius.model.currency.class%', '%sylius.form.type.currency.validation_groups%']
```

and here is the error : 

> MappingException in MappingException.php line 96: Class 'Sylius\Component\Currency\Model\CurrencyInterface' does not exist

**Comment by TheMadeleine** [comment]
Hi.

1. http://docs.sylius.org/en/latest/customization/form.html These are the docs you should be following.
2. You are working with a wrong form type. `SyliusCurrencyBundle\Form\Type\CurrencyType` is the correct one to extend (to write an extension to).

**Comment by PyRowMan** [comment]
Hello @TheMadeleine Thank you for your answer :)

I have already tried to make an extension of the currency bundle, but I don't know at all were i should call the extended form and actually how :/

here is the part were i have extended the form : 

```
namespace RiftBundle\Form;

use Sylius\Bundle\ResourceBundle\Form\EventSubscriber\AddCodeFormSubscriber;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * @author Saša Stamenković <umpirsky@gmail.com>
 * @author Paweł Jędrzejewski <pawel@sylius.org>
 */
final class CurrencyTypeExtension extends \Symfony\Component\Form\AbstractTypeExtension
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->addEventSubscriber(new AddCodeFormSubscriber(\RiftBundle\Form\Type\CurrencyType::class, [
                'label' => 'sylius.form.currency.code',
                'choices' => \RiftBundle\Intl\Intl::getCurrencyBundle()->getCurrencyNames()
            ]))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getExtendedType()
    {
        return \Sylius\Bundle\CurrencyBundle\Form\Type\CurrencyType::class;
    }

}
```
```
services:
    rift.form.extension.type.currency:
            class: RiftBundle\Form\CurrencyTypeExtension
            tags:
                - { name: form.type_extension, extended_type: \Sylius\Bundle\CurrencyBundle\Form\Type\CurrencyType }
```

**Comment by TheMadeleine** [comment]
And @PyRowMan ? What happens when you do so? (just like above)

**Comment by PyRowMan** [comment]
@TheMadeleine Nothing :P

The form dosn't seem to be affected by the extension

**Comment by TheMadeleine** [comment]
Do you render the fields in twig?

**Comment by PyRowMan** [comment]
Yes, it is the default currency add form : http://demo.sylius.org/admin/currencies/new


But by digging, I found out that the field was generated automatically with a subscriber event ("PreSetData")

I followed every step of the symfony documentation (since extending a FormType is a symfony task....


But it doesn't work, the class is not interpreted


here is what i tried now : 
```
namespace RiftBundle\Form\Type;



class CurrencyTypeExtension extends \Symfony\Component\Form\AbstractTypeExtension
{
    /**
     * Currency loaded choice list.
     *
     * The choices are lazy loaded and generated from the Intl component.
     *
     * {@link \Symfony\Component\Intl\Intl::getCurrencyBundle()}.
     *
     * @var \Symfony\Component\Form\ChoiceList\ArrayChoiceList
     */
    private $choiceList;

    public function configureOptions(\Symfony\Component\OptionsResolver\OptionsResolver $resolver)
    {
        dump('Ohputain');
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    public function buildForm(\Symfony\Component\Form\FormBuilderInterface $builder, array $options)
    {
        dump('Ohputain');
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function finishView(\Symfony\Component\Form\FormView $view, \Symfony\Component\Form\FormInterface $form, array $options)
    {
        dump('Ohputain');
        parent::finishView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    public function buildView(\Symfony\Component\Form\FormView $view, \Symfony\Component\Form\FormInterface $form, array $options)
    {
        dump('Ohputain');
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function loadChoiceList($value = null)
    {
        dump('Ohputain');
        if (null !== $this->choiceList) {
            return $this->choiceList;
        }
        return $this->choiceList = new \Symfony\Component\Form\ChoiceList\ArrayChoiceList(array_flip(\RiftBundle\Intl\Intl::getCurrencyBundle()->getCurrencyNames()), $value);
    }

    public function getExtendedType()
    {
        return \Symfony\Component\Form\Extension\Core\Type\CurrencyType::class;
    }
}
```
```

services:
    rift.currency_type_extension:
        class: RiftBundle\Form\Type\CurrencyTypeExtension
        tags:
            - { name: form.type_extension, extended_type: \Symfony\Component\Form\Extension\Core\Type\CurrencyType, priority: 1 }
```

With this i was expecting to make an extension of the Basic CurrencyType of symfony used in the Sylius\Bundle\CurrencyBundle\Form\Type\CurrencyType on line 31 here is the class : 

```
namespace Sylius\Bundle\CurrencyBundle\Form\Type;

use Sylius\Bundle\ResourceBundle\Form\EventSubscriber\AddCodeFormSubscriber;
use Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\CurrencyType as SymfonyCurrencyType;

/**
 * @author Saša Stamenković <umpirsky@gmail.com>
 * @author Paweł Jędrzejewski <pawel@sylius.org>
 */
final class CurrencyType extends AbstractResourceType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->addEventSubscriber(new AddCodeFormSubscriber(SymfonyCurrencyType::class, [
                'label' => 'sylius.form.currency.code',
            ]))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'sylius_currency';
    }
}
```

Not one of the dumps are showing up :/


I'm like really sad now :P

**Comment by PyRowMan** [comment]
Thanks to @lchrusciel here is the solution : 

Make a whole new CurrencyType Form by doing this : 

```
namespace RiftBundle\Form;

use Sylius\Bundle\ResourceBundle\Form\EventSubscriber\AddCodeFormSubscriber;
use Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType;
use Symfony\Component\Form\FormBuilderInterface;


final class CurrencyType extends AbstractResourceType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->addEventSubscriber(new AddCodeFormSubscriber(\RiftBundle\Form\Type\CurrencyType::class, [
                'label' => 'sylius.form.currency.code',
            ]))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'sylius_currency';
    }

    public function getName()
    {
        return 'sylius_currency';
    }

}
```
Which is using your first CurrencyType Type : 

```
namespace RiftBundle\Form\Type;

use \Symfony\Component\Form\Extension\Core\Type\CurrencyType as MainCurrencyType;


class CurrencyType extends MainCurrencyType
{
    /**
     * Currency loaded choice list.
     *
     * The choices are lazy loaded and generated from the Intl component.
     *
     * {@link \Symfony\Component\Intl\Intl::getCurrencyBundle()}.
     *
     * @var \Symfony\Component\Form\ChoiceList\ArrayChoiceList
     */
    private $choiceList;

    /**
     * {@inheritdoc}
     */
    public function loadChoiceList($value = null)
    {
        if (null !== $this->choiceList) {
            return $this->choiceList;
        }
        return $this->choiceList = new \Symfony\Component\Form\ChoiceList\ArrayChoiceList(array_flip(\RiftBundle\Intl\Intl::getCurrencyBundle()->getCurrencyNames()), $value);
    }
}
```

Then configure it in the services : 

```
rift.form.type.currency:
        class: RiftBundle\Form\CurrencyType
        tags:
            - { name: form.type }
        arguments: ['%sylius.model.currency.class%', '%sylius.form.type.currency.validation_groups%']
```

And finaly declare it in your config.yml by doing so : 

```
sylius_currency:
    resources:
        currency:
            classes:
                form: RiftBundle\Form\CurrencyType
```
