### ISSUE TITLE
pre_create  & pre_update events are not triggered for product_variant

### ISSUE THREAD

**Issue by brunocombodo** [Sylius/Sylius#7443]
Hello, 
as I posted on [slack](https://sylius-devs.slack.com/archives/support/p1486479882004478), 
it seems that the pre_create  & pre_update events are not triggered for product_variant.
I tested with this service : 

```yaml
  app.listener.compressed_file_upload_listener:
      class: AppBundle\EventListener\CompressedFileUploadListener
      arguments: ['@app.compressed_file_uploader']
      tags:
          - { name: kernel.event_listener, event: sylius.product_variant.pre_create, method: uploadCompressedFile }
          - { name: kernel.event_listener, event: sylius.product_variant.pre_update, method: uploadCompressedFile }

          ##debug temp!!!!!!
          - { name: kernel.event_listener, event: sylius.product.pre_create, method: uploadCompressedFile }
          - { name: kernel.event_listener, event: sylius.product.pre_update, method: uploadCompressedFile }
          ##end of debug temp!!!
```
the product trigger the event, but not the product_variant.
