### ISSUE TITLE
Adding translations to Sylius entities

### ISSUE THREAD

**Issue by DmitriyTrt** [Sylius/Sylius#7496]
I'm trying to add a translation class to the `Sylius\Component\Addressing\Model\Zone` with some custom fields. In order to achieve it I've added the following to my app/config/config.yml:
```
sylius_addressing:
    resources:
        zone:
            classes:
                model: AppBundle\Entity\Zone
            translation:
                classes:
                    model: AppBundle\Entity\ZoneTranslation
```
And I get an exception:
```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
Unrecognized option "translation" under "sylius_addressing.resources.zone"
```

It doesn't seem to be possible due to the configuration tree defined by Addressing bundle without a `translation` child.

Is there a different way to add a translation support? Or is it maybe possible to modify configuration definition of a bundle from the application level?
