### ISSUE TITLE
grid action type links : the customization fail

### ISSUE THREAD

**Issue by brunocombodo** [Sylius/Sylius#7529]
Hello,

I'm triing to customize the sylius_admin_product grid.

when I try this : 
```yml
sylius_grid:
    grids:
        sylius_admin_product:
            actions:
                main:
                    create:
                        options:
                            visible: false
```
and add `{% dump %}` in the `UiBundle/Resources/views/Grid/Action/links.html.twig`, I've got this result : 
![image](https://cloud.githubusercontent.com/assets/22890131/23018886/0a5ad13e-f440-11e6-85ed-df4d1ba2e43b.png)

the node `0 => false` under the `option` node represent the yaml `visible: false` => instead of using my string as key, it insert my modification with a numerical key.

(I use the beta 1)
