### ISSUE TITLE
[Checkout] Shipping/ShippingTax Adjustments in the cart

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#7551]
Hi,
Is it possible to have no shipping adjustment (_and no related shipping tax adjustment too_) in the first step of the checkout (cart) ?

It's really confusing for the customers to see a shipping method price when they have not selected any shipping method yet. Hiding the shipping price in the cart _does not work_ since tax is applied to the shipping price, and thus the total tax price is wrong if we hide the shipping price.

Any idea ?
Thanks !

**Comment by michalmarcinkowski** [comment]
@tchapi you can override the `DefaulShippingMethodResolver` and just throw `UnresolvedDefaultShippingMethodException`.  Then it should not assign the default shipping to the cart.

**Comment by tchapi** [comment]
Ok thanks, I'll try that asap !

**Comment by tchapi** [comment]
Is the following correct ? It looks like my custom resolver is never called, maybe I skipped a step :

```
    my_web.shipping.no_shipping_method:
        class: My\WebBundle\Shipping\MyNoShippingMethodResolver
        tags:
            - { name: sylius.shipping_method_resolver, type: default, label: Default }
```

```
<?php
namespace My\WebBundle\Shipping;

use Sylius\Component\Shipping\Exception\UnresolvedDefaultShippingMethodException;
use Sylius\Component\Shipping\Model\ShipmentInterface;
use Sylius\Component\Shipping\Repository\ShippingMethodRepositoryInterface;

final class MyNoShippingMethodResolver implements DefaultShippingMethodResolverInterface
{
    public function getDefaultShippingMethod(ShipmentInterface $shipment)
    {
        throw new UnresolvedDefaultShippingMethodException();
    }
}
```

Thanks again !

**Comment by michalmarcinkowski** [comment]
Try this definition:
```yaml
sylius.resolver.default_shipping_method:
    class: My\WebBundle\Shipping\MyNoShippingMethodResolver
```

**Comment by tchapi** [comment]
Yeah, works better with you fix, but then It prevents me from selecting the shipping method later in the checkout process. Ultimately, this seems the correct way to do :

```php
<?php

namespace My\WebBundle\Shipping;

use Sylius\Component\Shipping\Exception\UnresolvedDefaultShippingMethodException;
use Sylius\Component\Shipping\Model\ShipmentInterface;
use Sylius\Component\Shipping\Repository\ShippingMethodRepositoryInterface;
use Sylius\Component\Shipping\Resolver\DefaultShippingMethodResolverInterface;
use Sylius\Component\Core\OrderCheckoutStates;

final class MyNoShippingMethodResolver implements DefaultShippingMethodResolverInterface
{
    /**
     * @var ShippingMethodRepositoryInterface
     */
    private $shippingMethodRepository;

    /**
     * @param ShippingMethodRepositoryInterface $shippingMethodRepository
     */
    public function __construct(ShippingMethodRepositoryInterface $shippingMethodRepository)
    {
        $this->shippingMethodRepository = $shippingMethodRepository;
    }

    public function getDefaultShippingMethod(ShipmentInterface $shipment)
    {
        if ($shipment->getOrder()->getCheckoutState() == OrderCheckoutStates::STATE_CART) {
            throw new UnresolvedDefaultShippingMethodException();
        }

        $channel = $shipment->getOrder()->getChannel();

        $shippingMethods = $this->shippingMethodRepository->findEnabledForChannel($channel);
        if (empty($shippingMethods)) {
            throw new UnresolvedDefaultShippingMethodException();
        }
        
        return $shippingMethods[0];
    }
}
```

With 

```yaml
    sylius.resolver.default_shipping_method:
        class: My\WebBundle\Shipping\MyNoShippingMethodResolver
        arguments:
            - "@sylius.repository.shipping_method"
```
