### ISSUE TITLE
Can't override Channel-Model from AppBundle

### ISSUE THREAD

**Issue by psren** [Sylius/Sylius#7579]
Hey there. I'm not quite sure if this is a bug in the code, a bug in the [Documentation](http://docs.sylius.org/en/latest/customization/model.html) or I failed :-D

I want to override Channel from my app.

I created an entity

```php
<?php

namespace AppBundle\Entity;

class Channel extends \Sylius\Component\Core\Model\Channel
{

    private $location = null;

    /**
     * @return null
     */
    public function getLocation()
    {
        return $this->location;
    }

    /**
     * @param null $location
     */
    public function setLocation($location)
    {
        $this->location = $location;
    }

}
```

Then i places my mapping-file

```yaml
# src/AppBundle/Resources/config/doctrine/Channel.orm.yml
AppBundle\Entity\Channel:
    type: entity
    table: sylius_channel
    fields:
        location:
            class: AppBundle\Entity\Location
            nullable: true
```

Location-Model and Mapping exists, but I leave that out here because I don't think it's relevant for this issue.

Following the "Tutorial" I want to update my database.

```sh
bin/console doctrine:migrations:diff
```

But the command throws:

```
[Doctrine\DBAL\Schema\SchemaException]                            
  The table with name 'apomile_dev.sylius_channel' already exists.
```

which is obviously correct. But shouldn't it update that table, since the original Channel I'm extending from is a MappedSuperClass?
