### ISSUE TITLE
[CoreBundle] Cannot be used without ApiBundle

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#7581]
`CoreBundle\Resources\config\app\config.yml` contains:
```yml
fos_rest:
    body_listener:
        array_normalizer: sylius.normalizer.camel_keys
```

The `sylius.normalizer.camel_keys` service is defined by ApiBundle.

Edit: Whoops, just saw a PR that will fix this (https://github.com/Sylius/Sylius/pull/7556). Will keep ticket open until PR is merged.
