### ISSUE TITLE
index route throws Rout Not Found Exception

### ISSUE THREAD

**Issue by samanmohamadi** [Sylius/Sylius#7658]
I created a resource named article and  added a route for  indexing articles in frontend:
```
app_article_index:
    path: /articles
    methods: [GET]
    defaults:
        _controller: app.controller.article:indexAction
        _sylius:
            template:  AppBundle:Article:index.html.twig
```
Route is visible in debug:
```
]$ php bin/console debug:router | grep articles

  app_article_index                                    GET             ANY      ANY    /articles                                                                 
  app_admin_article_index                              GET             ANY      ANY    /admin/articles/                                                          
  app_admin_article_create                             GET|POST        ANY      ANY    /admin/articles/new                                                       
  app_admin_article_update                             GET|PUT|PATCH   ANY      ANY    /admin/articles/{id}/edit                                                 
  app_admin_article_show                               GET             ANY      ANY    /admin/articles/{id}                                                      
  app_admin_article_delete                             DELETE          ANY      ANY    /admin/articles/{id} 
```

But when I visit **/articles** I get This :

> No route found for "GET /articles/"

changing path from /articles to anything else (like /articles1) works without problem.
```
app_article_index:
    path: /articles1
    methods: [GET]
    defaults:
        _controller: app.controller.article:indexAction
        _sylius:
            template:  AppBundle:Article:index.html.twig
```

> /articles1 --> show list of articles

**Comment by pjedrzejewski** [comment]
I think it has to do with the ``/`` at the end of the path you tried to access.

**Comment by samanmohamadi** [comment]
Thanks @pjedrzejewski Adding the `/` to end of the path solved the problem.
```
app_article_index:
    path: /articles/
    methods: [GET]
    defaults:
        _controller: app.controller.article:indexAction
        _sylius:
            template:  AppBundle:Article:index.html.twig
```
