### ISSUE TITLE
Documentation for grid sorting is incomplete

### ISSUE THREAD

**Issue by mvar** [Sylius/Sylius#7794]
Configuration example from the current documentation:

```yml
# app/config/grids/admin/supplier.yml
sylius_grid:
    grids:
        app_admin_supplier:
                ...
            sorting:
                name: asc
                ...
```

I have set up my grid like this:

```yml
sylius_grid:
    grids:
        foo:
            driver:
                name: doctrine/orm
                options:
                    class: Foo
            fields:
                id:
                    type: string
                ...
            sorting:
                id: desc
```

And I get exception about invalid SQL query:

```
[3/3] Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 57 near 'desc': Error: Class Foo has no field or association named desc").

[2/3] QueryException: [Semantical Error] line 0, col 57 near 'desc': Error: Class Foo has no field or association named desc

[1/3] QueryException: SELECT o FROM Foo o ORDER BY o. desc
```

As you can see, SQL query does not have a name of field by which I'm trying to sort. Following examples in Sylius code I have figured out that I need to configure `sortable`:

```yml
            fields:
                id:
                    type: string
                    sortable: ~
```

First, documentation could inform about `sortable`. Second, it would be nice to get error about invalid configuration, not about failing query.

Sylius version: v1.0.0-beta.1
