### ISSUE TITLE
[SyliusResourceBundle]: Call to a member function addPrefix() on null

### ISSUE THREAD

**Issue by nietzscheson** [Sylius/Sylius#7799]
I'm using SyliusResources v1.0.0-beta.1 on Symfony 3.2. I followed the [documentation](http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/) to create resources. All good, even when I have needed to exclude some of the routes of the resource:
```yml
app_admin_user:
    resource: |
        alias: app.user
        section: admin
        except: ['delete', 'update']
        redirect: update
    type: sylius.resource
```
It throws me the following:
```
FatalThrowableError in YamlFileLoader.php line 148:
Call to a member function addPrefix() on null```
