### ISSUE TITLE
[BC Break] Unify naming of tag attributes

### ISSUE THREAD

**Issue by mvar** [Sylius/Sylius#7838]
Current Sylius configuration:

```yml
services:
    foo.grid.filter.bar:
        class: FooBundle\Grid\Filter\BarFilter
        tags:
            -
                name: sylius.grid_filter
                type: bar
                form-type: 'FooBundle\Form\Type\Filter\BarType'
```

Please note `form-type`.

In Symfony all attributes follows underscore naming convention. As Sylius is highly dependent on Symfony, it would be nice to see the same coding style too. I suggest to find and replace all similar places before first RC.
