### ISSUE TITLE
Template events throw UndefinedOptionsException

### ISSUE THREAD

**Issue by Persata** [Sylius/Sylius#7871]
Hello all,

I noticed when trying to utilise the recently added Sonata events for customising templates that those events which pass extra data, e.g. the `resource` here:

```
{{ sonata_block_render_event('sylius.admin.order.show.after_summary', {'resource': resource}) }}
```

will throw an `UndefinedOptionsException` because those keys are not permitted:

```
error while resolving options - The option "resource" does not exist. Defined options are: "attr", "extra_cache_keys", "template", "ttl", "use_cache".
```

This causes the default Sonata template to be rendered instead of the custom template you have specified.

I've come across two possible solutions so far:

### 1 - Add Sonata `blocks_by_class` settings to `config.yml`

The Sonata bundle has a compiler pass for adding allowed options to the block rendering service. Adding the following in `config.yml` will allow the settings to be passed through and used in the template:

```
sonata_block:
    blocks_by_class:
        Sonata\BlockBundle\Model\Block:
            settings:
                form: ~
                taxon: ~
                order_item: ~
                cart: ~
                customer: ~
                statistics: ~
                order: ~
                orders: ~
                product_review: ~
                product_reviews: ~
                product: ~
                products: ~
                resource: ~
                resources: ~
                address: ~
                addresses: ~
```

I believe that covers all the various objects passed into the template events. The objects can then be accessed via the `settings` key inside your custom template, e.g.

```
{{ settings.order_item.variant.product.name }}
```

We would need to let users know that if they are creating their own custom template events then any data passed into them will need to be added to to the above list on their project.

### 2 - Use the `attr` key

Credit for this goes to @kurakin-oleksandr. The `attr` key of the settings object could be used instead, passing objects in like this:

```
{{ sonata_block_render_event('sylius.admin.order.show.after_summary', {'attr': {'resource': resource}}) }}
```

and then can be accessed inside your template like so:

```
{{ settings.attr.order_item.variant.product.name }}
```

This would require that all the current events in the templates be redone to use the `attr` key, and documentation updated to let users know to use the `attr` key for their own events.

Any thoughts or alternative solutions?

**Comment by pjedrzejewski** [comment]
@Persata Thanks for reporting this! The problem with solution 1. is that it would need to be configured for all block types (block classes). :/ Second one is nice, but requires reworking all templates and also can be a bit annoying to have this extra ``attr`` reference.

@GSadee How did it work with ``resource`` for you without this configuration?

**Comment by GSadee** [comment]
@pjedrzejewski unfortunately I didn't test that with a `resource` attribute 😞

**Comment by Persata** [comment]
@pjedrzejewski No problem!

Wouldn't it just need to be configured for `Sonata\BlockBundle\Model\Block` since that's the class that's always instantiated inside Sylius's `Sylius\Bundle\UiBundle\Block\BlockEventListener` class?

If that's not suitable, an alternative to option 1 would be to use Sonata's `settingsByType` instead of `settingsByClass`, so the config would look like this:

```
sonata_block:
    blocks:
        sonata.block.service.template:
            settings:
                form: ~
                taxon: ~
                order_item: ~
                cart: ~
                customer: ~
                statistics: ~
                order: ~
                orders: ~
                product_review: ~
                product_reviews: ~
                product: ~
                products: ~
                resource: ~
                resources: ~
                address: ~
                addresses: ~
```

It adds those setting keys to any block with type `sonata.block.service.template`, which is hardcoded into the `\Sylius\Bundle\UiBundle\Block\BlockEventListener::onBlockEvent` method.

I've verified this works correctly also.
