### ISSUE TITLE
Template events do not render properly

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#7872]
I'm trying to load a template:

```
    app.block_event_listener.sylius.shop.product.show.after_price:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@App/delivery_week.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.after_price, method: onBlockEvent }
```

Template exists in `src/AppBundle/Resources/views/delivery_week.html.twig` with a single `<div>` in it.

Output in the frontend: 

```
Sonata Block Template

If you want to use the sonata.block.template block type, you need to create a template :
{# file: 'MyBundle:Block:my_block_feature_1.html.twig' #}
{% extends sonata_block.templates.block_base %}

{% block block %}
    <h3>The block title</h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel turpis at lacus
        vehicula fringilla at eu lectus. Duis vitae arcu congue, porttitor nisi sit amet,
        mattis metus. Nunc mollis elit ut lectus cursus luctus. Aliquam eu magna sit amet
        massa volutpat auctor.
    </p>
{% endblock %}
And then call it from a template with the sonata_block_render helper:
{{ sonata_block_render({ 'type': 'sonata.block.service.template' }, {
    'template': 'MyBundle:Block:my_block_feature_1.html.twig',
}) }}
```

I think I followed the instructions from http://docs.sylius.org/en/latest/customization/template.html#how-to-use-template-events-for-customizations exactly..
