### ISSUE TITLE
Display / edit soft deleted resources in backend

### ISSUE THREAD

**Issue by jjanvier** [Sylius/Sylius#79]
Soft deleted resources should surely be displayed in the backend (like products for example).

Here are my thoughts :
- adding a new parameter (for example `getSoftDeletedResources`) to `ResourceBundle\Controller\Configuration`
- retrieving it in the `indexAction` and `updateAction` methods of `ResourceBundle\Controller\ResourceBundle\Controller`

``` php
$getSoftDeletedResources = $config->get('getSoftDeletedResources', false);
```
- disabling it before getting resources

``` php
if ($getSoftDeletedResources) {
    $this->getManager()->getFilters()->disable('softdeleteable');
}
 // get ressources
```
- re enabling it after getting resources

``` php
if ($getSoftDeletedResources) {
    $this->getManager()->getFilters()->enable('softdeleteable');
 }
```
- configuring the listing of product backend

``` yaml
sylius_backend_product_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Product:index.html.twig
            method: createFilterPaginator
            arguments: [$criteria, $sorting, $getSoftDeletedResources]
        criteria: {}
        sorting: { createdAt: desc }
        getSoftDeletedResources: {true}
```

I have not tested yet but I think this can work. However if I really don't know if it's good way to do. I'll code it if you find it valid.
