### ISSUE TITLE
skip shipping and payement problems

### ISSUE THREAD

**Issue by bruno-ds** [Sylius/Sylius#7943]
Hello,

I use both your new features [skip shipping](https://github.com/Sylius/Sylius/pull/7276) and [skip payement](https://github.com/Sylius/Sylius/pull/7031).

(I don't know if you prefer that I put the comment grouped here or use some other way, so please tell me if I'm doing wrong)

here are the issues I encountered  : 
# 1. as said in the original issue [#7215](https://github.com/Sylius/Sylius/issues/7215#issuecomment-294118756) : 

> - if the shipping is skipped, the address step still ask for the shipping address, it should only ask for the billing address. (it could be simpler for you to invert the two steps)
> - if either the shipping and the payement steps are going to be skipped, no address at all should be asked (this is subject to discussion, but in our shop, we decided to go that way)

# 2. the order state remain "new" instead of becoming fulfilled
when an order skip both shipping and payement, its state do not change : it remain "new"
PS : I tested also with just skipping the shipping, the problem still occurs.

it is **really important** since this break this kind of custom logic and I don't see a workaround : 
```yaml
  sylius_order:
    callbacks:
      after:
        app_store_order_complete:
          on: ["fulfill"]
          do: ["@app.event_listener.order_state_machine", "onOrderStateMachineStateComplete"]
          args: ["object"]
```

# 3. when you skip the paiement, 
the state remain "awaiting_payment", it should be "payment_skipped" (I'm not the only on to think that : https://github.com/Sylius/Sylius/pull/7031#issuecomment-271103631)

# 4. same for the shipping, 
the state should become "shipping_skipped", in addition, this state is missing in `Sylius\Component\Core\OrderCheckoutStates`
