### ISSUE TITLE
[ResourceBundle] | Using a Custom Criteria

### ISSUE THREAD

**Issue by nietzcheson** [Sylius/Sylius#7958]
I'm use SyliusResourceBundle in other project. Out to Sylius. And I'want do the following: 

I have two entities: User | Book

```yml

AppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        user:
            type: string
        years:
            type: integer
            length: 23

AppBundle\Entity\Book:
    type: entity
    table: book
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        book:
            type: string
    oneToOne:
        user:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
```
I created the resources for the entities:

```yml
sylius_resource:
    drivers:
        - doctrine/orm

    resources:
        app.user:
            classes:
                model: AppBundle\Entity\User

        app.book:
            classes:
                model: AppBundle\Entity\Book
```
And her routes.
```yml
app_user:
    resource: |
        alias: app.user
        section: admin
        path: user
        except: ['delete', 'show']
    type: sylius.resource
    prefix: /admin

app_book:
    resource: |
        alias: app.book
        section: admin
        path: book
        except: ['delete', 'show']
    type: sylius.resource
    prefix: /admin
```
Book has a relationship with User:
```yml
app_user_book:
    resource: |
        alias: app.book
        section: admin
        path: book
        criteria:
            user: $userId
        except: ['delete', 'show']
    type: sylius.resource
    prefix: /admin
```
The result the all this is:
```console
  app_admin_user_index                GET|ANY|ANY /admin/user/
  app_admin_user_create              GET|POST|ANY|ANY| /admin/user/new
  app_admin_user_update             GET|PUT|PATCH|ANY|ANY /admin/user/{id}/edit
  app_admin_book_index               GET|ANY|ANY /admin/book/
  app_admin_book_create             GET|POST|ANY|ANY| /admin/book/new
  app_admin_book_update            GET|PUT|PATCH|ANY|ANY /admin/book/{id}/edit
```
The routes for relationship user | book do'nt work. Any solution?

For all this I follow the this part to the [doc](http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/routing.html#using-a-custom-criteria)

**Comment by lchrusciel** [comment]
You probably want something like this:
```ymlapp_book:
    resource: |
        alias: app.book
        section: admin
        path: {$userId}/books
        criteria:
            user: $userId
        except: ['delete', 'show']
    type: sylius.resource
    prefix: /admin
```
