### ISSUE TITLE
Extend AdminUser Model

### ISSUE THREAD

**Issue by craphunter** [Sylius/Sylius#7975]
Hi!

I do also have a problem to extend Core Model. I want to extend the AdminUser table. I want to add `dealer_id`.

My:  src/AppBundle/Resources/config/doctrine/AdminUser.orm.yml

```
 AppBundle\Entity\AdminUser:
     type: entity
     table: sylius_admin_user
     fields:
         dealerId:
             type: integer
             nullable: true
```

My:  src/AppBundle/Entity/AdminUser.php

```
<?php

namespace AppBundle\Entity;

use Sylius\Component\Core\Model\AdminUser as BaseAdminUser;

class AdminUser extends BaseAdminUser
{
    /**
     * @var bool
     */
    private $dealerId;

    /**
     * @return bool
     */
    public function getDealerId()
    {
        return $this->dealerId;
    }

    /**
     * @param bool $dealerId
     */
    public function setDealerId($dealerId)
    {
        $this->dealerId = $dealerId;
    }
}
```

And last but not least...how it is in your documentation:
My:  app/config/config.yml 

```
doctrine:
    orm:
        mappings:
            AppBundle: ~
    dbal:
        driver: pdo_mysql
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8
        schema_filter: /^extension_sylius_dealer/

sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: AppBundle\Entity\AdminUser
```

I get the error message when I want to do the command:

`php bin/console doctrine:schema:update --force`

My error message:

```
[PDOException]                                                                                     
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'sylius_admin_user' already exists 
```

What do I do wrong?

Is there a huge lack in the documentation? Or don't you can extend it?

PS: Very nice thing the sylius!!! Good job!
