### ISSUE TITLE
[ResourceBundle] | Related Resources | Grids 

### ISSUE THREAD

**Issue by nietzscheson** [Sylius/Sylius#7976]
I have 3 entities: accounts, users, accountUsers

The account grid looks like this: [Account Grid](https://drive.google.com/file/d/0B9n4AHO2-JjTek94RWkwcnJ5cVE/view?usp=sharing)

When I am in the grid of the users of the account the route does not work.

I have users but their actions do not work: /admin/account/{account}/user/new. Appears as: /admin/ users/new?Account=1

```yml

#account grid

sylius_grid:
    grids:
        app_admin_account:
            driver:
                name: doctrine/orm
                options:
                    class: "%app.entity.account.class%"
            fields:
                account:
                    type: string
                    label: Account
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                subitem:
                    users:
                        type: links
                        label: Users
                        options:
                            links:
                                index:
                                    label: Users
                                    route: app_admin_account_user_index
                                    parameters:
                                        account: resource.id
                                create:
                                    label: Create
                                    route: app_admin_account_user_create
                                    parameters:
                                        account: resource.id


            filters:
                account:
                    type: string
```
```yml
#account_user grid

sylius_grid:
    grids:
        app_admin_account_user:
            driver:
                name: doctrine/orm
                options:
                    class: "%app.entity.user.class%"
                    repository:
                        method: createQueryBuilderAccountUsers
                        arguments: [$account]
            fields:
                username:
                    type: string
                    label: Username
                    sortable: true
                email:
                    type: string
                    label: Email
            actions:
                main:
                    create:
                        type: create
                        options:
                            link:
                                parameters:
                                    account: $account
                item:
                    update:
                        type: update
                        options:
                            link:
                                parameters:
                                    id: resource.id
                                    account: $account
                    delete:
                        type: delete

            filters:
                username:
                    label: Username
                    type: string
                email:
                    type: string
```
The routing:

```yml
#account
app_admin_account_user:
    resource: "@AppBundle/Resources/config/routing/admin/account/user.yml"
    prefix:   /accounts/{account}/users/

app_admin_account:
    resource: |
        alias: app.account
        section: admin
        templates: AppBundle:Crud
        except: ['show']
        redirect: update
        grid: app_admin_account
    type: sylius.resource
```
```yml
#account/user
app_admin_account_user_index:
    path: /
    methods: [GET]
    defaults:
        _controller: app.controller.user:indexAction
        _sylius:
            template: "@App/Crud/index.html.twig"
            grid: app_admin_account_user
            section: admin
            permission: true
            vars:
                route:
                    parameters:
                        account: $account

app_admin_account_user_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: app.controller.user:createAction
        _sylius:
            factory:
                method: createForAccount
                arguments:
                  - expr:notFoundOnNull(service('app.repository.account').find($account))
            template: "@App/Crud/create.html.twig"
            grid: app_admin_account_user
            section: admin
            redirect:
                route: app_admin_account_user_index
                parameters: { account: $ac!ount }
            permission: true
```
When I debug the template throws me: [Account User Grid](https://drive.google.com/file/d/0B9n4AHO2-JjTX2EtaF96OG9KaGM/view?usp=sharing)

**Comment by nietzcheson** [comment]
I do not want to close this issue because I think it should be taken into account to improve the documentation of the bundle, since it is not clear enough.

My solution for this case:

I could solve it and it was:
Due to the need of the project (and for my own things) I had to organize the routes in a certain way:

In:

Resources / config:

```yml
routing/
- admin/
    account/
	 - user.yml
  - user.yml
  - account.yml
- admin.yml
routing.yml
```
Account.yml and user.yml within admin belong to the admin section:
```yml
- app_admin_user:
     resource: |
         alias: app.user
         section: admin

- app_admin_account:
     resource: |
         alias: app.account
         section: admin
```

The same value of the section was being passed to user.yml in account /. The only thing I had to do was change admin by admin_account:

```yml
- _sylius:
	template: "@App/Crud/index.html.twig"
	grid: app_admin_account_user
	section: admin_account
```
Everything works.
