### ISSUE TITLE
[ResourceBundle] Route criteria not working

### ISSUE THREAD

**Issue by bpolaszek** [Sylius/Sylius#7986]
Hi there,

When using *SyliusResourceBundle* as a standalone, there's a feature which allows filtering based on a route parameter, i.e.:
``` 
/author/{authorId}/books
```
> which should filters books for _this_ `{authorId}`.

To achieve this, the routing must be configured as follows:
```yml
app_book:
    resource: |
        alias: app.book
        path: /authors/{authorId}/books
        criteria:
            author: $authorId
    type: sylius.resource_api
```

This feature currently does not work: books are not filtered.
Try my [sample app](https://github.com/bpolaszek/SyliusResourceBundleExample) to reproduce the bug.

**Comment by Zales0123** [comment]
According to [default implementation](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourcesResolver.php#L34) criteria from request configuration are applied only if there is `filterable` parameter set... However, I'm not sure is it possible to set this argument while routing generation. Therefore it's a bug indeed ;)

**Comment by lchrusciel** [comment]
It is not an issue. Criteria section just helps you to gather resource based on that data(e.g. code instead of id), not filter the results. If you need such a logic try to use [route parameters](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/product_variant.yml#L12-L15). It was also mentioned in this PR #7976

**Comment by misterx** [comment]
You can set default option for filtering

```
sylius_resource:
    settings:
        filterable: true
    resources:
       app.book: .....


```
