### ISSUE TITLE
How to extend admin CSS and JS with own code?

### ISSUE THREAD

**Issue by DmitriyTrt** [Sylius/Sylius#8002]
Is there an expected way for third-party developers to add some code to the admin.css and admin.js files generated by Gulp that are included into the admin pages? Don't see an easy way to achieve it and docs say nothing.

**Comment by stefandoorn** [comment]
I added my own Gulpfile to my AppBundle and did whatever required in there (or just put them in Resources/public and install the assets..). From the base Gulpfile (in the root) I added to run my own Gulpfile next to the shop & admin Gulpfiles. 

Then override the layout of Admin to load your additional CSS/JS.

**Comment by DmitriyTrt** [comment]
Thanks for details! I did the same on the previous project, but it looks like a workaround without proper versioning and we also have to deliver 2 files instead of merging everything into a single one. Looks like the only possible way is to completely ignore Gulpfile from the Admin bundle and write our own aggregating everything with custom code together. And add versioning query parameter somehow...

**Comment by stefandoorn** [comment]
Another option is to disable the default Admin Gulp run (in the root Gulpfile.js) & then copy paste it to your own project (the admin one) & adjust according to your needs. This allows you easily to merge the default admin css/js & your project files I think. Then in the root Gulpfile.js you point to your own version.

Biggest downside are Sylius upgrades, but that should be fairly easy to figure out between versions.

**Comment by wadjeroudi** [comment]
@DmitriyTrt Best way should be to add a new generated file in Gulpfile like @stefandoorn said but for the layout admin, you don't need to override anymore.
You can use the sonata block event to add your javascripts  (or css):
http://docs.sylius.org/en/latest/customization/template.html#how-to-use-template-events-for-customizations

Example for javascripts block in admin layout:
```yaml
services:
    app.block_event_listener.admin.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - 'Admin/javascripts.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.layout.javascripts, method: onBlockEvent }
```
