### ISSUE TITLE
[ResourceBundle] API cannot create entity with relation ManyToOne

### ISSUE THREAD

**Issue by Lubricat** [Sylius/Sylius#8018]
Hello,

I have two connected entities User and Gender.
```
class User implements ResourceInterface
{
    /**
     * @var int
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="first_name", type="string", length=255)
     */
    private $firstName;

    /**
     * @var string
     * @ORM\Column(name="last_name", type="string", length=255)
     */
    private $lastName;
    
    /**
    * @ORM\ManyToOne(targetEntity="UserBundle\Entity\Gender")
    * @ORM\JoinColumn(nullable=false)
    * @var UserBundle\Entity\Gender
    */
    private $gender;
    /// Getters / Setters
}

class Gender implements ResourceInterface
{
    /**
     * @var int
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="gender_type", type="string", length=255)
     */
    private $genderType;
    /// Getters / Setters
}
```
I have configured the bundle this way:
```
// app/config/config.yml
fos_rest:
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: 'json', prefer_extension: false }
sylius_resource:
    resources:
        app.user:
            classes:
                model: UserBundle\Entity\User
        app.gender:
            classes:
                model: UserBundle\Entity\Gender

// app/config/routing.yml
app_user:
    resource: |
        alias: app.user
    type: sylius.resource_api
app_gender:
    resource: |
        alias: app.gender
    type: sylius.resource_api

```

And the routes app_user_index, app_user_update, app_user_show, app_user_delete work perfectly but the app_user_create always return the 
```
{
"code": 500,
"message": "The option "property" does not exist. Defined options are: "action", "allow_extra_fields", "attr", "auto_initialize", "block_name", "by_reference", "choice_attr", "choice_label", "choice_loader", "choice_name", "choice_translation_domain", "choice_value", "choices", "choices_as_values", "class", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "disabled", "em", "empty_data", "error_bubbling", "error_mapping", "expanded", "extra_fields_message", "group_by", "id_reader", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "mapped", "method", "multiple", "placeholder", "post_max_size_message", "preferred_choices", "property_path", "query_builder", "required", "translation_domain", "trim", "upload_max_size_message", "validation_groups"."
 }
```
unless I delete the variable $gender from the user object. May I miss something or there is a bug with relations ?

Thank you :)

PS: The API works well for the _create route with genders object.
