### ISSUE TITLE
criteria ignored 

### ISSUE THREAD

**Issue by samanmohamadi** [Sylius/Sylius#8061]
```
app_shop_blog_index:
    path: /
    methods: [GET]
    defaults:
        _controller: app.controller.blog:indexAction
        _sylius:
            paginate: 20
            criteria:
                enabled: true
            template:  AppBundle:Blog:index.html.twig
```

I add a blog entity with an index route as shown above.
the criteria is ignored and all entities(including disabled ones) are available in template.
