### ISSUE TITLE
User-Bundle issue

### ISSUE THREAD

**Issue by Adraesh** [Sylius/Sylius#8074]
Hi,

I installed with success sylius/user-bundle following the command: 

> composer require sylius/user-bundle dev-master

I got an issue when I start to implement the configuration related to it following the documentation: http://docs.sylius.org/en/latest/bundles/SyliusUserBundle/summary.html

Issue: 

> [Symfony\Component\Debug\Exception\ContextErrorException]                                                  
  Warning: class_implements(): Class Sylius\Component\Core\Model\AdminUser does not exist and could not be   
  loaded

Also if I check my vendors/sylius folder, I don't have any Component folder.

Thank you in advance.

**Comment by mbabker** [comment]
That config reference isn't really great for using the bundle standalone as it makes references to the non-standalone core bundle.  Until that's updated, you're probably better off using the bundle's [Configuration class](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php) as your config reference.

**Comment by Adraesh** [comment]
Hi,

In fact let me explain the whole context of my project.

I have a sylius/sylius-standard project installed and working perfectly. On the same server I have another project on which I want to be able to access to the ShopUser of my sylius/sylius-standard project to be able to share the ShopUser between those 2 projects (like  you can do with FOSUserBundle by when installed specifying the "model_manager_name" which target a "entity_manager" which target a doctrine connection and have an extended FOSUserBundle).

I need to find a way to share the ShopUser between my 2 projects because I would like to access also to the "sylius.factory.shop_user" which provide me ways to validate things (check password etc ...) from my 2nd project. The Sylius API does not provide this kind of services.

I hope it is clear enough.

Thanks again.

**Comment by Adraesh** [comment]
I don't know if I am on the right way but here is the actual code I could have:

AppKernel.php:
```
$bundles = [
            new FOS\RestBundle\FOSRestBundle(),
            new JMS\SerializerBundle\JMSSerializerBundle($this),
            new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle(),
            new WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle(),
            new Bazinga\Bundle\HateoasBundle\BazingaHateoasBundle(),
            new winzou\Bundle\StateMachineBundle\winzouStateMachineBundle(),
            new Sylius\Bundle\ResourceBundle\SyliusResourceBundle(),
            new Sylius\Bundle\MailerBundle\SyliusMailerBundle(),
            new Sylius\Bundle\UserBundle\SyliusUserBundle(),
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle(),
            new Nelmio\CorsBundle\NelmioCorsBundle(),
            new Nelmio\ApiDocBundle\NelmioApiDocBundle(),
            new AppBundle\AppBundle(),
            new UserBundle\UserBundle(),
        ];
```

config.yml:
```
orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: default
                mappings:
                    AppBundle: ~
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable
                        is_bundle: false

            some_other:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                connection: some_other
                mappings:
                    SyliusUserBundle: ~
                    UserBundle: ~

sylius_user:
    driver: doctrine/orm
    resources:
        shop:
            user:
                classes:
                    model: UserBundle\Entity\ShopUser
                    repository: UserBundle\Repository\ShopUserRepository
                    form: Sylius\Bundle\CoreBundle\Form\Type\User\ShopUserType
                    interface: Sylius\Component\User\Model\UserInterface
                    controller: Sylius\Bundle\UserBundle\Controller\UserController
                    factory: Sylius\Component\Resource\Factory\Factory
                templates: 'SyliusUserBundle:User'
                resetting:
                    token:
                        ttl: P1D
                        length: 16
                        field_name: passwordResetToken
                    pin:
                        length: 4
                        field_name: passwordResetToken
                verification:
                    token:
                        length: 16
                        field_name: emailVerificationToken
```

security.yml:
```
providers:
        sylius_shop_user_provider:
            id: sylius.shop_user_provider.email_or_name_based
```

UserBundle.php:
```
<?php

namespace UserBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class UserBundle extends Bundle
{
	public function getParent()
    {
        return 'SyliusUserBundle';
    }
}
```

ShopUser.php:
```
<?php

namespace UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Sylius\Component\User\Model\User as BaseUser;

/**
 * ShopUser
 *
 * @ORM\Table(name="shop_user")
 * @ORM\Entity(repositoryClass="UserBundle\Repository\ShopUserRepository")
 */
class ShopUser extends BaseUser
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
```

doctrine:mapping:info:

> ....
[OK]   Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry
[OK]   Gedmo\Loggable\Entity\LogEntry
[OK]   Sylius\Component\User\Model\User
[OK]   Sylius\Component\User\Model\UserOAuth

And I got this error:

> [Doctrine\Common\Persistence\Mapping\MappingException]                                                     
  The class 'UserBundle\Entity\ShopUser' was not found in the chain configured namespaces AppBundle\Entity,  
   Gedmo\Loggable\Entity, Sylius\Component\User\Model

Thank you in advance.
