### ISSUE TITLE
@SyliusUi/Grid/Field/money.html.twig uses non existing twig filter

### ISSUE THREAD

**Issue by reyostallenberg** [Sylius/Sylius#8080]
I wanted to use a formatted money number in a custom grid by configuring:
```yml
sylius_grid:
    grids:
        app_admin_my_grid:
            driver:
                name: doctrine/orm
                options:
                    class: "%app.model.entity.class%"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [someField]
            fields:
                someFieldThatRepresentsMoney:
                    type: twig
                    label: Label
                    position: 1
                    options:
                        template: "@SyliusUi/Grid/Field/money.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
```

Then I got the error: `Unknown "sylius_money" filter.` Because apparently this twig filter is replaced for sylius_format_money. So '@SyliusUi/Grid/Field/money.html.twig' needs to be corrected

Shall I make a PR to correct this?
