### ISSUE TITLE
[Product][Serializer] ProductVariant and Taxon serializers has to be not dependent on SyliusAdminApiBundle

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#8087]
In fact, i disabled Api in my Sylius installation because i do not need it for the moment.

In product admin form, in associations, autocomplete use serializer which defines relations in that way : 

```yaml 
 relations:
        -   rel: self
            href:
                route: sylius_admin_api_product_variant_show
                parameters:
                    code: expr(object.getCode())
                    productCode: expr(object.getProduct().getCode())
                    version: 1
        -   rel: product
            href:
                route: sylius_admin_api_product_show
                parameters:
                    code: expr(object.getProduct().getCode())
                    version: 1
            exclusion:
                groups: [Detailed]
```

I think routes like that has to depend on sylius_admin_ajax_*, WDYT ?

**Comment by lchrusciel** [comment]
With this serialization we have coupled ProductBundle with AdminApiBundle (so with CoreBundle). We should move `relations` to Core and change the routes to `sylius_admin_ajax_*` as you proposed.

**Comment by Niiko** [comment]
I'm not that good with serializers, but if i'm correct, serializer config has to be in same bundle that the entity belongs to no ?

**Comment by lchrusciel** [comment]
It is a matter of configuration. We can move this part:
```yml

jms_serializer:
    metadata:
        directories:
            sylius-core:
                namespace_prefix: "Sylius\\Component\\Core"
                path: "@SyliusCoreBundle/Resources/config/serializer"
``` 
from `Sylius/Bundle/CoreBundle/Resources/config/app/config.yml` to `Sylius/Bundle/AdminApiBundle/Resources/config/app/config.yml` and change the path.
