### ISSUE TITLE
Event sylius.payment.post_complete not triggered after a Paypal Express Checkout payment

### ISSUE THREAD

**Issue by Adraesh** [Sylius/Sylius#8109]
I don't know if it's an issue but I noticed that the event sylius.payment.post_complete was never triggered after I performed a Paypal Express Checkout payment (through sandbox), so basically, the Order "paymentState" was never "paid".

I managed to force and dispatch the sylius.payment.post_complete event by creating a listener on the event kernel.response and by targeting the desired controller's action as bellow:

```
app.payum.after_capture:
        class: AppBundle\EventListener\PayumAfterCaptureListener
        arguments: ["@sylius.repository.order", "@event_dispatcher"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
```

```
<?php

namespace AppBundle\EventListener;

use Sylius\Bundle\CoreBundle\Doctrine\ORM\OrderRepository;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpKernel\Event\FilterResponseEvent;
use Sylius\Bundle\ResourceBundle\Event\ResourceControllerEvent;

class PayumAfterCaptureListener
{
	private $orderRepository;
	private $eventDispatcher;

	public function __construct(OrderRepository $orderRepository, EventDispatcherInterface $eventDispatcher)
	{
		$this->orderRepository = $orderRepository;
		$this->eventDispatcher = $eventDispatcher;
	}

	public function onKernelResponse(FilterResponseEvent $event)
    {
    	$request = $event->getRequest();
    	if ($request->attributes->get('_controller') === 'sylius.controller.payum:afterCaptureAction')
    	{
    		if ($request->getSession()->getFlashBag()->has('info'))
    		{
    			$message = $request->getSession()->getFlashBag()->get('info')[0];
    			if ($message === 'sylius.payment.completed')
    			{
    				$order = $this->orderRepository->find($request->getSession()->get('sylius_order_id'));
    				if ($order)
    				{
    					$payment = $order->getPayments()->first();
    					if ($payment)
    					{
	    					$event = new ResourceControllerEvent($payment);
	    					$this->eventDispatcher->dispatch('sylius.payment.post_complete', $event);
	    				}
    				}

    				$request->getSession()->getBag('flashes')->add('info', $message);
    			}
    		}
    	}
    }
}
```

I assume it's not the most beautiful thing, but it's working.
