### ISSUE TITLE
[#ProductTranslation] - Fail add a custom translatable model

### ISSUE THREAD

**Issue by nietzcheson** [Sylius/Sylius#8116]
Hey, @all...

I have a problem. I'm following the [doc](http://docs.sylius.org/en/latest/cookbook/custom-translatable-model.html) and it throws me: 

```console
Expected value of type "Doctrine\Common\Collections\Collection|array" for association field "Sylius\Component\Core\Model\Product#$translations", got "Sylius\Component\Core\M
  odel\ProductTranslation" instead.
```
All I have is:
```yml
sylius_product:
    resources:
        product:
            translation:
                classes:
                    model: AppBundle\Entity\ProductTranslation
```
```php
<?php

namespace AppBundle\Entity;

use Sylius\Component\Core\Model\ProductTranslation as BaseProductTranslation;

class ProductTranslation extends BaseProductTranslation
{

    /**
     * @var string $specifications
     */
    private $specifications;

    /**
     * @var string $dimensions
     */
    private $proportions;

    /**
     * @var string $materials
     */
    private $materials;

    /**
     * {@inheritdoc}
     */
    public function setSpecifications($specifications)
    {
        $this->specifications = $specifications;
    }

    /**
     * {@inheritdoc}
     */
    public function getSpecifications()
    {
        return $this->specifications;
    }

    /**
     * {@inheritdoc}
     */
    public function setProportions($proportions)
    {
        $this->proportions = $proportions;
    }

    /**
     * {@inheritdoc}
     */
    public function getProportions()
    {
        return $this->proportions;
    }

    /**
     * {@inheritdoc}
     */
    public function setMaterials($materials)
    {
        $this->materials = $materials;
    }

    /**
     * {@inheritdoc}
     */
    public function getMaterials()
    {
        return $this->materials;
    }
}
```
```yml
AppBundle\Entity\ProductTranslation:
    type: entity
    table: sylius_product_translation
    fields:
        specifications:
            type: text
            nullable: true
        proportions:
            type: text
            nullable: true
        materials:
            type: text
            nullable: true
```
I will be careful. Thank you!
