### ISSUE TITLE
On Symfony 3.3.2, problem parsing routing/cart.yml

### ISSUE THREAD

**Issue by wadjeroudi** [Sylius/Sylius#8165]
```
[Symfony\Component\Config\Exception\FileLoaderLoadException]                                                                                                              
  The file "alias: sylius.order                                                                                                                                             
  path: '" does not exist in /var/www/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/cart.yml (which is being imported from "/var/www/vend  
  or/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/main.yml"). 
```
Am I the only one getting this error ?
If I remove this part, everything works.
```
sylius_admin_api_carts:
    resource: |
        alias: sylius.order
        path: '/'
        only: [index]
        grid: sylius_admin_api_cart
        section: admin_api
        serialization_version: $version
    type: sylius.resource_api
```
