### ISSUE TITLE
Shipping Calculators Configurable In Admin Shipping Methods

### ISSUE THREAD

**Issue by silverbackdan** [Sylius/Sylius#8176]
There are a number of useful shipping calculators available:
http://docs.sylius.org/en/latest/components/Shipping/calculators.html

It appears in the admin area, shipping methods can only have flat rates, or flat rates per item defined. Apologies if I'm missing something, but is it not possible to have the FlexibleRateCalculator, for example, option available when selecting rate calculations on a shipping method?

I believe this is just a feature request though, but a dev who has been working on this may know more as to if this had been implemented on earlier versions.

**Comment by silverbackdan** [comment]
So I've seen that the calculator is newer than the latest beta release but has not been implemented with a form as far as I'm aware yet. If it's helpful, this is how I've implemented the flexible rate calculator manually into the latest beta release:

1. Of course I just copied the FlexibleRateCalculator class into my own AppBundle to be used instead.

2. The service defined in YML (pointing to the copied class in my AppBundle)
```yaml
sylius.shipping_calculator.flexible_rate:
        class: AppBundle\Component\Shipping\Calculator\FlexibleRateCalculator
        tags:
            - { name: sylius.shipping_calculator, calculator: flexible_rate, form-type: AppBundle\Form\Type\Calculator\ChannelBasedFlexibleRateConfigurationType, label: "sylius.form.shipping_calculator.flexible_rate_configuration.label" }
```

3. This points to a ChannelBasedFlexibleRateConfigurationType. In Sylius this would be moved to the namespace `Sylius\Bundle\CoreBundle\Form\Type\Shipping\Calculator`
```php
<?php
// Namespace would need changing if implemented in Sylius core
namespace AppBundle\Form\Type\Calculator;

use Sylius\Bundle\CoreBundle\Form\Type\ChannelCollectionType;
use Sylius\Component\Core\Model\ChannelInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @author Daniel West <daniel@silverback.is>
 */
final class ChannelBasedFlexibleRateConfigurationType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'entry_type' => FlexibleRateConfigurationType::class,
            'entry_options' => function (ChannelInterface $channel) {
                return [
                    'label' => $channel->getName(),
                    'currency' => $channel->getBaseCurrency()->getCode(),
                ];
            },
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return ChannelCollectionType::class;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'sylius_channel_based_shipping_calculator_flexible_rate';
    }
}

```
I also defined this as a service (perhaps unnecessary though)
```yaml
sylius.form.type.channel_based_shipping_calculator.per_unit_rate:
        class: AppBundle\Form\Type\Calculator\ChannelBasedFlexibleRateConfigurationType
        tags:
          - { name: form.type }
```

4. The class above then calls FlexibleRateConfigurationType which in Sylius would be in the namespace `Sylius\Bundle\ShippingBundle\Form\Type\Calculator`
```php
<?php
// Namespace would need changing if implemented in Sylius core
namespace AppBundle\Form\Type\Calculator;

use Sylius\Bundle\MoneyBundle\Form\Type\MoneyType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Type;

/**
 * @author Daniel West <daniel@silverback.is>
 */
final class FlexibleRateConfigurationType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_item_cost', MoneyType::class, [
                'label' => 'sylius.form.shipping_calculator.flexible_rate_configuration.first_item_cost',
                'constraints' => [
                    new NotBlank(['groups' => ['sylius']]),
                    new Type(['type' => 'integer', 'groups' => ['sylius']]),
                ],
                'currency' => $options['currency'],
            ])
            ->add('additional_item_cost', MoneyType::class, [
                'label' => 'sylius.form.shipping_calculator.flexible_rate_configuration.additional_item_cost',
                'constraints' => [
                    new NotBlank(['groups' => ['sylius']]),
                    new Type(['type' => 'integer', 'groups' => ['sylius']]),
                ],
                'currency' => $options['currency'],
            ])
            ->add('additional_item_limit', IntegerType::class, [
                'label' => 'sylius.form.shipping_calculator.flexible_rate_configuration.additional_item_limit',
                'constraints' => [
                    new NotBlank(['groups' => ['sylius']]),
                    new Type(['type' => 'integer', 'groups' => ['sylius']]),
                ]
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                'data_class' => null,
            ])
            ->setRequired('currency')
            ->setAllowedTypes('currency', 'string')
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'sylius_shipping_calculator_flexible_unit_rate';
    }
}
```

Then finally translations messages.en.yml:
```yaml
sylius:
    form:
        shipping_calculator:
            flexible_rate_configuration:
                label: Flexible rate per item
                first_item_cost: First item shipping cost
                additional_item_cost: Additional item shipping cost
                additional_item_limit: Additional item limit
```

I've got to the stage now where the option is available in the admin. I'll post updates if there are any other adjustments required or if someone does spot an issue with this approach I'd love to know.

Thanks.
