### ISSUE TITLE
[Grid] Exception when customising grid fields' options

### ISSUE THREAD

**Issue by sweoggy** [Sylius/Sylius#8187]
While trying to customise the order grid (same happens when customising any other grid) an exception occurs as soon as I am trying to change a field's default options:

> An exception has been thrown during the rendering of a template ("The option "0" does not exist. Defined options are: "format".").

Code:
```
sylius_grid:
    grids:
        sylius_admin_order:
            fields:
                number:
                    position: 1
                customer:
                    position: 2
                    path: '.'
                total:
                    position: 3
                state:
                    position: 4
                paymentState:
                    position: 5
                shippingState:
                    position: 6
                date:
                    position: 7
                    options:
                        format: Y-m-d H:i:s
```
