### ISSUE TITLE
Can not create a product attribute fixture of type 'select'

### ISSUE THREAD

**Issue by Keloo** [Sylius/Sylius#8264]
In the config.yml I have my fixutres. I want to create an product attribute fixture of type 'select'.
I can not find the right definition of it.
I tried like this:

<pre>
sylius_fixtures:
    suites:
        app:
            listeners:
                logger: ~
            fixtures:            
                product_attribute:
                    options:
                        custom:
                            canvas_type:
                                name: "type"
                                code: "type"
                                type: "select"
                                configuration:
                                    choices:
                                        - "Type 2"
                                        - "Type 2"
</pre>

when I try to load the fixutres it says:
`[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]     
  Unrecognized option "configuration" under "product_attribute.custom.canvas_type"  `

**Comment by pjedrzejewski** [comment]
@pamil Is it possible? :)

**Comment by lchrusciel** [comment]
@Keloo which version of Sylius are you using? [`configuration` node](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Fixture/ProductAttributeFixture.php#L58) has been added after beta.2, so you will need to update to newest master in order to use it.

**Comment by Keloo** [comment]
@lchrusciel I'm using beta 1.  Thx for the info regarding beta 2 version. :+1:

**Comment by lchrusciel** [comment]
Closing then. :)

**Comment by broiniac** [comment]
Just for the record: in version 1.1.2 (and probably up) working fixture look like this:

```
sylius_fixtures:
    suites:
        app:
            listeners:
                logger: ~
            fixtures:
                product_attribute:
                    options:
                        custom:
                            custom_attribute_name: 
                                name: real name here # attribute name (for default locale)
                                code: code_name_here
                                type: select
                                configuration:
                                    choices:
                                        -
                                            # localeCode: translated name
                                            en_US: "name 1"
                                            pl: "nazwa 1"
                                        -
                                            en_US: "name 2"
                                            pl: "nazwa 2"
                                    multiple: false   # optional
                                    min: 1            # optional
                                    max: 1            # optional
```

**Comment by venyii** [comment]
Hm not sure this is correct. I tried to define them like it's described here but when trying to add the attribute to a product with one or more values, I get an error `This value should be of type string.` on the multiselect input.

![image](https://user-images.githubusercontent.com/502368/38504783-e43d730c-3c15-11e8-8ce3-96baf200b563.png)

Looking at how the attribute configuration was inserted, it looks different than a select attribute that was created via the shop backend:

The comment above produces:
```
a:2:{s:7:"choices";a:14:{i:0;a:1:{s:5:"en_US";s:9:"Something";}
```

Creating one in the backend produces:
```
a:4:{s:7:"choices";a:2:{s:36:"ced63470-3bf9-11e8-9568-38c9860c388b";a:1:{s:5:"en_US";s:9:"Something";}
```

So the difference is the array index for each choice (which explains the form error message on the input) which needs to be a string code. Creating them like the following works:
```
something:
  name: Name 1
  code: name1
  type: select
  configuration:
    choices:
      some-code1:
        en_US: "Something"
      some-code2:
        en_US: "Something 2"
```

That was at least my experience, maybe I'm missing something here. The fixture doesn't seem to throw any errors, no matter how you enter the configuration. Any thoughts on this @pamil @lchrusciel  since you "👍" the comment?
