### ISSUE TITLE
[Documentation] Adding a custom translatable model

### ISSUE THREAD

**Issue by czende** [Sylius/Sylius#8324]
Hi, I just set up my custom translatable model with this tutorial http://docs.sylius.org/en/latest/cookbook/custom-translatable-model.html and found some missing important things. You have to define two more fields in supplier_translation table - locale and translatable_id and of course relation between supplier and supplier_translation.

My config after some adjustments:
```
# SupplierTranslation.orm.yml
AppBundle\Entity\SupplierTranslation:
    type: entity
    table: sylius_supplier_translation
    repositoryClass: AppBundle\Repository\SupplierTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        locale:
            type: string
            length: 255
    oneToOne:
        supplier:
          targetEntity: AppBundle\Entity\Supplier
          joinColumn:
            name: translatable_id
            referencedColumnName: id
            nullable: false
            onDelete: CASCADE
    lifecycleCallbacks: {  }
```
