### ISSUE TITLE
[Grid] Adding links on product grid failed

### ISSUE THREAD

**Issue by gpekz** [Sylius/Sylius#8362]
Hello everyone,

I got a problem trying to add links to a main action 

```
# AppBundle/Resources/config/grids/admin/product.yml
sylius_grid:
    grids:
        sylius_admin_product:
            actions:
                main:
                    create:
                        options:                 
                            links:
                                simple:
                                    label: sylius.ui.simple_product
                                    icon: plus
                                    route: sylius_admin_product_create_simple
                                configurable:
                                    label: sylius.ui.configurable_product
                                    icon: plus
                                    route: sylius_admin_product_create
                                # want to add new links
                                enabled:
                                    label: app.ui.enabled_product
                                    icon: plus
                                    route: sylius_admin_product_create_enabled
                                disabled:
                                    label: app.ui.disabled_product
                                    icon: plus
                                    route: sylius_admin_product_create_disabled
```

The links are not added to the "create action", so I tried to dump the grid in a listener

```
namespace AppBundle\Grid;

use Sylius\Component\Grid\Event\GridDefinitionConverterEvent;

final class AdminProductGridListener
{
    public function addMainActions(GridDefinitionConverterEvent $event)
    {
        dump($event->getGrid()->getActionGroup('main')->getAction('create')->getOptions());
    }
}
```

And got 

```
array:5 [
    "class" => "primary"
    "icon" => "plus"
    "header" => array:2 
    "links" => array:2 [
        "simple" => array:3 
        "configurable" => array:3 
    ]
    0 => array:4 [
        "simple" => array:3 
        "configurable" => array:3 
        "enabled" => array:3 
        "disabled" => array:3 
    ]
]
```

I temporarily solved the problem with a listener 

```
namespace AppBundle\Grid;

use Sylius\Component\Grid\Event\GridDefinitionConverterEvent;

final class AdminProductGridListener
{
    public function addMainActions(GridDefinitionConverterEvent $event)
    {
        $links = [
            "enabled" => [
                "label" => "app.ui.enabled_product",
                "icon" => "plus",
                "route" => "sylius_admin_product_create_enabled"
            ],
            "disabled" => [
                "label" => "app.ui.disabled_product",
                "icon" => "plus",
                "route" => "sylius_admin_product_create_disabled"
            ]
        ];

        $action = $event->getGrid()->getActionGroup('main')->getAction('create');

        $options = $action->getOptions();

        $options['links'] = array_merge($options['links'], $links);

        $action->setOptions($options);
    }
}
```

I also tried to override the entire grid in "app/Resources/SyliusAdminBundle" and it works. 

Is that a bug or am I doing something wrong ? I use beta version.

Thanks in advance.
