### ISSUE TITLE
Problem save many to one 

### ISSUE THREAD

**Issue by piterssson** [Sylius/Sylius#8373]
I trying save many to one data in form sylius and return null in referencedColumnName

![many_to_one](https://user-images.githubusercontent.com/16086241/28996698-941eca42-7a05-11e7-8735-11e756bc079a.jpg)

```
MyBundle\Entity\Files:
   ...
    manyToOne:
        ownerpage:
            targetEntity: MyBundle\Entity\Page
            inversedBy: files
            joinColumn:
                name: ownerpage_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false
```

```
class Files
{
    protected $ownerpage;

    /**
     * {@inheritdoc}
     */
    public function getOwnerpage()
    {
        return $this->ownerpage;
    }

    /**
     * {@inheritdoc}
     */
    public function setOwnerpage($ownerpage)
    {
        $this->ownerpage = $ownerpage;
    }

   ...

}
```

```
MyBundle\Entity\Page:
   ...
    oneToMany:
        files:
            targetEntity: MyBundle\Entity\Files
            mappedBy: ownerpage
            orphanRemoval: true
            cascade:
                - all
```

```
class Page implements ResourceInterface, ImagesAwareInterface
{
    private $files;

    public function __construct()
    {
        $this->files = new ArrayCollection();

    }
..
}

```

```
....
class PageType extends AbstractResourceType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ....
            ->add('files', CollectionType::class, [
                'entry_type' => FilesType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'mapped' => true,
                'label' => 'sylius.form.page.files',
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'page';
    }
}
```

But I create custom controller and save form -  this working
