### ISSUE TITLE
Error on Symfony 3.3 and sylius 1.0.0-beta.3 for routing with template path

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#8376]
This following example fails

```
app_backend_address:
    resource: |
        alias: app.address
        section: backend
        templates: :backend/crud
        except: ['show']
        [...]
    type: sylius.resource
```
The file "alias: app.address
section: backend
templates: :backend" does not exist

But after moving templates var at the end of the parameters, everything works.

```
app_backend_address:
    resource: |
        alias: app.address
        section: backend
        except: ['show']
        [...]
        templates: :backend/crud
    type: sylius.resource
```
