### ISSUE TITLE
Could not extend Customer model

### ISSUE THREAD

**Issue by lpitteloud** [Sylius/Sylius#8379]
Hi there !

I'm trying to extend Customer model but I got the following error when registering the customer:

> INSERT INTO sylius_customer (email, email_canonical, first_name, last_name, birthday, gender, created_at, updated_at, phone_number, subscribed_to_newsletter, customer_group_id, dtype) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["l.pitteloud+1@gmail.com", null, null, null, null, "u", "2017-08-08 14:36:50", "2017-08-08 14:36:51", null, 0, null, "customer"]

It seems to only keep email form field value but lose the others...

Here is the files I updated:

**Customer.php**
```
<?php
namespace AppBundle\Entity;
...
use Sylius\Component\Customer\Model\Customer as BaseCustomer;

class Customer extends BaseCustomer
...
```

**Customer.orm.yml**
```
AppBundle\Entity\Customer:
    type: mappedSuperclass
    inheritanceType: SINGLE_TABLE
    table: sylius_customer
    ...
```

**config.yml**
```
sylius_customer:
    resources:
        customer:
            classes:
                model: AppBundle\Entity\Customer
```

What did I do wrong ?

Thank you for your time !
