### ISSUE TITLE
[Resource] Wrong redirection when using sylius.resource and custom criteria

### ISSUE THREAD

**Issue by aeyoll** [Sylius/Sylius#8382]
For example, lets say you have customers who manage some documents attached to them, with a following routing configuration.

```
app_document:
    prefix: /customers/{customerId}/
    resource: |
        alias: app.document
        section: ...
        templates: ...
        redirect: index
        grid: app_document
        form:
            type: ...
        criteria:
            customer: $customerId
        vars:
            all:
                route:
                    parameters:
                        customerId: $customerId
    type: sylius.resource
```

On create or update, when redirecting to the index page, only the ```id``` parameter from the resource is present, missing the ```customerId```parameter, making the route generation fail.

I've got a PR coming to fix this issue, by adding extra redirect parameters to the ```vars``` section
