### ISSUE TITLE
pre/post payment events not being triggered

### ISSUE THREAD

**Issue by kochen** [Sylius/Sylius#8395]
Following this example: http://docs.sylius.org/en/latest/cookbook/disabling-order-confirmation-email.html#overriding-service-definition

I've noticed that:
1. the event name should actually be: `sylius.payment.post_complete`
2. overriding the service definition does cancel the original `orderConfirmation` email but does not send one after payment, because non of the pre/post payment complete events are triggered.

PR for the documentation will follow after the main bug is fixed.

**Comment by kochen** [comment]
related to: #8109

**Comment by kochen** [comment]
@pjedzejewski shouldn't this be fixed (later release?), instead of jut changing the docs because it doesn't work?

**Comment by pjedrzejewski** [comment]
@kochen Sorry it was automatically closed via reference. We removed docs to avoid confusion but we need to figure out a better way to solve it.

**Comment by kochen** [comment]
@pjedzejewski I know.
I say move it to `v1.1.0`, it's not a must have for `v1.0.0`

**Comment by kochen** [comment]
@pjedzejewski any plan to pick this up?

**Comment by czende** [comment]
@kochen Is this solved or not? I have same problem as described here #8109 :/

**Comment by kochen** [comment]
@czende As far as I know it was never address directly.
But might have been addressed indirectly - never checked...

**Comment by pamil** [comment]
IIRC there was no work done with this one.

**Comment by Gounlaf** [comment]
> I think sylius.payment.post_complete event is still not triggered

I didn't found triggering of this event too =/
The official [InvoicingPlugin](https://github.com/Sylius/InvoicingPlugin) doesn't rely on it too.

**Comment by LucaGallinari** [comment]
The sylius.payment.* events are still not triggered. They are triggered only when the payment is manually confirmed from the admin.
A possible workaround is to use the "pay" callback on the "sylius_order_payment" entity. So you have to do something like this in your _sylius.yaml:

```
winzou_state_machine:
    sylius_order_payment:
        callbacks:
            after:
                my_custom_logic_name:
                    on: ["pay"]
                    do: ["@YOUR_SERVICE_ID", "THE_METHOD_TO_CALL"]
                    args: ["object"]

```

I opened another issue https://github.com/Sylius/Sylius/issues/12541, at least the docs should be modified accordingly.
