### ISSUE TITLE
[ResourceBundle] configuring grid bundle with doctrine/phpcr-odm

### ISSUE THREAD

**Issue by mitalcoi** [Sylius/Sylius#8397]
Hello. I am using fresh installed sylius application and trying to configure grid bundle to work with doctrine/phpcr-odm driver. I have configuration like:
```
doctrine_phpcr:
    session:
        backend:   '%phpcr_backend%'
        workspace: '%phpcr_workspace%'
        username:  '%phpcr_user%'
        password:  '%phpcr_pass%'
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: '%kernel.debug%'

sylius_resource:
    drivers:
        - doctrine/orm
        - doctrine/phpcr-odm
    resources:
        app.article:
            driver: doctrine/phpcr-odm
            classes:
                model: AppBundle\Document\Article
sylius_grid:
    grids:
        app_admin_article:
            driver:
                name: doctrine/phpcr-odm
                options:
                    class: AppBundle\Document\Article
            fields:
                title:
                    type: string
                    label: sylius.ui.title
```
The error I've got is following
<img width="1322" alt="2017-08-12 13 15 30" src="https://user-images.githubusercontent.com/3224226/29239824-60101390-7f60-11e7-8314-524474010570.png">

I've debugged ```DataSourceProvider``` and driver is actually registered. But ```$this->driversRegistry->has($driverName)``` returns ```false``` for ```doctrine/phpcr-odm```

I was following the documentation and rechecked configuration is according to manual, please, advice, what may cause this problem?
