### ISSUE TITLE
[Resource] Problem with resources.definition when using resources in plugin

### ISSUE THREAD

**Issue by Dukecz** [Sylius/Sylius#8400]
I am creating plugin for sylius and trying to use resources to generate admin pages but I am getting problem with `Neither the property "definition" nor one of the methods "definition()", "getdefinition()"/"isdefinition()" or "__call()" exist and have public access in class "Pagerfanta\Pagerfanta".` (or similar error on array if I set `paginage: false` for route) in `in vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/views/Crud/index.html.twig at line 5`

`src/Resources/config/app/config.yml:`
```yml
sylius_resource:
    resources:
        app_plugin.partner:
            classes:
                model: App\PartnerPlugin\Entity\Partner
```

`src/Resources/config/app/routing.yml`
```yml
app_plugin_partner:
    resource: |
        alias: app_plugin.partner
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: index
        permission: true
    type: sylius.resource
```
```php
<?php

namespace App\PartnerPlugin\Entity;

use Sylius\Component\Resource\Model\ResourceInterface;

/**
 * Class Partner
 * @package App\PartnerPlugin\Entity
 */
class Partner implements ResourceInterface
{

	/**
	 * @var integer
	 */
	protected $id;

	/**
	 * @return int
	 */
	public function getId()
	{
		return $this->id;
	}
}
```

Do you have any idea where might be the problem?
