### ISSUE TITLE
[Grids] Add alignment on grid cells

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#8413]
That's a pretty common use, and some conventions about number display especially.

For now, i used a quick and dirty workaround by using : 
```yml
sylius_grid:
    grids:
        sylius_admin_product:
            fields:
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        vars:
                            td_class: center aligned middle aligned
```

And i overrided the macro associated

```twig
{% macro row(grid, definition, row) %}
    <tr class="item">
    {% for field in definition.enabledFields|sort_by('position') %}
        <td {% if field.options.vars.td_class is defined %}class="{{ field.options.vars.td_class }}"{% endif %}>{{ sylius_grid_render_field(grid, field, row) }}</td>
    {% endfor %}
    {% if definition.actionGroups.item is defined and definition.getEnabledActions('item')|length > 0 %}
        <td>
            <div class="ui mini buttons">
                {% for action in definition.getEnabledActions('item')|sort_by('position') %}
                    {{ sylius_grid_render_action(grid, action, row) }}
                {% endfor %}
            </div>
            {% if definition.actionGroups.subitem is defined and definition.getEnabledActions('subitem')|length > 0 %}
            <div class="ui fitted divider"></div>
            <div class="ui mini buttons">
                {% for action in definition.getEnabledActions('subitem')|sort_by('position') %}
                    {{ sylius_grid_render_action(grid, action, row) }}
                {% endfor %}
            </div>
            {% endif %}
        </td>
    {% endif %}
    </tr>
{% endmacro %}
```
What do you prefer : 

- A css class added on cell levels
- An alignment property (left/right/center)

WDYT ? 

Could PR that one.

**Comment by sweoggy** [comment]
I personally prefer CSS class added on cell levels as one might want to do more styling than just alignment of the cell.

**Comment by Mipme** [comment]
use :nth-child(1...x) as a selector in your css for alignment and other styling. This way u can achieve loose coupling of code and style, which helps a lot if you work in groups with codes and designers and suddenly decide to change column order for instance...

**Comment by Niiko** [comment]
The only way for changing order is to change "position" in grids, so, if it's a parameter of grid, no need to change css.

Plus, we are using semantic-ui, i think it's better to use their classes to align in that case.

But i agree, coupling style with code, it's not a best practice...so, this i why there is my second proposition (which can be used in json grids for example)

**Comment by Mipme** [comment]
- As css grid is coming up u can easily change the order of a table: https://css-tricks.com/snippets/css/complete-guide-grid/
- if you programmatically change the order ur coder also has to change the css classes -> causes more communication issues
- although Semantic UI is quite nice, i personally try to avoid (css) frameworks; especially close coupling to a (css) framework, so i would augment against using framework related classes in your HTML code

But there is definitely a point in providing more flexibility on the grid HTML code. I would opt for a ``template`` var where i can define the HTML container for that grid element:

````
    sylius_grid:
    grids:
        sylius_admin_product:
            fields:
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        vars:
                            template: '@AppBundle\myviews\Grid\snippets\my-column'
````

This is also used throughout other config possibilities in Sylius. It is easy to spread the work for designers and coders and gives you full flexibility.

Just my 2 cents...

**Comment by Niiko** [comment]
In grids, we can already define a twig for a cell, but it's not on "td level" but in "td". Maybe we can change that in that way too (but it's a huge BC break)

I disagree with the change of programmatically change order, if the class used is already defined in the grid, no need to change css (i'ts only the case if you used nth:child solution).

Personnaly i prefer to use angular + api, but the problem is still there, i need to know alignement of the cell, i don't want to style each grids with css, but a more generic way (again, the second proposition).

I really don't know which is the best, for me the second one.

BTW, thanks for css grid, i was not aware of it :)

**Comment by liverbool** [comment]
My DX, it can be option of all column types.

```yaml
options:
    align: center
    width: 100px
    style: css
```
Or
```yaml
options:
    align: center
    width: 100px
    style:
        cssKey: value
```
