### ISSUE TITLE
Database name is hardcoded in config_dev.yml

### ISSUE THREAD

**Issue by bpolaszek** [Sylius/Sylius#8476]
Hi there,

Before everything gets written in the rock, I was wondering about these lines of code:
```yaml
# app/config/config_dev.yml
doctrine:
    dbal:
        dbname: "%database_name%_dev"
```

Why is the database name hardcoded when using the `dev` environement? This is not the case in Symfony Standard edition, because such config should only rely on `parameters.yml`.

For my use case, I have the same `sylius` database both for `dev` and `prod` environment, on my local machine, because sometimes I want to test things against the same dataset.

So I have to remove the `_dev` part in my `app/config/config_dev.yml`, but this conflicts with the VCS when upgrading Sylius (This should not happen with `Sylius-standard`, but it does with `Sylius`).

## First solution

IMO these lines should be removed for 1.0, to comply with Symfony Standard. What do you think?

## Another solution

If you really just want to keep a different database name by default (which I suggest not - because one could also have a different host, user, etc), here's how we could replace this:

```yml
# app/config/parameters.yml.dist
parameters:
    # ...
    database_name_dev: '%database_name%_dev'
```
```yml
# app/config/config_dev.yml
doctrine:
    dbal:
        dbname:   "%database_name_dev%"
```

This way, we could use any database name in dev environment just by editing `app/config/parameters.yml`, and no more VCS issues.

Thank you,
Ben
