### ISSUE TITLE
Include in form a property with 'mapped' => false

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#8484]
Hello.

In older version of sylius I included in form some field with property 'mapped' => false, for example "terms and conditions" or "recaptcha".

Yesterday I realized that this fields does not work now, I think that could be some update of sylius.

Are there some documentation about include field captcha in form register for example ?

I have the route:
```
sylius_user_registration:
    path: /registro/
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            form: MyProject\UserBundle\Form\Type\RegistrationFormType
            event: register
            template: SyliusShopBundle::register.html.twig
            factory:
                method: createNewFromSource
                arguments: [ 'form_default' ]
            redirect:
                route: user_registration_success
            flash: sylius.customer.register
```

And in RegistrationFormType

```
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder,$options);
        $builder
            ->add('legal', CheckboxType::class, array(
                'mapped' => false,
                'label' => false,
                'required' => true,
                'constraints' => new IsTrue(array('message' => 'Términos no aceptados')),
            ));
    }
```
The field is rendered in my template, but If I dont check property, the form work anyway... any idea ?

Only I found this page http://docs.sylius.org/en/latest/customization/form.html 

Thanks in advance.
