### ISSUE TITLE
[GRID] Sorting is not inherited when extending grids

### ISSUE THREAD

**Issue by waaghals** [Sylius/Sylius#8502]
Is there a strong reason for not inheriting sorting configuration when extending grid configuration?
It is unclear to me what could be the reason why this is not inherited.

Would a PR be accepted which does not unset the sorting configuration of the parent? 
Another solution might be to make it conditional so based on another setting, something like:

```
sylius_grid:
    grids:
        tp_admin_entity_name:
            extends: 'tp_admin_base_grid'
            inherit_sorting: true
```
