### ISSUE TITLE
Using channel context in kernel.request listener in admin results in out of memory

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8538]
I have this service that listens on `kernel.request` and injects the Channel Context. As long as one channel is in the admin, all is ok. As soon as a second one is added to the channels, it runs into out of memory issues at every admin page.

```yaml
services:
    sylius.google_tag_manager.listener.context:
        class: GtmPlugin\EventListener\ContextListener
        arguments:
            - "@google_tag_manager"
            - "@sylius.context.channel"
            - "@sylius.context.locale"
            - "@sylius.context.currency"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
```

Dumping the `sylius.context.channel` output results in a `Sylius\Component\Channel\Context\CachedPerRequestChannelContext` object. As soon as I call the `getChannel` method on it, it runs out of memory.

I don't even want to have this listener do something in the admin, so I might be able to check on this, but else it seems to me that this should be working or am I expecting too much from it? E.g. that `getChannel` should return null as it's unknown?
