### ISSUE TITLE
UUID for entities, routing to be changed

### ISSUE THREAD

**Issue by PapsOu** [Sylius/Sylius#8544]
Hello,

according to these issues (#3379, #6511), there still an implicit usage of IDs as integer.

For example :
```yml
sylius_shop_partial_product_review_latest:
    path: /latest/{count}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_review:indexAction
        _sylius:
            template: $template
            repository:
                method: findLatestByProductId
                arguments:
                    - !!int $productId
                    - !!int $count
        count: 3
```

$productId is still handled only as integer (double and float allowed too in vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Controller/ParametersParser.php

This issue happen when overriding the Sylius product with custom entity that uses Uuid instead of autogenerated int ID. It cause this exception :
```log
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT l0_.title AS title_0, l0_.rating AS rating_1, l0_.comment AS comment_2, l0_.status AS status_3, l0_.created_at AS created_at_4, l0_.updated_at AS updated_at_5, l0_.id AS id_6, l0_.product_id AS product_id_7, l0_.author_id AS author_id_8 FROM librinfo_ecommerce_productreview l0_ WHERE l0_.product_id = ? AND l0_.status = ? ORDER BY l0_.created_at DESC LIMIT 3' with params [9223372036854775807, "accepted"]:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for uuid: "9223372036854775807"").
```
