### ISSUE TITLE
[Promotion] field translation

### ISSUE THREAD

**Issue by kuzyk** [Sylius/Sylius#8695]
Hi,
Is it possible to translate promotion name and description?

I try to add:
> sylius_promotion:
    resources:
        promotion:
            translation:
                classes:
                    model: ...`

but it throw error 
`Unrecognized option "translation" under "sylius_promotion.resources.promotion"`

**Comment by lchrusciel** [comment]
It will require more work. Promotions are not translatable atm, so based on this http://docs.sylius.org/en/latest/cookbook/custom-translatable-model.html and this http://docs.sylius.org/en/latest/customization/model.html you should be able to do it on your own.

Do we plan to introduce it to the core? /cc @Sylius/core-team

**Comment by Zales0123** [comment]
I vote for introducing this in the nearest future, as it would be useful to display some info about current promotions for customer (which now is hardly impossible with only one locale on promotion).

**Comment by kuzyk** [comment]
Customize promotion model it's quite simple and no problems with this.
But I long time try add translation to this model without any results

**Comment by laurentdabbb** [comment]
Hi,

This request is closed for 4 years ago...so sorry...

But, I think it would always be a good thing to translate name and description. 
Everybody don't need this features, so I understand you don't implement it.

However, like @lchrusciel said, we can implement it on our project following the cookbook...but **it's not totally true** (I think)...
Promotion is a Sylius resource. to Attach a translation model to this resource we have to declare it in the **_sylius.yaml**, but promotionBundle configuration does not allow _"translation"_ attribute after the _"classes"_ one for _"promotion"_ resource...

Perhaps, you could simply allow "translation" attribute in the treeBuilder and stay it optionnal. In this way, everyone could simply attach a translation resource to promotion... ;-)

I hope other people will be interested in this little evolution.

Thanks in advance for your consideration ;-)

**Comment by vvasiloi** [comment]
@laurentdabbb although bundles have configuration for their resources, you can also configure those resources directly though the resource bundle configuration using the same resource alias.
Let me know if you need more details.

**Comment by laurentdabbb** [comment]
Thank you @vvasiloi  !

I had tested this solution, but I had not correctly overloaded the whole configuration. 
Because the resource bundle define default values for resources we have to correctly redefine "interface", "repository" and "form" entries with Promotion ones.  

Your answer got me back on track.

Here is my configuration `sylius_resource.yaml` if anyone has the same need ;-)

```yaml
sylius.promotion:
    driver: doctrine/orm
    classes:
        model: App\Entity\Promotion\Promotion
        interface: App\Entity\Promotion\PromotionInterface
        repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\PromotionRepository
        form: Sylius\Bundle\PromotionBundle\Form\Type\PromotionType
    translation:
        classes:
            model: App\Entity\Promotion\PromotionTranslation
            interface: App\Entity\Promotion\PromotionTranslationInterface
            form: App\Form\Type\PromotionTranslationType
```
