### ISSUE TITLE
No MetadataInterface service found for customized ProductController

### ISSUE THREAD

**Issue by matthijsch** [Sylius/Sylius#8870]
| Q                | A
| ---------------- | -----
| Bug report?      |yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.0

Following the documentation (http://docs.sylius.org/en/latest/customization/controller.html) the following error occurs when creating a custom ProductController

"Cannot autowire service "AppBundle\Controller\ProductController": argument "$metadata" of method "Sylius\Bundle\ResourceBundle\Controller\ResourceController::__construct()" references interface "Sylius\Component\Resource\Metadata\MetadataInterface" but no such service exists."

**The code:**

_AppBundle\Controller\ProductController.php:_
```php
namespace AppBundle\Controller;

use Sylius\Bundle\ResourceBundle\Controller\ResourceController;
use Symfony\Component\HttpFoundation\Request;

class ProductController extends ResourceController
{
    public function seoAction(Request $request)
    {
    }
}
```
_app/config/config.yml_
```yml
sylius_product:
    resources:
        product:
            classes:
                controller: AppBundle\Controller\ProductController`
```

_app/config/routing.yml_
```yml
app_shop_product_seo:
    path: /products/{slug}/seo
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:seoAction
        _sylius:
            repository:
                method: findOneByChannelAndSlug
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - "expr:service('sylius.context.locale').getLocaleCode()"
                    - $slug`
```

**Comment by matthijsch** [comment]
This issue seems to be fixed by disabling autowire for the ProductController class in the configuration.

**Comment by wjs876046992** [comment]
I have the save problem. @matthijsch And, it does not work when disabling autowire. How do you fix it?

**Comment by h3llr4iser** [comment]
same problem here, any solution?

**Comment by h3llr4iser** [comment]
I have solved it by disabling autowiring this way in case someone else has this problem.


```
 services: 
   _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false
```
