### ISSUE TITLE
customizing product translation

### ISSUE THREAD

**Issue by samanmohamadi** [Sylius/Sylius#8881]
Customizing productTranslation throws this error:
**(1/1) InvalidConfigurationExceptionUnrecognized**  
 option "product_translation" under "sylius_product.resources"

**Comment by stefandoorn** [comment]
I think it should be `translation`.

**Comment by samanmohamadi** [comment]
@stefandoorn I tried that but not works.

**Comment by stefandoorn** [comment]
Ah sorry, you have to nest it a level deeper:

```
sylius_product:
    resources:
        product:
            classes:
                model: AppBundle\Entity\Product
                repository: AppBundle\Repository\ProductRepository
                controller: AppBundle\Controller\ProductController
            translation:
                classes:
                    model: AppBundle\Entity\ProductTranslation
```
