### ISSUE TITLE
Customize ProductAttributeValue model.

### ISSUE THREAD

**Issue by samanmohamadi** [Sylius/Sylius#8885]
I have customized `ProductAttributeValue` but I don't know how to tell Sylius about my new customized model.
I tried this:   

    sylius_product:
        resources:
            product_attribute_value:
                classes:
                    model: AppBundle\Entity\ProductAttributeValue

and get this error:  
  **Unrecognized option "product_attribute_value" under "sylius_product.resources"**

**Comment by GSadee** [comment]
This is a specific resource which is configured dynamically in [SyliusProductExtension](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ProductBundle/DependencyInjection/SyliusProductExtension.php)

I guess that this configuration should work for you:
```
sylius_attribute:
    resources:
        product:
            attribute_value:
                classes:
                    model: AppBundle\Entity\ProductAttributeValue
```
I close that issue as it is not a bug.
