### ISSUE TITLE
Documentation on how to extend the API

### ISSUE THREAD

**Issue by mlelong** [Sylius/Sylius#8916]
| Q                | A
| ---------------- | -----
| Doc request? |  yes
| Sylius version   | 1.*

Hi there, 

I was wondering if i miss something. I want to put in the **Sylius API** all our **business logic** (add some methods to create easily an order from a basket, get some stats on a product...) to make it available for any front or apps we could write in the future. But i really dont get it about **how customize the existing Sylius REST API** ?

Can someone advice me on the doc or the better way to begin ?

Thanks.

**Comment by igormukhingmailcom** [comment]
Sylius doesn't have any API that can be used by front. There are Sylius Shop API Plugin for this (google it). And it can be customized exactly same way as any other symfony controller.

**Comment by mlelong** [comment]
Thanks for reply, i worked on the API during the last week. And i understand now that the existing api is more to use with a PIM or ERP as a private API.
And we will use the shop api as a public api that we will extends for our needs.

> And it can be customized exactly same way as any other symfony controller.

As sylius use FOSRestBundle, pagerfanta, hateoas, i spend a little time to find how to build the data response, and its finally close to what i found in SyliusShopApi (https://github.com/Sylius/SyliusShopApiPlugin)

Here is an example of our work in progress that has been done on api, and that will be moved in shop/api :

SupplierController

```
<?php

namespace AppBundle\Controller\Api;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use FOS\RestBundle\View\View;
use Pagerfanta\Adapter\ArrayAdapter;
use Pagerfanta\Pagerfanta;
use Hateoas\Configuration\Route;
use Hateoas\Representation\Factory\PagerfantaFactory;

/**
 * Class SupplierController
 * @package AppBundle\Controller\Api
 */
class SupplierController extends Controller
{

    public function getSupplierAction(Request $request, $supplierId = null, $restaurantId = null)
    {

        if ($supplierId) {
            $suppliers = $this->get('app.repository.supplier')->findById($supplierId);
        } else {
            $suppliers = $this->get('app.repository.supplier')->findAll();
        }

        $items = [];
        foreach ($suppliers as $supplier) {

            $items[$supplier->getId()] = [
                'id' => $supplier->getId(),
                'name' => $supplier->getName(),
                'city' => $supplier->getCity(),
                'productsCount' => $this->get('app.repository.supplier_product_informations')->getProductsCount($supplier),
            ];
        }

        $page = $request->query->get('page', 1);
        $adapter = new ArrayAdapter($items);
        $pagerfanta = new Pagerfanta($adapter);
        $pagerfanta->setCurrentPage($page);

        $pagerfantaFactory   = new PagerfantaFactory();

        $paginatedCollection = $pagerfantaFactory->createRepresentation(
            $pagerfanta,
            new Route($request->get('_route'), $request->attributes->get('_route_params'))
        );
        
        return $this->get('fos_rest.view_handler')->handle(View::create($paginatedCollection, Response::HTTP_OK));
    }
}
```

And for the routing : 

routing.yml

```
app_api_bundle:
    resource: "@AppBundle/Resources/config/routing/api.yml"
    prefix:   /api
```
	
api.yml

```
app_api_suppliers_detail:
    path: /v{version}/suppliers/detail/
    methods: [GET]
    requirements:
    defaults:
        _controller: AppBundle:Api\Supplier:getSupplier

app_api_supplier_detail:
    path: /v{version}/suppliers/detail/{supplierId}/{restaurantId}
    methods: [GET]
    requirements:
        supplierId: '\d+'
        restaurantId: '\d+'
    defaults:
        _controller: AppBundle:Api\Supplier:getSupplier
        restaurantId: null	
```
