### ISSUE TITLE
Override order Model

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/Sylius#8988]
Hi,
i what to add 2 fields in the sylius_order table. agb and widerruf.

On doctrine:migrations i get:

> [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
>   Unrecognized option "order" under "sylius_core.resources"  

I guess something is not correct:

AppBundle/Entity/Order.php
```
<?php


namespace AppBundle\Entity;

use Sylius\Component\Order\Model\Order as BaseOrder;

class Order extends BaseOrder
{
    // agb
    /**
     * @var bool
     */
    private $agb;

    /**
     * @return bool
     */
    public function getAgb(): bool
    {
        return $this->agb;
    }

    /**
     * @param bool $agb
     */
    public function setAgb(bool $agb): void
    {
        $this->agb = $agb;
    }
    // widerruf
    /**
     * @var bool
     */
    private $widerruf;

    /**
     * @return bool
     */
    public function getWiderruf(): bool
    {
        return $this->widerrufwiderruf;
    }

    /**
     * @param bool $widerruf
     */
    public function setWiderruf(bool $widerruf): void
    {
        $this->widerruf = $widerruf;
    }
}
```

AppBundle/Resources/config/doctrine/Order.orm.yml:
```
AppBundle\Entity\Order:
    type: entity
    table: sylius_order
    fields:
        agb:
            type: boolean
            nullable: true

AppBundle\Entity\Order:
    type: entity
    table: sylius_order
    fields:
        widerruf:
            type: boolean
            nullable: true
```

app/config/config.yml:
```sylius_core:
    resources:
        order:
            classes:
                model: AppBundle\Entity\Order
```

THX for help
Mike

**Comment by lchrusciel** [comment]
Our main support channels are SO or slack. Please, ask such questions there.

BTW.
If you are using the whole platform, then you should extend a core model instead of a model from the order component. Also, possible error:
```yml
sylius_order: # You have a `sylius_core` here probably, but the `sylius_order` should be here.
    resources:
        order:                                                     
            classes:
                model: AppBundle\Entity\Order
```
