### ISSUE TITLE
[SupportRequest]  "Compile Error: require(): Failed opening required ...SyliusComponentCurrencyModelCurrency

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#9042]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.0.0-beta2

Hi,

I've this weird error, that is usually associated with mistypes, caches and such, but in my case it looks like something else. (Resource configuration issue maybe?)

It happens only in `PROD` env, it works fine in `DEV`

I'm extending `Sylius/Component/Currency/Model/Currency` into `AppBundle/Entity/Currency`.

```
 <?php
 
 namespace AppBundle\Entity;
 
 use Doctrine\ORM\Mapping as ORM;
 use Sylius\Component\Currency\Model\Currency as BaseCurrency;
 
 /**
  * @ORM\Entity
  * @ORM\Table(name="sylius_currency")
  */
 class Currency extends BaseCurrency
 {
 }

``` 

My `sylius_currency` configuration.
```
 sylius_currency:
     resources:
         currency:
             classes:
                 model: AppBundle\Entity\Currency
```
and tried this variant. (As I've saw, that sylius specifies default repository classes in Core configuration for other resources)
```
 sylius_currency:
     resources:
         currency:
             classes:
                 model: AppBundle\Entity\Currency
                 repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
         exchange_rate:
             classes:
                 repository: Sylius\Bundle\CurrencyBundle\Doctrine\ORM\ExchangeRateRepository
```

And I'm still getting this error

> [2017-12-19 10:06:22] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: require(): Failed opening required 'Acme/var/cache/prod/doctrine/orm/Proxies/__CG__SyliusComponentCurrencyModelCurrency.php' (include_path='.:/usr/share/php7:/usr/share/php')" at Acme/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php line 209 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorExceptio n(code: 0): Compile Error: require(): Failed opening required 'Acme/var/cache/prod/doctrine/orm/Proxies/__CG__SyliusComponentCurrencyModelCurrency .php' (include_path='.:/usr/share/php7:/usr/share/php') at Acme/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php:209)"} [ ]

Any ideas would be appreciated.
Thanks
