### ISSUE TITLE
Resource routing parsing doesn't work in some cases

### ISSUE THREAD

**Issue by versgui** [Sylius/Sylius#9072]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.6

In some cases, the routing config throws a parsing exception. Just changing the location of a line change the behavior, whereas it shouldn't. Just see the **templates** line in this example.

Works:
```
dashboard_frontend_project:
    resource: |
        alias: dashboard.project
        section: frontend
        redirect: index
        only: ['show', 'create']
        templates: :Frontend/Project
    type: sylius.resource
```

Doesn't work:

```
dashboard_frontend_project:
    resource: |
        alias: dashboard.project
        section: frontend
        templates: :Frontend/Project
        redirect: index
        only: ['show', 'create']
    type: sylius.resource
```

I get this error : 

> The file "alias: dashboard.portfolio
section: backend
templates: :Backend" does not exist in /var/www/dashboard/src/ProjectBundle/Resources/config/routing/Backend/portfolio.yml

Seems related to #8376 and symfony/symfony#23412
