### ISSUE TITLE
Can´t extend sylius user

### ISSUE THREAD

**Issue by JSabio** [Sylius/Sylius#9118]
I follow up the guide "Customizing Models" but I can´t extend sylius user.

I have on my AppBundle\Entity a User.php with new fields, getters and setters. I created a user.orm.xml n AppBundle\Resources\config\doctrine mapping the new fields.

Finally on app\config y edit my config.yml adding these lines:

```
sylius_user:
    driver: doctrine/orm
    resources:
        shop:
            user:
                classes:
                    model: AppBundle\Entity\User
```

Should I add any extra lines there? Thanks a lot
