### ISSUE TITLE
Sensitive data should not be present in non-parameter configuration files

### ISSUE THREAD

**Issue by Im0rtality** [Sylius/Sylius#921]
Ran SensioInsight over my project and got this (edited to make it shorter):

**[in app/config/config.yml, line 65](https://github.com/Sylius/Sylius/blob/master/app/config/config.yml#L65)**

> A sensitive data has been detected in your configuration file (`username` parameter). You should consider storing it in a single parameter file.

```
doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
        workspace: default
        username: admin
        password: admin
    odm:
        auto_mapping: true
```
