### ISSUE TITLE
[RFC] Make the checkout steps configurable in ``sylius_core``

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#924]
If you look at the CheckoutProcessScenario, it's super simple to set the order of the steps / custom steps via configuration file. I think this would be uber + for customization. In long run I want to refactor the SyliusFlowBundle to provide this out of the box, but for now I think it would be cool if you can add / remove steps from a configuration file.

@Sylius opinions?

``` yaml
sylius_core:
    checkout:
        securty: sylius_checkout_security
        addressing: sylius_checkout_security
        shipping: sylius_checkout_security
        payment: sylius_checkout_security
        custom: sylius_checkout_custom_wrapping
        finalize: sylius_checkout_security
        purchase: sylius_checkout_security
```
