### ISSUE TITLE
It's impossible to add translatable model for ProductImage

### ISSUE THREAD

**Issue by bitbager** [Sylius/Sylius#9393]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | yes
| RFC?             | yes
| Sylius version   | 1.1.5

When I configure the `sylius_product_image` resource to refer to a translatable model, I am getting `Undefined "translation" key under sylius.core.product_image` error. 

```yaml
sylius_core:
    resources:
        product_image:
            translation:
                classes:
                    model: AppBundle\Entity\ProductImageTranslation
```

I understand that it's nor build in the SyliusCore DI Configuration class, but it makes sense to add translatable models for any Sylius core resources. For instance, I want to add a translatable alt property to the product image. What's more, overriding the whole config does not work either, even if I do it in the vendor. 

Would it be possible to extend Sylius core models for this purpose?

**Comment by lchrusciel** [comment]
It won't be in our scope for now. Mikołaj, do you think you can contribute this to the core?

**Comment by vvasiloi** [comment]
It's possible to define the image translation with resource bundle configuration:
```
sylius_resource:
    resources:
        sylius.product_image:
            classes:
                model: App\Entity\Product\ProductImage
            translation:
                classes:
                    model: App\Entity\Product\ProductImageTranslation
```
