### ISSUE TITLE
SyliusResourceBundle - ResourceController::redirectTo with custom route placeholder

### ISSUE THREAD

**Issue by amenophis** [Sylius/Sylius#941]
Hi,
I try to build a hierarchical CRUD with standalone SyliusResourceBundle but i find a problem ...

I got 2 resources: Item, SubItem

I got this 2 routes

``` yaml
subitem_create:
    pattern: /item/{item_id}/subitem/new
    methods: [GET, POST]
    defaults:
        _controller: cfa.controller.testplan:createAction
        _sylius:
            redirect:
                route: subitem_show
                parameters:
                    testplanprovider_id: $testplanprovider_id
                    id: ????

subitem_show:
    pattern: /item/{item_id}/subitem/{id}
    methods: [GET]
    defaults:
        _controller: cfa.controller.testplan:showAction
```

I can't be correctly redirected to the subitem_show with a correct {id} ...

How can I do that ?

Maybe we can only override the passed parameters, but always add the id parameter  in ResourceController redirectTo method. Instead of test if parameters is empty (https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php#L270-L272), we can add it to the parameters if it is not present ? 

@Sylius Any idea on this ?
