### ISSUE TITLE
Resource image upload on custom model

### ISSUE THREAD

**Issue by mangelsnc** [Sylius/Sylius#9434]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.6

Hi to everyone,

I created a new custom resource entity `Designer` which implements ResourceInterface. I add the backoffice grid to manage the instances. Everything works perfectly and I can create/update/delete my instances in the backend.
I followed those steps to create it: http://docs.sylius.com/en/latest/cookbook/entities/custom-model.html

Then I want to add images to my model, and I followed this guide: http://docs.sylius.com/en/latest/cookbook/images/images-on-entity.html

The form shows OK, the enctype is correct... everything looks good, but when I submit the form...

```
An exception occurred while executing 'INSERT INTO app_designer_image (type, path, owner_id) VALUES (?, ?, ?)' with params ["avatar", null, 12]:
```
I noticed that the events `sylius.designer.pre_create` and `sylius.designer.pre_update` are not triggered. They are in the "Not called listeners" section of the Symfony Profiler.

I published a question in StackOverflow and I write in the Slack channel without any response, in the GitHub issues I found this one: https://github.com/Sylius/Sylius/issues/5282 that is an exact clone of my case, but in my case the *enctype* is "multipart/form-data" so this not solve my problem.

This is my models mapping:
```
AppBundle\Entity\Designer:
    type: entity
    table: app_designer
    repositoryClass: AppBundle\Repository\DesignerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        motto:
            type: string
            length: 255
        quote:
            type: string
            length: 255
        description:
            type: text
        featuredDesigner:
            type: boolean
            default: false

    oneToMany:
        images:
            targetEntity: AppBundle\Entity\DesignerImage
            mappedBy: owner
            orphanRemoval: true
            cascade:
                - all
```
```
AppBundle\Entity\DesignerImage:
    type: entity
    table: app_designer_image
    manyToOne:
        owner:
            targetEntity: AppBundle\Entity\Designer
            inversedBy: images
            joinColumn:
                name: owner_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
```

And this is a fragment of my `services.yml` with the events configuration:

```
services:
    app.form.type.designer_image:
        class: AppBundle\Form\Type\DesignerImageType
        tags:
            - { name: form.type }
        arguments:
            - 'AppBundle\Entity\DesignerImage'

    app.form.type.designer:
        class: AppBundle\Form\Type\DesignerType
        tags:
            - { name: form.type }
        arguments:
            - 'AppBundle\Entity\Designer'
            - '%app.form.type.designer.validation_groups%'

    app.form.extension.type.designer:
        class: AppBundle\Form\Extension\DesignerTypeExtension
        tags:
            - { name: form.type_extension, extended_type: AppBundle\Form\Type\DesignerType }

    app.listener.images_upload:
        class: Sylius\Bundle\CoreBundle\EventListener\ImagesUploadListener
        parent: sylius.listener.images_upload
        autowire: true
        autoconfigure: false
        public: false
        tags:
            - { name: kernel.event_listener, event: sylius.designer.pre_update, method: uploadImages }
            - { name: kernel.event_listener, event: sylius.designer.pre_create, method: uploadImages }
```
If I submit the image, the `Designer` entity is not persisted.

I'm stuck here with no idea of how to solve this. Any idea?

Thanks.
