### ISSUE TITLE
Render controller inside twig template

### ISSUE THREAD

**Issue by Stefun** [Sylius/Sylius#9486]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.5

I'm trying to include controller inside twig template using 
{{ render(controller('SyliusUserBundle:Security:login')) }}

My use case:
Render login form or forgot password template if the user is not logged-in and on click of login link show these template as the popup.

We got the same error when we tried other custom template sample for testing. It might be specific to Sylius and `ResourceContoller` as same concept works fine with standard symfony.

Error:
`An exception has been thrown during the rendering of a template ("Template is not configured.").`

 `Security.yml`
```
    sylius_shop_login:
        path: /login
        methods: [GET]
        defaults:
            _controller: sylius.controller.security:loginAction
            _sylius:
            template: "@SyliusShop/login.html.twig"
            logged_in_route: sylius_shop_account_dashboard
```
