### ISSUE TITLE
Allow null hostname for channel fixture

### ISSUE THREAD

**Issue by sanpii** [Sylius/Sylius#9509]
**Sylius version affected**: 1.1.7

**Description**  
The fixture configuration requires an hostname, but setting its to null directly in database is allowed and seems to be good to automaticaly detect hostname (for email in my case).

**Steps to reproduce**  
```yaml
sylius_fixtures:
    suites:
        default:
                channel:
                    options:
                        custom:
                            fr_web_store:
                                name: "Boutique FR"
                                code: "FR"
                                locales:
                                    - "fr"
                                currencies:
                                    - "EUR"
                                enabled: true
                                hostname: ~
```

**Possible Solution**  
Allow null hostname in fixture.

Currently I create an `AfterSuiteListenerInterface` to updates the desired hostname.
