### ISSUE TITLE
Cart form validation hidden

### ISSUE THREAD

**Issue by sanpii** [Sylius/Sylius#9520]
**Sylius version affected**: 1.1.7

**Description**  
I have override the quantity form type to add a minimun quantity validation.

The validation works fine on the product page, but on the cart page, when I update an item with an invalid quantity the symfony debug toolbar display the form error but it’s not display on the page.

**Steps to reproduce**  
```php
<?php

declare(strict_types=1);

namespace AppBundle\Form\Extension;

use Sylius\Bundle\OrderBundle\Form\Type\CartItemType;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Range;

final class CartItemExtension extends AbstractTypeExtension
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $min = 10;
        $builder
            ->add('quantity', IntegerType::class, [
                'attr' => ['min' => $min],
                'data' => $min,
                'label' => 'sylius.ui.quantity',
                'constraints' => [
                    new Range([
                        'min' => $min,
                        'groups' => ['sylius'],
                    ]),
                ],
            ]);
    }

    public function getExtendedType(): string
    {
        return CartItemType::class;
    }
}
```
```yaml
services:
    app.form.extension.type.cart_item:
        class: AppBundle\Form\Extension\CartItemExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\OrderBundle\Form\Type\CartItemType, priority: -1 }
```
