### ISSUE TITLE
My new theme isn't being loaded

### ISSUE THREAD

**Issue by teratux** [Sylius/Sylius#9522]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.3

Hi ... I'm currently trying to create a custom theme after reading the official documentation on how to do it.  I created an EventListener that I registered in my Kernel so that when the site loads I can select which theme I want to display.   The problem is that the new theme is not registering itself in the Sylius system, I'm using the full stack Sylius version, not a Symfony install that uses Sylius' bundles.

These are the files:
services.yml:
```
    Redbridge\EventListener\ThemeRequestListener:
        public: true
        autowire: true
        autoconfigure: true
        class: 'Redbridge\EventListener\ThemeRequestListener'
        arguments:
          - '@sylius.repository.theme'
          - '@sylius.theme.context.settable'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
```
src/EventListener/ThemeRequestListener.php:
```
<?php

namespace Redbridge\EventListener;

use Sylius\Bundle\ThemeBundle\Context\SettableThemeContext;
use Sylius\Bundle\ThemeBundle\Repository\InMemoryThemeRepository;
use Sylius\Bundle\ThemeBundle\Repository\ThemeRepositoryInterface;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\HttpKernelInterface;

class ThemeRequestListener
{
    /**
     * @var ThemeRepositoryInterface
     */
    private $themeRepository;

    /**
     * @var SettableThemeContext
     */
    private $themeContext;

    /**
     * @param ThemeRepositoryInterface $themeRepository
     * @param SettableThemeContext $themeContext
     */
    public function __construct( ThemeRepositoryInterface $themeRepository, SettableThemeContext $themeContext )
    {
        $this->themeRepository = $themeRepository;
        $this->themeContext = $themeContext;
    }

    /**
     * @param GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        if (HttpKernelInterface::MASTER_REQUEST !== $event->getRequestType()) {
            // don't do anything if it's not the master request
            return;
        }

        $this->themeContext->setTheme( $this->themeRepository->findOneByName('first_template') );
    }
}
```
app/themes/MyNewTheme/composer.json:
```
{
  "name": "first_template",
  "title": "A first Redbridge Template",
  "description": "A first Redbridge Template",
  "authors": [
    {
      "name": "Roberto Espi",
      "email": "teratux@gmail.com",
      "homepage": "http://kamil.kokot.me",
      "role": "Developer"
    }
  ]
}
```
config.yml:
```
sylius_theme:
    sources:
        filesystem: ~
```
When I run the command: $ bin/console sylius:theme:list I get:
`There are no themes.`

Any help would be appreciated
Thanks ...
