### ISSUE TITLE
[ResourceBundle][sf4] unable to find templates when you have no bundles

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#9532]
**Sylius version affected**: 1.2.0

**Description**  

When using resource bundle with a symfony 4 directory structure, you have no bundle at all on your src.
Then there is a problem with templates option.

**Steps to reproduce**  

```
app_backend_address:
    resource: |
        alias: app.address
        section: backend
        except: ['show']
        redirect: index
        grid: app_backend_address
        vars:
            all:
                subheader: app.ui.manage_addresses
                templates:
                    form: backend/address/_form.html.twig
            index:
                icon: map
        templates: backend/crud
    type: sylius.resource
```
It throws: "Unable to find template "backend/crud:index.html.twig"

**Possible Solution**  

On ResourceLoader, we have that:
`$defaults['_sylius']['template'] = sprintf('%s:%s.html.twig', $configuration['templates'], $actionName);`

Maybe we can replace by this line:
``$defaults['_sylius']['template'] = sprintf('%s/%s.html.twig', $configuration['templates'], $actionName);`
`
But I'm not sure it will work with bundles like this:
`templates: SyliusAdminBundle:Crud`
