### ISSUE TITLE
[ResourceBundle] Error with mongodb-odm

### ISSUE THREAD

**Issue by lardyNiji** [Sylius/Sylius#9544]
Hi 
I'm trying to configure Sylius Resource Bundle with Doctrine MongoDB ODM.
I've created a sf3.4 projet from Symfony Standard Edition, i've a working mongo connection with symfony.

After that i've installed Sylius Resource Bundle based on the documentation and i've created a simple sample document.
```php
<?php

// src/AppBundle/Document/Sample.php
namespace AppBundle\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use Sylius\Component\Resource\Model\ResourceInterface;

/**
* @MongoDB\Document
*/
class Sample implements ResourceInterface
{
    /**
    * @MongoDB\Id
    */
    protected $id;

    /**
    * @MongoDB\Field(type="string")
    */
    protected $name;

    /**
     * Get id
     *
     * @return id $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Get name
     *
     * @return string $name
     */
    public function getName()
    {
        return $this->name;
    }
}
```
I've configured as well yamls
```yml
#config.yml
sylius_resource:
    drivers:
        - doctrine/mongodb-odm
    resources:
        app.sample:
            driver: doctrine/mongodb-odm
            classes:
                model: AppBundle\Document\Sample
```
```yml
#routing.yml
app_sample:
    resource: |
        alias: app.sample
    type: sylius.resource_api
```

./bin/console debug:router show routes for this resource :
```
app_sample_index           GET         ANY      ANY    /samples/                          
app_sample_create          POST        ANY      ANY    /samples/                          
app_sample_update          PUT|PATCH   ANY      ANY    /samples/{id}                      
app_sample_show            GET         ANY      ANY    /samples/{id}                      
app_sample_delete          DELETE      ANY      ANY    /samples/{id}           
```

And when i try to get the resource with postman or curl i've the following error:
`The parameter "sylius.mongodb.odm.repository.class" must be defined`

Do i miss something to configure ?
Thx in advance

**Comment by lardyNiji** [comment]
I've just tried the following configuration : 
```yml
sylius_resource:
    drivers:
        - doctrine/mongodb-odm
    resources:
        app.sample:
            driver: doctrine/mongodb-odm
            classes:
                model: AppBundle\Document\Sample
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ODM\MongoDB\DocumentRepository
```
By adding a repository entry in my resource classes, i obtain the following error :
`
Compile Error: Declaration of Sylius\Bundle\ResourceBundle\Doctrine\ODM\Mon  
  goDB\DocumentRepository::find($id) must be compatible with Doctrine\ODM\Mon  
  goDB\DocumentRepository::find($id, $lockMode = Doctrine\ODM\MongoDB\LockMod  
  e::NONE, $lockVersion = NULL)
`
