### ISSUE TITLE
doctrine.resolve_target_entities fails with sylius resource class parameter

### ISSUE THREAD

**Issue by tautelis** [Sylius/Sylius#9591]
**Sylius version affected**: 1.1.8 and higher

Since this version the following was introduced:

> It's no longer required to put Sylius bundles before Doctrine Bundle (#9527)

Then having DoctrineBundle loaded before SyliusResourceBundle fails the following config definition:
````
doctrine:
    orm:
        resolve_target_entities:
            Sylius\Component\Core\Model\ShopUserInterface: '%sylius.model.shop_user.class%'
````
...since `%sylius.model.shop_user.class%` is not defined.

Any solutions?
