### ISSUE TITLE
User : Model customization config is not correct

### ISSUE THREAD

**Issue by pierre-H** [Sylius/Sylius#9641]
**Sylius version affected**: 1.2.4

**Description**  
I try to customize the User Model and the config described in the doc is not correct of User

**Steps to reproduce**  
Config that should work according to the doc but doesn't : 

```yaml
sylius_user:
    resources:
        user:
            classes:
                model: AppBundle\Entity\User
```

Code that works (double **user** key …) : 

```yaml
sylius_user:
    resources:
        user:
            user:
                classes:
                    model: AppBundle\Entity\User
```
