### ISSUE TITLE
Translations in fixtures

### ISSUE THREAD

**Issue by nenadalm** [Sylius/Sylius#9645]
**Describe the proposed solution**
Hi. It would be nice if it was possible to specify stuff in fixtures for more locales.

For example when I want to specify name of `Taxon`, I have to specify one name for all locales: https://github.com/Sylius/Sylius/blob/9b5b5e3698a26fe67efd306f6ae9c43b30a8ebf1/src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxonExampleFactory.php#L102

like so:
```yaml
taxon:
    options:
        custom:
            category:
                name: Category
                code: category
                slug: category
```

Example of how I imagine specifying `name` for more locales:
```yaml
taxon:
    options:
        custom:
            category:
                name: 
                    en_US: Category
                    cs_CZ: Kategorie
                code: category
                slug: category

```

You could preserve backward compatibility by allowing translatable fields to be either string (it would work like now - first case) or map (which would allow to specify the string in more locales).

**Comment by loic425** [comment]
I think it could be better with that structure:
```
taxon:
    options:
        custom:
            category:
                code: category
                translations:
                    en_US:
                        name: Category
                        slug: category
                    cs_CZ: 
                       name: Kategorie
                       slug: category
```
