### ISSUE TITLE
Disabling a bulk action still show section and checkboxes

### ISSUE THREAD

**Issue by ofinsterbusch** [Sylius/Sylius#9694]
**Sylius version affected**: 1.2.x

**Description**  
When extending a grid disabling a bulk action in the yaml file the action button disappear but the actions sections and the checkboxes in the grid are still there even if there are not actions

**Steps to reproduce**  
For example in the shipping method grid I want to disable the delete bulk action like this: 

```
actions:
   bulk:
      delete:
         type: delete
         enabled: false
```

You get an empty bulk section and checkboxes:
<img width="575" alt="screen shot 2018-09-04 at 13 51 27" src="https://user-images.githubusercontent.com/10028025/45029681-c5a7a680-b049-11e8-918e-fd438d7d170e.png">
