### ISSUE TITLE
PromotionActionExampleFactory amount is not int

### ISSUE THREAD

**Issue by tautelis** [Sylius/Sylius#9728]
**Sylius version affected**: 1.x

**Description**  
PromotionActionExampleFactory inserts invalid configuration to database.

**Steps to reproduce**  
say we have the following fixture:
````
promotion:
    options:
        custom:
            bugged_promotion:
                code: "bugged_promotion"
                name: "This promo is not working"
                usage_limit: 10
                priority: 2
                starts_at: "-7 day"
                ends_at: "7 day"
                channels:
                    - "b2c"
                rules:
                    -
                        type: "item_total"
                        configuration:
                            b2c:
                                amount: 100.00
                actions:
                    -
                        type: "order_fixed_discount"
                        configuration:
                            b2c:
                                amount: 10.00 <=== here we have a float price
````
such fixture does not pass the validation here:
https://github.com/Sylius/Sylius/blob/06060159f832d14a83e319efb2434f2a5acf7d84/src/Sylius/Component/Core/Promotion/Action/FixedDiscountPromotionActionCommand.php#L95

**Possible Solution**  
https://github.com/Sylius/Sylius/blob/06060159f832d14a83e319efb2434f2a5acf7d84/src/Sylius/Bundle/CoreBundle/Fixture/Factory/PromotionActionExampleFactory.php#L81

here we need to cast `$configuration[$channelCode]['amount']` to `int`.

Also same applies for the `PromotionRuleExampleFactory`.
