### ISSUE TITLE
Directory for themes

### ISSUE THREAD

**Issue by xElysioN** [Sylius/Sylius#9807]
Hi, 
We still need to create our theme in `app/themes` in Sylius 1.3, but with the new symfony structure, app doesn't exist. (cf: https://docs.sylius.com/en/1.3/components_and_bundles/bundles/SyliusThemeBundle/your_first_theme.html)
As @pamil said on slack : 
It'll be better to use the `templates` directory or create a top level directory `themes`.

**Sylius version**
1.3

**Describe the proposed solution**
Use the `templates` directory like `templates/themes`

**Describe alternatives you've considered**
Or create a top level directory `themes`

**Comment by Zales0123** [comment]
It should be probably resolved by https://github.com/Sylius/Sylius/pull/9804? cc @pamil

**Comment by pamil** [comment]
@Zales0123 not really, #9804 solves templates resolving, their location is another issue to solve.

**Comment by Prometee** [comment]
The default path : `%kernel.project_dir%/app/themes` has to be changed in `Sylius\Bundle\ThemeBundle\Configuration\Filesystem\FilesystemConfigurationSourceFactory`, in all a test file, and documentation.

I use this conf now to get ride of this bug :
```
# config/packages/sylius_theme.yaml
sylius_theme:
    sources:
        filesystem:
            directories:
                - "%kernel.project_dir%/templates/themes"
```

I agree that `templates/themes` should be the new place for themes. We also need a better doc on how to build a theme with a real and updated theme skeleton.
