### ISSUE TITLE
Cannot override User model

### ISSUE THREAD

**Issue by andychan94** [Sylius/Sylius#9857]
I am trying to add a `telegramUsername` field to the User model, following the docs I am now getting the
`The table with name 'shop_dev.sylius_shop_user' already exists.`

What am I doing wrong? Below are my files

```
// src/AppBundle/Entity/User.php
namespace AppBundle\Entity;

use Sylius\Component\Core\Model\ShopUser as BaseUser;

class User extends BaseUser
{
    /**
     * @var string|null
     */
    protected $telegramUsername;
```
```
// src/AppBundle/Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User:
  type: entity
  table: sylius_shop_user
  fields:
    telegramUsername:
      type: string
      nullable: true
```
```
// app/config/_sylius.yml
sylius_user:
  resources:
    shop:
      user:
        classes:
          model: AppBundle\Entity\User
```

In the docs, I could not find info on extending the models extended in core components. This has probably been asked many times, but after looking at other Issues I could not find a solution. Thanks.

**Comment by andychan94** [comment]
I moved the contents of _sylius.yml to config.yml and it worked. Did I miss something here? Should I import my _sylius.yml file somewhere in the configs?

**Comment by andychan94** [comment]
I just imported the _sylius.yml in config.yml

Everything has been resolved now, sorry to have bothered!

**Comment by Roshyo** [comment]
The doctrine mapping must be of type "mappedSuperclass" not "entity"

```yml
// src/AppBundle/Resources/config/doctrine/User.orm.yml
AppBundle\Entity\User:
  type: mappesSuperclass #HERE
  table: sylius_shop_user
  fields:
    telegramUsername:
      type: string
      nullable: true
```
