### ISSUE TITLE
Indentation error .platform.app.yaml in docs

### ISSUE THREAD

**Issue by renklaf** [Sylius/Sylius#9861]
**Sylius docs version**: 1.3 / latest

**Description**
There's missing an indent in the .platform.app.yaml file, in [this](https://docs.sylius.com/en/latest/cookbook/deployment/platform-sh.html#make-the-application-ready-to-deploy) section, causing an error when attempting to push to platform.sh:
`E: Error parsing configuration files:
    - applications./.variables: "None" is not a mapping type: Does not implement dict-like functionality.`

See snippets below for where the indentation is missing:
```yaml
variables:
env: 
    APP_ENV: 'prod'
    APP_DEBUG: 0
```
Should be:
```yaml
variables:
    env: 
        APP_ENV: 'prod'
        APP_DEBUG: 0
```
