### ISSUE TITLE
[API] Orders API missing

### ISSUE THREAD

**Issue by trickreich** [Sylius/Sylius#9938]
**Sylius version affected**: 1.3.*

**Description**  
The endpoint `/api/v1/orders` is missing. In the documentation it is declared: https://docs.sylius.com/en/1.3/api/orders.html

Was this endpoint removed or am I missconfigured something?

```
bin/console debug:router | grep api_order
  sylius_admin_api_order_index                           GET              ANY      ANY    /api/v{version}/carts/                                                    
  sylius_admin_api_order_item_update                     PUT|PATCH        ANY      ANY    /api/v{version}/carts/{cartId}/items/{id}                                 
  sylius_admin_api_order_item_delete                     DELETE           ANY      ANY    /api/v{version}/carts/{cartId}/items/{id}                                 
  sylius_admin_api_order_show                            GET              ANY      ANY    /api/v{version}/orders/{id}                                               
  sylius_admin_api_order_cancel                          PUT              ANY      ANY    /api/v{version}/orders/{id}/cancel                                        
  sylius_admin_api_order_shipment_ship                   PUT              ANY      ANY    /api/v{version}/orders/{orderId}/shipments/{id}/ship                      
  sylius_admin_api_order_payment_complete                PUT              ANY      ANY    /api/v{version}/orders/{orderId}/payments/{id}/complete
```

Is there a reason why the `index` action isn't set in the routing?

```
sylius_admin_api_order:
    resource: |
        alias: sylius.order
        section: admin_api
        only: [show]
        grid: sylius_admin_order
        serialization_version: $version
    type: sylius.resource_api
```

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/order.yml#L8

**Comment by mamazu** [comment]
Looks like there is a route configuration missing.

**Comment by trickreich** [comment]
I think the order and cart are overwriting each order cause of naming conflicts.

**Comment by mamazu** [comment]
Looks like it is missing a method. It should be `only: [show, index]` in the line you linked.

**Comment by trickreich** [comment]
Nope.. when you are adding `index` the `/api/v{version}/carts/ ` route isn't working anymore

**Comment by lchrusciel** [comment]
It is rather missing feature than bug. We need to add a new route. More buggy are names of `cart` endpoints. We should change them to be more clear what you are able to do. But BC-Break policy blocks us here, so I would say, that adding a new configuration with `admin_order` section will resolve all of the tensions here.

**Comment by trickreich** [comment]
Thanks for the response.
I think you are right, maybe the cart api should have it's own prefix.

**Comment by trickreich** [comment]
In other words:
You will not introduce an API endpoint for `orders` before 2.0?

**Comment by lchrusciel** [comment]
No, in other words, we can introduce orders endpoint in 1.4/master if there will be a PR with it ;) More or less in January. 

Only thing we need is this configuration:
```yml
sylius_admin_api_order:
    resource: |
        alias: sylius.order
        section: admin_api_order
        only: [index]
        grid: sylius_admin_order
        serialization_version: $version
    type: sylius.resource_api
```
+ docs + tests + explenation why do we have different section here

**Comment by trickreich** [comment]
This config exists already:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/order.yml#L4

The problem is that the cart uses this name already:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/cart.yml#L6

Therefore they are overwriting each other I think?

**Comment by lchrusciel** [comment]
No, they aren't as you posted links above. What is more name of generated path will be different ;)

**Comment by trickreich** [comment]
I've tested it for me:
When I'm chancing https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/order.yml#L8
from `only: [show]` to `only: [index, show]`, then the `/api/v1/carts` isn't working anymore cause it was overwritten by the `orders` API.

Routes before:
```
bin/console debug:router | grep api_order
  sylius_admin_api_order_item_update                     PUT|PATCH        ANY      ANY    /api/v{version}/carts/{cartId}/items/{id}                                 
  sylius_admin_api_order_item_delete                     DELETE           ANY      ANY    /api/v{version}/carts/{cartId}/items/{id}                                 
  sylius_admin_api_order_index                           GET              ANY      ANY    /api/v{version}/orders/                                                   
  sylius_admin_api_order_show                            GET              ANY      ANY    /api/v{version}/orders/{id}                                               
  sylius_admin_api_order_cancel                          PUT              ANY      ANY    /api/v{version}/orders/{id}/cancel                                        
  sylius_admin_api_order_shipment_ship                   PUT              ANY      ANY    /api/v{version}/orders/{orderId}/shipments/{id}/ship                      
  sylius_admin_api_order_payment_complete                PUT              ANY      ANY    /api/v{version}/orders/{orderId}/payments/{id}/complete  
```
Routes after
```
debug:router | grep api_order
  sylius_admin_api_order_item_update                     PUT|PATCH        ANY      ANY    /api/v{version}/carts/{cartId}/items/{id}                                 
  sylius_admin_api_order_item_delete                     DELETE           ANY      ANY    /api/v{version}/carts/{cartId}/items/{id}                                 
  sylius_admin_api_order_index                           GET              ANY      ANY    /api/v{version}/orders/                                                   
  sylius_admin_api_order_show                            GET              ANY      ANY    /api/v{version}/orders/{id}                                               
  sylius_admin_api_order_cancel                          PUT              ANY      ANY    /api/v{version}/orders/{id}/cancel                                        
  sylius_admin_api_order_shipment_ship                   PUT              ANY      ANY    /api/v{version}/orders/{orderId}/shipments/{id}/ship                      
  sylius_admin_api_order_payment_complete                PUT              ANY      ANY    /api/v{version}/orders/{orderId}/payments/{id}/complete
```

**Comment by trickreich** [comment]
As you can see the `sylius_admin_api_order_index` is the same..
So I think they were overwritten..

**Comment by lchrusciel** [comment]
But instead, can you add this additional routing to Sylius? I didn't mention changing `only: [show]` to `only: [index, show]`. I meant adding
```yml
sylius_admin_api_order_index:
    resource: |
        alias: sylius.order
        section: admin_api_order
        only: [index]
        grid: sylius_admin_order
        serialization_version: $version
    type: sylius.resource_api
```
here https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/order.yml#L12

+ test it
+ add docs ;)

**Comment by trickreich** [comment]
Sorry.. haven't seen that you've edited your message.
I understand now what you mean.

But in fact it's really confusing.
Why the definition of the `carts` section gets also the name with order?
Because it's defined with `sylius_admin_api_carts`?

**Comment by lchrusciel** [comment]
The root of the problem is in the way, how the routing is autogenerated. Splitting it part by part, while we have config like this:
```yml
sylius_admin_api_order:
    resource: |
        alias: sylius.order
        section: admin_api
        only: [show]
        grid: sylius_admin_order
        serialization_version: $version
    type: sylius.resource_api
```

`sylius_admin_api_order` is just a name of `generation`, so it will allow you to override this configuration, while it will not affect names of generated paths. Next line `alias: sylius.order`. It tells us which resource is taken to generate and it is the only requirement to generate paths. Also, it will provide the base for path resolution. Now we have the following paths:
* sylius_order_index
* sylius_order_show
* sylius_order_create
* sylius_order_update
* sylius_order_delete

If we have two configurations for the same resource it will resolve same names. As a result, one will override another one. That's why we have `section: admin_api` part. Now we have `sylius_`__admin_api__`_order_index`. In my example I have changed section, so name of generated paths will not collide. 

Ref: https://docs.sylius.com/en/1.3/components_and_bundles/bundles/SyliusResourceBundle/index.html
