### ISSUE TITLE
AbstractResourceFixture: Node `prototype` not defined at `options` node

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#9942]
**Sylius version affected**: 1.3.3

**Description**  
I would like to use `prototype` option during random fixtures creation for my custom resource as far as my resource have some mandatory options which can't be generated by faker and should be provided at `prototype` to populate to every random fixture (this option is designed for this as I noticed reading code).

But as far as this option never used by Sylius itself, it was not tested and actually not working as far as node `prototype` not defined at `options` node.

**Steps to reproduce**  
```
# config/packages/_sylius.yaml
sylius_fixtures:
    suites:
        default:
            fixtures:
                any_resource_fixture:
                    options:
                        random: 3
                        prototype: # <------- This one is not defined at AbstractResourceFixture::getConfigTreeBuilder, but used at AbstractResourceFixture::__construct to produce random fixtures
                            mandatory_option_name: 'bla1'
                        custom:
                            resource_fixture_1:
                                mandatory_option_name: 'bla2'
```

**Possible Solution**  
I will prepare PR now with next change:
```php
<?php
# AbstractResourceFixture.php

abstract class AbstractResourceFixture implements FixtureInterface
{
    // ...
    final public function getConfigTreeBuilder(): TreeBuilder
    {
        // ...
        $optionsNode->children()
            ->integerNode('random')->min(0)->defaultValue(0)->end()
            ->variableNode('prototype')->end() // <------ This line was added
        ;
        // ...
        return $treeBuilder;
    }
    // ...
}
```
