### ISSUE TITLE
[ProductBundle] Serializations require admin api bundle

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#9966]
**Sylius version affected**: 1.*

**Description**  

Product serialization on product bundle are linked with admin api bundle.
This is not possible to use product bundle serialization with jms out of the box without overriding the jms config.

Example:
```
Sylius\Component\Product\Model\ProductOption:
    exclusion_policy: ALL
    xml_root_name: product-option
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        code:
            expose: true
            type: string
            groups: [Default, Detailed]
        position:
            expose: true
            type: integer
            groups: [Default, Detailed]
        values:
            expose: true
            type: array
            groups: [Default, Detailed]
        translations:
            expose: true
            type: array
            groups: [Default, Detailed]
    relations:
        -   rel: self
            href:
                route: sylius_admin_api_product_option_show
                parameters:
                    code: expr(object.getCode())
                    version: 1

```

**Steps to reproduce**  

**Possible Solution**  

remove links in product bundle and override serialization into admin api bundle to add these links.
