### ISSUE TITLE
[BUG][DOC] Add images to ProductOptionValue entity

### ISSUE THREAD

**Issue by michalsztepun** [Sylius/Sylius#9981]
**Sylius docs version**: 1.x / latest

**Description**
Hello!

I'm trying to add images to ProductOptionValue entity following the documentation:
https://docs.sylius.com/en/1.3/cookbook/images/images-on-entity.html
Unfortunately after finishing all steps there is no effect. I was trying to create my own form with images, but when submiting form with changed OptionValues, that events are not working: 

- sylius.product_option_value.pre_create
- sylius.product_option_value.pre_update

Here is images upload listener configuration:
```
    app.listener.images_upload:
            class: Sylius\Bundle\CoreBundle\EventListener\ImagesUploadListener
            parent: sylius.listener.images_upload
            autowire: true
            autoconfigure: false
            public: false
            tags:
                - { name: kernel.event_listener, event: sylius.product_option_value.pre_create, method: uploadImages }
                - { name: kernel.event_listener, event: sylius.product_option_value.pre_update, method: uploadImages }

```

Everything works except that event, when submitting the form I got:
`Integrity constraint violation: 1048 Column 'path' cannot be null`

**Comment by mamazu** [comment]
The Image has inherited properties that you need to fill.

**Comment by michalsztepun** [comment]
Yeah sure, but it is not actually uploading the images, so I can't fill the data. I got the feeling that solution provided in DOC won't work for collections like OptionValues.

**Comment by mamazu** [comment]
You need to add it to the form and then it will automatically map it so to the `OptionValue`.

**Comment by wapcrazut** [comment]
I had the same issue, the problem was that the `product_option_value` resource doesn't trigger the events. So you have to call the main resource `product_options` but if you only do that the Image listener will give you an exception because the main resource doesn't implement the `ImagesAwareInterface`.

The solution is:

1. Create custom listener
2. Call main resource in the listener

My `services.yaml`
```
app.listener.product_option_value.images_upload:
    class: App\Listener\ProductOptionValueImagesUploadListener
    parent: sylius.listener.images_upload
    autowire: true
    autoconfigure: false
    public: false
    tags:
        - { name: kernel.event_listener, event: sylius.product_option.pre_create, method: uploadImages }
        - { name: kernel.event_listener, event: sylius.product_option.pre_update, method: uploadImages }
```

The listener `ProductOptionValueImagesUploadListener.php`
```
namespace App\Listener;

use Sylius\Component\Core\Model\ImagesAwareInterface;
use Sylius\Component\Core\Uploader\ImageUploaderInterface;
use Symfony\Component\EventDispatcher\GenericEvent;
use Webmozart\Assert\Assert;

final class ProductOptionValueImagesUploadListener
{
    /** @var ImageUploaderInterface */
    private $uploader;

    public function __construct(ImageUploaderInterface $uploader)
    {
        $this->uploader = $uploader;
    }

    public function uploadImages(GenericEvent $event): void
    {
        $subject = $event->getSubject();
        foreach ($subject->getValues() as $value) {
            $this->uploadSubjectImages($value);
        }
    }

    private function uploadSubjectImages(ImagesAwareInterface $subject): void
    {
        $images = $subject->getImages();
        foreach ($images as $image) {
            if ($image->hasFile()) {
                $this->uploader->upload($image);
            }

            // Upload failed? Let's remove that image.
            if (null === $image->getPath()) {
                $images->removeElement($image);
            }
        }
    }
}
```

This is an modified version of the `ImagesUploadListener` class. If you check the `uploadImages` method you will see that we are getting the values of the `ProductOption` object and looping trough them to upload each image. 

That should do the trick.
